import { test } from 'node:test';import assert from 'node:assert/strict';import type { DecisionProposal } from '@jhadina/core-spine';import { CriticUnavailableError,CriticVerificationPipeline } from './critic-verification.js';
const proposal:DecisionProposal={id:'p',contextId:'ctx',disposition:'PROCEED',recommendation:'r',rationale:'why',evidence:[],uncertainty:[],alternatives:[]};
const context=(risk='standard',complexity='simple'):any=>({task:{id:'t',riskClass:risk,complexity},packet:{id:'ctx'},evidenceIds:[],contextHash:'h'});
const pass={async verify(p:any){return p}};
test('simple standard-risk proposal bypasses optional critic',async()=>{let calls=0;const v=new CriticVerificationPipeline({evidenceVerifier:pass,critic:{async critique(){calls++;return{accepted:true,issues:[],uncertainty:[]}}}});assert.equal((await v.verify(proposal,context())).disposition,'PROCEED');assert.equal(calls,0)});
test('high-risk proposal requires critic',async()=>{const v=new CriticVerificationPipeline({evidenceVerifier:pass});await assert.rejects(()=>v.verify(proposal,context('high')),CriticUnavailableError)});
test('critic rejection can only downgrade proposal to DEFER',async()=>{const v=new CriticVerificationPipeline({evidenceVerifier:pass,critic:{async critique(){return{accepted:false,issues:['unsupported leap'],uncertainty:['low confidence']}}}});const o=await v.verify(proposal,context('high'));assert.equal(o.disposition,'DEFER');assert.match(o.uncertainty.join(' '),/unsupported leap/)});
test('accepted critique preserves disposition and can add uncertainty',async()=>{const v=new CriticVerificationPipeline({evidenceVerifier:pass,critic:{async critique(){return{accepted:true,issues:[],uncertainty:['edge case']}}}});const o=await v.verify(proposal,context('standard','complex'));assert.equal(o.disposition,'PROCEED');assert.deepEqual(o.uncertainty,['edge case'])});
test('evidence verifier always runs after critic',async()=>{const order:string[]=[];const v=new CriticVerificationPipeline({critic:{async critique(){order.push('critic');return{accepted:true,issues:[],uncertainty:[]}}},evidenceVerifier:{async verify(p){order.push('evidence');return p}}});await v.verify(proposal,context('critical'));assert.deepEqual(order,['critic','evidence'])});
