import {test} from 'node:test';import assert from 'node:assert/strict';import {GovernedUniversalIntakeRouter} from './universal-intake.js';
const asset=(filename:string,modality:any='video'):any=>({id:'a1',actorId:'u1',modality,mediaType:'video/mp4',assetRef:'opaque',filename,privacyClass:'internal',createdAt:'2026-01-01T00:00:00Z'});
test('routes sports video to sports intelligence',async()=>{const r=await new GovernedUniversalIntakeRouter().route(asset('boxing match.mp4'));assert.equal(r.routes[0].subsystem,'sports-intelligence')});
test('can produce multiple subsystem routes from one asset intent',async()=>{const r=await new GovernedUniversalIntakeRouter().route(asset('football game footage for film analysis.mp4'));assert.ok(r.routes.some(x=>x.subsystem==='sports-intelligence'));assert.ok(r.routes.some(x=>x.subsystem==='director-studio'));assert.equal(r.requiresHumanSelection,true)});
test('document with no domain signal routes to knowledge',async()=>{const r=await new GovernedUniversalIntakeRouter().route(asset('notes.pdf','document'));assert.equal(r.routes[0].subsystem,'knowledge')});
test('fails closed without actor or asset reference',async()=>{const r=new GovernedUniversalIntakeRouter();await assert.rejects(()=>r.route({...asset('x'),actorId:''}),/ACTOR_REQUIRED/);await assert.rejects(()=>r.route({...asset('x'),assetRef:''}),/ASSET_REFERENCE_REQUIRED/)});
test('routing has no execution authority',()=>{const r:any=new GovernedUniversalIntakeRouter();assert.equal(r.execute,undefined);assert.equal(r.approve,undefined);assert.equal(r.writeMemory,undefined)});

test('explicit intent can authorize multi-subsystem routing without selection',async()=>{const r=await new GovernedUniversalIntakeRouter().route(asset('game-footage.mp4'),'analyze this boxing footage for film direction');assert.ok(r.routes.length>1);assert.equal(r.requiresHumanSelection,false)});
