"use client";

import { useMemo, useState } from "react";
import type { PodJob, PodJobStage, PodJobStatus } from "@/lib/pod/workflow";

const STAGES: { id: PodJobStage; label: string }[] = [
  { id: "photo_received", label: "Photo" }, { id: "ai_generation", label: "AI" }, { id: "artwork_qa", label: "Artwork QA" }, { id: "print_composition", label: "Compose" }, { id: "production_qa", label: "Print QA" }, { id: "customer_approval", label: "Approval" }, { id: "provider_upload", label: "Provider" }, { id: "order_created", label: "Order" }, { id: "production", label: "Production" }, { id: "shipping", label: "Shipping" }, { id: "complete", label: "Complete" },
];

const STATUS: Record<PodJobStatus, string> = { queued: "Queued", running: "Running", waiting: "Waiting", failed: "Failed", complete: "Complete" };

export default function PODOperationsPanel({ initialJobs = [] }: { initialJobs?: PodJob[] }) {
  const [jobs, setJobs] = useState<PodJob[]>(initialJobs); const [filter, setFilter] = useState<"all" | PodJobStatus>("all");
  const visible = useMemo(() => filter === "all" ? jobs : jobs.filter((job) => job.status === filter), [filter, jobs]);
  const counts = useMemo(() => ({ all: jobs.length, failed: jobs.filter((j) => j.status === "failed").length, waiting: jobs.filter((j) => j.status === "waiting").length, running: jobs.filter((j) => j.status === "running").length, complete: jobs.filter((j) => j.status === "complete").length }), [jobs]);
  const retry = (id: string) => setJobs((current) => current.map((job) => job.id === id ? { ...job, status: "queued", lastError: undefined } : job));

  return <section className="rounded-[1.75rem] border border-cream/10 bg-ink p-5 text-cream shadow-xl" aria-label="PupsonStuff POD operations"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.3em] text-gold">PupsonStuff Ops</p><h2 className="mt-1 text-2xl font-semibold">Production Command Center</h2><p className="mt-1 text-sm text-cream/50">Monitor every custom creation from dog photo to doorstep.</p></div><div className="flex flex-wrap gap-1.5">{(["all", "running", "waiting", "failed", "complete"] as const).map((key) => <button key={key} onClick={() => setFilter(key)} className={`rounded-full px-3 py-1.5 text-[10px] ${filter === key ? "bg-gold text-ink" : "bg-cream/10 text-cream/60"}`}>{key === "all" ? `All ${counts.all}` : `${STATUS[key]} ${counts[key]}`}</button>)}</div></div><div className="space-y-3">{visible.length === 0 ? <div className="rounded-2xl border border-dashed border-cream/10 p-8 text-center text-sm text-cream/40">No production jobs in this view.</div> : visible.map((job) => { const stageIndex = STAGES.findIndex((stage) => stage.id === job.stage); return <article key={job.id} className="rounded-2xl border border-cream/10 bg-cream/[.03] p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-semibold">{job.creationId}</p><p className="text-[10px] text-cream/40">Job {job.id} · Attempt {job.attempts + 1}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[9px] uppercase tracking-wider ${job.status === "failed" ? "bg-red-400/10 text-red-300" : job.status === "complete" ? "bg-emerald-400/10 text-emerald-300" : "bg-gold/10 text-gold"}`}>{STATUS[job.status]}</span>{job.status === "failed" && <button onClick={() => retry(job.id)} className="rounded-full border border-cream/10 px-2.5 py-1 text-[9px] text-cream/70">Retry</button>}</div></div><div className="grid grid-cols-2 gap-1 sm:grid-cols-6 lg:grid-cols-11">{STAGES.map((stage, index) => <div key={stage.id} className={`rounded-lg px-2 py-2 text-center text-[8px] ${index < stageIndex ? "bg-emerald-400/10 text-emerald-300" : index === stageIndex ? "bg-gold text-ink" : "bg-cream/5 text-cream/30"}`}><div className="truncate">{stage.label}</div></div>)}</div>{job.lastError && <p className="mt-3 rounded-xl bg-red-400/5 px-3 py-2 text-[10px] text-red-300">{job.lastError}</p>}</article>})}</div></section>;
}
