import { test } from 'node:test';
import assert from 'node:assert/strict';
import { GovernedRuntimeExecutor, deriveExecutionId, type ExecutionRequest, type RuntimeAdapterPort, type RuntimeAuditEvent, type RuntimeAuditSink } from './index.js';

const input = { actorId: 'actor-1', artifactDigestSha256: 'a'.repeat(64), manifestId: 'manifest-1', requestedAt: '2026-09-01T12:00:00.000Z' };
const request: ExecutionRequest = { executionId: deriveExecutionId(input), actorId: input.actorId, artifact: { artifactId: 'artifact-1', digestSha256: input.artifactDigestSha256, mediaType: 'application/octet-stream', trust: 'trusted' }, manifest: { manifestId: input.manifestId, artifactDigestSha256: input.artifactDigestSha256, entrypoint: 'main', requestedCapabilities: ['runtime.read'], resourceLimits: { maxWallTimeMs: 1000, maxMemoryMb: 64, maxOutputBytes: 4096 } }, capabilityGrants: [{ grantId: 'grant-1', capability: 'runtime.read' }], requestedAt: input.requestedAt };
class Audit implements RuntimeAuditSink { events: RuntimeAuditEvent[] = []; async append(event: RuntimeAuditEvent) { this.events.push(event); } }
class Adapter implements RuntimeAdapterPort { calls = 0; constructor(private readonly result: 'completed' | 'failed' = 'completed') {} async execute(request: ExecutionRequest) { this.calls++; return { executionId: request.executionId, status: this.result }; } }
const policy = { async evaluate() { return 'allow' as const; } };

test('denied policy never reaches adapter', async () => { const audit = new Audit(); const adapter = new Adapter(); const executor = new GovernedRuntimeExecutor({ async evaluate() { return 'deny' as const; } }, adapter, audit); await assert.rejects(() => executor.execute(request), /denied/); assert.equal(adapter.calls, 0); assert.deepEqual(audit.events.map(e => e.status), ['denied']); });
test('audit failure before execution fails closed', async () => { const adapter = new Adapter(); const executor = new GovernedRuntimeExecutor(policy, adapter, { async append() { throw new Error('audit down'); } }); await assert.rejects(() => executor.execute(request), /audit down/); assert.equal(adapter.calls, 0); });
test('allow is audited before adapter execution', async () => { const audit = new Audit(); const adapter = new Adapter(); const executor = new GovernedRuntimeExecutor(policy, adapter, audit); const result = await executor.execute(request); assert.equal(result.status, 'completed'); assert.equal(adapter.calls, 1); assert.deepEqual(audit.events.map(e => e.status), ['allowed', 'completed']); });
test('adapter failure is audited as failed', async () => { const audit = new Audit(); const adapter = new Adapter('failed'); const executor = new GovernedRuntimeExecutor(policy, adapter, audit); const result = await executor.execute(request); assert.equal(result.status, 'failed'); assert.deepEqual(audit.events.map(e => e.status), ['allowed', 'failed']); });
test('invalid request is denied before policy evaluation', async () => { const audit = new Audit(); const adapter = new Adapter(); let policyCalls = 0; const executor = new GovernedRuntimeExecutor({ async evaluate() { policyCalls++; return 'allow' as const; } }, adapter, audit); await assert.rejects(() => executor.execute({ ...request, actorId: '' }), /actor binding/); assert.equal(policyCalls, 0); assert.equal(adapter.calls, 0); assert.equal(audit.events[0]?.status, 'denied'); });
