import { test } from 'node:test';
import assert from 'node:assert/strict';
import { GovernedRuntimeExecutor, deriveExecutionId, type ExecutionRequest, type ResourceEnforcerPort, type RuntimeAdapterPort, type RuntimeAuditEvent, type RuntimeAuditSink, type RuntimeResourceLease } from './index.js';

const input = { actorId: 'actor-1', artifactDigestSha256: 'a'.repeat(64), manifestId: 'manifest-1', requestedAt: '2026-09-01T12:00:00.000Z' };
const request: ExecutionRequest = { executionId: deriveExecutionId(input), actorId: input.actorId, artifact: { artifactId: 'artifact-1', digestSha256: input.artifactDigestSha256, mediaType: 'application/octet-stream', trust: 'trusted' }, manifest: { manifestId: input.manifestId, artifactDigestSha256: input.artifactDigestSha256, entrypoint: 'main', requestedCapabilities: ['runtime.read'], resourceLimits: { maxWallTimeMs: 1000, maxMemoryMb: 64, maxOutputBytes: 4096 } }, capabilityGrants: [{ grantId: 'grant-1', capability: 'runtime.read' }], requestedAt: input.requestedAt };
class Audit implements RuntimeAuditSink { events: RuntimeAuditEvent[] = []; async append(event: RuntimeAuditEvent) { this.events.push(event); } }
class Lease implements RuntimeResourceLease { constructor(public readonly executionId: string, public readonly limits = request.manifest.resourceLimits) {} enforcement = 'enforced' as const; released = false; async release() { this.released = true; } }
class Enforcer implements ResourceEnforcerPort { calls = 0; constructor(private readonly lease: RuntimeResourceLease = new Lease(request.executionId)) {} async acquire() { this.calls++; return this.lease; } }
class Adapter implements RuntimeAdapterPort { calls = 0; constructor(private readonly result: 'completed' | 'failed' = 'completed') {} async execute(req: ExecutionRequest) { this.calls++; return { executionId: req.executionId, status: this.result }; } }
const policy = { async evaluate() { return 'allow' as const; } };

function executor(policyOverride = policy, adapter = new Adapter(), audit: RuntimeAuditSink = new Audit(), enforcer: ResourceEnforcerPort = new Enforcer()) { return new GovernedRuntimeExecutor(policyOverride, adapter, audit, enforcer); }

test('denied policy never reaches resource enforcer or adapter', async () => { const audit = new Audit(); const adapter = new Adapter(); const enforcer = new Enforcer(); await assert.rejects(() => executor({ async evaluate() { return 'deny' as const; } }, adapter, audit, enforcer), /denied/); assert.equal(enforcer.calls, 0); assert.equal(adapter.calls, 0); assert.deepEqual(audit.events.map(e => e.status), ['denied']); });
test('resource enforcement failure fails closed before adapter', async () => { const audit = new Audit(); const adapter = new Adapter(); const enforcer: ResourceEnforcerPort = { async acquire() { throw new Error('sandbox unavailable'); } }; await assert.rejects(() => executor(policy, adapter, audit, enforcer), /sandbox unavailable/); assert.equal(adapter.calls, 0); assert.deepEqual(audit.events.map(e => e.status), ['denied']); });
test('invalid resource lease is rejected', async () => { const audit = new Audit(); const adapter = new Adapter(); const enforcer = new Enforcer(new Lease('different-execution')); await assert.rejects(() => executor(policy, adapter, audit, enforcer), /resource lease/); assert.equal(adapter.calls, 0); assert.equal((enforcer as Enforcer).calls, 1); assert.equal((enforcer as Enforcer)['lease'].released, true); });
test('audit failure after resource acquisition releases lease and never executes', async () => { const adapter = new Adapter(); const lease = new Lease(request.executionId); const enforcer = new Enforcer(lease); await assert.rejects(() => executor(policy, adapter, { async append(event) { if (event.status === 'allowed') throw new Error('audit down'); } }, enforcer), /audit down/); assert.equal(adapter.calls, 0); assert.equal(lease.released, true); });
test('successful enforcement precedes adapter and releases lease', async () => { const audit = new Audit(); const adapter = new Adapter(); const lease = new Lease(request.executionId); const enforcer = new Enforcer(lease); const result = await executor(policy, adapter, audit, enforcer).execute(request); assert.equal(result.status, 'completed'); assert.equal(enforcer.calls, 1); assert.equal(adapter.calls, 1); assert.equal(lease.released, true); assert.deepEqual(audit.events.map(e => e.status), ['allowed', 'completed']); });
test('adapter failure is audited and lease is released', async () => { const audit = new Audit(); const adapter = new Adapter('failed'); const lease = new Lease(request.executionId); const result = await executor(policy, adapter, audit, new Enforcer(lease)).execute(request); assert.equal(result.status, 'failed'); assert.equal(lease.released, true); assert.deepEqual(audit.events.map(e => e.status), ['allowed', 'failed']); });
test('invalid request is denied before policy evaluation', async () => { const audit = new Audit(); const adapter = new Adapter(); let policyCalls = 0; const enforcer = new Enforcer(); await assert.rejects(() => executor({ async evaluate() { policyCalls++; return 'allow' as const; } }, adapter, audit, enforcer).execute({ ...request, actorId: '' }), /actor binding/); assert.equal(policyCalls, 0); assert.equal(enforcer.calls, 0); assert.equal(adapter.calls, 0); assert.equal(audit.events[0]?.status, 'denied'); });
