import {describe,it} from 'node:test';import assert from 'node:assert/strict';
import {analyzeReferences,assertReferenceSafeForCode,classifyIntegrations,compileRequirements,createBuildReceipt,evaluatePreview,parseAppBuildIntent,planFeatureSlices,prepareDeployment,resolveArchitecture} from './app-builder.js';

describe('BUILDER.3.1-3.15 conversational app + website builder',()=>{
 it('3.1 includes websites as a first-class build surface',()=>{assert.equal(parseAppBuildIntent('build me a website for my project').surface,'website');});
 it('3.2 preserves unknown requirements',()=>{assert.deepEqual(compileRequirements({purpose:'site'}).unresolved,['users','features','acceptance']);});
 it('3.3/4 reuses existing subsystems before creating parallel architecture',()=>{const i=parseAppBuildIntent('build app');const a=resolveArchitecture({intent:i,existingTarget:'apps/jhadina-web',matches:[{capability:'memory.read',subsystem:'memory',reuse:'required'}]});assert.equal(a.placement,'existing-app');assert.deepEqual(a.dependencies,['memory']);assert.equal(a.doctorRegistrationRequired,true);});
 it('3.5 references never gain executable authority',()=>{const [r]=analyzeReferences(['https://github.com/example/project'],new Set(['https://github.com/example/project']));assert.equal(r!.executableAuthority,false);assert.throws(()=>assertReferenceSafeForCode(r!),/LICENSE/);});
 it('3.6/7 plans incremental tested feature slices',()=>{const r=compileRequirements({purpose:'site',users:['visitor'],features:['contact form'],acceptance:['contact form submits']});assert.equal(planFeatureSlices(r)[0]!.tests[0],'test:contact-form');});
 it('3.8 identifies governed data/auth/secrets integrations',()=>{assert.equal(classifyIntegrations(['Supabase database','public API'])[0]!.governed,true);});
 it('3.9 routes conversational UI changes as modifications',()=>{assert.equal(parseAppBuildIntent('make your website interface blue').action,'modify_app');});
 it('3.10 requires Doctor registration for every architecture',()=>{assert.equal(resolveArchitecture({intent:parseAppBuildIntent('new website'),matches:[]}).doctorRegistrationRequired,true);});
 it('3.11 fails acceptance separately from build success',()=>{const r=compileRequirements({purpose:'site',users:['visitor'],features:['form'],acceptance:['form works']});const p=evaluatePreview(r,[]);assert.equal(p.buildPassed,true);assert.deepEqual(p.requirementsFailed,['form works']);});
 it('3.12 deployment is always separately approval gated',()=>{assert.equal(prepareDeployment({buildPassed:true,requirementsPassed:[],requirementsFailed:[],assumptions:[]},[]).requiresApproval,true);});
 it('3.13 receipt preserves Doctor repair history',()=>{const intent=parseAppBuildIntent('website');const requirements=compileRequirements({purpose:'site',users:['visitor'],features:['home'],acceptance:['home renders']});const architecture=resolveArchitecture({intent,matches:[]});const preview=evaluatePreview(requirements,['home renders']);const receipt=createBuildReceipt({intent,requirements,architecture,references:[],slices:planFeatureSlices(requirements),tests:['test:home'],doctorRepairs:['repair-1'],preview,integrations:[]});assert.deepEqual(receipt.doctorRepairs,['repair-1']);});
 it('3.14 existing-app drill: interface blue stays a modification of canonical target',()=>{const intent=parseAppBuildIntent('make your interface blue');const architecture=resolveArchitecture({intent,existingTarget:'apps/jhadina-web',matches:[]});assert.equal(intent.action,'modify_app');assert.equal(architecture.target,'apps/jhadina-web');});
 it('3.15 new website drill compiles → architects → slices → accepts → prepares governed deployment',()=>{const intent=parseAppBuildIntent('build me a website for tracking contracts');const requirements=compileRequirements({purpose:'track contracts',users:['owner'],features:['contract list','status filter'],acceptance:['contract list','status filter']});const architecture=resolveArchitecture({intent,matches:[{capability:'research.run',subsystem:'knowledge',reuse:'preferred'}]});const slices=planFeatureSlices(requirements);const preview=evaluatePreview(requirements,['contract list','status filter']);const receipt=createBuildReceipt({intent,requirements,architecture,references:analyzeReferences(['https://example.com'],new Set(['https://example.com'])),slices,tests:slices.flatMap(s=>s.tests),doctorRepairs:[],preview,integrations:[]});assert.equal(intent.surface,'website');assert.equal(receipt.preview.requirementsFailed.length,0);assert.equal(receipt.deployment.ready,true);assert.equal(receipt.deployment.requiresApproval,true);});
});
