export type BuilderPhase=8|9|10|11|12|13|14|15|16|17;
export type WorkerKind='research'|'coding'|'test'|'doctor'|'visual'|'integration'|'deployment';
export interface CanonicalBindings{askJhadina:boolean;coreSpine:boolean;securityCore:boolean;hippocampus:boolean;patternEngine:boolean;opportunityCore:boolean;referenceProvenance:boolean;subsystemDoctor:boolean;github:boolean;supabase:boolean;vercel:boolean;}
export interface HardeningFinding{id:string;phase:BuilderPhase;severity:'low'|'medium'|'high'|'critical';kind:'duplicate_model'|'contract_only'|'disconnected_adapter'|'authority_bypass'|'missing_evidence'|'missing_runtime';canonicalOwner:string;resolved:boolean;evidenceRefs:readonly string[];}
export interface RuntimeRequest{id:string;utterance:string;projectId:string;intent:string;evidenceRefs:readonly string[];}
export interface RuntimeRoute{requestId:string;stages:readonly ('ask_jhadina'|'knowledge'|'planner'|'builder'|'doctor'|'security'|'github'|'supabase'|'vercel'|'verification'|'receipt'|'hippocampus')[];}
export interface BuilderUXState{projectId:string;status:'working'|'waiting_for_human'|'failed'|'preview_ready'|'pr_ready'|'complete';completed:number;total:number;decisionIds:readonly string[];evidenceRefs:readonly string[];}
export interface VisualRuntimeAcceptance{canvasMounted:boolean;sourceMapped:boolean;responsiveVerified:boolean;conversationApplied:boolean;previewVerified:boolean;}
export interface WorkerLease{worker:WorkerKind;projectId:string;paths:readonly string[];expiresAt:string;}
export interface PersistedProject{id:string;graphRef:string;checkpointRef:string;evidenceRefs:readonly string[];approvalRefs:readonly string[];leaseRefs:readonly string[];receiptRefs:readonly string[];}
export interface InfrastructureEvidence{gitRef?:string;previewDeploymentRef?:string;migrationRef?:string;productionDeploymentRef?:string;runtimeLogRefs:readonly string[];smokeRefs:readonly string[];rollbackRef?:string;}
export type AdversarialVector='malicious_repo'|'prompt_injection'|'poisoned_website'|'dependency_confusion'|'secret_exfiltration'|'self_authorization'|'unsafe_migration'|'protected_path'|'fake_test_success';
export interface AdversarialResult{vector:AdversarialVector;blocked:boolean;evidenceRef:string;}
export interface SubsystemCertification{subsystem:'pupsonstuff'|'opportunity'|'knowledge'|'media'|'sports'|'money'|'safety'|'overage'|'clean_app';canonicalReuseVerified:boolean;duplicateControlPlane:false;evidenceRefs:readonly string[];}
export interface FinalAcceptanceInput{request:RuntimeRequest;bindings:CanonicalBindings;hardening:readonly HardeningFinding[];visual:VisualRuntimeAcceptance;persisted:PersistedProject;infra:InfrastructureEvidence;adversarial:readonly AdversarialResult[];subsystems:readonly SubsystemCertification[];interruptionRecovered:boolean;controlledFailureRecovered:boolean;humanGateRespected:boolean;testsDiscovered:number;testsExecuted:number;regressionsPassed:boolean;receiptRefs:readonly string[];}
export interface FinalAcceptanceReceipt{phase:17;accepted:boolean;missing:readonly string[];requestId:string;projectId:string;evidenceRefs:readonly string[];authorityEscalated:false;}

export function auditBuilder(bindings:CanonicalBindings,findings:readonly HardeningFinding[]):readonly HardeningFinding[]{const missing=Object.entries(bindings).filter(([,v])=>!v).map(([k],i):HardeningFinding=>({id:`binding:${i}`,phase:8,severity:'high',kind:'disconnected_adapter',canonicalOwner:k,resolved:false,evidenceRefs:[]}));return[...findings,...missing];}
export function runtimeRoute(request:RuntimeRequest):RuntimeRoute{if(!request.evidenceRefs.length)throw new Error('REQUEST_EVIDENCE_REQUIRED');return{requestId:request.id,stages:['ask_jhadina','knowledge','planner','builder','doctor','security','github','supabase','vercel','verification','receipt','hippocampus']};}
export function uxState(projectId:string,completed:number,total:number,decisionIds:readonly string[],evidenceRefs:readonly string[]):BuilderUXState{return{projectId,completed,total,decisionIds,evidenceRefs,status:decisionIds.length?'waiting_for_human':completed>=total?'complete':'working'};}
export function verifyVisualRuntime(x:VisualRuntimeAcceptance):boolean{return x.canvasMounted&&x.sourceMapped&&x.responsiveVerified&&x.conversationApplied&&x.previewVerified;}
export function canAcquireLease(candidate:WorkerLease,active:readonly WorkerLease[]):boolean{return!active.some(l=>l.projectId===candidate.projectId&&l.worker!==candidate.worker&&l.paths.some(p=>candidate.paths.some(c=>c===p||c.startsWith(p)||p.startsWith(c))));}
export function resumable(x:PersistedProject):boolean{return Boolean(x.graphRef&&x.checkpointRef&&x.evidenceRefs.length&&x.receiptRefs.length);}
export function infrastructureCertified(x:InfrastructureEvidence):boolean{return Boolean(x.gitRef&&x.previewDeploymentRef&&x.smokeRefs.length&&x.runtimeLogRefs.length);}
export function adversarialCertified(results:readonly AdversarialResult[]):boolean{const required:AdversarialVector[]=['malicious_repo','prompt_injection','poisoned_website','dependency_confusion','secret_exfiltration','self_authorization','unsafe_migration','protected_path','fake_test_success'];return required.every(v=>results.some(r=>r.vector===v&&r.blocked&&r.evidenceRef));}
export function crossSubsystemCertified(xs:readonly SubsystemCertification[]):boolean{const required= new Set(['pupsonstuff','opportunity','knowledge','media','sports','money','safety','overage','clean_app']);return xs.every(x=>x.canonicalReuseVerified&&!x.duplicateControlPlane&&x.evidenceRefs.length>0)&&[...required].every(x=>xs.some(s=>s.subsystem===x));}
export function finalAutonomousAcceptance(x:FinalAcceptanceInput):FinalAcceptanceReceipt{const missing:string[]=[];if(auditBuilder(x.bindings,x.hardening).some(f=>!f.resolved))missing.push('hardening');if(!runtimeRoute(x.request))missing.push('runtime');if(!verifyVisualRuntime(x.visual))missing.push('visual_runtime');if(!resumable(x.persisted))missing.push('durable_resume');if(!infrastructureCertified(x.infra))missing.push('infrastructure');if(!adversarialCertified(x.adversarial))missing.push('adversarial');if(!crossSubsystemCertified(x.subsystems))missing.push('cross_subsystem');if(!x.interruptionRecovered)missing.push('interruption_recovery');if(!x.controlledFailureRecovered)missing.push('failure_recovery');if(!x.humanGateRespected)missing.push('human_gate');if(x.testsDiscovered<1)missing.push('tests_discovered');if(x.testsExecuted<1)missing.push('tests_executed');if(!x.regressionsPassed)missing.push('regressions');if(!x.receiptRefs.length)missing.push('receipts');return{phase:17,accepted:missing.length===0,missing,requestId:x.request.id,projectId:x.request.projectId,evidenceRefs:[...new Set([...x.request.evidenceRefs,...x.persisted.evidenceRefs,...x.infra.runtimeLogRefs,...x.infra.smokeRefs,...x.receiptRefs])],authorityEscalated:false};}
