export interface BuildExperience{id:string;intent:string;contextTags:readonly string[];planRef:string;implementationRefs:readonly string[];testRefs:readonly string[];repairRefs:readonly string[];deploymentRefs:readonly string[];outcome:'success'|'failure'|'partial';evidenceRefs:readonly string[];}
export interface LearningEnvelope{experience:BuildExperience;route:'hippocampus';directMutationAllowed:false;}
export interface BuildPattern{id:string;kind:'reuse'|'architecture'|'failure'|'repair'|'test'|'deployment';evidenceRefs:readonly string[];successes:number;failures:number;}
export interface BayesianBelief{patternId:string;alpha:number;beta:number;mean:number;}
export interface SimilarBuild{id:string;score:number;evidenceRefs:readonly string[];}
export interface ReuseCandidate{id:string;compatibility:number;evidenceRefs:readonly string[];provenanceRef:string;}
export interface ArchitectureOption{id:string;strategy:'reuse_existing'|'extend_existing'|'new_component'|'new_app';evidenceRefs:readonly string[];}
export interface TestSuggestion{test:string;reason:string;evidenceRefs:readonly string[];}
export interface RepairLearning{symptom:string;rootCause:string;repairRef:string;verificationRef:string;recurrence:number;}
export interface EfficiencyObservation{buildId:string;durationMs:number;toolCalls:number;failedAttempts:number;duplicateWork:number;}
export interface DriftFinding{kind:'duplicate_memory'|'duplicate_policy'|'duplicate_domain_model'|'direct_llm_authority'|'missing_provenance'|'duplicate_component';path:string;evidenceRef:string;}
export interface OptimizedPlan{taskIds:readonly string[];reusedIds:readonly string[];testSuggestions:readonly TestSuggestion[];driftFindings:readonly DriftFinding[];}
export interface LearningDecision{patternId:string;confidence:number;proposalEligible:boolean;authorityGranted:false;protectedMutationAllowed:false;}
export interface IntelligenceReport{patterns:readonly BuildPattern[];findings:readonly DriftFinding[];unresolved:readonly string[];evidenceRefs:readonly string[];}
export interface LearningDrillReceipt{builds:readonly string[];retrievalUsed:boolean;planImproved:boolean;dangerousPatternRejected:boolean;authorityUnchanged:true;}

export function captureExperience(x:BuildExperience):BuildExperience{if(!x.evidenceRefs.length)throw new Error('BUILD_EXPERIENCE_EVIDENCE_REQUIRED');return x;}
export function toHippocampus(x:BuildExperience):LearningEnvelope{return{experience:captureExperience(x),route:'hippocampus',directMutationAllowed:false};}
export function detectPattern(id:string,kind:BuildPattern['kind'],experiences:readonly BuildExperience[]):BuildPattern{const evidenceRefs=[...new Set(experiences.flatMap(x=>x.evidenceRefs))];return{id,kind,evidenceRefs,successes:experiences.filter(x=>x.outcome==='success').length,failures:experiences.filter(x=>x.outcome==='failure').length};}
export function updateBelief(pattern:BuildPattern,prior={alpha:1,beta:1}):BayesianBelief{const alpha=prior.alpha+pattern.successes,beta=prior.beta+pattern.failures;return{patternId:pattern.id,alpha,beta,mean:alpha/(alpha+beta)};}
export function similarity(queryTags:readonly string[],experiences:readonly BuildExperience[]):readonly SimilarBuild[]{const q=new Set(queryTags);return experiences.map(x=>{const overlap=x.contextTags.filter(t=>q.has(t)).length;const union=new Set([...queryTags,...x.contextTags]).size;return{id:x.id,score:union?overlap/union:0,evidenceRefs:x.evidenceRefs};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);}
export function rankReuse(candidates:readonly ReuseCandidate[]):readonly ReuseCandidate[]{return[...candidates].filter(x=>x.evidenceRefs.length&&x.provenanceRef).sort((a,b)=>b.compatibility-a.compatibility);}
export function architectureOptions(existing:boolean,evidenceRefs:readonly string[]):readonly ArchitectureOption[]{const out:ArchitectureOption[]=[];if(existing)out.push({id:'reuse',strategy:'reuse_existing',evidenceRefs},{id:'extend',strategy:'extend_existing',evidenceRefs});out.push({id:'component',strategy:'new_component',evidenceRefs},{id:'app',strategy:'new_app',evidenceRefs});return out;}
export function suggestTests(changeTags:readonly string[],evidenceRefs:readonly string[]):readonly TestSuggestion[]{const out:TestSuggestion[]=[];if(changeTags.some(x=>/database|migration|schema/.test(x)))out.push({test:'migration-compatibility',reason:'database change',evidenceRefs});if(changeTags.some(x=>/visual|ui|css/.test(x)))out.push({test:'responsive-accessibility',reason:'visual change',evidenceRefs});if(changeTags.some(x=>/money|security|policy/.test(x)))out.push({test:'governance-regression',reason:'governed boundary',evidenceRefs});return out;}
export function learnRepair(x:RepairLearning):RepairLearning{if(!x.verificationRef)throw new Error('REPAIR_VERIFICATION_REQUIRED');return x;}
export function efficiencyScore(x:EfficiencyObservation):number{return Math.max(0,1-(x.failedAttempts+x.duplicateWork)/(Math.max(1,x.toolCalls)));}
export function detectDrift(paths:readonly string[]):readonly DriftFinding[]{const rules:[RegExp,DriftFinding['kind']][]=[[/second-memory|episodic-memory-v2/i,'duplicate_memory'],[/policy-engine-v2|alternate-policy/i,'duplicate_policy'],[/opportunity-model-v2/i,'duplicate_domain_model'],[/llm.*authorize|authorize.*llm/i,'direct_llm_authority'],[/unprovenanced/i,'missing_provenance'],[/duplicate-component/i,'duplicate_component']];return paths.flatMap(path=>rules.filter(([r])=>r.test(path)).map(([,kind])=>({kind,path,evidenceRef:`repo:${path}`})));} 
export function optimizePlan(taskIds:readonly string[],reuse:readonly ReuseCandidate[],tests:readonly TestSuggestion[],drift:readonly DriftFinding[]):OptimizedPlan{return{taskIds,reusedIds:rankReuse(reuse).map(x=>x.id),testSuggestions:tests,driftFindings:drift};}
export function governLearning(pattern:BuildPattern):LearningDecision{const confidence=updateBelief(pattern).mean;return{patternId:pattern.id,confidence,proposalEligible:pattern.evidenceRefs.length>0&&confidence>=.5,authorityGranted:false,protectedMutationAllowed:false};}
export function intelligenceReport(patterns:readonly BuildPattern[],findings:readonly DriftFinding[],unresolved:readonly string[]):IntelligenceReport{return{patterns,findings,unresolved,evidenceRefs:[...new Set([...patterns.flatMap(p=>p.evidenceRefs),...findings.map(f=>f.evidenceRef)])]};}
export function builder715Drill(builds:readonly BuildExperience[],dangerous:BuildPattern):LearningDrillReceipt{if(builds.length<3)throw new Error('THREE_BUILDS_REQUIRED');const retrieved=similarity(builds[2]!.contextTags,builds.slice(0,2));const safe=governLearning(dangerous);return{builds:builds.map(x=>x.id),retrievalUsed:retrieved.length>0,planImproved:retrieved.length>0&&builds[2]!.testRefs.length>=builds[0]!.testRefs.length,dangerousPatternRejected:!safe.authorityGranted&&!safe.protectedMutationAllowed,authorityUnchanged:true};}
