import{describe,it}from'node:test';import assert from'node:assert/strict';import{adversarialCertified,auditBuilder,canAcquireLease,crossSubsystemCertified,finalAutonomousAcceptance,infrastructureCertified,resumable,runtimeRoute,uxState,verifyVisualRuntime,type AdversarialVector,type CanonicalBindings,type SubsystemCertification}from'./builder-final-acceptance.js';
const bindings:CanonicalBindings={askJhadina:true,coreSpine:true,securityCore:true,hippocampus:true,patternEngine:true,opportunityCore:true,referenceProvenance:true,subsystemDoctor:true,github:true,supabase:true,vercel:true};
const vectors:AdversarialVector[]=['malicious_repo','prompt_injection','poisoned_website','dependency_confusion','secret_exfiltration','self_authorization','unsafe_migration','protected_path','fake_test_success'];
const subs=['pupsonstuff','opportunity','knowledge','media','sports','money','safety','overage','clean_app'].map(subsystem=>({subsystem,canonicalReuseVerified:true,duplicateControlPlane:false,evidenceRefs:[`cert:${subsystem}`]})) as SubsystemCertification[];
describe('BUILDER.8-17 hardening and final acceptance',()=>{
it('8 audits canonical bindings and unresolved hardening',()=>assert.equal(auditBuilder(bindings,[]).length,0));
it('9 wires the canonical runtime route',()=>assert.equal(runtimeRoute({id:'r',utterance:'build it',projectId:'p',intent:'build',evidenceRefs:['request']}).stages.at(-1),'hippocampus'));
it('10 exposes human decisions without pretending completion',()=>assert.equal(uxState('p',8,10,['approval'],['e']).status,'waiting_for_human'));
it('11 requires a real mapped responsive conversational preview',()=>assert.equal(verifyVisualRuntime({canvasMounted:true,sourceMapped:true,responsiveVerified:true,conversationApplied:true,previewVerified:true}),true));
it('12 prevents workers from leasing overlapping paths',()=>assert.equal(canAcquireLease({worker:'coding',projectId:'p',paths:['apps/x'],expiresAt:'x'},[{worker:'doctor',projectId:'p',paths:['apps/x'],expiresAt:'x'}]),false));
it('13 requires graph checkpoint evidence and receipts for resume',()=>assert.equal(resumable({id:'p',graphRef:'g',checkpointRef:'c',evidenceRefs:['e'],approvalRefs:[],leaseRefs:[],receiptRefs:['r']}),true));
it('14 requires provider/runtime evidence rather than deployment intent',()=>assert.equal(infrastructureCertified({gitRef:'g',previewDeploymentRef:'v',runtimeLogRefs:['l'],smokeRefs:['s']}),true));
it('15 blocks every required adversarial vector with evidence',()=>assert.equal(adversarialCertified(vectors.map(vector=>({vector,blocked:true,evidenceRef:`e:${vector}`}))),true));
it('16 certifies canonical reuse across real subsystem classes',()=>assert.equal(crossSubsystemCertified(subs),true));
it('17 accepts only evidence-complete autonomous execution with recovery and unchanged authority',()=>{const r=finalAutonomousAcceptance({request:{id:'r',utterance:'build and handle everything you can',projectId:'p',intent:'build',evidenceRefs:['request']},bindings,hardening:[],visual:{canvasMounted:true,sourceMapped:true,responsiveVerified:true,conversationApplied:true,previewVerified:true},persisted:{id:'p',graphRef:'g',checkpointRef:'c',evidenceRefs:['state'],approvalRefs:['human'],leaseRefs:['lease'],receiptRefs:['state-receipt']},infra:{gitRef:'git',previewDeploymentRef:'preview',migrationRef:'migration',productionDeploymentRef:'prod',runtimeLogRefs:['runtime'],smokeRefs:['smoke'],rollbackRef:'rollback'},adversarial:vectors.map(vector=>({vector,blocked:true,evidenceRef:`adv:${vector}`})),subsystems:subs,interruptionRecovered:true,controlledFailureRecovered:true,humanGateRespected:true,testsDiscovered:17,testsExecuted:17,regressionsPassed:true,receiptRefs:['final']});assert.equal(r.accepted,true);assert.equal(r.authorityEscalated,false);assert.deepEqual(r.missing,[])});
});
