export type OpportunityBuildIntent='research_opportunity'|'import_opportunity'|'start_pursuit'|'evaluate_fit'|'find_provider'|'build_supporting_tool'|'prepare_response'|'monitor_opportunity'|'close_pursuit';
export interface OpportunityEvidence { id:string; source:'sam_api'|'url'|'document'|'conversation'|'other'; locator:string; authoritative:boolean; fetchedAt:string; }
export interface OpportunityRecord { id:string; source:'sam'|'overage'|'employment'|'affiliate'|'pod'|'other'; title:string; solicitationNumber?:string; agency?:string; naics?:string; psc?:string; deadline?:string; setAside?:string; placeOfPerformance?:string; evidence:readonly OpportunityEvidence[]; }
export interface PursuitWorkspace { id:string; opportunityId:string; researchRefs:readonly string[]; documentRefs:readonly string[]; providerIds:readonly string[]; deadlines:readonly string[]; decisionRefs:readonly string[]; }
export type RequirementCategory='mandatory'|'technical'|'staffing'|'certification'|'past_performance'|'pricing'|'submission'|'deadline';
export interface PursuitRequirement { id:string; category:RequirementCategory; text:string; explicit:boolean; evidenceRefs:readonly string[]; status:'satisfied'|'unresolved'|'blocked'; }
export interface CapabilityGap { requirementId:string; resolution:'existing_capability'|'provider'|'research'|'missing_capability'|'software_tool'; target?:string; }
export interface ProviderCandidate { id:string; naics:readonly string[]; evidenceRefs:readonly string[]; matchedRequirementIds:readonly string[]; contacted:false; }
export interface ResearchTask { id:string; topic:string; evidenceRequired:true; }
export interface BuildOnDemandProposal { requirementId:string; reason:string; builderSurface:'website'|'web_app'|'api'|'worker'|'package'; authorized:false; }
export interface ResponseWorkspace { opportunityId:string; complianceMatrix:Readonly<Record<string,string>>; capabilityRefs:readonly string[]; providerEvidenceRefs:readonly string[]; technicalSections:readonly string[]; pricingInputRefs:readonly string[]; attachmentRefs:readonly string[]; }
export interface Readiness { satisfied:number; unresolved:number; blocked:number; ready:boolean; }
export interface ExternalAction { kind:'email'|'provider_contact'|'form_submit'|'representation_sign'|'publish'|'bid_submit'; authorized:false; }
export interface OpportunityDoctorEvidence { stage:'source'|'normalization'|'database'|'core'|'ui'; passed:boolean; evidenceRef:string; }
export interface OpportunityOutcome { opportunityId:string; state:'not_pursued'|'pursuing'|'submitted'|'won'|'lost'|'cancelled'; evidenceRefs:readonly string[]; learningEligible:boolean; }
export interface Builder415Receipt { opportunity:OpportunityRecord; workspace:PursuitWorkspace; requirements:readonly PursuitRequirement[]; gaps:readonly CapabilityGap[]; providers:readonly ProviderCandidate[]; research:readonly ResearchTask[]; buildProposals:readonly BuildOnDemandProposal[]; response:ResponseWorkspace; readiness:Readiness; externalActions:readonly ExternalAction[]; doctor:readonly OpportunityDoctorEvidence[]; outcome:OpportunityOutcome; stoppedBeforeSubmission:true; }

export function routeOpportunityIntent(q:string):OpportunityBuildIntent {const s=q.toLowerCase();if(/start|pursue/.test(s))return'start_pursuit';if(/provider|subcontractor/.test(s))return'find_provider';if(/build|tool/.test(s))return'build_supporting_tool';if(/response|proposal/.test(s))return'prepare_response';if(/monitor|watch/.test(s))return'monitor_opportunity';if(/close/.test(s))return'close_pursuit';if(/fit|qualif/.test(s))return'evaluate_fit';if(/import|add/.test(s))return'import_opportunity';return'research_opportunity';}
export function canonicalizeSam(input:{noticeId:string;title:string;sourceUrl:string;fetchedAt:string;solicitationNumber?:string;agency?:string;naics?:string;psc?:string;deadline?:string;setAside?:string;placeOfPerformance?:string}):OpportunityRecord {if(!input.noticeId.trim()||!input.sourceUrl.trim())throw new Error('SAM_EVIDENCE_REQUIRED');return{id:`sam:${input.noticeId}`,source:'sam',title:input.title,solicitationNumber:input.solicitationNumber,agency:input.agency,naics:input.naics,psc:input.psc,deadline:input.deadline,setAside:input.setAside,placeOfPerformance:input.placeOfPerformance,evidence:[{id:`sam:${input.noticeId}:source`,source:'sam_api',locator:input.sourceUrl,authoritative:true,fetchedAt:input.fetchedAt}]};}
export function createPursuitWorkspace(o:OpportunityRecord):PursuitWorkspace{return{id:`pursuit:${o.id}`,opportunityId:o.id,researchRefs:[],documentRefs:o.evidence.map(e=>e.id),providerIds:[],deadlines:o.deadline?[o.deadline]:[],decisionRefs:[]};}
export function decomposeRequirements(o:OpportunityRecord):readonly PursuitRequirement[]{const ev=o.evidence.map(e=>e.id),r:PursuitRequirement[]=[];const add=(category:RequirementCategory,text:string,explicit:boolean)=>r.push({id:`${o.id}:req:${r.length+1}`,category,text,explicit,evidenceRefs:explicit?ev:[],status:explicit?'unresolved':'blocked'});if(o.naics)add('mandatory',`NAICS ${o.naics}`,true);else add('mandatory','NAICS unresolved',false);if(o.setAside)add('certification',o.setAside,true);if(o.deadline)add('deadline',o.deadline,true);else add('deadline','Deadline unresolved',false);add('technical',o.title,true);add('pricing','Pricing requirements require solicitation review',false);add('submission','Submission instructions require solicitation review',false);return r;}
export function resolveCapabilityGaps(reqs:readonly PursuitRequirement[],known:Readonly<Record<string,string>>):readonly CapabilityGap[]{return reqs.map(r=>known[r.id]?{requirementId:r.id,resolution:'existing_capability',target:known[r.id]}:{requirementId:r.id,resolution:r.category==='technical'?'provider':'research'});}
export function matchProviders(reqs:readonly PursuitRequirement[],providers:readonly {id:string;naics:string[];evidenceRefs:string[]}[]):readonly ProviderCandidate[]{const n=reqs.flatMap(r=>r.text.match(/NAICS (\d+)/)?.[1]??[]);return providers.filter(p=>p.naics.some(x=>n.includes(x))).map(p=>({id:p.id,naics:p.naics,evidenceRefs:p.evidenceRefs,matchedRequirementIds:reqs.filter(r=>p.naics.some(x=>r.text.includes(x))).map(r=>r.id),contacted:false}));}
export function researchTasks(reqs:readonly PursuitRequirement[]):readonly ResearchTask[]{return reqs.filter(r=>r.status!=='satisfied').map(r=>({id:`research:${r.id}`,topic:r.text,evidenceRequired:true}));}
export function proposeSupportingBuild(gaps:readonly CapabilityGap[]):readonly BuildOnDemandProposal[]{return gaps.filter(g=>g.resolution==='software_tool'||g.resolution==='missing_capability').map(g=>({requirementId:g.requirementId,reason:'Verified capability gap requires supporting software',builderSurface:'web_app',authorized:false}));}
export function responseWorkspace(o:OpportunityRecord,reqs:readonly PursuitRequirement[],providers:readonly ProviderCandidate[]):ResponseWorkspace{return{opportunityId:o.id,complianceMatrix:Object.fromEntries(reqs.map(r=>[r.id,r.status])),capabilityRefs:[],providerEvidenceRefs:providers.flatMap(p=>p.evidenceRefs),technicalSections:[],pricingInputRefs:[],attachmentRefs:o.evidence.map(e=>e.id)};}
export function readiness(reqs:readonly PursuitRequirement[]):Readiness{const satisfied=reqs.filter(r=>r.status==='satisfied').length,unresolved=reqs.filter(r=>r.status==='unresolved').length,blocked=reqs.filter(r=>r.status==='blocked').length;return{satisfied,unresolved,blocked,ready:unresolved===0&&blocked===0};}
export function prepareExternalAction(kind:ExternalAction['kind']):ExternalAction{return{kind,authorized:false};}
export function diagnoseOpportunity(e:readonly OpportunityDoctorEvidence[]):{failedStage?:OpportunityDoctorEvidence['stage'];evidenceRefs:readonly string[]}{const f=e.find(x=>!x.passed);return{failedStage:f?.stage,evidenceRefs:e.map(x=>x.evidenceRef)};}
export function outcome(opportunityId:string,state:OpportunityOutcome['state'],evidenceRefs:readonly string[]):OpportunityOutcome{return{opportunityId,state,evidenceRefs,learningEligible:evidenceRefs.length>0};}
export function runBuilder415(input:{opportunity:OpportunityRecord;knownCapabilities?:Readonly<Record<string,string>>;providers?:readonly {id:string;naics:string[];evidenceRefs:string[]}[];doctor?:readonly OpportunityDoctorEvidence[]}):Builder415Receipt{const o=input.opportunity,w=createPursuitWorkspace(o),requirements=decomposeRequirements(o),gaps=resolveCapabilityGaps(requirements,input.knownCapabilities??{}),providers=matchProviders(requirements,input.providers??[]),research=researchTasks(requirements),buildProposals=proposeSupportingBuild(gaps),response=responseWorkspace(o,requirements,providers),ready=readiness(requirements),doctor=input.doctor??[],out=outcome(o.id,'pursuing',o.evidence.map(e=>e.id));return{opportunity:o,workspace:w,requirements,gaps,providers,research,buildProposals,response,readiness:ready,externalActions:[prepareExternalAction('provider_contact'),prepareExternalAction('bid_submit')],doctor,outcome:out,stoppedBeforeSubmission:true};}
