export type ProductionIntent='deploy'|'configure_domain'|'run_migration'|'configure_environment'|'rollback'|'inspect_production'|'repair_production'|'promote_release'|'retire_release';
export type EnvironmentName='local'|'dev'|'preview'|'staging'|'production';
export interface EnvironmentTarget{name:EnvironmentName;explicit:boolean;provider?:string;}
export interface ProviderResolution{kind:'vercel'|'supabase'|'github_actions'|'railway'|'other';evidenceRefs:readonly string[];existing:true;}
export interface SecretRequirement{name:string;present:boolean;valueExposed:false;}
export interface MigrationPlan{id:string;files:readonly string[];compatibilityChecked:boolean;recoveryConsidered:boolean;stagingVerified:boolean;productionAuthorized:false;}
export interface DeploymentEvidence{id:string;environment:EnvironmentName;provider:string;commit:string;status:'requested'|'building'|'ready'|'failed';evidenceRefs:readonly string[];}
export interface ReadinessGate{testsExecuted:boolean;regressionsPassed:boolean;securityPassed:boolean;migrationsReady:boolean;environmentReady:boolean;secretsReady:boolean;rollbackReady:boolean;acceptanceReceipts:readonly string[];ready:boolean;}
export interface DomainPlan{domain:string;dnsVerified:boolean;tlsVerified:boolean;redirectsVerified:boolean;authorized:false;}
export interface ReleaseManifest{id:string;commit:string;projectId:string;testReceiptRefs:readonly string[];migrationIds:readonly string[];configurationVersion:string;previewDeploymentId:string;approvalRef?:string;deploymentId?:string;frozen:boolean;}
export interface ProductionAuthorization{releaseId:string;approved:boolean;approvalRef?:string;}
export interface SmokeResult{target:string;passed:boolean;evidenceRef:string;}
export interface ProductionHealth{deploymentId:string;healthy:boolean;smokes:readonly SmokeResult[];runtimeErrorRefs:readonly string[];}
export interface ProductionIncident{deploymentId:string;failureEvidenceRefs:readonly string[];repairBranchRequired:true;liveEditAllowed:false;rollbackRecommended:boolean;}
export interface RollbackPlan{fromDeploymentId:string;toDeploymentId:string;databaseCompatibilityChecked:boolean;authorized:false;}
export interface ProductionReceipt{release:ReleaseManifest;deployment:DeploymentEvidence;health:ProductionHealth;incident?:ProductionIncident;state:'preview'|'awaiting_approval'|'deployed_healthy'|'failed'|'rollback_required';}

export function routeProductionIntent(q:string):ProductionIntent{const s=q.toLowerCase();if(/domain|dns/.test(s))return'configure_domain';if(/migration|schema/.test(s))return'run_migration';if(/rollback/.test(s))return'rollback';if(/repair|fix/.test(s))return'repair_production';if(/inspect|health/.test(s))return'inspect_production';if(/retire/.test(s))return'retire_release';if(/promote|production/.test(s))return'promote_release';if(/environment|secret/.test(s))return'configure_environment';return'deploy';}
export function targetEnvironment(name:EnvironmentName,explicit:boolean):EnvironmentTarget{if(name==='production'&&!explicit)throw new Error('PRODUCTION_TARGET_MUST_BE_EXPLICIT');return{name,explicit};}
export function resolveProvider(kind:ProviderResolution['kind'],evidenceRefs:readonly string[]):ProviderResolution{if(!evidenceRefs.length)throw new Error('PROVIDER_EVIDENCE_REQUIRED');return{kind,evidenceRefs,existing:true};}
export function secretRequirement(name:string,present:boolean):SecretRequirement{return{name,present,valueExposed:false};}
export function migrationPlan(id:string,files:readonly string[]):MigrationPlan{return{id,files,compatibilityChecked:false,recoveryConsidered:false,stagingVerified:false,productionAuthorized:false};}
export function previewDeployment(input:{id:string;provider:string;commit:string;evidenceRefs:readonly string[];status:DeploymentEvidence['status']}):DeploymentEvidence{return{...input,environment:'preview'};}
export function evaluateReadiness(input:Omit<ReadinessGate,'ready'>):ReadinessGate{const ready=input.testsExecuted&&input.regressionsPassed&&input.securityPassed&&input.migrationsReady&&input.environmentReady&&input.secretsReady&&input.rollbackReady&&input.acceptanceReceipts.length>0;return{...input,ready};}
export function domainPlan(domain:string):DomainPlan{return{domain,dnsVerified:false,tlsVerified:false,redirectsVerified:false,authorized:false};}
export function freezeRelease(input:Omit<ReleaseManifest,'frozen'>):ReleaseManifest{if(!input.commit||!input.previewDeploymentId||!input.testReceiptRefs.length)throw new Error('RELEASE_EVIDENCE_INCOMPLETE');return{...input,frozen:true};}
export function authorizeProduction(releaseId:string,approvalRef?:string):ProductionAuthorization{return{releaseId,approved:Boolean(approvalRef),approvalRef};}
export function executeDeployment(input:{release:ReleaseManifest;authorization:ProductionAuthorization;provider:string;deploymentId:string;evidenceRefs:readonly string[]}):DeploymentEvidence{if(!input.release.frozen)throw new Error('RELEASE_NOT_FROZEN');if(!input.authorization.approved)throw new Error('PRODUCTION_APPROVAL_REQUIRED');return{id:input.deploymentId,environment:'production',provider:input.provider,commit:input.release.commit,status:'requested',evidenceRefs:input.evidenceRefs};}
export function verifyProduction(deploymentId:string,smokes:readonly SmokeResult[],runtimeErrorRefs:readonly string[]):ProductionHealth{return{deploymentId,smokes,runtimeErrorRefs,healthy:smokes.length>0&&smokes.every(s=>s.passed)&&runtimeErrorRefs.length===0};}
export function productionIncident(deploymentId:string,failureEvidenceRefs:readonly string[]):ProductionIncident{return{deploymentId,failureEvidenceRefs,repairBranchRequired:true,liveEditAllowed:false,rollbackRecommended:true};}
export function rollbackPlan(fromDeploymentId:string,toDeploymentId:string,databaseCompatibilityChecked:boolean):RollbackPlan{return{fromDeploymentId,toDeploymentId,databaseCompatibilityChecked,authorized:false};}
export function productionReceipt(input:{release:ReleaseManifest;deployment:DeploymentEvidence;health:ProductionHealth}):ProductionReceipt{if(input.deployment.status!=='ready')return{...input,state:input.deployment.status==='failed'?'failed':'awaiting_approval'};if(!input.health.healthy)return{...input,incident:productionIncident(input.deployment.id,input.health.runtimeErrorRefs.length?input.health.runtimeErrorRefs:input.health.smokes.filter(s=>!s.passed).map(s=>s.evidenceRef)),state:'rollback_required'};return{...input,state:'deployed_healthy'};}
export function builder615Drill(input:{commit:string;projectId:string;preview:DeploymentEvidence;readiness:ReadinessGate;approvalRef?:string;production?:DeploymentEvidence;smokes?:readonly SmokeResult[];runtimeErrors?:readonly string[]}):ProductionReceipt{const release=freezeRelease({id:`release:${input.commit}`,commit:input.commit,projectId:input.projectId,testReceiptRefs:input.readiness.acceptanceReceipts,migrationIds:[],configurationVersion:'v1',previewDeploymentId:input.preview.id,approvalRef:input.approvalRef,deploymentId:input.production?.id});if(!input.readiness.ready||!input.approvalRef||!input.production)return{release,deployment:input.preview,health:{deploymentId:input.preview.id,healthy:false,smokes:[],runtimeErrorRefs:[]},state:'awaiting_approval'};const health=verifyProduction(input.production.id,input.smokes??[],input.runtimeErrors??[]);return productionReceipt({release,deployment:input.production,health});}
