export type ProjectIntent='build'|'finish_subsystem'|'repair_project'|'fulfill_opportunity'|'build_website';
export type TaskState='pending'|'ready'|'running'|'blocked'|'waiting_approval'|'failed'|'complete';
export interface ProjectTask {id:string;title:string;subsystem:string;dependsOn:readonly string[];state:TaskState;acceptance:readonly string[];evidenceRefs:readonly string[];protectedPaths:readonly string[];}
export interface ProjectGraph {id:string;goal:string;tasks:readonly ProjectTask[];createdAt:string;}
export interface ExistingWork {repoRefs:readonly string[];handoffRefs:readonly string[];receiptRefs:readonly string[];openPrRefs:readonly string[];capabilities:readonly string[];}
export interface HumanGate {taskId:string;reason:string;capability:string;approved:false;}
export interface ProjectEvent {projectId:string;taskId?:string;kind:'planned'|'started'|'evidence'|'doctor'|'approval_required'|'completed'|'failed';at:string;evidenceRef?:string;}
export interface DurableProjectState {graph:ProjectGraph;events:readonly ProjectEvent[];checkpoints:readonly string[];gates:readonly HumanGate[];}
export interface WorkLease {taskId:string;paths:readonly string[];holder:string;}
export interface CompletionAudit {complete:boolean;missing:readonly string[];executedTests:number;discoveredTests:number;regressionsPassed:boolean;receiptRefs:readonly string[];}
export interface CommandCenter {working:readonly string[];waitingForHuman:readonly string[];failed:readonly string[];doctorRepairing:readonly string[];ready:readonly string[];complete:readonly string[];}
export interface ExecutionResult {state:DurableProjectState;audits:Readonly<Record<string,CompletionAudit>>;commandCenter:CommandCenter;stoppedAt:'verified_completion'|'human_gate'|'blocked';}

export function routeProjectIntent(q:string):ProjectIntent{const s=q.toLowerCase();if(/website|site/.test(s))return'build_website';if(/opportunity|sam|contract/.test(s))return'fulfill_opportunity';if(/repair|fix/.test(s))return'repair_project';if(/finish|complete subsystem/.test(s))return'finish_subsystem';return'build';}
export function compileWorkGraph(input:{id:string;goal:string;tasks:readonly Omit<ProjectTask,'state'|'evidenceRefs'>[];now:string}):ProjectGraph{const ids=new Set(input.tasks.map(t=>t.id));for(const t of input.tasks)for(const d of t.dependsOn)if(!ids.has(d))throw new Error('UNKNOWN_TASK_DEPENDENCY');return{id:input.id,goal:input.goal,tasks:input.tasks.map(t=>({...t,state:t.dependsOn.length?'pending':'ready',evidenceRefs:[]})),createdAt:input.now};}
export function reconcileExistingWork(work:ExistingWork):ExistingWork{return{repoRefs:[...new Set(work.repoRefs)],handoffRefs:[...new Set(work.handoffRefs)],receiptRefs:[...new Set(work.receiptRefs)],openPrRefs:[...new Set(work.openPrRefs)],capabilities:[...new Set(work.capabilities)]};}
export function nextExecutable(graph:ProjectGraph):readonly ProjectTask[]{const done=new Set(graph.tasks.filter(t=>t.state==='complete').map(t=>t.id));return graph.tasks.filter(t=>['ready','pending'].includes(t.state)&&t.dependsOn.every(d=>done.has(d))).map(t=>({...t,state:'ready'}));}
export function routeResearchGap(task:ProjectTask,missingCapability:boolean):{route:'knowledge'|'builder';resumeTaskId:string}{return{route:missingCapability?'builder':'knowledge',resumeTaskId:task.id};}
export function needsVisualWorkspace(intent:ProjectIntent):boolean{return intent==='build_website';}
export function doctorRecovery(task:ProjectTask,diagnosed:boolean):ProjectTask{return{...task,state:diagnosed?'waiting_approval':'failed'};}
export function collectHumanGates(tasks:readonly ProjectTask[]):readonly HumanGate[]{return tasks.filter(t=>t.state==='waiting_approval').map(t=>({taskId:t.id,reason:'Governed action requires human authorization',capability:'evolution.propose',approved:false}));}
export function appendEvent(state:DurableProjectState,event:ProjectEvent):DurableProjectState{return{...state,events:[...state.events,event]};}
export function resumeProject(state:DurableProjectState):readonly ProjectTask[]{return nextExecutable(state.graph);}
export function canLease(task:ProjectTask,leases:readonly WorkLease[]):boolean{return!leases.some(l=>l.taskId!==task.id&&l.paths.some(p=>task.protectedPaths.some(tp=>tp===p||tp.startsWith(p)||p.startsWith(tp))));}
export function auditCompletion(input:{task:ProjectTask;discoveredTests:number;executedTests:number;regressionsPassed:boolean;receiptRefs:readonly string[]}):CompletionAudit{const missing:string[]=[];if(input.task.acceptance.length===0)missing.push('acceptance');if(input.task.evidenceRefs.length===0)missing.push('evidence');if(input.discoveredTests<1)missing.push('tests_discovered');if(input.executedTests<1)missing.push('tests_executed');if(!input.regressionsPassed)missing.push('regressions');if(input.receiptRefs.length===0)missing.push('receipt');return{complete:missing.length===0,missing,discoveredTests:input.discoveredTests,executedTests:input.executedTests,regressionsPassed:input.regressionsPassed,receiptRefs:input.receiptRefs};}
export function commandCenter(graph:ProjectGraph,doctorIds:ReadonlySet<string>=new Set()):CommandCenter{const ids=(s:TaskState)=>graph.tasks.filter(t=>t.state===s).map(t=>t.id);return{working:ids('running'),waitingForHuman:ids('waiting_approval'),failed:ids('failed'),doctorRepairing:graph.tasks.filter(t=>doctorIds.has(t.id)).map(t=>t.id),ready:nextExecutable(graph).map(t=>t.id),complete:ids('complete')};}
export function runUninterrupted(input:{state:DurableProjectState;audits:Readonly<Record<string,CompletionAudit>>}):ExecutionResult{let state=input.state;for(const task of nextExecutable(state.graph)){if(task.state==='waiting_approval')continue;const audit=input.audits[task.id];if(!audit?.complete)continue;state={...state,graph:{...state.graph,tasks:state.graph.tasks.map(t=>t.id===task.id?{...t,state:'complete',evidenceRefs:[...new Set([...t.evidenceRefs,...audit.receiptRefs])]}:t)}};}const gates=collectHumanGates(state.graph.tasks);const remaining=state.graph.tasks.filter(t=>t.state!=='complete');return{state,audits:input.audits,commandCenter:commandCenter(state.graph),stoppedAt:gates.length?'human_gate':remaining.length?'blocked':'verified_completion'};}
