import{describe,it}from'node:test';import assert from'node:assert/strict';import{appendEvent,auditCompletion,canLease,collectHumanGates,commandCenter,compileWorkGraph,doctorRecovery,needsVisualWorkspace,nextExecutable,reconcileExistingWork,resumeProject,routeProjectIntent,routeResearchGap,runUninterrupted,type DurableProjectState,type ProjectTask}from'./project-executor.js';
const task=(id:string,deps:string[]=[],state?:ProjectTask['state']):ProjectTask=>({id,title:id,subsystem:'builder',dependsOn:deps,state:state??(deps.length?'pending':'ready'),acceptance:['verified'],evidenceRefs:['ev'],protectedPaths:[`apps/${id}`]});
describe('BUILDER.5.1-5.15',()=>{
it('5.1 routes project intent',()=>assert.equal(routeProjectIntent('finish this subsystem'),'finish_subsystem'));
it('5.2 compiles dependency graph',()=>assert.equal(compileWorkGraph({id:'p',goal:'g',now:'2026-09-20T00:00:00Z',tasks:[{id:'a',title:'a',subsystem:'x',dependsOn:[],acceptance:['ok'],protectedPaths:[]},{id:'b',title:'b',subsystem:'x',dependsOn:['a'],acceptance:['ok'],protectedPaths:[]}]}).tasks[1]!.state,'pending'));
it('5.3 reconciles duplicate prior work refs',()=>assert.deepEqual(reconcileExistingWork({repoRefs:['a','a'],handoffRefs:[],receiptRefs:[],openPrRefs:[],capabilities:[]}).repoRefs,['a']));
it('5.4 chooses only dependency-ready tasks',()=>assert.deepEqual(nextExecutable({id:'p',goal:'g',createdAt:'x',tasks:[task('a'),task('b',['a'])]}).map(t=>t.id),['a']));
it('5.5 supports cross-subsystem tasks',()=>{const g={id:'p',goal:'g',createdAt:'x',tasks:[{...task('a'),subsystem:'knowledge'},{...task('b'),subsystem:'opportunity'}]};assert.equal(new Set(g.tasks.map(t=>t.subsystem)).size,2)});
it('5.6 routes missing research capability into Builder and preserves resume target',()=>assert.deepEqual(routeResearchGap(task('a'),true),{route:'builder',resumeTaskId:'a'}));
it('5.7 website projects enter visual workspace',()=>assert.equal(needsVisualWorkspace(routeProjectIntent('build a website')),true));
it('5.8 Doctor diagnosis cannot self-authorize repair',()=>assert.equal(doctorRecovery(task('a'),true).state,'waiting_approval'));
it('5.9 accumulates genuine human gates',()=>assert.equal(collectHumanGates([{...task('a'),state:'waiting_approval'}]).length,1));
it('5.10 persists append-only project events',()=>{const s:DurableProjectState={graph:{id:'p',goal:'g',createdAt:'x',tasks:[task('a')]},events:[],checkpoints:[],gates:[]};assert.equal(appendEvent(s,{projectId:'p',kind:'planned',at:'x'}).events.length,1)});
it('5.11 resumes from durable graph state',()=>{const s:DurableProjectState={graph:{id:'p',goal:'g',createdAt:'x',tasks:[task('a')]},events:[],checkpoints:[],gates:[]};assert.deepEqual(resumeProject(s).map(t=>t.id),['a'])});
it('5.12 prevents overlapping path leases',()=>assert.equal(canLease(task('a'),[{taskId:'other',paths:['apps/a'],holder:'worker'}]),false));
it('5.13 completion requires actual discovered/executed tests, regression and receipt',()=>{const a=auditCompletion({task:task('a'),discoveredTests:0,executedTests:0,regressionsPassed:true,receiptRefs:['r']});assert.equal(a.complete,false);assert.ok(a.missing.includes('tests_executed'))});
it('5.14 command center exposes operational states',()=>{const c=commandCenter({id:'p',goal:'g',createdAt:'x',tasks:[{...task('a'),state:'running'},{...task('b'),state:'waiting_approval'}]});assert.deepEqual(c.working,['a']);assert.deepEqual(c.waitingForHuman,['b'])});
it('5.15 uninterrupted drill advances verified work and stops only at dependency/block/gate',()=>{const a=task('a');const b=task('b',['a']);const state:DurableProjectState={graph:{id:'p',goal:'build and verify',createdAt:'x',tasks:[a,b]},events:[],checkpoints:[],gates:[]};const audit=auditCompletion({task:a,discoveredTests:2,executedTests:2,regressionsPassed:true,receiptRefs:['receipt:a']});const first=runUninterrupted({state,audits:{a:audit}});assert.equal(first.state.graph.tasks[0]!.state,'complete');assert.equal(first.stoppedAt,'blocked');assert.deepEqual(nextExecutable(first.state.graph).map(t=>t.id),['b']);});
});
