import {describe,it} from 'node:test';import assert from 'node:assert/strict';import {BUILDER_3V_REFERENCES,addAsset,applyVisualOperation,assertResponsive,bindBackend,conversationalVisualOperation,createCheckpoint,createVisualProject,createWorkspace,previewReady,reuseComponent,selectNode,verifyVisualAcceptance,type VisualProject} from './visual-builder.js';
function project():VisualProject{return {...createVisualProject({id:'site',surface:'website',branch:'build/site'}),nodes:{hero:{id:'hero',kind:'component',name:'Hero',sourcePath:'components/Hero.tsx',children:[],styles:{},responsive:{mobile:{display:'block'}}}},pages:['home']};}
describe('BUILDER.3V.1-3V.15 visual website/app workspace',()=>{
 it('3V.1 admits references with zero authority and Webstudio architecture-only',()=>{assert.equal(BUILDER_3V_REFERENCES[0]!.use,'architecture-only');assert.equal(BUILDER_3V_REFERENCES.every(r=>!r.executionAuthority),true);});
 it('3V.2 canonical project model maps page/component/source/style',()=>{assert.equal(project().nodes.hero!.sourcePath,'components/Hero.tsx');});
 it('3V.3 creates isolated workspace from known-good commit',()=>{assert.equal(createWorkspace(project(),'abc').isolated,true);});
 it('3V.4 requires compiled healthy live preview',()=>{assert.equal(previewReady({compiled:true,runtimeHealthy:true,consoleErrors:[],accessibilityViolations:[],responsiveFailures:[]}),true);});
 it('3V.5/6 canvas selection maps visible node to source',()=>{assert.deepEqual(selectNode(project(),'hero'),{nodeId:'hero',sourcePath:'components/Hero.tsx'});});
 it('3V.7 conversational visual edits target selection',()=>{const p=project(),op=conversationalVisualOperation(selectNode(p,'hero'),'make this blue');assert.equal(applyVisualOperation(p,op).nodes.hero!.styles.color,'blue');});
 it('3V.8 mobile behavior is explicit',()=>{assert.doesNotThrow(()=>assertResponsive(project(),'hero'));});
 it('3V.9 reuses existing design components',()=>{assert.equal(reuseComponent(project(),'Hero')?.id,'hero');});
 it('3V.10 manages assets without duplicates',()=>{assert.deepEqual(addAsset(addAsset(project(),'logo.png'),'logo.png').assets,['logo.png']);});
 it('3V.11 backend binding never exposes secrets to client',()=>{const b=bindBackend({nodeId:'hero',provider:'supabase',capability:'database.write',secretRefs:['SUPABASE_KEY']});assert.equal(b.clientExposedSecrets,false);assert.equal(b.governed,true);});
 it('3V.12 source mapping supports synchronized code workspace',()=>{assert.equal(selectNode(project(),'hero').sourcePath,'components/Hero.tsx');});
 it('3V.13 creates reversible verified checkpoints',()=>{const op=conversationalVisualOperation(selectNode(project(),'hero'),'make this taller');assert.equal(createCheckpoint({id:'v1',beforeHash:'a',afterHash:'b',operation:op,verified:true}).verified,true);});
 it('3V.14 visual acceptance includes runtime, accessibility, responsive and Doctor evidence',()=>{const p=project(),op=conversationalVisualOperation(selectNode(p,'hero'),'make this blue'),cp=createCheckpoint({id:'v1',beforeHash:'a',afterHash:'b',operation:op,verified:true});const r=verifyVisualAcceptance({project:p,preview:{compiled:true,runtimeHealthy:true,consoleErrors:[],accessibilityViolations:[],responsiveFailures:[]},checkpoints:[cp],doctorRepairs:['doctor-1']});assert.equal(r.mobileVerified,true);assert.deepEqual(r.doctorRepairs,['doctor-1']);});
 it('3V.15 full website drill stays unpublished after prompt→canvas→responsive→repair→verify',()=>{let p=project();const ws=createWorkspace(p,'known-good');const selected=selectNode(p,'hero');const op=conversationalVisualOperation(selected,'make this blue','mobile');p=applyVisualOperation(p,op);assertResponsive(p,'hero');const cp=createCheckpoint({id:'v1',beforeHash:'before',afterHash:'after',operation:op,verified:true});const receipt=verifyVisualAcceptance({project:p,preview:{compiled:true,runtimeHealthy:true,consoleErrors:[],accessibilityViolations:[],responsiveFailures:[]},checkpoints:[cp],doctorRepairs:['controlled-defect-repaired']});assert.equal(ws.isolated,true);assert.equal(receipt.desktopVerified,true);assert.equal(receipt.mobileVerified,true);assert.equal(receipt.unpublished,true);assert.equal(receipt.deploymentRequiresApproval,true);});
});
