import { createHash } from 'node:crypto';

export type ProvenanceStatus = 'SOURCE_VERIFIED' | 'BUILD_VERIFIED' | 'ARTIFACT_VERIFIED' | 'DEPLOYMENT_VERIFIED' | 'RUNTIME_VERIFIED' | 'EFFECT_VERIFIED' | 'PARTIAL' | 'CONTRADICTED' | 'UNKNOWN';
export type ProvenanceNodeType = 'source' | 'commit' | 'manifest' | 'contract' | 'compiler' | 'dependency' | 'build' | 'artifact' | 'sbom' | 'signature' | 'attestation' | 'test' | 'canary' | 'promotion' | 'deployment' | 'workload' | 'runtime' | 'effect' | 'provider_receipt';
export type ProvenanceEdgeType = 'DERIVED_FROM' | 'COMPILED_FROM' | 'GENERATED_FROM' | 'DEPENDS_ON' | 'BUILT_BY' | 'SIGNED_BY' | 'ATTESTED_BY' | 'TESTED_BY' | 'CANARIED_BY' | 'PROMOTED_BY' | 'DEPLOYED_AS' | 'LOADED_BY' | 'EXECUTED_BY' | 'CAUSED' | 'PRODUCED' | 'VERIFIED_BY' | 'RECONCILED_BY';
export type ProvenanceNode = { id: string; type: ProvenanceNodeType; hash: string; metadata?: Record<string, unknown> };
export type ProvenanceEdge = { from: string; to: string; type: ProvenanceEdgeType; evidenceRefs?: string[] };
export type ArtifactIdentity = { artifactId: string; artifactType: string; artifactHash: string; sourceHash?: string; contractHash?: string; semanticHash?: string; dependencyLockHash?: string; compilerHash?: string; buildPlanHash?: string; environmentHash?: string; configurationHash?: string; provenanceHash: string; identityHash: string };
export type ProvenanceSnapshot = { nodes: ProvenanceNode[]; edges: ProvenanceEdge[]; controlEpoch?: number; graphHash: string };
function canonical(value: unknown): string { if (value === null || typeof value !== 'object') return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(',')}}`; }
export function sha256(value: unknown): string { return createHash('sha256').update(canonical(value)).digest('hex'); }
export function createArtifactIdentity(input: Omit<ArtifactIdentity, 'provenanceHash' | 'identityHash'>): ArtifactIdentity { const provenanceHash = sha256({ sourceHash: input.sourceHash, contractHash: input.contractHash, semanticHash: input.semanticHash, dependencyLockHash: input.dependencyLockHash, compilerHash: input.compilerHash, buildPlanHash: input.buildPlanHash, environmentHash: input.environmentHash, configurationHash: input.configurationHash }); const identityHash = sha256({ ...input, provenanceHash }); return { ...input, provenanceHash, identityHash }; }
export function createProvenanceSnapshot(nodes: ProvenanceNode[], edges: ProvenanceEdge[], controlEpoch?: number): ProvenanceSnapshot { const sortedNodes = [...nodes].sort((a, b) => a.id.localeCompare(b.id)); const sortedEdges = [...edges].sort((a, b) => `${a.from}:${a.to}:${a.type}`.localeCompare(`${b.from}:${b.to}:${b.type}`)); return { nodes: sortedNodes, edges: sortedEdges, controlEpoch, graphHash: sha256({ nodes: sortedNodes, edges: sortedEdges, controlEpoch }) }; }
export function traceProvenance(snapshot: ProvenanceSnapshot, start: string, direction: 'backward' | 'forward'): ProvenanceNode[] { const edges = direction === 'forward' ? snapshot.edges : snapshot.edges.map((edge) => ({ ...edge, from: edge.to, to: edge.from })); const adjacency = new Map<string, string[]>(); for (const edge of edges) adjacency.set(edge.from, [...(adjacency.get(edge.from) ?? []), edge.to]); const seen = new Set<string>(); const queue = [start]; while (queue.length) { const current = queue.shift()!; for (const next of adjacency.get(current) ?? []) if (!seen.has(next)) { seen.add(next); queue.push(next); } } return snapshot.nodes.filter((node) => seen.has(node.id)); }
export function detectProvenanceDrift(resourceId: string, expectedHash: string | undefined, observedHash: string | undefined, snapshot: ProvenanceSnapshot) { if (!expectedHash || !observedHash) return { resourceId, expectedHash, observedHash, status: 'UNKNOWN' as const, affectedNodeIds: [] as string[] }; if (expectedHash === observedHash) return { resourceId, expectedHash, observedHash, status: 'MATCH' as const, affectedNodeIds: [] as string[] }; return { resourceId, expectedHash, observedHash, status: 'DRIFT' as const, affectedNodeIds: traceProvenance(snapshot, resourceId, 'forward').map((node) => node.id) }; }
export function validateProductionArtifact(identity: ArtifactIdentity): ProvenanceStatus { if (!identity.artifactHash || !identity.provenanceHash || !identity.identityHash) return 'UNKNOWN'; const expected = createArtifactIdentity({ artifactId: identity.artifactId, artifactType: identity.artifactType, artifactHash: identity.artifactHash, sourceHash: identity.sourceHash, contractHash: identity.contractHash, semanticHash: identity.semanticHash, dependencyLockHash: identity.dependencyLockHash, compilerHash: identity.compilerHash, buildPlanHash: identity.buildPlanHash, environmentHash: identity.environmentHash, configurationHash: identity.configurationHash }); return expected.identityHash === identity.identityHash && expected.provenanceHash === identity.provenanceHash ? 'ARTIFACT_VERIFIED' : 'CONTRADICTED'; }
