import { createHash } from 'node:crypto'
import type { HttpClient } from './read-only-http-bank-adapter.js'
import type { ExecutionAttempt } from './execution-attempt.js'
import type { RecoveryObservation } from './execution-recovery.js'
import type { MoneyExecutionReconciliationAdapter } from './execution-reconciliation-adapter.js'
import type { LiveBrokerOrderRequest,LiveBrokerSubmitContext,LiveBrokerSubmissionResult,ManualLiveBrokerAdapter } from './manual-live-broker-contracts.js'
import type { ProductionBrokerAccountSnapshot,ProductionBrokerOrderObservation,ProductionBrokerPosition,ProductionBrokerReadSurface } from './production-broker-http-adapter.js'
import { money,parseDecimal } from './exact-money.js'
import type { ProviderExecutionEvent } from './execution-receipt-contracts.js'

export type AlpacaTradingMode='PAPER'|'LIVE'
export type AlpacaCredentials=Readonly<{keyId:string;secretKey:string}>
export type AlpacaCredentialResolver=()=>Promise<AlpacaCredentials>|AlpacaCredentials
export const ALPACA_PAPER_BASE_URL='https://paper-api.alpaca.markets'
export const ALPACA_LIVE_BASE_URL='https://api.alpaca.markets'

type AlpacaClientOptions=Readonly<{mode:AlpacaTradingMode;credentials:AlpacaCredentialResolver;fetchImpl?:HttpClient;timeoutMs?:number}>
type Json=Record<string,unknown>
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex')
const base=(mode:AlpacaTradingMode)=>mode==='LIVE'?ALPACA_LIVE_BASE_URL:ALPACA_PAPER_BASE_URL
const str=(v:unknown,label:string)=>{if(typeof v!=='string'||!v)throw new Error('MONEY_056_ALPACA_FIELD:'+label);return v}
const decimalToMinor=(v:unknown)=>{const s=str(v,'money');if(!/^-?\d+(\.\d+)?$/.test(s))throw new Error('MONEY_056_ALPACA_MONEY_INVALID');const [w,f='']=s.split('.');const sign=w.startsWith('-')?-1n:1n;const abs=w.replace('-','');return sign*(BigInt(abs)*100n+BigInt((f+'00').slice(0,2)))}
const minorToDecimal=(v:bigint)=>{const sign=v<0n?'-':'';const n=v<0n?-v:v;return sign+(n/100n).toString()+'.'+(n%100n).toString().padStart(2,'0')}
const instrumentToSymbol=(id:string)=>{const m=/^(stock|etf):([A-Za-z0-9.\-]+)$/.exec(id);if(!m)throw new Error('MONEY_056_ALPACA_INSTRUMENT_UNSUPPORTED');return m[2]!.toUpperCase()}
const qtyForNotional=(notionalMinor:string,limitPriceMinor:string)=>{const n=BigInt(notionalMinor),p=BigInt(limitPriceMinor);if(n<=0n||p<=0n)throw new Error('MONEY_056_ALPACA_ORDER_ECONOMICS_INVALID');const micros=n*1_000_000n/p;if(micros<=0n)throw new Error('MONEY_056_ALPACA_QTY_ZERO');const whole=micros/1_000_000n,frac=(micros%1_000_000n).toString().padStart(6,'0').replace(/0+$/,'');return frac?whole.toString()+'.'+frac:whole.toString()}
const state=(s:unknown):ProductionBrokerOrderObservation['state']=>{switch(String(s).toLowerCase()){case'filled':return'FILLED';case'partially_filled':return'PARTIALLY_FILLED';case'rejected':return'REJECTED';case'canceled':case'cancelled':case'expired':return'CANCELLED';case'accepted':case'new':case'pending_new':case'accepted_for_bidding':return'ACKNOWLEDGED';case'pending_cancel':case'pending_replace':case'held':return'PENDING';default:return'UNKNOWN'}}

export class AlpacaTradingApiClient implements ProductionBrokerReadSurface{
 readonly provider='alpaca';readonly baseUrl:string;private fetchImpl:HttpClient
 constructor(readonly mode:AlpacaTradingMode,private options:AlpacaClientOptions){if(mode!==options.mode)throw new Error('MONEY_056_ALPACA_MODE_MISMATCH');this.baseUrl=base(mode);this.fetchImpl=options.fetchImpl??fetch}
 private async request(path:string,init:RequestInit,now:string,allow404=false):Promise<{payload:unknown;requestId:string}>{
  const creds=await this.options.credentials();if(!creds.keyId||!creds.secretKey)throw new Error('MONEY_056_ALPACA_CREDENTIALS_MISSING')
  const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),this.options.timeoutMs??10000)
  try{const response=await this.fetchImpl(new URL(path,this.baseUrl),{...init,headers:{Accept:'application/json','APCA-API-KEY-ID':creds.keyId,'APCA-API-SECRET-KEY':creds.secretKey,'X-Jhadina-Observed-At':now,...init.headers},signal:controller.signal}),requestId=response.headers.get('x-request-id')??'missing-request-id';if(allow404&&response.status===404)return{payload:{not_found:true},requestId};if(!response.ok)throw new Error('MONEY_056_ALPACA_HTTP:'+response.status+':'+requestId);if(response.status===204)return{payload:{accepted:true},requestId};return{payload:await response.json(),requestId}}finally{clearTimeout(timeout)}
 }
 async getAccount(accountId:string,now:string):Promise<ProductionBrokerAccountSnapshot>{const {payload,requestId}=await this.request('/v2/account',{method:'GET'},now),p=payload as Json,id=str(p.id,'account.id');if(id!==accountId)throw new Error('MONEY_056_ALPACA_ACCOUNT_BINDING');return Object.freeze({provider:this.provider,accountId:id,currency:String(p.currency??'USD'),cashMinor:decimalToMinor(p.cash),settledCashMinor:decimalToMinor(p.cash),buyingPowerMinor:decimalToMinor(p.buying_power),asOf:now,evidenceIds:Object.freeze(['alpaca-account:'+requestId])})}
 async listPositions(accountId:string,now:string):Promise<readonly ProductionBrokerPosition[]>{const {payload,requestId}=await this.request('/v2/positions',{method:'GET'},now);if(!Array.isArray(payload))throw new Error('MONEY_056_ALPACA_POSITIONS_INVALID');return Object.freeze(payload.map((raw,index)=>{const p=raw as Json,symbol=str(p.symbol,'position.symbol').toUpperCase();return Object.freeze({provider:this.provider,accountId,instrumentId:'stock:'+symbol,quantity:str(p.qty,'position.qty'),marketValueMinor:decimalToMinor(p.market_value),currency:'USD',asOf:now,evidenceIds:Object.freeze(['alpaca-positions:'+requestId+':'+index])})}))}
 async getOrder(providerReference:string|undefined,clientOrderId:string,now:string):Promise<ProductionBrokerOrderObservation>{const path=providerReference?'/v2/orders/'+encodeURIComponent(providerReference):'/v2/orders:by_client_order_id?client_order_id='+encodeURIComponent(clientOrderId),{payload,requestId}=await this.request(path,{method:'GET'},now,true),p=payload as Json;if(p.not_found===true)return Object.freeze({providerReference:providerReference??'',clientOrderId,state:'NOT_FOUND',observedAt:now,evidenceIds:Object.freeze(['alpaca-order-not-found:'+requestId])});return Object.freeze({providerReference:str(p.id,'order.id'),clientOrderId:String(p.client_order_id??clientOrderId),state:state(p.status),observedAt:now,evidenceIds:Object.freeze(['alpaca-order:'+requestId])})}
 async submit(request:LiveBrokerOrderRequest,context:LiveBrokerSubmitContext):Promise<LiveBrokerSubmissionResult>{if(request.currency!=='USD')throw new Error('MONEY_056_ALPACA_CURRENCY_UNSUPPORTED');const symbol=instrumentToSymbol(request.instrumentId),body={symbol,qty:qtyForNotional(request.notionalMinor,request.limitPriceMinor),side:request.side.toLowerCase(),type:'limit',time_in_force:'day',limit_price:minorToDecimal(BigInt(request.limitPriceMinor)),client_order_id:request.clientOrderId,extended_hours:false};try{const {payload,requestId}=await this.request('/v2/orders',{method:'POST',headers:{'Content-Type':'application/json','X-Jhadina-Execution-Id':context.executionId},body:JSON.stringify(body)},context.now),p=payload as Json,providerReference=str(p.id,'order.id'),mapped=state(p.status);return Object.freeze({providerReference,providerEventId:'alpaca-submit:'+providerReference+':'+requestId,state:mapped==='REJECTED'?'REJECTED':mapped==='UNKNOWN'?'UNKNOWN':'ACKNOWLEDGED',occurredAt:String(p.submitted_at??context.now),observedAt:context.now,receivedAt:context.now,availableAt:context.now,evidenceIds:Object.freeze(['alpaca-submit:'+requestId])})}catch(error){const e='alpaca-submit-ambiguous:'+hash({executionId:context.executionId,error:String(error)});return Object.freeze({providerReference:'unknown:'+context.executionId,providerEventId:e,state:'UNKNOWN',occurredAt:context.now,observedAt:context.now,receivedAt:context.now,availableAt:context.now,evidenceIds:Object.freeze([e])})}}
 async cancelOrder(providerReference:string,now:string):Promise<ProductionBrokerOrderObservation>{const {requestId}=await this.request('/v2/orders/'+encodeURIComponent(providerReference),{method:'DELETE'},now);return Object.freeze({providerReference,clientOrderId:'',state:'PENDING',observedAt:now,evidenceIds:Object.freeze(['alpaca-cancel-accepted:'+requestId])})}
 async listFillEvents(attempt:ExecutionAttempt,now:string):Promise<readonly ProviderExecutionEvent[]>{if(attempt.provider!=='alpaca'||!attempt.providerReference)throw new Error('MONEY_056_ALPACA_FILL_ATTEMPT_INVALID');const {payload,requestId}=await this.request('/v2/account/activities/FILL?order_id='+encodeURIComponent(attempt.providerReference)+'&direction=asc&page_size=100',{method:'GET'},now);if(!Array.isArray(payload))throw new Error('MONEY_056_ALPACA_FILL_ACTIVITIES_INVALID');return Object.freeze(payload.map((raw,index)=>{const p=raw as Json,id=str(p.id,'activity.id'),qty=str(p.qty,'activity.qty'),price=parseDecimal(str(p.price,'activity.price')),leaves=String(p.leaves_qty??'0'),activitySide=String(p.side??attempt.actionSnapshot.side??'').toUpperCase();if(activitySide!=='BUY'&&activitySide!=='SELL')throw new Error('MONEY_056_ALPACA_FILL_SIDE_INVALID');const occurredAt=String(p.transaction_time??now);return Object.freeze({eventId:'alpaca-fill:'+id,providerEventId:id,provider:'alpaca',executionId:attempt.attemptId,actionFingerprint:attempt.actionFingerprint,providerReference:attempt.providerReference,state:leaves==='0'?'FILLED' as const:'PARTIALLY_FILLED' as const,economics:{orderId:attempt.providerReference!,instrumentId:attempt.actionSnapshot.instrumentId!,side:activitySide,filledQuantity:qty,fillPrice:money(price.coefficient,price.scale,attempt.actionSnapshot.currency)},occurredAt,observedAt:now,receivedAt:now,availableAt:now,sequence:index+2,evidenceIds:Object.freeze(['alpaca-fill:'+requestId+':'+id]),payloadHash:hash(p),provenanceHash:hash({requestId,id,orderId:attempt.providerReference}),authority:'EVIDENCE_ONLY' as const})}))}
}

export class AlpacaManualLiveBrokerAdapter implements ManualLiveBrokerAdapter,ProductionBrokerReadSurface,MoneyExecutionReconciliationAdapter{
 readonly provider='alpaca';readonly environment='LIVE' as const;readonly adapterId='money-056:alpaca-live';readonly adapterVersion=1
 constructor(private client:AlpacaTradingApiClient,private liveTradingEnabled:boolean){if(client.mode!=='LIVE'||client.baseUrl!==ALPACA_LIVE_BASE_URL)throw new Error('MONEY_056_ALPACA_LIVE_CLIENT_REQUIRED')}
 submitOrder(context:LiveBrokerSubmitContext,request:LiveBrokerOrderRequest){if(!this.liveTradingEnabled)throw new Error('MONEY_056_ALPACA_LIVE_DISABLED');return this.client.submit(request,context)}
 getAccount(accountId:string,now:string){return this.client.getAccount(accountId,now)}
 listPositions(accountId:string,now:string){return this.client.listPositions(accountId,now)}
 getOrder(providerReference:string|undefined,clientOrderId:string,now:string){return this.client.getOrder(providerReference,clientOrderId,now)}
 cancelOrder(providerReference:string,now:string){if(!this.liveTradingEnabled)throw new Error('MONEY_056_ALPACA_LIVE_DISABLED');return this.client.cancelOrder(providerReference,now)}
 canReconcile(attempt:ExecutionAttempt){return attempt.provider===this.provider&&attempt.operation==='money.trade.submit'}
 async reconcile(attempt:ExecutionAttempt):Promise<RecoveryObservation>{const checkedAt=new Date().toISOString(),o=await this.getOrder(attempt.providerReference,attempt.idempotencyKey,checkedAt),observedState=o.state==='FILLED'?'SUCCEEDED':o.state==='REJECTED'||o.state==='CANCELLED'?'FAILED':o.state==='NOT_FOUND'?'NOT_FOUND':o.state==='UNKNOWN'?'UNKNOWN':'PENDING';return{executionId:attempt.attemptId,proposalHash:attempt.actionFingerprint,providerOperation:attempt.operation,providerReference:o.providerReference||attempt.providerReference,observedState,evidence:{provider:'alpaca',order:o},evidenceHash:hash(o),adapterId:this.adapterId,adapterVersion:this.adapterVersion,checkedAt}}
}
export function createAlpacaPaperClient(options:Omit<AlpacaClientOptions,'mode'>){return new AlpacaTradingApiClient('PAPER',{...options,mode:'PAPER'})}
export function createAlpacaLiveAdapter(options:Omit<AlpacaClientOptions,'mode'>&{liveTradingEnabled:boolean}){const client=new AlpacaTradingApiClient('LIVE',{...options,mode:'LIVE'});return new AlpacaManualLiveBrokerAdapter(client,options.liveTradingEnabled)}
