import { createHash } from 'node:crypto'

export type BrokerEntitlementCapability='money.market.observe'|'money.trade.submit'
export type BrokerAccountEntitlementStatus='ACTIVE'|'REVOKED'|'EXPIRED'
export type BrokerAccountEntitlement=Readonly<{entitlementId:string;userId:string;provider:string;accountId:string;capabilities:readonly BrokerEntitlementCapability[];status:BrokerAccountEntitlementStatus;createdAt:string;expiresAt?:string;revokedAt?:string;evidenceIds:readonly string[];provenanceHash:string;authority:'ENTITLEMENT_ONLY'}>
export interface BrokerAccountEntitlementStore{put(entitlement:BrokerAccountEntitlement):Promise<void>|void;get(entitlementId:string):Promise<BrokerAccountEntitlement|undefined>|BrokerAccountEntitlement|undefined;findActive(input:{userId:string;provider:string;accountId:string;capability:BrokerEntitlementCapability;now:string}):Promise<BrokerAccountEntitlement|undefined>|BrokerAccountEntitlement|undefined;revoke(entitlementId:string,revokedAt:string):Promise<void>|void}
export function hash047(v:unknown){return createHash('sha256').update(JSON.stringify(v)).digest('hex')}
export function createBrokerAccountEntitlement(input:{entitlementId:string;userId:string;provider:string;accountId:string;capabilities:readonly BrokerEntitlementCapability[];createdAt:string;expiresAt?:string;evidenceIds:readonly string[]}):BrokerAccountEntitlement{for(const x of [input.entitlementId,input.userId,input.provider,input.accountId])if(!x.trim())throw new Error('MONEY_047_ENTITLEMENT_INCOMPLETE');if(!input.capabilities.length)throw new Error('MONEY_047_CAPABILITY_REQUIRED');if(!input.evidenceIds.length)throw new Error('MONEY_047_ENTITLEMENT_UNPROVEN');if(Number.isNaN(Date.parse(input.createdAt))||input.expiresAt&&Number.isNaN(Date.parse(input.expiresAt)))throw new Error('MONEY_047_ENTITLEMENT_TIME_INVALID');if(input.expiresAt&&input.expiresAt<=input.createdAt)throw new Error('MONEY_047_ENTITLEMENT_EXPIRY_INVALID');const capabilities=Object.freeze([...new Set(input.capabilities)].sort()) as readonly BrokerEntitlementCapability[],evidenceIds=Object.freeze([...new Set(input.evidenceIds)].sort()),provenanceHash=hash047({userId:input.userId,provider:input.provider,accountId:input.accountId,capabilities,createdAt:input.createdAt,expiresAt:input.expiresAt??null,evidenceIds});return Object.freeze({...input,capabilities,status:'ACTIVE',evidenceIds,provenanceHash,authority:'ENTITLEMENT_ONLY'})}
export function assertBrokerAccountEntitlement(e:BrokerAccountEntitlement,input:{userId:string;provider:string;accountId:string;capability:BrokerEntitlementCapability;now:string}){if(e.authority!=='ENTITLEMENT_ONLY'||e.status!=='ACTIVE')throw new Error('MONEY_047_ENTITLEMENT_NOT_ACTIVE');if(e.userId!==input.userId)throw new Error('MONEY_047_ENTITLEMENT_USER_MISMATCH');if(e.provider!==input.provider)throw new Error('MONEY_047_ENTITLEMENT_PROVIDER_MISMATCH');if(e.accountId!==input.accountId)throw new Error('MONEY_047_ENTITLEMENT_ACCOUNT_MISMATCH');if(!e.capabilities.includes(input.capability))throw new Error('MONEY_047_ENTITLEMENT_CAPABILITY_MISSING');if(e.expiresAt&&input.now>=e.expiresAt)throw new Error('MONEY_047_ENTITLEMENT_EXPIRED');if(!e.evidenceIds.length||!e.provenanceHash)throw new Error('MONEY_047_ENTITLEMENT_UNPROVEN')}
export async function requireBrokerAccountEntitlement(store:BrokerAccountEntitlementStore,input:{userId:string;provider:string;accountId:string;capability:BrokerEntitlementCapability;now:string}){const e=await store.findActive(input);if(!e)throw new Error('MONEY_047_ACCOUNT_NOT_ENTITLED');assertBrokerAccountEntitlement(e,input);return e}

export class InMemoryBrokerAccountEntitlementStore implements BrokerAccountEntitlementStore{private rows=new Map<string,BrokerAccountEntitlement>();put(e:BrokerAccountEntitlement){if(this.rows.has(e.entitlementId))throw new Error('MONEY_047_ENTITLEMENT_EXISTS');this.rows.set(e.entitlementId,e)}get(id:string){return this.rows.get(id)}findActive(input:{userId:string;provider:string;accountId:string;capability:BrokerEntitlementCapability;now:string}){return [...this.rows.values()].find(e=>e.status==='ACTIVE'&&e.userId===input.userId&&e.provider===input.provider&&e.accountId===input.accountId&&e.capabilities.includes(input.capability)&&(!e.expiresAt||e.expiresAt>input.now))}revoke(id:string,revokedAt:string){const e=this.rows.get(id);if(!e)throw new Error('MONEY_047_ENTITLEMENT_NOT_FOUND');this.rows.set(id,Object.freeze({...e,status:'REVOKED',revokedAt}))}}
