import type { AssetClass } from './financial-intelligence-contracts.js'
import { assertFusionEvidence, hash039, type DialecticalAssessment, type FinancialThesis, type FusionEvidence, type IntelligenceDomain, type OpportunityCandidateV2, type RegimeInterpretation, type ThesisAssumption, type ThesisDirection, type ThesisHorizon, type TransmissionEdge, type TransmissionPath } from './cross-asset-fusion-contracts.js'

function unique<T>(xs:readonly T[]):readonly T[]{return Object.freeze([...new Set(xs)])}
function clamp(n:number){return Math.max(0,Math.min(1,n))}
function directionalValue(d:ThesisDirection){return d==='BULLISH'?1:d==='BEARISH'?-1:0}
export function evidenceWeight(e:FusionEvidence):number{return e.strength*e.confidence}
export function buildFinancialThesis(input:{subjectId:string;instrumentIds:readonly string[];assetClasses:readonly AssetClass[];direction:ThesisDirection;horizon:ThesisHorizon;statement:string;evidence:readonly FusionEvidence[];assumptions:readonly ThesisAssumption[];informationCutoff:string;createdAt:string;expiresAt:string;modelId:string;modelVersion:string;methodologyVersion:string}):FinancialThesis{
 if(!input.subjectId||!input.instrumentIds.length||!input.statement.trim()||input.createdAt<input.informationCutoff||input.expiresAt<=input.createdAt)throw new Error('MONEY_039_THESIS_INPUT_INVALID')
 input.evidence.forEach(e=>assertFusionEvidence(e,input.informationCutoff))
 const deduped=[...new Map(input.evidence.map(e=>[e.evidenceId,e])).values()],support=deduped.filter(e=>e.stance==='SUPPORTS'),oppose=deduped.filter(e=>e.stance==='CONTRADICTS'),neutral=deduped.filter(e=>e.stance==='NEUTRAL')
 if(!support.length)throw new Error('MONEY_039_THESIS_SUPPORT_REQUIRED')
 const sourceGroups=new Map<string,FusionEvidence[]>();for(const e of deduped)sourceGroups.set(e.sourceGroup,[...(sourceGroups.get(e.sourceGroup)??[]),e])
 const independent=[...sourceGroups.values()].map(xs=>xs.sort((a,b)=>evidenceWeight(b)-evidenceWeight(a))[0]!),s=independent.filter(e=>e.stance==='SUPPORTS').reduce((n,e)=>n+evidenceWeight(e),0),o=independent.filter(e=>e.stance==='CONTRADICTS').reduce((n,e)=>n+evidenceWeight(e),0),confidence=clamp(s/(s+o+1))
 const ids=deduped.map(e=>e.evidenceId).sort(),inputHash=hash039({ids,assumptions:input.assumptions,direction:input.direction,horizon:input.horizon,cutoff:input.informationCutoff,modelId:input.modelId,modelVersion:input.modelVersion}),provenanceHash=hash039({subjectId:input.subjectId,instrumentIds:[...input.instrumentIds].sort(),inputHash,methodologyVersion:input.methodologyVersion})
 return Object.freeze({thesisId:`thesis:${provenanceHash}`,subjectId:input.subjectId,instrumentIds:unique([...input.instrumentIds].sort()),assetClasses:unique(input.assetClasses),direction:input.direction,horizon:input.horizon,statement:input.statement,supportingEvidenceIds:Object.freeze(support.map(e=>e.evidenceId).sort()),contradictingEvidenceIds:Object.freeze(oppose.map(e=>e.evidenceId).sort()),neutralEvidenceIds:Object.freeze(neutral.map(e=>e.evidenceId).sort()),assumptions:Object.freeze(input.assumptions.map(a=>Object.freeze({...a,evidenceIds:Object.freeze([...a.evidenceIds])}))),confidence,informationCutoff:input.informationCutoff,createdAt:input.createdAt,expiresAt:input.expiresAt,modelId:input.modelId,modelVersion:input.modelVersion,methodologyVersion:input.methodologyVersion,inputHash,provenanceHash,authority:'INTELLIGENCE_ONLY'})
}
export function assessThesisDialectically(thesis:FinancialThesis,evidence:readonly FusionEvidence[],contradictionIds:readonly string[]):DialecticalAssessment{
 const byId=new Map(evidence.map(e=>[e.evidenceId,e])),support=thesis.supportingEvidenceIds.map(id=>byId.get(id)).filter((x):x is FusionEvidence=>Boolean(x)),oppose=thesis.contradictingEvidenceIds.map(id=>byId.get(id)).filter((x):x is FusionEvidence=>Boolean(x)),supportScore=support.reduce((n,e)=>n+evidenceWeight(e),0),oppositionScore=oppose.reduce((n,e)=>n+evidenceWeight(e),0),netScore=supportScore-oppositionScore
 const invalid=thesis.assumptions.some(a=>a.status==='INVALIDATED'),status:DialecticalAssessment['status']=invalid?'INVALIDATED':contradictionIds.length||oppositionScore>=supportScore*.5?'CONTESTED':supportScore<.25?'WEAK':'SUPPORTED',provenanceHash=hash039({thesisId:thesis.thesisId,supportScore,oppositionScore,contradictionIds:[...contradictionIds].sort(),status})
 return Object.freeze({assessmentId:`dialectic:${provenanceHash}`,thesisId:thesis.thesisId,supportScore,oppositionScore,netScore,supportingDomains:Object.freeze([...unique(support.map(e=>e.domain))].sort()) as readonly IntelligenceDomain[],opposingDomains:Object.freeze([...unique(oppose.map(e=>e.domain))].sort()) as readonly IntelligenceDomain[],unresolvedContradictionIds:Object.freeze([...contradictionIds].sort()),status,provenanceHash})
}
export function interpretThesisInRegime(input:{thesis:FinancialThesis;regimeId:string;regimeLabel:string;compatibility:-1|0|1;regimeConfidence:number;rationaleEvidenceIds:readonly string[];regimeCutoff:string}):RegimeInterpretation{
 if(input.regimeCutoff>input.thesis.informationCutoff)throw new Error('MONEY_039_REGIME_FUTURE_LEAK');if(input.regimeConfidence<0||input.regimeConfidence>1||!input.rationaleEvidenceIds.length)throw new Error('MONEY_039_REGIME_INPUT_INVALID');const confidenceMultiplier=input.compatibility===1?1+(.25*input.regimeConfidence):input.compatibility===-1?1-(.5*input.regimeConfidence):1,provenanceHash=hash039({thesisId:input.thesis.thesisId,regimeId:input.regimeId,compatibility:input.compatibility,confidence:input.regimeConfidence,evidence:[...input.rationaleEvidenceIds].sort()});return Object.freeze({interpretationId:`regime-interpretation:${provenanceHash}`,thesisId:input.thesis.thesisId,regimeId:input.regimeId,regimeLabel:input.regimeLabel,compatibility:input.compatibility,confidenceMultiplier,rationaleEvidenceIds:Object.freeze([...input.rationaleEvidenceIds]),informationCutoff:input.thesis.informationCutoff,provenanceHash,authority:'ANALYSIS_ONLY'})
}
export function traceTransmission(input:{fromId:string;toId:string;edges:readonly TransmissionEdge[];cutoff:string;maxDepth?:number}):TransmissionPath{
 const usable=input.edges.filter(e=>e.availableAt<=input.cutoff&&(!e.expiresAt||input.cutoff<e.expiresAt)&&e.evidenceIds.length),max=input.maxDepth??4,queue:[string,TransmissionEdge[]][]=[[input.fromId,[]]],visited=new Set<string>()
 while(queue.length){const [node,path]=queue.shift()!;if(path.length>max)continue;if(node===input.toId&&path.length){const dir=path.reduce<number>((n,e)=>n*e.direction,1) as 1|-1,strength=path.reduce<number>((n,e)=>n*e.strength,1),conf=Math.min(...path.map(e=>e.confidence)),causal=path.every(e=>e.relationship==='CAUSAL_EVIDENCE')?'CAUSAL_EVIDENCE':'OBSERVED_OR_MODELED',ids=path.map(e=>e.edgeId),provenanceHash=hash039({ids,cutoff:input.cutoff});return Object.freeze({pathId:`transmission:${provenanceHash}`,fromId:input.fromId,toId:input.toId,edgeIds:Object.freeze(ids),netDirection:dir,effectiveStrength:strength,minimumConfidence:conf,causality:causal,informationCutoff:input.cutoff,provenanceHash,authority:'ANALYSIS_ONLY'})}if(visited.has(node))continue;visited.add(node);for(const e of usable)if(e.fromId===node&&!visited.has(e.toId))queue.push([e.toId,[...path,e]])}
 throw new Error('MONEY_039_TRANSMISSION_PATH_NOT_FOUND')
}
export function createOpportunityFromThesis(input:{thesis:FinancialThesis;assessment:DialecticalAssessment;regime?:RegimeInterpretation;expectedUpside:number;expectedDownside:number;liquidityStatus:'ASSESSED'|'UNKNOWN';riskStatus:'ASSESSED'|'UNKNOWN';invalidationConditions:readonly string[];expiresAt:string}):OpportunityCandidateV2{
 if(input.assessment.thesisId!==input.thesis.thesisId||input.assessment.status!=='SUPPORTED')throw new Error('MONEY_039_OPPORTUNITY_THESIS_NOT_SUPPORTED');if(input.expectedUpside<=0||input.expectedDownside>0||!input.invalidationConditions.length)throw new Error('MONEY_039_OPPORTUNITY_INPUT_INVALID');if(input.liquidityStatus!=='ASSESSED'||input.riskStatus!=='ASSESSED')throw new Error('MONEY_039_OPPORTUNITY_RISK_INCOMPLETE')
 const confidence=clamp(input.thesis.confidence*(input.regime?.confidenceMultiplier??1)),evidenceIds=Object.freeze([...unique([...input.thesis.supportingEvidenceIds,...input.thesis.contradictingEvidenceIds,...input.thesis.neutralEvidenceIds])].sort()),provenanceHash=hash039({thesisId:input.thesis.thesisId,assessmentId:input.assessment.assessmentId,confidence,expectedUpside:input.expectedUpside,expectedDownside:input.expectedDownside,evidenceIds})
 return Object.freeze({opportunityId:`opportunity:${provenanceHash}`,thesisId:input.thesis.thesisId,subjectId:input.thesis.subjectId,instrumentIds:input.thesis.instrumentIds,assetClasses:input.thesis.assetClasses,direction:input.thesis.direction,horizon:input.thesis.horizon,expectedUpside:input.expectedUpside,expectedDownside:input.expectedDownside,confidence,liquidityStatus:input.liquidityStatus,riskStatus:input.riskStatus,invalidationConditions:Object.freeze([...input.invalidationConditions]),evidenceIds,informationCutoff:input.thesis.informationCutoff,expiresAt:input.expiresAt,provenanceHash,authority:'NONE'})
}
export function expectedDirectionFromEvidence(evidence:readonly FusionEvidence[]):ThesisDirection{const score=evidence.reduce((n,e)=>n+directionalValue(e.direction)*evidenceWeight(e)*(e.stance==='CONTRADICTS'?-1:1),0);return score>.1?'BULLISH':score<-.1?'BEARISH':'NEUTRAL'}
