import type { AssetClass } from './financial-intelligence-contracts.js'
import type { CanonicalInformationEvent } from './information-integrity-engine.js'
import type { MacroStateSnapshot } from './macro-economic-engine.js'
import type { ValuationResult } from './fundamental-valuation-engine.js'
import type { FusionEvidence, IntelligenceDomain, ThesisDirection } from './cross-asset-fusion-contracts.js'
import { hash039 } from './cross-asset-fusion-contracts.js'

export type GovernedIntelligenceArtifact=Readonly<{artifactId:string;domain:'MARKET'|'PREDICTION'|'SHARK'|'CROSS_ASSET'|'OTHER';subjectId:string;instrumentId:string;assetClass:AssetClass;direction:ThesisDirection;strength:number;confidence:number;informationCutoff:string;expiresAt?:string;evidenceRefs:readonly string[];provenanceHash:string;financialAuthority:'NONE'}>
export function adaptGovernedIntelligence(a:GovernedIntelligenceArtifact,stance:FusionEvidence['stance'],sourceGroup:string):FusionEvidence{if(a.financialAuthority!=='NONE')throw new Error('MONEY_039_ADAPTER_AUTHORITY_FORBIDDEN');if(!a.evidenceRefs.length||!a.provenanceHash)throw new Error('MONEY_039_ADAPTER_EVIDENCE_REQUIRED');return Object.freeze({evidenceId:`fusion-evidence:${a.artifactId}`,domain:a.domain,subjectId:a.subjectId,instrumentId:a.instrumentId,assetClass:a.assetClass,stance,direction:a.direction,strength:a.strength,confidence:a.confidence,effectiveAt:a.informationCutoff,availableAt:a.informationCutoff,expiresAt:a.expiresAt,sourceGroup,inputHash:hash039({artifactId:a.artifactId,evidenceRefs:[...a.evidenceRefs].sort()}),provenanceHash:a.provenanceHash,authority:'NONE'})}

export function adaptMacroSnapshot(input:{snapshot:MacroStateSnapshot;subjectId:string;instrumentId?:string;assetClass?:AssetClass;direction:ThesisDirection;strength:number;confidence:number;stance:FusionEvidence['stance']}):FusionEvidence{if(input.snapshot.authority!=='INTELLIGENCE_ONLY')throw new Error('MONEY_039_MACRO_AUTHORITY_FORBIDDEN');return Object.freeze({evidenceId:`fusion-evidence:${input.snapshot.snapshotId}`,domain:'MACRO',subjectId:input.subjectId,instrumentId:input.instrumentId,assetClass:input.assetClass,stance:input.stance,direction:input.direction,strength:input.strength,confidence:input.confidence,effectiveAt:input.snapshot.informationCutoff,availableAt:input.snapshot.informationCutoff,sourceGroup:`macro:${input.snapshot.methodologyVersion}`,inputHash:input.snapshot.inputSnapshotHash,provenanceHash:input.snapshot.provenanceHash,authority:'NONE'})}

export function adaptInformationEvent(input:{event:CanonicalInformationEvent;subjectId:string;instrumentId?:string;assetClass?:AssetClass;direction:ThesisDirection;strength:number;stance:FusionEvidence['stance']}):FusionEvidence{if(input.event.authority!=='EVIDENCE_ONLY')throw new Error('MONEY_039_EVENT_AUTHORITY_FORBIDDEN');return Object.freeze({evidenceId:`fusion-evidence:${input.event.eventId}`,domain:'EVENT',subjectId:input.subjectId,instrumentId:input.instrumentId,assetClass:input.assetClass,stance:input.stance,direction:input.direction,strength:input.strength,confidence:input.event.confidence,effectiveAt:input.event.effectiveAt,availableAt:input.event.availableAt,sourceGroup:`event:${[...input.event.independentSourceGroups].sort().join('+')}`,inputHash:input.event.inputHash,provenanceHash:input.event.provenanceHash,authority:'NONE'})}

export function adaptValuation(input:{valuation:ValuationResult;subjectId:string;instrumentId?:string;assetClass?:AssetClass;direction:ThesisDirection;strength:number;confidence:number;stance:FusionEvidence['stance']}):FusionEvidence{if(input.valuation.authority!=='ANALYSIS_ONLY')throw new Error('MONEY_039_VALUATION_AUTHORITY_FORBIDDEN');return Object.freeze({evidenceId:`fusion-evidence:${input.valuation.valuationId}`,domain:'VALUATION',subjectId:input.subjectId,instrumentId:input.instrumentId,assetClass:input.assetClass,stance:input.stance,direction:input.direction,strength:input.strength,confidence:input.confidence,effectiveAt:input.valuation.informationCutoff,availableAt:input.valuation.informationCutoff,sourceGroup:`valuation:${input.valuation.methodologyVersion}`,inputHash:input.valuation.inputSnapshotHash,provenanceHash:input.valuation.provenanceHash,authority:'NONE'})}
export function assertFusionAdapterDomain(domain:IntelligenceDomain){if(!domain)throw new Error('MONEY_039_ADAPTER_DOMAIN_REQUIRED')}
