import { createHash } from 'node:crypto'
import type { AssetClass } from './financial-intelligence-contracts.js'

export type ThesisDirection='BULLISH'|'BEARISH'|'NEUTRAL'|'MIXED'|'UNKNOWN'
export type ThesisHorizon='INTRADAY'|'SHORT'|'MEDIUM'|'LONG'
export type IntelligenceDomain='MARKET'|'FUNDAMENTAL'|'VALUATION'|'MACRO'|'EVENT'|'PREDICTION'|'CROSS_ASSET'|'SHARK'|'RISK'|'OTHER'
export type EvidenceStance='SUPPORTS'|'CONTRADICTS'|'NEUTRAL'
export type FusionEvidence=Readonly<{evidenceId:string;domain:IntelligenceDomain;subjectId:string;instrumentId?:string;assetClass?:AssetClass;stance:EvidenceStance;direction:ThesisDirection;strength:number;confidence:number;effectiveAt:string;availableAt:string;expiresAt?:string;sourceGroup:string;inputHash:string;provenanceHash:string;authority:'NONE'}>
export type ThesisAssumption=Readonly<{assumptionId:string;statement:string;status:'ACTIVE'|'CHALLENGED'|'INVALIDATED';evidenceIds:readonly string[]}>
export type FinancialThesis=Readonly<{thesisId:string;subjectId:string;instrumentIds:readonly string[];assetClasses:readonly AssetClass[];direction:ThesisDirection;horizon:ThesisHorizon;statement:string;supportingEvidenceIds:readonly string[];contradictingEvidenceIds:readonly string[];neutralEvidenceIds:readonly string[];assumptions:readonly ThesisAssumption[];confidence:number;informationCutoff:string;createdAt:string;expiresAt:string;modelId:string;modelVersion:string;methodologyVersion:string;inputHash:string;provenanceHash:string;authority:'INTELLIGENCE_ONLY'}>
export type DialecticalAssessment=Readonly<{assessmentId:string;thesisId:string;supportScore:number;oppositionScore:number;netScore:number;supportingDomains:readonly IntelligenceDomain[];opposingDomains:readonly IntelligenceDomain[];unresolvedContradictionIds:readonly string[];status:'SUPPORTED'|'CONTESTED'|'WEAK'|'INVALIDATED';provenanceHash:string}>
export type RegimeInterpretation=Readonly<{interpretationId:string;thesisId:string;regimeId:string;regimeLabel:string;compatibility:-1|0|1;confidenceMultiplier:number;rationaleEvidenceIds:readonly string[];informationCutoff:string;provenanceHash:string;authority:'ANALYSIS_ONLY'}>
export type TransmissionEdge=Readonly<{edgeId:string;fromId:string;toId:string;channel:'RATE'|'FX'|'COMMODITY'|'LIQUIDITY'|'RISK'|'ISSUER'|'SUPPLY'|'DEMAND'|'SENTIMENT'|'RESOLUTION'|'OTHER';relationship:'OBSERVED'|'MODELED'|'CAUSAL_EVIDENCE';direction:1|-1;strength:number;confidence:number;effectiveAt:string;availableAt:string;expiresAt?:string;evidenceIds:readonly string[];methodologyVersion:string;provenanceHash:string}>
export type TransmissionPath=Readonly<{pathId:string;fromId:string;toId:string;edgeIds:readonly string[];netDirection:1|-1;effectiveStrength:number;minimumConfidence:number;causality:'OBSERVED_OR_MODELED'|'CAUSAL_EVIDENCE';informationCutoff:string;provenanceHash:string;authority:'ANALYSIS_ONLY'}>
export type OpportunityCandidateV2=Readonly<{opportunityId:string;thesisId:string;subjectId:string;instrumentIds:readonly string[];assetClasses:readonly AssetClass[];direction:ThesisDirection;horizon:ThesisHorizon;expectedUpside:number;expectedDownside:number;confidence:number;liquidityStatus:'ASSESSED'|'UNKNOWN';riskStatus:'ASSESSED'|'UNKNOWN';invalidationConditions:readonly string[];evidenceIds:readonly string[];informationCutoff:string;expiresAt:string;provenanceHash:string;authority:'NONE'}>
export type ThesisOutcome=Readonly<{outcomeId:string;thesisId:string;horizonEndedAt:string;observedAt:string;expectedDirection:ThesisDirection;realizedDirection:ThesisDirection;realizedReturn?:number;matched:boolean;evidenceIds:readonly string[];resolutionAuthority:string;ruleVersion:string;provenanceHash:string}>
export type ThesisCalibrationRecord=Readonly<{calibrationId:string;thesisId:string;outcomeId:string;forecastConfidence:number;matched:boolean;brierLikeError:number;createdAt:string;modelId:string;modelVersion:string;inputHash:string;authority:'LEARNING_ONLY'}>
export type FusionReplayManifest=Readonly<{replayId:string;informationCutoff:string;evidenceIds:readonly string[];thesisIds:readonly string[];opportunityIds:readonly string[];excludedFutureEvidenceIds:readonly string[];methodologyVersion:string;inputHash:string;provenanceHash:string;authority:'RESEARCH_ONLY'}>

export function hash039(value:unknown):string{return createHash('sha256').update(JSON.stringify(value)).digest('hex')}
export function assertFusionEvidence(e:FusionEvidence,cutoff:string){if(e.availableAt>cutoff)throw new Error('MONEY_039_FUTURE_EVIDENCE');if(e.expiresAt&&e.expiresAt<=cutoff)throw new Error('MONEY_039_STALE_EVIDENCE');if(e.strength<0||e.strength>1||e.confidence<0||e.confidence>1)throw new Error('MONEY_039_EVIDENCE_WEIGHT_INVALID');if(!e.sourceGroup||!e.inputHash||!e.provenanceHash)throw new Error('MONEY_039_EVIDENCE_UNPROVEN');if(e.authority!=='NONE')throw new Error('MONEY_039_EVIDENCE_AUTHORITY_FORBIDDEN')}
export function assertThesisBoundary(t:FinancialThesis){if(t.authority!=='INTELLIGENCE_ONLY')throw new Error('MONEY_039_THESIS_AUTHORITY_FORBIDDEN')}
export function assertOpportunityBoundary(o:OpportunityCandidateV2){if(o.authority!=='NONE')throw new Error('MONEY_039_OPPORTUNITY_AUTHORITY_FORBIDDEN')}
