import type { DecisionAssessment, DecisionCase } from './decision-workflow-contracts.js'
import { hash039, type FinancialThesis, type FusionEvidence, type FusionReplayManifest, type OpportunityCandidateV2, type ThesisCalibrationRecord, type ThesisDirection, type ThesisOutcome } from './cross-asset-fusion-contracts.js'

export type OpportunityDecisionIngress=Readonly<{decisionCase:DecisionCase;assessment:DecisionAssessment;opportunity:OpportunityCandidateV2;evidenceIds:readonly string[];authority:'NONE'}>
export function toDecisionWorkflow(input:{opportunity:OpportunityCandidateV2;accountId:string;requestedBy:string;createdAt:string;stressComplete:boolean;simulationComplete:boolean;calibrationSufficient:boolean;openContradictionIds:readonly string[]}):OpportunityDecisionIngress{
 const o=input.opportunity;if(o.authority!=='NONE')throw new Error('MONEY_039_OPPORTUNITY_AUTHORITY_FORBIDDEN');if(input.createdAt<o.informationCutoff)throw new Error('MONEY_039_DECISION_CREATED_BEFORE_CUTOFF')
 const blocked=!input.stressComplete||!input.simulationComplete||!input.calibrationSufficient||input.openContradictionIds.length>0||o.riskStatus!=='ASSESSED'||o.liquidityStatus!=='ASSESSED'
 const decisionCase:DecisionCase=Object.freeze({caseId:`fusion-decision:${o.opportunityId}`,accountId:input.accountId,subjectId:o.subjectId,requestedBy:input.requestedBy,informationCutoff:o.informationCutoff,createdAt:input.createdAt,status:blocked?'REQUIRES_REVIEW':'OPPORTUNITY',provenanceHash:o.provenanceHash})
 const assessment:DecisionAssessment=Object.freeze({caseId:decisionCase.caseId,evidenceStatus:o.evidenceIds.length?'DERIVED':'MISSING',freshnessStatus:'POINT_IN_TIME_BOUND',riskStatus:o.riskStatus,stressStatus:input.stressComplete?'ASSESSED':'NOT_PROVIDED',simulationStatus:input.simulationComplete?'ASSESSED':'NOT_RUN',liquidityStatus:o.liquidityStatus,calibrationStatus:input.calibrationSufficient?'SUFFICIENT':'INSUFFICIENT',authorityStatus:'MISSING',disposition:blocked?'REQUIRES_REVIEW':'OPPORTUNITY'})
 return Object.freeze({decisionCase,assessment,opportunity:o,evidenceIds:Object.freeze([...o.evidenceIds]),authority:'NONE'})
}
export function assertFusionDecisionCannotSelfAuthorize(x:OpportunityDecisionIngress){if(x.authority!=='NONE'||x.assessment.authorityStatus!=='MISSING'||x.assessment.disposition==='PROPOSAL_ELIGIBLE')throw new Error('MONEY_039_DECISION_AUTHORITY_VIOLATION')}

function matchedDirection(expected:ThesisDirection,realized:ThesisDirection){if(expected==='NEUTRAL')return realized==='NEUTRAL';if(expected==='MIXED'||expected==='UNKNOWN')return false;return expected===realized}
export function resolveThesisOutcome(input:{thesis:FinancialThesis;observedAt:string;realizedDirection:ThesisDirection;realizedReturn?:number;evidenceIds:readonly string[];resolutionAuthority:string;ruleVersion:string}):ThesisOutcome{
 if(input.observedAt<input.thesis.expiresAt)throw new Error('MONEY_039_OUTCOME_BEFORE_HORIZON');if(!input.evidenceIds.length||!input.resolutionAuthority||!input.ruleVersion)throw new Error('MONEY_039_OUTCOME_UNPROVEN');const matched=matchedDirection(input.thesis.direction,input.realizedDirection),provenanceHash=hash039({thesisId:input.thesis.thesisId,observedAt:input.observedAt,realizedDirection:input.realizedDirection,realizedReturn:input.realizedReturn,evidence:[...input.evidenceIds].sort(),authority:input.resolutionAuthority,ruleVersion:input.ruleVersion});return Object.freeze({outcomeId:`thesis-outcome:${provenanceHash}`,thesisId:input.thesis.thesisId,horizonEndedAt:input.thesis.expiresAt,observedAt:input.observedAt,expectedDirection:input.thesis.direction,realizedDirection:input.realizedDirection,realizedReturn:input.realizedReturn,matched,evidenceIds:Object.freeze([...input.evidenceIds]),resolutionAuthority:input.resolutionAuthority,ruleVersion:input.ruleVersion,provenanceHash})
}
export function calibrateThesisOutcome(input:{thesis:FinancialThesis;outcome:ThesisOutcome;createdAt:string}):ThesisCalibrationRecord{if(input.outcome.thesisId!==input.thesis.thesisId)throw new Error('MONEY_039_CALIBRATION_THESIS_MISMATCH');if(input.createdAt<input.outcome.observedAt)throw new Error('MONEY_039_CALIBRATION_BEFORE_OUTCOME');const target=input.outcome.matched?1:0,brierLikeError=(input.thesis.confidence-target)**2,inputHash=hash039({thesis:input.thesis.inputHash,outcome:input.outcome.provenanceHash}),calibrationId=`thesis-calibration:${hash039({inputHash,createdAt:input.createdAt})}`;return Object.freeze({calibrationId,thesisId:input.thesis.thesisId,outcomeId:input.outcome.outcomeId,forecastConfidence:input.thesis.confidence,matched:input.outcome.matched,brierLikeError,createdAt:input.createdAt,modelId:input.thesis.modelId,modelVersion:input.thesis.modelVersion,inputHash,authority:'LEARNING_ONLY'})}
export function assertCalibrationCannotMutateAuthority(x:ThesisCalibrationRecord){if(x.authority!=='LEARNING_ONLY')throw new Error('MONEY_039_CALIBRATION_AUTHORITY_VIOLATION')}

export function buildFusionReplayManifest(input:{cutoff:string;evidence:readonly FusionEvidence[];theses:readonly FinancialThesis[];opportunities:readonly OpportunityCandidateV2[];methodologyVersion:string}):FusionReplayManifest{
 const eligible=input.evidence.filter(e=>e.availableAt<=input.cutoff&&(!e.expiresAt||input.cutoff<e.expiresAt)).sort((a,b)=>a.evidenceId.localeCompare(b.evidenceId)),future=input.evidence.filter(e=>e.availableAt>input.cutoff).map(e=>e.evidenceId).sort(),eligibleIds=new Set(eligible.map(e=>e.evidenceId)),theses=input.theses.filter(t=>t.informationCutoff<=input.cutoff&&[...t.supportingEvidenceIds,...t.contradictingEvidenceIds,...t.neutralEvidenceIds].every(id=>eligibleIds.has(id))).sort((a,b)=>a.thesisId.localeCompare(b.thesisId)),thesisIds=new Set(theses.map(t=>t.thesisId)),opps=input.opportunities.filter(o=>o.informationCutoff<=input.cutoff&&thesisIds.has(o.thesisId)&&o.evidenceIds.every(id=>eligibleIds.has(id))).sort((a,b)=>a.opportunityId.localeCompare(b.opportunityId))
 const manifest={informationCutoff:input.cutoff,evidenceIds:eligible.map(e=>e.evidenceId),thesisIds:theses.map(t=>t.thesisId),opportunityIds:opps.map(o=>o.opportunityId),excludedFutureEvidenceIds:future,methodologyVersion:input.methodologyVersion},inputHash=hash039(manifest),provenanceHash=hash039({inputHash,authority:'RESEARCH_ONLY'})
 return Object.freeze({replayId:`fusion-replay:${provenanceHash}`,...manifest,evidenceIds:Object.freeze(manifest.evidenceIds),thesisIds:Object.freeze(manifest.thesisIds),opportunityIds:Object.freeze(manifest.opportunityIds),excludedFutureEvidenceIds:Object.freeze(future),inputHash,provenanceHash,authority:'RESEARCH_ONLY'})
}
