import { createHash } from 'node:crypto'

export type RawMarketObservation=Readonly<{rawId:string;provider:string;instrumentQuery:string;field:string;rawValue:string;unit?:string;currency?:string;effectiveAt:string;observedAt:string;receivedAt:string;availableAt:string;sourceRef:string;sourceHash:string}>
export type ValidatedObservation=Readonly<RawMarketObservation & {instrumentId:string;status:'VALID'|'STALE'|'MALFORMED'|'FUTURE_LEAK'|'UNRESOLVED_INSTRUMENT'|'UNIT_ERROR'|'CURRENCY_ERROR';validationVersion:string}>
export type NormalizedObservation=Readonly<{observationId:string;rawId:string;provider:string;instrumentId:string;field:string;value:string;unit?:string;currency?:string;effectiveAt:string;availableAt:string;normalizationVersion:string;provenanceHash:string}>
export type ReconciledValue=Readonly<{reconciliationId:string;instrumentId:string;field:string;value:string;effectiveAt:string;availableAt:string;sourceObservationIds:readonly string[];status:'CANONICAL'|'CONFLICTING'|'INSUFFICIENT';methodologyVersion:string;provenanceHash:string}>
export function validateObservation(raw:RawMarketObservation,input:{instrumentId?:string;cutoff:string;maxAgeMs:number;now:string;validationVersion:string}):ValidatedObservation{let status:ValidatedObservation['status']='VALID';if(!input.instrumentId)status='UNRESOLVED_INSTRUMENT';else if(!raw.rawValue.trim()||!raw.sourceHash||!raw.sourceRef)status='MALFORMED';else if(raw.availableAt>input.cutoff)status='FUTURE_LEAK';else if(Date.parse(input.now)-Date.parse(raw.observedAt)>input.maxAgeMs)status='STALE';return Object.freeze({...raw,instrumentId:input.instrumentId??'',status,validationVersion:input.validationVersion})}
export function normalizeObservation(v:ValidatedObservation,normalizationVersion:string):NormalizedObservation{if(v.status!=='VALID')throw new Error('MONEY_NORMALIZATION_REQUIRES_VALID_OBSERVATION');const provenanceHash=createHash('sha256').update(JSON.stringify(v)).digest('hex');return Object.freeze({observationId:`obs:${v.rawId}:${normalizationVersion}`,rawId:v.rawId,provider:v.provider,instrumentId:v.instrumentId,field:v.field,value:v.rawValue.trim(),unit:v.unit,currency:v.currency,effectiveAt:v.effectiveAt,availableAt:v.availableAt,normalizationVersion,provenanceHash})}
export function reconcileObservations(xs:readonly NormalizedObservation[],methodologyVersion:string):ReconciledValue{if(!xs.length)throw new Error('MONEY_RECONCILIATION_EMPTY');const key=`${xs[0]!.instrumentId}:${xs[0]!.field}`;if(xs.some(x=>`${x.instrumentId}:${x.field}`!==key))throw new Error('MONEY_RECONCILIATION_KEY_MISMATCH');const groups=new Map<string,NormalizedObservation[]>();for(const x of xs)groups.set(x.value,[...(groups.get(x.value)??[]),x]);const ranked=[...groups.entries()].sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0]));const winner=ranked[0]!;const tied=ranked.length>1&&ranked[1]![1].length===winner[1].length;const status=tied?'CONFLICTING':'CANONICAL';const effectiveTimes=xs.map(x=>x.effectiveAt).sort(),availableTimes=xs.map(x=>x.availableAt).sort();const effectiveAt=effectiveTimes[effectiveTimes.length-1]!,availableAt=availableTimes[availableTimes.length-1]!;const ids=xs.map(x=>x.observationId).sort();const provenanceHash=createHash('sha256').update(JSON.stringify({ids,methodologyVersion,status,winner:winner[0]})).digest('hex');return Object.freeze({reconciliationId:`recon:${provenanceHash}`,instrumentId:xs[0]!.instrumentId,field:xs[0]!.field,value:winner[0],effectiveAt,availableAt,sourceObservationIds:Object.freeze(ids),status,methodologyVersion,provenanceHash})}
export type CanonicalMarketSnapshot=Readonly<{snapshotId:string;informationCutoff:string;reconciliationIds:readonly string[];methodologyVersion:string;inputHash:string;provenanceHash:string}>
export function buildCanonicalMarketSnapshot(values:readonly ReconciledValue[],cutoff:string,methodologyVersion:string):CanonicalMarketSnapshot{if(values.some(v=>v.status!=='CANONICAL'||v.availableAt>cutoff))throw new Error('MONEY_CANONICAL_MARKET_INPUT_INVALID');const ids=values.map(v=>v.reconciliationId).sort(),inputHash=createHash('sha256').update(JSON.stringify(values.map(v=>v.provenanceHash).sort())).digest('hex'),provenanceHash=createHash('sha256').update(JSON.stringify({cutoff,ids,methodologyVersion,inputHash})).digest('hex');return Object.freeze({snapshotId:`market:${provenanceHash}`,informationCutoff:cutoff,reconciliationIds:Object.freeze(ids),methodologyVersion,inputHash,provenanceHash})}

export type EvidenceGateInput=Readonly<{evidenceIds:readonly string[];fresh:boolean;contradictionIds:readonly string[];riskComplete:boolean;stressComplete:boolean;simulationComplete:boolean;calibrationSufficient:boolean;authority:'NONE'|'AUTHORIZED'}>
export type EvidenceGateResult=Readonly<{status:'PASS'|'BLOCKED'|'REVIEW';reasons:readonly string[]}>
export function evaluateEvidenceGate(i:EvidenceGateInput):EvidenceGateResult{const reasons:string[]=[];if(!i.evidenceIds.length)reasons.push('EVIDENCE_MISSING');if(!i.fresh)reasons.push('EVIDENCE_STALE');if(!i.riskComplete)reasons.push('RISK_INCOMPLETE');if(!i.stressComplete)reasons.push('STRESS_INCOMPLETE');if(!i.simulationComplete)reasons.push('SIMULATION_INCOMPLETE');if(!i.calibrationSufficient)reasons.push('CALIBRATION_INSUFFICIENT');if(i.authority!=='AUTHORIZED')reasons.push('AUTHORITY_MISSING');if(i.contradictionIds.length)reasons.push('CONTRADICTIONS_PRESENT');return Object.freeze({status:reasons.length===0?'PASS':i.contradictionIds.length?'REVIEW':'BLOCKED',reasons:Object.freeze(reasons)})}
export type Contradiction=Readonly<{contradictionId:string;subjectId:string;claim:string;leftEvidenceId:string;rightEvidenceId:string;detectedAt:string;status:'OPEN'|'RESOLVED';resolutionEvidenceId?:string}>
export function assertNoOpenContradictions(xs:readonly Contradiction[]){if(xs.some(x=>x.status==='OPEN'))throw new Error('MONEY_DECISION_CONTRADICTION_OPEN')}
export type DecisionOutcome=Readonly<{caseId:string;proposalId?:string;executionId?:string;expected:string;actual:string;observedAt:string;evidenceIds:readonly string[];predictionError?:number}>
export type DecisionPostmortem=Readonly<{caseId:string;outcomeId:string;lessons:readonly string[];calibrationImpact:string;createdAt:string;inputSnapshotHash:string}>
