import { createHash } from 'node:crypto'
import type { ExactMoney } from './canonical-financial-state.js'
export type ProviderExecutionEventState='ACKNOWLEDGED'|'PARTIALLY_FILLED'|'FILLED'|'REJECTED'|'CANCELLED'|'PENDING'|'UNKNOWN'
export type ProviderExecutionEconomics=Readonly<{orderId:string;instrumentId:string;side:'BUY'|'SELL';filledQuantity:string;fillPrice?:ExactMoney;fee?:ExactMoney;settlementStatus?:'EXPECTED'|'PENDING'|'SETTLED'|'FAILED'|'DISPUTED'|'UNKNOWN';settlementExpectedAt?:string;settlementActualAt?:string}>
export type ProviderExecutionEvent=Readonly<{eventId:string;providerEventId:string;provider:string;executionId:string;actionFingerprint:string;providerReference?:string;state:ProviderExecutionEventState;economics?:ProviderExecutionEconomics;occurredAt:string;observedAt:string;receivedAt:string;availableAt:string;sequence?:number;evidenceIds:readonly string[];payloadHash:string;provenanceHash:string;authority:'EVIDENCE_ONLY'}>
export type ExecutionReceipt=Readonly<{receiptId:string;executionId:string;provider:string;providerEventId:string;state:ProviderExecutionEventState;providerReference?:string;eventHash:string;recordedAt:string;evidenceIds:readonly string[];authority:'EVIDENCE_ONLY'}>
export type ProviderEventClaim=Readonly<{claimKey:string;eventId:string;payloadHash:string;disposition:'ACCEPTED'|'DUPLICATE';authority:'NONE'}>
export type ExecutionReconciliationDecision=Readonly<{decisionId:string;executionId:string;eventId:string;disposition:'APPLY'|'IGNORE_DUPLICATE'|'BLOCK_CONFLICT'|'MANUAL_REVIEW';nextState:'SUCCEEDED'|'FAILED'|'UNKNOWN'|'RECOVERY_REQUIRED';reasonCodes:readonly string[];providerReference?:string;authority:'RECONCILIATION_ONLY'}>
export type JournalPostingIntent=Readonly<{postingIntentId:string;executionId:string;eventId:string;kind:'FILL'|'FEE'|'SETTLEMENT';payloadHash:string;evidenceIds:readonly string[];authority:'NONE'}>
export type FinancialOutboxRecord=Readonly<{outboxId:string;aggregateId:string;eventType:'EXECUTION_RECEIPT'|'FILL_READY'|'FEE_READY'|'SETTLEMENT_READY';payloadHash:string;createdAt:string;status:'PENDING';authority:'NONE'}>
export type ExecutionReceiptLearning=Readonly<{learningId:string;executionId:string;terminalState:ProviderExecutionEventState;eventCount:number;unknownObserved:boolean;latencyMs:number;createdAt:string;evidenceIds:readonly string[];authority:'LEARNING_ONLY'}>
export type ExecutionReceiptReplay=Readonly<{replayId:string;executionId:string;informationCutoff:string;includedEventIds:readonly string[];excludedFutureEventIds:readonly string[];terminalState:ProviderExecutionEventState;inputHash:string;provenanceHash:string;authority:'RESEARCH_ONLY'}>
export function hash042(v:unknown){return createHash('sha256').update(JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x)).digest('hex')}
export function assertProviderExecutionEvent(e:ProviderExecutionEvent){for(const x of [e.eventId,e.providerEventId,e.provider,e.executionId,e.actionFingerprint,e.payloadHash,e.provenanceHash])if(!x)throw new Error('MONEY_042_EVENT_INCOMPLETE');if(!e.evidenceIds.length)throw new Error('MONEY_042_EVENT_UNPROVEN');if(e.authority!=='EVIDENCE_ONLY')throw new Error('MONEY_042_EVENT_AUTHORITY_FORBIDDEN');const times=[e.occurredAt,e.observedAt,e.receivedAt,e.availableAt].map(Date.parse);if(times.some(Number.isNaN)||times[1]!<times[0]||times[2]!<times[1]||times[3]!<times[2])throw new Error('MONEY_042_EVENT_CLOCK_INVALID');if(e.sequence!==undefined&&(!Number.isInteger(e.sequence)||e.sequence<0))throw new Error('MONEY_042_EVENT_SEQUENCE_INVALID')}
