import type { ExecutionAttempt } from './execution-attempt.js'
import { createFill, createSettlement, type Fill, type Settlement } from './accounting-lifecycle-contracts.js'
import { parseDecimal } from './exact-money.js'
import { assertProviderExecutionEvent, hash042, type ExecutionReceipt, type ExecutionReceiptLearning, type ExecutionReceiptReplay, type ExecutionReconciliationDecision, type FinancialOutboxRecord, type JournalPostingIntent, type ProviderEventClaim, type ProviderExecutionEvent, type ProviderExecutionEventState } from './execution-receipt-contracts.js'

const terminal=new Set<ProviderExecutionEventState>(['FILLED','REJECTED','CANCELLED'])
const rank:Record<ProviderExecutionEventState,number>={UNKNOWN:0,PENDING:1,ACKNOWLEDGED:2,PARTIALLY_FILLED:3,FILLED:4,REJECTED:4,CANCELLED:4}
export function claimProviderEvent(event:ProviderExecutionEvent,existing:readonly ProviderExecutionEvent[]):ProviderEventClaim{assertProviderExecutionEvent(event);const prior=existing.find(e=>e.provider===event.provider&&e.providerEventId===event.providerEventId);if(prior&&prior.payloadHash!==event.payloadHash)throw new Error('MONEY_042_PROVIDER_EVENT_ID_CONFLICT');return Object.freeze({claimKey:event.provider+':'+event.providerEventId,eventId:event.eventId,payloadHash:event.payloadHash,disposition:prior?'DUPLICATE':'ACCEPTED',authority:'NONE'})}
export function createExecutionReceipt(event:ProviderExecutionEvent,recordedAt:string):ExecutionReceipt{assertProviderExecutionEvent(event);if(Date.parse(recordedAt)<Date.parse(event.receivedAt))throw new Error('MONEY_042_RECEIPT_BEFORE_EVENT');const eventHash=hash042(event);return Object.freeze({receiptId:'execution-receipt:'+eventHash,executionId:event.executionId,provider:event.provider,providerEventId:event.providerEventId,state:event.state,providerReference:event.providerReference,eventHash,recordedAt,evidenceIds:Object.freeze([...event.evidenceIds]),authority:'EVIDENCE_ONLY'})}
const decision=(attempt:ExecutionAttempt,event:ProviderExecutionEvent,disposition:ExecutionReconciliationDecision['disposition'],nextState:ExecutionReconciliationDecision['nextState'],reasonCodes:readonly string[])=>Object.freeze({decisionId:'reconcile:'+hash042({a:attempt.attemptId,e:event.eventId,disposition,nextState,reasonCodes}),executionId:attempt.attemptId,eventId:event.eventId,disposition,nextState,reasonCodes:Object.freeze([...reasonCodes]),providerReference:event.providerReference,authority:'RECONCILIATION_ONLY' as const})
export function reconcileProviderEvent(input:{attempt:ExecutionAttempt;event:ProviderExecutionEvent;priorEvents:readonly ProviderExecutionEvent[]}):ExecutionReconciliationDecision{const {attempt,event}=input;assertProviderExecutionEvent(event);const claim=claimProviderEvent(event,input.priorEvents);if(claim.disposition==='DUPLICATE')return decision(attempt,event,'IGNORE_DUPLICATE',attempt.state==='SUCCEEDED'?'SUCCEEDED':attempt.state==='FAILED'?'FAILED':'UNKNOWN',['DUPLICATE_PROVIDER_EVENT'])
 const reasons:string[]=[];if(event.executionId!==attempt.attemptId)reasons.push('EXECUTION_ID_MISMATCH');if(event.actionFingerprint!==attempt.actionFingerprint)reasons.push('ACTION_FINGERPRINT_MISMATCH');if(event.provider!==attempt.provider)reasons.push('PROVIDER_MISMATCH');if(attempt.providerReference&&event.providerReference&&attempt.providerReference!==event.providerReference)reasons.push('PROVIDER_REFERENCE_MISMATCH');if(reasons.length)return decision(attempt,event,'BLOCK_CONFLICT','RECOVERY_REQUIRED',reasons)
 const prior=input.priorEvents.filter(e=>e.executionId===attempt.attemptId&&e.provider===attempt.provider).sort((a,b)=>(a.sequence??-1)-(b.sequence??-1)||a.availableAt.localeCompare(b.availableAt)),last=prior.at(-1);if(last&&terminal.has(last.state)&&event.state!==last.state)return decision(attempt,event,'MANUAL_REVIEW','RECOVERY_REQUIRED',['TERMINAL_STATE_CONFLICT']);if(last&&event.sequence!==undefined&&last.sequence!==undefined&&event.sequence<last.sequence)return decision(attempt,event,'MANUAL_REVIEW','RECOVERY_REQUIRED',['OUT_OF_ORDER_PROVIDER_EVENT']);if(last&&rank[event.state]<rank[last.state]&&event.state!=='UNKNOWN')return decision(attempt,event,'MANUAL_REVIEW','RECOVERY_REQUIRED',['STATE_REGRESSION'])
 const next=event.state==='FILLED'?'SUCCEEDED':event.state==='REJECTED'||event.state==='CANCELLED'?'FAILED':event.state==='UNKNOWN'?'RECOVERY_REQUIRED':'UNKNOWN';return decision(attempt,event,'APPLY',next,[event.state])}
export function projectFillFromProviderEvent(event:ProviderExecutionEvent):Fill|undefined{assertProviderExecutionEvent(event);if(event.state!=='PARTIALLY_FILLED'&&event.state!=='FILLED')return undefined;const x=event.economics;if(!x?.fillPrice||parseDecimal(x.filledQuantity).coefficient<=0n)throw new Error('MONEY_042_FILL_ECONOMICS_INCOMPLETE');return createFill({fillId:'fill:'+event.provider+':'+event.providerEventId,orderId:x.orderId,instrumentId:x.instrumentId,quantity:x.filledQuantity,price:x.fillPrice,executedAt:event.occurredAt,providerExecutionId:event.providerReference??event.executionId,feeIds:x.fee?['fee:'+event.provider+':'+event.providerEventId]:[],evidenceRefs:Object.freeze([...event.evidenceIds,event.eventId])})}
export function projectSettlementFromProviderEvent(event:ProviderExecutionEvent,fill:Fill):Settlement|undefined{const x=event.economics;if(!x?.settlementStatus)return undefined;if(!x.settlementExpectedAt)throw new Error('MONEY_042_SETTLEMENT_EXPECTED_TIME_REQUIRED');return createSettlement({settlementId:'settlement:'+event.provider+':'+event.providerEventId,orderId:fill.orderId,fillIds:[fill.fillId],status:x.settlementStatus,expectedAt:x.settlementExpectedAt,actualAt:x.settlementActualAt,evidenceRefs:Object.freeze([...event.evidenceIds,event.eventId])})}
export function buildJournalPostingIntents(event:ProviderExecutionEvent):readonly JournalPostingIntent[]{const fill=projectFillFromProviderEvent(event),out:JournalPostingIntent[]=[];if(fill)out.push(Object.freeze({postingIntentId:'posting:fill:'+fill.fillId,executionId:event.executionId,eventId:event.eventId,kind:'FILL',payloadHash:hash042(fill),evidenceIds:fill.evidenceRefs,authority:'NONE'}));if(fill&&event.economics?.fee)out.push(Object.freeze({postingIntentId:'posting:fee:'+event.providerEventId,executionId:event.executionId,eventId:event.eventId,kind:'FEE',payloadHash:hash042(event.economics.fee),evidenceIds:Object.freeze([...event.evidenceIds,event.eventId]),authority:'NONE'}));if(fill&&event.economics?.settlementStatus)out.push(Object.freeze({postingIntentId:'posting:settlement:'+event.providerEventId,executionId:event.executionId,eventId:event.eventId,kind:'SETTLEMENT',payloadHash:hash042(projectSettlementFromProviderEvent(event,fill)),evidenceIds:Object.freeze([...event.evidenceIds,event.eventId]),authority:'NONE'}));return Object.freeze(out)}
export function buildExecutionOutbox(event:ProviderExecutionEvent,receipt:ExecutionReceipt,createdAt:string):readonly FinancialOutboxRecord[]{if(receipt.executionId!==event.executionId||receipt.eventHash!==hash042(event))throw new Error('MONEY_042_RECEIPT_EVENT_MISMATCH');const rows:FinancialOutboxRecord[]=[Object.freeze({outboxId:'outbox:receipt:'+receipt.receiptId,aggregateId:event.executionId,eventType:'EXECUTION_RECEIPT',payloadHash:hash042(receipt),createdAt,status:'PENDING',authority:'NONE'})];for(const p of buildJournalPostingIntents(event))rows.push(Object.freeze({outboxId:'outbox:'+p.postingIntentId,aggregateId:event.executionId,eventType:p.kind==='FILL'?'FILL_READY':p.kind==='FEE'?'FEE_READY':'SETTLEMENT_READY',payloadHash:p.payloadHash,createdAt,status:'PENDING',authority:'NONE'}));return Object.freeze(rows)}
export function learnFromExecutionReceipts(input:{executionId:string;events:readonly ProviderExecutionEvent[];createdAt:string}):ExecutionReceiptLearning{const xs=input.events.filter(e=>e.executionId===input.executionId).sort((a,b)=>a.availableAt.localeCompare(b.availableAt));if(!xs.length)throw new Error('MONEY_042_LEARNING_EVENTS_REQUIRED');xs.forEach(assertProviderExecutionEvent);const first=xs[0]!,last=xs.at(-1)!,latency=Math.max(0,Date.parse(last.receivedAt)-Date.parse(first.occurredAt));return Object.freeze({learningId:'receipt-learning:'+hash042({executionId:input.executionId,events:xs.map(x=>x.eventId)}),executionId:input.executionId,terminalState:last.state,eventCount:xs.length,unknownObserved:xs.some(x=>x.state==='UNKNOWN'),latencyMs:latency,createdAt:input.createdAt,evidenceIds:Object.freeze([...new Set(xs.flatMap(x=>x.evidenceIds))].sort()),authority:'LEARNING_ONLY'})}
export function buildExecutionReceiptReplay(input:{executionId:string;events:readonly ProviderExecutionEvent[];informationCutoff:string}):ExecutionReceiptReplay{const eligible=input.events.filter(e=>e.executionId===input.executionId&&e.availableAt<=input.informationCutoff).sort((a,b)=>a.availableAt.localeCompare(b.availableAt)||a.eventId.localeCompare(b.eventId)),future=input.events.filter(e=>e.executionId===input.executionId&&e.availableAt>input.informationCutoff).map(e=>e.eventId).sort();if(!eligible.length)throw new Error('MONEY_042_REPLAY_NO_AVAILABLE_EVIDENCE');eligible.forEach(assertProviderExecutionEvent);const terminalState=eligible.at(-1)!.state,inputHash=hash042({executionId:input.executionId,cutoff:input.informationCutoff,eventIds:eligible.map(e=>e.eventId)}),provenanceHash=hash042({inputHash,future});return Object.freeze({replayId:'receipt-replay:'+provenanceHash,executionId:input.executionId,informationCutoff:input.informationCutoff,includedEventIds:Object.freeze(eligible.map(e=>e.eventId)),excludedFutureEventIds:Object.freeze(future),terminalState,inputHash,provenanceHash,authority:'RESEARCH_ONLY'})}
