import { createHash } from 'node:crypto'
import { addDecimal,addMoney,compareMoney,money,multiplyDecimal,multiplyMoney,parseDecimal,subtractDecimal,subtractMoney,type ExactDecimal,type MoneyAmount } from './exact-money.js'
import type { OrderState,SettlementState } from './accounting-lifecycle-contracts.js'

export type FinancialEvent =
 | Readonly<{eventId:string;kind:'CASH';accountId:string;effectiveAt:string;recordedAt:string;amount:MoneyAmount;bucket:'SETTLED'|'UNSETTLED'|'RESERVED';evidenceRefs:readonly string[]}>
 | Readonly<{eventId:string;kind:'FILL';accountId:string;effectiveAt:string;recordedAt:string;fillId:string;orderId:string;instrumentId:string;side:'BUY'|'SELL';quantity:string;price:MoneyAmount;fee?:MoneyAmount;lotSelectionPolicy?:'FIFO'|'LIFO'|'HIFO'|'SPECIFIC_ID';specificLotIds?:readonly string[];evidenceRefs:readonly string[]}>
 | Readonly<{eventId:string;kind:'SETTLEMENT';accountId:string;effectiveAt:string;recordedAt:string;settlementId:string;fillId:string;status:SettlementState;evidenceRefs:readonly string[]}>
 | Readonly<{eventId:string;kind:'CORPORATE_ACTION';accountId:string;effectiveAt:string;recordedAt:string;instrumentId:string;action:'SPLIT'|'REVERSE_SPLIT'|'DIVIDEND'|'MERGER'|'SPINOFF'|'SYMBOL_CHANGE'|'DELISTING';ratio?:string;cashAmount?:MoneyAmount;successorInstrumentId?:string;basisAllocationBps?:number;evidenceRefs:readonly string[]}>
 | Readonly<{eventId:string;kind:'COST';accountId:string;effectiveAt:string;recordedAt:string;costType:'COMMISSION'|'EXCHANGE'|'REGULATORY'|'BORROW'|'FUNDING'|'TAX'|'OTHER';amount:MoneyAmount;evidenceRefs:readonly string[]}>

export type LotState=Readonly<{lotId:string;instrumentId:string;openedAt:string;quantity:ExactDecimal;unitCost:MoneyAmount;remainingCostBasis?:MoneyAmount;sourceFillId:string}>
export type DerivedFinancialState=Readonly<{accountId:string;informationCutoff:string;settledCash:MoneyAmount;unsettledCash:MoneyAmount;reservedCash:MoneyAmount;availableCash:MoneyAmount;positions:Readonly<Record<string,string>>;lots:readonly LotState[];instrumentStatuses:Readonly<Record<string,'ACTIVE'|'DELISTED'>>;realizedPnl:MoneyAmount;costs:MoneyAmount;sourceEventIds:readonly string[];stateHash:string}>

function hash(value:unknown){return createHash('sha256').update(JSON.stringify(value,(_,v)=>typeof v==='bigint'?v.toString():v)).digest('hex')}
function requireEvidence(e:FinancialEvent){if(!e.eventId||!e.evidenceRefs.length)throw new Error('MONEY_EVENT_UNPROVEN');if(Number.isNaN(Date.parse(e.recordedAt))||Number.isNaN(Date.parse(e.effectiveAt)))throw new Error('MONEY_EVENT_CLOCK_INVALID')}
function zero(currency:string){return money(0n,0,currency)}
function qtext(q:ExactDecimal){const sign=q.coefficient<0n?'-':'';const d=(q.coefficient<0n?-q.coefficient:q.coefficient).toString().padStart(q.scale+1,'0');return sign+(q.scale?d.slice(0,-q.scale)+'.'+d.slice(-q.scale):d)}
function positive(q:ExactDecimal,label:string){if(q.coefficient<=0n)throw new Error(label)}
function lotBasis(lot:LotState){return lot.remainingCostBasis??multiplyMoney(lot.unitCost,lot.quantity)}
function allocatedBasis(basis:MoneyAmount,take:ExactDecimal,whole:ExactDecimal){const s=Math.max(take.scale,whole.scale),t=take.coefficient*10n**BigInt(s-take.scale),w=whole.coefficient*10n**BigInt(s-whole.scale);if(t===w)return basis;const precision=12;return money(basis.coefficient*t*10n**BigInt(precision)/w,basis.scale+precision,basis.currency)}
function selectedLotIndexes(lots:readonly LotState[],instrumentId:string,policy:'FIFO'|'LIFO'|'HIFO'|'SPECIFIC_ID',specificIds:readonly string[]){let xs=lots.map((lot,index)=>({lot,index})).filter(x=>x.lot.instrumentId===instrumentId&&x.lot.quantity.coefficient>0n);if(policy==='FIFO')xs.sort((a,b)=>a.lot.openedAt.localeCompare(b.lot.openedAt)||a.lot.lotId.localeCompare(b.lot.lotId));if(policy==='LIFO')xs.sort((a,b)=>b.lot.openedAt.localeCompare(a.lot.openedAt)||a.lot.lotId.localeCompare(b.lot.lotId));if(policy==='HIFO')xs.sort((a,b)=>-compareMoney(a.lot.unitCost,b.lot.unitCost)||a.lot.openedAt.localeCompare(b.lot.openedAt));if(policy==='SPECIFIC_ID'){const order=new Map(specificIds.map((id,i)=>[id,i]));xs=xs.filter(x=>order.has(x.lot.lotId)).sort((a,b)=>order.get(a.lot.lotId)!-order.get(b.lot.lotId)!)}return xs}
function consumeLongLots(input:{lots:LotState[];instrumentId:string;quantity:ExactDecimal;sellPrice:MoneyAmount;policy:'FIFO'|'LIFO'|'HIFO'|'SPECIFIC_ID';specificIds:readonly string[]}):MoneyAmount{let remaining=input.quantity,realized=zero(input.sellPrice.currency);for(const {lot,index} of selectedLotIndexes(input.lots,input.instrumentId,input.policy,input.specificIds)){if(remaining.coefficient<=0n)break;const s=Math.max(remaining.scale,lot.quantity.scale),r=remaining.coefficient*10n**BigInt(s-remaining.scale),q=lot.quantity.coefficient*10n**BigInt(s-lot.quantity.scale),take=Object.freeze({coefficient:r<q?r:q,scale:s});const proceeds=multiplyMoney(input.sellPrice,take),basis=allocatedBasis(lotBasis(lot),take,lot.quantity);realized=addMoney(realized,subtractMoney(proceeds,basis));const nextQ=subtractDecimal(lot.quantity,take),nextBasis=subtractMoney(lotBasis(lot),basis);input.lots[index]=Object.freeze({...lot,quantity:nextQ,remainingCostBasis:nextBasis});remaining=subtractDecimal(remaining,take)}if(remaining.coefficient!==0n)throw new Error('MONEY_SELL_EXCEEDS_LONG_LOTS');return realized}
function movePosition(qty:Map<string,ExactDecimal>,from:string,to:string,multiplier:ExactDecimal){const current=qty.get(from);if(!current)return;qty.delete(from);qty.set(to,addDecimal(qty.get(to)??{coefficient:0n,scale:0},multiplyDecimal(current,multiplier)))}
function applyLotMultiplier(lots:LotState[],instrumentId:string,multiplier:ExactDecimal,successor?:string){for(let i=0;i<lots.length;i++){const lot=lots[i]!;if(lot.instrumentId!==instrumentId||lot.quantity.coefficient===0n)continue;lots[i]=Object.freeze({...lot,instrumentId:successor??lot.instrumentId,quantity:multiplyDecimal(lot.quantity,multiplier),remainingCostBasis:lotBasis(lot)})}}

export function deriveFinancialState(input:{accountId:string;currency:string;informationCutoff:string;events:readonly FinancialEvent[]}):DerivedFinancialState{
 let settled=zero(input.currency),unsettled=zero(input.currency),reserved=zero(input.currency),realized=zero(input.currency),costs=zero(input.currency)
 const qty=new Map<string,ExactDecimal>(),lots:LotState[]=[],fillCash=new Map<string,MoneyAmount>(),statuses=new Map<string,'ACTIVE'|'DELISTED'>()
 const events=input.events.filter(e=>e.accountId===input.accountId&&e.recordedAt<=input.informationCutoff).sort((a,b)=>a.effectiveAt.localeCompare(b.effectiveAt)||a.recordedAt.localeCompare(b.recordedAt)||a.eventId.localeCompare(b.eventId))
 const seen=new Set<string>()
 for(const e of events){requireEvidence(e);if(seen.has(e.eventId))throw new Error('MONEY_DUPLICATE_EVENT');seen.add(e.eventId)
  if(e.kind==='CASH'){if(e.amount.currency!==input.currency)throw new Error('MONEY_STATE_CURRENCY_MISMATCH');if(e.bucket==='SETTLED')settled=addMoney(settled,e.amount);else if(e.bucket==='UNSETTLED')unsettled=addMoney(unsettled,e.amount);else reserved=addMoney(reserved,e.amount)}
  if(e.kind==='COST'){costs=addMoney(costs,e.amount);settled=subtractMoney(settled,e.amount)}
  if(e.kind==='FILL'){const q=parseDecimal(e.quantity);positive(q,'MONEY_FILL_QUANTITY_INVALID');if(e.price.currency!==input.currency||e.fee&&e.fee.currency!==input.currency)throw new Error('MONEY_STATE_CURRENCY_MISMATCH');const signed=e.side==='BUY'?q:{coefficient:-q.coefficient,scale:q.scale},prev=qty.get(e.instrumentId)??{coefficient:0n,scale:0},next=addDecimal(prev,signed);qty.set(e.instrumentId,next);statuses.set(e.instrumentId,statuses.get(e.instrumentId)??'ACTIVE')
   const notional=multiplyMoney(e.price,q);if(e.side==='BUY'){unsettled=subtractMoney(unsettled,notional);const basis=e.fee?addMoney(notional,e.fee):notional;lots.push(Object.freeze({lotId:'lot:'+e.fillId,instrumentId:e.instrumentId,openedAt:e.effectiveAt,quantity:q,unitCost:e.price,remainingCostBasis:basis,sourceFillId:e.fillId}))}else{const pnl=consumeLongLots({lots,instrumentId:e.instrumentId,quantity:q,sellPrice:e.price,policy:e.lotSelectionPolicy??'FIFO',specificIds:e.specificLotIds??[]});realized=addMoney(realized,pnl);unsettled=addMoney(unsettled,notional)}
   let cashDelta=e.side==='BUY'?money(-notional.coefficient,notional.scale,notional.currency):notional;if(e.fee){costs=addMoney(costs,e.fee);unsettled=subtractMoney(unsettled,e.fee);cashDelta=subtractMoney(cashDelta,e.fee);if(e.side==='SELL')realized=subtractMoney(realized,e.fee)}fillCash.set(e.fillId,cashDelta)
  }
  if(e.kind==='SETTLEMENT'&&e.status==='SETTLED'){const delta=fillCash.get(e.fillId);if(!delta)throw new Error('MONEY_SETTLEMENT_FILL_UNKNOWN');unsettled=subtractMoney(unsettled,delta);settled=addMoney(settled,delta)}
  if(e.kind==='CORPORATE_ACTION'&&(e.action==='SPLIT'||e.action==='REVERSE_SPLIT')){if(!e.ratio)throw new Error('MONEY_CORPORATE_ACTION_RATIO_REQUIRED');const r=parseDecimal(e.ratio);positive(r,'MONEY_CORPORATE_ACTION_RATIO_INVALID');const p=qty.get(e.instrumentId);if(p)qty.set(e.instrumentId,multiplyDecimal(p,r));applyLotMultiplier(lots,e.instrumentId,r)}
  if(e.kind==='CORPORATE_ACTION'&&e.action==='DIVIDEND'){if(!e.cashAmount)throw new Error('MONEY_DIVIDEND_AMOUNT_REQUIRED');unsettled=addMoney(unsettled,e.cashAmount)}
  if(e.kind==='CORPORATE_ACTION'&&e.action==='SYMBOL_CHANGE'){if(!e.successorInstrumentId)throw new Error('MONEY_CORPORATE_ACTION_SUCCESSOR_REQUIRED');movePosition(qty,e.instrumentId,e.successorInstrumentId,{coefficient:1n,scale:0});applyLotMultiplier(lots,e.instrumentId,{coefficient:1n,scale:0},e.successorInstrumentId);statuses.delete(e.instrumentId);statuses.set(e.successorInstrumentId,'ACTIVE')}
  if(e.kind==='CORPORATE_ACTION'&&e.action==='MERGER'){if(!e.successorInstrumentId||!e.ratio)throw new Error('MONEY_MERGER_SUCCESSOR_RATIO_REQUIRED');if(e.cashAmount)throw new Error('MONEY_MERGER_MIXED_CONSIDERATION_REQUIRES_REVIEW');const r=parseDecimal(e.ratio);positive(r,'MONEY_CORPORATE_ACTION_RATIO_INVALID');movePosition(qty,e.instrumentId,e.successorInstrumentId,r);applyLotMultiplier(lots,e.instrumentId,r,e.successorInstrumentId);statuses.delete(e.instrumentId);statuses.set(e.successorInstrumentId,'ACTIVE')}
  if(e.kind==='CORPORATE_ACTION'&&e.action==='SPINOFF'){if(!e.successorInstrumentId||!e.ratio||!Number.isInteger(e.basisAllocationBps)||e.basisAllocationBps!<=0||e.basisAllocationBps!>=10000)throw new Error('MONEY_SPINOFF_BASIS_ALLOCATION_REQUIRED');const r=parseDecimal(e.ratio),parent=qty.get(e.instrumentId);positive(r,'MONEY_CORPORATE_ACTION_RATIO_INVALID');if(parent)qty.set(e.successorInstrumentId,addDecimal(qty.get(e.successorInstrumentId)??{coefficient:0n,scale:0},multiplyDecimal(parent,r)));for(const lot of [...lots])if(lot.instrumentId===e.instrumentId&&lot.quantity.coefficient>0n){const basis=lotBasis(lot),childBasis=money(basis.coefficient*BigInt(e.basisAllocationBps!)/10000n,basis.scale,basis.currency),parentBasis=subtractMoney(basis,childBasis),index=lots.findIndex(x=>x.lotId===lot.lotId);lots[index]=Object.freeze({...lot,remainingCostBasis:parentBasis});lots.push(Object.freeze({lotId:'spinoff:'+e.eventId+':'+lot.lotId,instrumentId:e.successorInstrumentId,openedAt:e.effectiveAt,quantity:multiplyDecimal(lot.quantity,r),unitCost:zero(input.currency),remainingCostBasis:childBasis,sourceFillId:lot.sourceFillId}))}statuses.set(e.successorInstrumentId,'ACTIVE')}
  if(e.kind==='CORPORATE_ACTION'&&e.action==='DELISTING')statuses.set(e.instrumentId,'DELISTED')
 }
 const available=subtractMoney(settled,reserved),positions=Object.freeze(Object.fromEntries([...qty.entries()].filter(([,v])=>v.coefficient!==0n).map(([k,v])=>[k,qtext(v)]))),activeLots=Object.freeze(lots.filter(l=>l.quantity.coefficient!==0n)),instrumentStatuses=Object.freeze(Object.fromEntries([...statuses.entries()].filter(([id])=>positions[id]!==undefined)))
 const sourceEventIds=Object.freeze(events.map(e=>e.eventId)),payload={accountId:input.accountId,cutoff:input.informationCutoff,settled,unsettled,reserved,positions,lots:activeLots,instrumentStatuses,realized,costs,sourceEventIds}
 return Object.freeze({accountId:input.accountId,informationCutoff:input.informationCutoff,settledCash:settled,unsettledCash:unsettled,reservedCash:reserved,availableCash:available,positions,lots:activeLots,instrumentStatuses,realizedPnl:realized,costs,sourceEventIds,stateHash:hash(payload)})
}

const allowed:Readonly<Record<OrderState,readonly OrderState[]>>={
 PROPOSED:['AUTHORIZED','REJECTED','CANCELLED'],AUTHORIZED:['SUBMITTED','CANCELLED','EXPIRED'],SUBMITTED:['ACKNOWLEDGED','PARTIALLY_FILLED','FILLED','REJECTED','CANCEL_REQUESTED','BROKER_ERROR','UNKNOWN'],ACKNOWLEDGED:['PARTIALLY_FILLED','FILLED','CANCEL_REQUESTED','EXPIRED','EXTERNALLY_CANCELLED','BROKER_ERROR','UNKNOWN'],PARTIALLY_FILLED:['PARTIALLY_FILLED','FILLED','CANCEL_REQUESTED','EXTERNALLY_CANCELLED','BROKER_ERROR','UNKNOWN'],FILLED:[],REJECTED:[],CANCEL_REQUESTED:['CANCELLED','FILLED','PARTIALLY_FILLED','EXTERNALLY_CANCELLED','UNKNOWN'],CANCELLED:[],EXPIRED:[],EXTERNALLY_CANCELLED:[],BROKER_ERROR:['UNKNOWN'],UNKNOWN:['ACKNOWLEDGED','PARTIALLY_FILLED','FILLED','REJECTED','CANCELLED','EXTERNALLY_CANCELLED','BROKER_ERROR']
}
export function assertOrderTransition(from:OrderState,to:OrderState){if(!allowed[from].includes(to))throw new Error('MONEY_ORDER_TRANSITION_INVALID:'+from+'->'+to)}

export type FxObservation=Readonly<{fxId:string;base:string;quote:string;rate:ExactDecimal;effectiveAt:string;availableAt:string;provider:string;evidenceRefs:readonly string[];provenanceHash:string}>
export type FxConversionResult=Readonly<{gross:MoneyAmount;cost:MoneyAmount;net:MoneyAmount;path:readonly string[];providers:readonly string[];authority:'DERIVED_ONLY'}>
function fxCandidates(observations:readonly FxObservation[],cutoff:string,priority:readonly string[]){const rank=new Map(priority.map((p,i)=>[p,i]));return observations.filter(x=>x.availableAt<=cutoff&&x.evidenceRefs.length&&x.provenanceHash&&x.rate.coefficient>0n).sort((a,b)=>(rank.get(a.provider)??999)-(rank.get(b.provider)??999)||b.effectiveAt.localeCompare(a.effectiveAt)||a.fxId.localeCompare(b.fxId))}
export function convertMoneyWithFxPathAtCutoff(input:{amount:MoneyAmount;target:string;observations:readonly FxObservation[];cutoff:string;providerPriority?:readonly string[];conversionCostBps?:number}):FxConversionResult{const target=input.target.toUpperCase(),costBps=input.conversionCostBps??0;if(!Number.isInteger(costBps)||costBps<0||costBps>=10000)throw new Error('MONEY_FX_COST_BPS_INVALID');if(input.amount.currency===target)return Object.freeze({gross:input.amount,cost:zero(target),net:input.amount,path:Object.freeze([]),providers:Object.freeze([]),authority:'DERIVED_ONLY'});const xs=fxCandidates(input.observations,input.cutoff,input.providerPriority??[]),direct=xs.find(x=>x.base===input.amount.currency&&x.quote===target);let gross:MoneyAmount,path:string[],providers:string[];if(direct){gross=money(multiplyMoney(input.amount,direct.rate).coefficient,multiplyMoney(input.amount,direct.rate).scale,target);path=[direct.fxId];providers=[direct.provider]}else{const first=xs.filter(x=>x.base===input.amount.currency),pair=first.map(a=>({a,b:xs.find(b=>b.base===a.quote&&b.quote===target)})).find(x=>x.b);if(!pair?.b)throw new Error('MONEY_FX_RATE_UNAVAILABLE');const mid=multiplyMoney(input.amount,pair.a.rate),out=multiplyMoney(money(mid.coefficient,mid.scale,pair.a.quote),pair.b.rate);gross=money(out.coefficient,out.scale,target);path=[pair.a.fxId,pair.b.fxId];providers=[pair.a.provider,pair.b.provider]}const cost=multiplyMoney(gross,{coefficient:BigInt(costBps),scale:4}),net=subtractMoney(gross,cost);return Object.freeze({gross,cost,net,path:Object.freeze(path),providers:Object.freeze(providers),authority:'DERIVED_ONLY'})}
export function convertMoneyAtCutoff(amount:MoneyAmount,target:string,observations:readonly FxObservation[],cutoff:string):MoneyAmount{return convertMoneyWithFxPathAtCutoff({amount,target,observations,cutoff}).net}

export type LeverageState=Readonly<{equity:MoneyAmount;grossExposure:MoneyAmount;netExposure:MoneyAmount;borrowedCapital:MoneyAmount;initialMarginRequired:MoneyAmount;maintenanceMarginRequired:MoneyAmount;maxLeverage:string}>
export function assertLiveLeveragePolicy(s:LeverageState){if(s.maxLeverage!=='1')throw new Error('MONEY_LIVE_LEVERAGE_DISABLED');if(compareMoney(s.borrowedCapital,zero(s.borrowedCapital.currency))>0)throw new Error('MONEY_LIVE_BORROW_DISABLED')}
export type LiquidationEvent=Readonly<{liquidationId:string;accountId:string;reason:'MARGIN'|'RISK'|'PROVIDER'|'REGULATORY';forced:boolean;instrumentId:string;quantity:string;observedAt:string;evidenceRefs:readonly string[]}>
export function assertLiquidation(e:LiquidationEvent){if(!e.forced||!e.evidenceRefs.length)throw new Error('MONEY_LIQUIDATION_UNPROVEN')}
