import test from 'node:test';
import assert from 'node:assert/strict';
import type { ActionIdentityVerifier, AuditRpcClient } from '@jhadina/action-core';
import type { BankAdapter, MoneyAdapterContext } from './bank-adapter.js';
import { createGovernedProviderTransactionReadExecutor } from './governed-provider-transaction-read.js';
function identity(userId='u1'):ActionIdentityVerifier{return {async verify(){return {userId,sessionId:'s1'}}}}
const supabase:AuditRpcClient={async rpc(){return {data:null,error:null}}};
function provider(onRead?:()=>void):BankAdapter{return {provider:'plaid',async listAccounts(){return []},async listTransactions(_ctx:MoneyAdapterContext,accountId:string){onRead?.();return [{id:'t1',accountId,amount:12,currency:'USD',occurredAt:'2026-09-20',description:'Merchant'}]}}}
const config={plaid:{enabled:true,credentialRef:'money/plaid/default',capabilities:['money.account.read','money.transaction.read'] as const}};
test('governed transaction read returns owned account transactions',async()=>{const executor=createGovernedProviderTransactionReadExecutor({identityVerifier:identity(),supabase,provider:provider(),providerConfig:config,ownership:(userId)=>({userId,accountIds:new Set(['acc1'])})});const result=await executor.execute({id:'r1',userId:'u1',type:'money.transaction.read',requestedAt:new Date().toISOString(),action:{capability:'money.transaction.read',accountId:'acc1'}});assert.equal(result.length,1)});
test('unowned account fails before provider read',async()=>{let called=false;const executor=createGovernedProviderTransactionReadExecutor({identityVerifier:identity(),supabase,provider:provider(()=>{called=true}),providerConfig:config,ownership:(userId)=>({userId,accountIds:new Set(['other'])})});await assert.rejects(()=>executor.execute({id:'r2',userId:'u1',type:'money.transaction.read',requestedAt:new Date().toISOString(),action:{capability:'money.transaction.read',accountId:'acc1'}}),/MONEY_ACCOUNT_ACCESS_DENIED/);assert.equal(called,false)});
test('transaction read rejects identity mismatch',async()=>{const executor=createGovernedProviderTransactionReadExecutor({identityVerifier:identity('actual'),supabase,provider:provider(),providerConfig:config,ownership:(userId)=>({userId,accountIds:new Set(['acc1'])})});await assert.rejects(()=>executor.execute({id:'r3',userId:'claimed',type:'money.transaction.read',requestedAt:new Date().toISOString(),action:{capability:'money.transaction.read',accountId:'acc1'}}),/Action identity mismatch/)});
