// Public surface for @jhadina/money-core.
export type { MoneyCapability, CapabilityRisk } from './capabilities.js';
export { getMoneyCapability, requiresMoneyApproval, isMoneyCapability } from './capabilities.js';
export type { MoneyAccount, MoneyTransaction, MoneyAdapterContext, BankAdapter } from './bank-adapter.js';
export { assertCapability } from './bank-adapter.js';
export type { ResolvedCredential, CredentialResolver } from './credential-resolver.js';
export { EnvironmentCredentialResolver, credentialRefToEnvKey } from './credential-resolver.js';
export type { ProviderHealthStatus, ProviderConfig, ProviderHealth, ProviderHealthChecker } from './provider-health.js';
export { MoneyProviderHealthGate } from './provider-health.js';
export { MoneyProviderRegistry } from './provider-registry.js';
export type { ProviderAdapterBuilder, ProviderAdapterFactoryOptions } from './provider-adapter-factory.js';
export { ProviderAdapterFactory } from './provider-adapter-factory.js';
export type { AccountReadAction, AccountReadHandlerDeps } from './account-read-handler.js';
export { MoneyAccountReadHandler } from './account-read-handler.js';
export type { GovernedAccountReadDeps, MoneyAccountReadRequest } from './governed-account-read.js';
export { MONEY_CORE_SECURITY_POLICY, createMoneyAccountReadSecurityRequest, createMoneyAccountReadHandler, createMoneySecurityCore } from './governed-account-read.js';
export type { ProductionMoneyAccountReadOptions } from './production-account-read.js';
export { createProductionMoneyAccountReadExecutor } from './production-account-read.js';
export type { GovernedProviderAccountReadOptions } from './governed-provider-account-read.js';
export { createGovernedProviderAccountReadExecutor } from './governed-provider-account-read.js';
export type { HttpClient, ReadOnlyHttpBankAdapterOptions } from './read-only-http-bank-adapter.js';
export { ReadOnlyHttpBankAdapter } from './read-only-http-bank-adapter.js';
export type { PlaidReadOnlyAdapterOptions } from './plaid-read-only-adapter.js';
export { PlaidReadOnlyAdapter } from './plaid-read-only-adapter.js';
export { buildPlaidReadOnlyAdapter, createPlaidReadOnlyAdapterBuilder } from './plaid-provider-builder.js';
export { PLAID_READ_ONLY_CONFIG, PLAID_SANDBOX_BASE_URL, assertPlaidSandboxBaseUrl, createPlaidProviderAdapterFactory } from './plaid-provider-registration.js';
export type { AssetClass, EvidenceQuality, EvidenceRef, FinancialHypothesis, PredictionDistribution, OpportunityCandidate, AllocationDecision, CapitalAllocationRequest, CapitalAllocationDecision, CanonicalFinancialAction } from './financial-intelligence-contracts.js';
export { assertIntelligenceOnly, assertProbability, assertPositiveAmount } from './financial-intelligence-contracts.js';
export type { IssuerStatus, IssuerIdentifierType, IssuerRelationshipType, IssuerInstrumentRelationshipType, FilingStatus, FactStatus, FundamentalStateStatus, ExactFinancialValue, Issuer, IssuerIdentifier, IssuerRelationship, IssuerInstrumentRelationship, Filing, FilingDocument, FinancialFactDimension, FinancialFact, FactRevision, FundamentalState } from './issuer-reality-contracts.js';
export { assertIssuerIdentifier, selectIssuerIdentifiersAt, assertPointInTimeFact, factWasAvailableAt, selectFactsAtCutoff, revisionsForFact, selectActiveFactsAtCutoff, buildFundamentalState, assertIssuerInstrumentRelationship, relationshipWasEffectiveAt, selectIssuerInstrumentRelationshipsAt } from './issuer-reality-contracts.js';
export type { SharkFundamentalInput } from './shark-fundamental-adapter.js';
export { toSharkFundamentalInput } from './shark-fundamental-adapter.js';
export type { AccountingValue, AccountingTreatment, PeriodKind, NormalizationStatus, AccountingConcept, NormalizationRule, NormalizedMetric, TtmMetric } from './fundamental-normalization-contracts.js';
export { assertAccountingValue, assertNormalizedMetric, normalizeReportedFact, buildTtmMetric } from './fundamental-normalization-contracts.js';
export type { EconomicIndicatorType, ObservationStatus, MacroRegimeType, MacroFactorType, EconomicIndicator, EconomicVintage, EconomicObservation, MacroFactor, MacroRegime, RegimeTransition, MacroSensitivity, MonetaryPolicyEvent, EconomicEvent, MacroSurprise, MacroSnapshot } from './macro-economic-contracts.js';
export { assertEconomicObservation, observationWasAvailableAt, selectEconomicObservationsAtCutoff, assertEconomicVintage, buildMacroSnapshot, calculateMacroSurprise } from './macro-economic-contracts.js';
export type { InvoiceEvidence, InvoiceValidationState, InvoiceAccountingCandidate } from './invoice-evidence.js';
export { validateInvoiceAmount, validateExtractionConfidence } from './invoice-evidence.js';
export type { PermitState, ExecutionAction, PermitBinding, ExecutionPermit, PermitIssuerInput, PermitVerificationContext, PermitStore } from './execution-permit.js';
export { canonicalizeAction, fingerprintAction, issueExecutionPermit, verifyExecutionPermit, consumeExecutionPermit } from './execution-permit.js';
export type { PostgresPermitStoreOptions } from './postgres-permit-store.js';
export { PostgresPermitStore } from './postgres-permit-store.js';
export type { MoneyExecutionPermit } from './execution-permit-gate.js';
export { toExecutionAction, authorizeAndConsumeMoneyPermit } from './execution-permit-gate.js';
export type { ExecutionAttempt, ExecutionAttemptState, ExecutionAttemptOutcome, ExecutionAttemptStore } from './execution-attempt.js';
export { createExecutionAttempt, executionIdempotencyKey } from './execution-attempt.js';
export type { PostgresExecutionAttemptStoreOptions } from './postgres-execution-attempt-store.js';
export { PostgresExecutionAttemptStore } from './postgres-execution-attempt-store.js';
export type { RecoveryObservation, RecoveryDisposition, RecoveryResult, ExecutionReconciler, ExecutionRecoveryLedger, RecoveryResolutionState } from './execution-recovery.js';
export { classifyRecovery } from './execution-recovery.js';
export type { RecoveryLease, ExecutionRecoveryLeaseStore } from './execution-recovery-lease.js';
export { assertRecoveryLease, assertLeaseSeconds } from './execution-recovery-lease.js';
export type { PostgresExecutionRecoveryLedgerOptions } from './postgres-execution-recovery-ledger.js';
export { PostgresExecutionRecoveryLedger, recoveryEvidenceHash } from './postgres-execution-recovery-ledger.js';
export type { PostgresExecutionRecoveryLeaseStoreOptions } from './postgres-execution-recovery-lease-store.js';
export { PostgresExecutionRecoveryLeaseStore } from './postgres-execution-recovery-lease-store.js';
export type { ExecutionRecoveryServiceOptions } from './execution-recovery-service.js';
export { MoneyExecutionRecoveryService } from './execution-recovery-service.js';
export type { MoneyReconciliationAdapter } from './execution-reconciliation-adapter.js';
export { ExecutionReconciliationAdapterRegistry, createExecutionReconciler } from './execution-reconciliation-adapter.js';
export type { ProviderExecutionIdentity } from './provider-execution-identity.js';
export { createProviderExecutionIdentity, createProviderExecutionIdentityFromAttempt, assertProviderExecutionIdentity } from './provider-execution-identity.js';
export type { AtomicRecoveryResolver, PostgresAtomicRecoveryResolverOptions } from './postgres-atomic-recovery-resolver.js';
export { PostgresAtomicRecoveryResolver } from './postgres-atomic-recovery-resolver.js';
export type { StripePaymentIntentReconciliationAdapterOptions } from './stripe-payment-intent-reconciliation-adapter.js';
export { StripePaymentIntentReconciliationAdapter } from './stripe-payment-intent-reconciliation-adapter.js';
