import { createHash } from 'node:crypto'
import { artifactsAtCutoff, claimsAtCutoff, type CanonicalInformationEvent, type InformationArtifact, type InformationClaim, type InformationSource } from './information-integrity-engine.js'

export type InformationNovelty=Readonly<{artifactId:string;status:'NOVEL'|'EXACT_DUPLICATE'|'DERIVED_DUPLICATE'|'REVISION';canonicalArtifactId:string;similarArtifactIds:readonly string[];methodologyVersion:string;provenanceHash:string}>
export function classifyArtifactNovelty(artifact:InformationArtifact,prior:readonly InformationArtifact[],methodologyVersion:string):InformationNovelty{
 const exact=prior.find(x=>x.contentHash===artifact.contentHash),revision=artifact.revisionOfArtifactId||artifact.supersedesArtifactId,derived=prior.filter(x=>x.sourceArtifactId===artifact.sourceArtifactId||Boolean(revision&&(x.artifactId===revision)))
 const status:InformationNovelty['status']=revision?'REVISION':exact?'EXACT_DUPLICATE':derived.length?'DERIVED_DUPLICATE':'NOVEL',canonicalArtifactId=revision??exact?.artifactId??derived[0]?.artifactId??artifact.artifactId,similarArtifactIds=[...new Set([...(exact?[exact.artifactId]:[]),...derived.map(x=>x.artifactId)])].sort(),provenanceHash=createHash('sha256').update(JSON.stringify({artifactId:artifact.artifactId,status,canonicalArtifactId,similarArtifactIds,methodologyVersion})).digest('hex')
 return Object.freeze({artifactId:artifact.artifactId,status,canonicalArtifactId,similarArtifactIds:Object.freeze(similarArtifactIds),methodologyVersion,provenanceHash})
}

export type MarketRelevance=Readonly<{relevanceId:string;eventId:string;instrumentId:string;channels:readonly ('FUNDAMENTAL'|'MACRO'|'REGULATORY'|'LIQUIDITY'|'VOLATILITY'|'SENTIMENT'|'SUPPLY'|'DEMAND'|'COUNTERPARTY'|'RESOLUTION')[];direction:'POSITIVE'|'NEGATIVE'|'MIXED'|'UNKNOWN';confidence:number;horizon:'INTRADAY'|'SHORT'|'MEDIUM'|'LONG'|'UNKNOWN';methodologyVersion:string;evidenceClaimIds:readonly string[];provenanceHash:string;authority:'ANALYSIS_ONLY'}>
export function createMarketRelevance(input:Omit<MarketRelevance,'relevanceId'|'provenanceHash'|'authority'>):MarketRelevance{if(input.confidence<0||input.confidence>1||!input.channels.length||!input.evidenceClaimIds.length)throw new Error('MONEY_038_RELEVANCE_INPUT_INVALID');const provenanceHash=createHash('sha256').update(JSON.stringify({...input,channels:[...input.channels].sort(),evidenceClaimIds:[...input.evidenceClaimIds].sort()})).digest('hex');return Object.freeze({...input,channels:Object.freeze([...input.channels]),evidenceClaimIds:Object.freeze([...input.evidenceClaimIds]),relevanceId:`market-relevance:${provenanceHash}`,provenanceHash,authority:'ANALYSIS_ONLY'})}
export function assertMarketRelevanceCannotAuthorize(x:MarketRelevance){if(x.authority!=='ANALYSIS_ONLY')throw new Error('MONEY_038_RELEVANCE_AUTHORITY_VIOLATION')}

export type SourceIndependenceAssessment=Readonly<{sourceIds:readonly string[];independenceGroups:readonly string[];independentCount:number;duplicateRisk:'LOW'|'MEDIUM'|'HIGH';provenanceHash:string}>
export function assessSourceIndependence(sourceIds:readonly string[],sources:readonly InformationSource[]):SourceIndependenceAssessment{const map=new Map(sources.map(s=>[s.sourceId,s])),ids=[...new Set(sourceIds)].sort(),groups=[...new Set(ids.map(id=>map.get(id)?.independenceGroup).filter((x):x is string=>Boolean(x)))].sort(),duplicateRisk=ids.length<=1?'HIGH':groups.length===ids.length?'LOW':groups.length===1?'HIGH':'MEDIUM',provenanceHash=createHash('sha256').update(JSON.stringify({ids,groups})).digest('hex');return Object.freeze({sourceIds:Object.freeze(ids),independenceGroups:Object.freeze(groups),independentCount:groups.length,duplicateRisk,provenanceHash})}

export type InformationReplayFrame=Readonly<{informationCutoff:string;artifactIds:readonly string[];claimIds:readonly string[];eventIds:readonly string[];sourceIds:readonly string[];inputHash:string}>
export function createInformationReplayFrame(cutoff:string,artifacts:readonly InformationArtifact[],claims:readonly InformationClaim[],events:readonly CanonicalInformationEvent[]):InformationReplayFrame{const activeArtifacts=artifactsAtCutoff(artifacts,cutoff),activeClaims=claimsAtCutoff(claims,artifacts,cutoff),a=activeArtifacts.map(x=>x.artifactId).sort(),c=activeClaims.map(x=>x.claimId).sort(),cset=new Set(c),e=events.filter(x=>x.availableAt<=cutoff&&x.claimIds.every(id=>cset.has(id))).map(x=>x.eventId).sort(),sourceIds=[...new Set(activeArtifacts.map(x=>x.sourceId))].sort(),inputHash=createHash('sha256').update(JSON.stringify({cutoff,a,c,e,sourceIds})).digest('hex');return Object.freeze({informationCutoff:cutoff,artifactIds:Object.freeze(a),claimIds:Object.freeze(c),eventIds:Object.freeze(e),sourceIds:Object.freeze(sourceIds),inputHash})}
