import { createHash } from 'node:crypto'

export type InformationSourceKind='REGULATOR'|'ISSUER'|'GOVERNMENT'|'EXCHANGE'|'NEWSWIRE'|'NEWS'|'RESEARCH'|'SOCIAL'|'ALTERNATIVE_DATA'|'PREDICTION_MARKET'|'OTHER'
export type SourceReliability='PRIMARY_AUTHORITY'|'PRIMARY_PARTY'|'INDEPENDENT_SECONDARY'|'AGGREGATOR'|'UNVERIFIED'
export type InformationSource=Readonly<{sourceId:string;name:string;kind:InformationSourceKind;reliability:SourceReliability;canonicalDomain?:string;independenceGroup:string;effectiveFrom:string;effectiveTo?:string;methodologyVersion:string;evidenceRefs:readonly string[];provenanceHash:string}>
export type ArtifactStatus='ACTIVE'|'CORRECTED'|'RETRACTED'|'DELETED'|'SUPERSEDED'
export type InformationArtifact=Readonly<{artifactId:string;sourceId:string;sourceArtifactId:string;contentHash:string;title?:string;publishedAt?:string;observedAt:string;receivedAt:string;availableAt:string;status:ArtifactStatus;revisionOfArtifactId?:string;supersedesArtifactId?:string;retrievalRef:string;evidenceRefs:readonly string[];provenanceHash:string}>
export type ClaimPolarity='AFFIRMS'|'DENIES'|'UNCERTAIN'
export type InformationClaim=Readonly<{claimId:string;artifactId:string;subjectIds:readonly string[];predicate:string;object:string;polarity:ClaimPolarity;effectiveAt?:string;availableAt:string;extractorVersion:string;confidence:number;evidenceRefs:readonly string[];provenanceHash:string}>
export type ClaimRelation='SUPPORTS'|'CONTRADICTS'|'DUPLICATES'|'UNRELATED'
export type ClaimRelationRecord=Readonly<{relationId:string;leftClaimId:string;rightClaimId:string;relation:ClaimRelation;detectedAt:string;methodologyVersion:string;provenanceHash:string}>
export type EventClass='EARNINGS'|'GUIDANCE'|'FILING'|'CORPORATE_ACTION'|'REGULATORY'|'LEGAL'|'MACRO_RELEASE'|'CENTRAL_BANK'|'GEOPOLITICAL'|'MARKET_STRUCTURE'|'CYBER'|'SUPPLY_CHAIN'|'MANAGEMENT'|'PRODUCT'|'M_AND_A'|'RUMOR'|'OTHER'
export type CanonicalInformationEvent=Readonly<{eventId:string;eventClass:EventClass;subjectIds:readonly string[];instrumentIds:readonly string[];effectiveAt:string;availableAt:string;claimIds:readonly string[];sourceIds:readonly string[];independentSourceGroups:readonly string[];corroborationCount:number;contradictionClaimIds:readonly string[];status:'UNVERIFIED'|'CORROBORATED'|'CONTESTED'|'PRIMARY_CONFIRMED'|'RETRACTED';confidence:number;methodologyVersion:string;inputHash:string;provenanceHash:string;authority:'EVIDENCE_ONLY'}>
export type InformationEvidenceBundle=Readonly<{bundleId:string;informationCutoff:string;eventIds:readonly string[];claimIds:readonly string[];artifactIds:readonly string[];sourceIds:readonly string[];openContradictionIds:readonly string[];inputHash:string;provenanceHash:string;authority:'EVIDENCE_ONLY'}>

function hash(v:unknown):string{return createHash('sha256').update(JSON.stringify(v)).digest('hex')}
function nonempty(v:string,code:string){if(!v.trim())throw new Error(code)}
export function assertInformationSource(s:InformationSource){nonempty(s.sourceId,'MONEY_038_SOURCE_ID_REQUIRED');nonempty(s.independenceGroup,'MONEY_038_INDEPENDENCE_GROUP_REQUIRED');if(!s.evidenceRefs.length||!s.provenanceHash)throw new Error('MONEY_038_SOURCE_UNPROVEN')}
export function assertInformationArtifact(a:InformationArtifact){nonempty(a.artifactId,'MONEY_038_ARTIFACT_ID_REQUIRED');nonempty(a.contentHash,'MONEY_038_CONTENT_HASH_REQUIRED');if(!a.retrievalRef||!a.evidenceRefs.length||!a.provenanceHash)throw new Error('MONEY_038_ARTIFACT_UNPROVEN');if(Date.parse(a.receivedAt)<Date.parse(a.observedAt)||Date.parse(a.availableAt)<Date.parse(a.receivedAt))throw new Error('MONEY_038_ARTIFACT_CLOCK_INVALID');if((a.status==='CORRECTED'||a.status==='SUPERSEDED')&&!a.revisionOfArtifactId&&!a.supersedesArtifactId)throw new Error('MONEY_038_REVISION_LINEAGE_REQUIRED')}
export function assertInformationClaim(c:InformationClaim){if(c.confidence<0||c.confidence>1)throw new Error('MONEY_038_CLAIM_CONFIDENCE_INVALID');if(!c.subjectIds.length||!c.predicate.trim()||!c.evidenceRefs.length||!c.provenanceHash)throw new Error('MONEY_038_CLAIM_UNPROVEN')}

export function artifactsAtCutoff(artifacts:readonly InformationArtifact[],cutoff:string):readonly InformationArtifact[]{const eligible=artifacts.filter(a=>{assertInformationArtifact(a);return a.availableAt<=cutoff});const superseded=new Set(eligible.flatMap(a=>[a.revisionOfArtifactId,a.supersedesArtifactId].filter((x):x is string=>Boolean(x))));return Object.freeze(eligible.filter(a=>!superseded.has(a.artifactId)&&a.status!=='RETRACTED'&&a.status!=='DELETED'&&a.status!=='SUPERSEDED').sort((a,b)=>a.artifactId.localeCompare(b.artifactId)))}
export function claimsAtCutoff(claims:readonly InformationClaim[],artifacts:readonly InformationArtifact[],cutoff:string):readonly InformationClaim[]{const active=new Set(artifactsAtCutoff(artifacts,cutoff).map(a=>a.artifactId));return Object.freeze(claims.filter(c=>{assertInformationClaim(c);return c.availableAt<=cutoff&&active.has(c.artifactId)}).sort((a,b)=>a.claimId.localeCompare(b.claimId)))}

export function relateClaims(left:InformationClaim,right:InformationClaim,methodologyVersion:string,detectedAt:string):ClaimRelationRecord{let relation:ClaimRelation='UNRELATED';const sameSubject=left.subjectIds.some(x=>right.subjectIds.includes(x)),samePredicate=left.predicate===right.predicate,sameObject=left.object.trim().toLowerCase()===right.object.trim().toLowerCase();if(left.claimId===right.claimId||left.artifactId===right.artifactId&&sameSubject&&samePredicate&&sameObject&&left.polarity===right.polarity)relation='DUPLICATES';else if(sameSubject&&samePredicate&&sameObject&&left.polarity===right.polarity)relation='SUPPORTS';else if(sameSubject&&samePredicate&&(left.polarity!==right.polarity||!sameObject))relation='CONTRADICTS';const provenanceHash=hash({left:left.provenanceHash,right:right.provenanceHash,relation,methodologyVersion});return Object.freeze({relationId:`claim-rel:${provenanceHash}`,leftClaimId:left.claimId,rightClaimId:right.claimId,relation,detectedAt,methodologyVersion,provenanceHash})}

export function buildInformationEvent(input:{eventClass:EventClass;subjectIds:readonly string[];instrumentIds:readonly string[];effectiveAt:string;cutoff:string;claims:readonly InformationClaim[];artifacts:readonly InformationArtifact[];sources:readonly InformationSource[];relations:readonly ClaimRelationRecord[];methodologyVersion:string}):CanonicalInformationEvent{
 const sourceMap=new Map(input.sources.map(s=>{assertInformationSource(s);return [s.sourceId,s] as const})),eligibleArtifacts=input.artifacts.filter(a=>a.availableAt<=input.cutoff),allArtifactMap=new Map(eligibleArtifacts.map(a=>[a.artifactId,a] as const)),activeArtifactMap=new Map(artifactsAtCutoff(input.artifacts,input.cutoff).map(a=>[a.artifactId,a] as const))
 let claims=claimsAtCutoff(input.claims,input.artifacts,input.cutoff).filter(c=>c.subjectIds.some(x=>input.subjectIds.includes(x))),retracted=false
 if(!claims.length){const withdrawn=input.claims.filter(c=>c.availableAt<=input.cutoff&&c.subjectIds.some(x=>input.subjectIds.includes(x))&&(['RETRACTED','DELETED'] as ArtifactStatus[]).includes(allArtifactMap.get(c.artifactId)?.status as ArtifactStatus));if(withdrawn.length){claims=withdrawn;retracted=true}else throw new Error('MONEY_038_EVENT_CLAIMS_REQUIRED')}
 const sourceIds=[...new Set(claims.map(c=>(activeArtifactMap.get(c.artifactId)??allArtifactMap.get(c.artifactId))?.sourceId).filter((x):x is string=>Boolean(x)))].sort(),groups=[...new Set(sourceIds.map(id=>sourceMap.get(id)?.independenceGroup).filter((x):x is string=>Boolean(x)))].sort()
 const primary=sourceIds.some(id=>sourceMap.get(id)?.reliability==='PRIMARY_AUTHORITY'),claimIds=claims.map(c=>c.claimId).sort(),claimSet=new Set(claimIds),contradictions=input.relations.filter(r=>r.relation==='CONTRADICTS'&&claimSet.has(r.leftClaimId)&&claimSet.has(r.rightClaimId)),contradictionClaimIds=[...new Set(contradictions.flatMap(r=>[r.leftClaimId,r.rightClaimId]))].sort()
 const status:CanonicalInformationEvent['status']=retracted?'RETRACTED':contradictions.length?'CONTESTED':primary?'PRIMARY_CONFIRMED':groups.length>=2?'CORROBORATED':'UNVERIFIED'
 const avg=claims.reduce((n,c)=>n+c.confidence,0)/claims.length,confidence=Math.max(0,Math.min(1,avg*(status==='CONTESTED'?.5:status==='RETRACTED'?0:1)))
 const availableAt=claims.map(c=>c.availableAt).sort().slice(-1)[0]!,inputHash=hash({claimIds,sourceIds,groups,relations:input.relations.map(r=>r.provenanceHash).sort(),methodologyVersion:input.methodologyVersion}),provenanceHash=hash({eventClass:input.eventClass,subjectIds:[...input.subjectIds].sort(),instrumentIds:[...input.instrumentIds].sort(),effectiveAt:input.effectiveAt,availableAt,status,inputHash})
 return Object.freeze({eventId:`info-event:${provenanceHash}`,eventClass:input.eventClass,subjectIds:Object.freeze([...input.subjectIds].sort()),instrumentIds:Object.freeze([...input.instrumentIds].sort()),effectiveAt:input.effectiveAt,availableAt,claimIds:Object.freeze(claimIds),sourceIds:Object.freeze(sourceIds),independentSourceGroups:Object.freeze(groups),corroborationCount:groups.length,contradictionClaimIds:Object.freeze(contradictionClaimIds),status,confidence,methodologyVersion:input.methodologyVersion,inputHash,provenanceHash,authority:'EVIDENCE_ONLY'})
}

export function buildInformationEvidenceBundle(input:{cutoff:string;events:readonly CanonicalInformationEvent[];claims:readonly InformationClaim[];artifacts:readonly InformationArtifact[];relations:readonly ClaimRelationRecord[]}):InformationEvidenceBundle{
 const events=input.events.filter(e=>e.availableAt<=input.cutoff&&e.status!=='RETRACTED').sort((a,b)=>a.eventId.localeCompare(b.eventId)),eventIds=events.map(e=>e.eventId),claimIds=[...new Set(events.flatMap(e=>e.claimIds))].sort(),claimSet=new Set(claimIds),artifactIds=[...new Set(input.claims.filter(c=>claimSet.has(c.claimId)).map(c=>c.artifactId))].sort(),artifactSet=new Set(artifactIds),sourceIds=[...new Set(input.artifacts.filter(a=>artifactSet.has(a.artifactId)).map(a=>a.sourceId))].sort(),openContradictionIds=input.relations.filter(r=>r.relation==='CONTRADICTS'&&claimSet.has(r.leftClaimId)&&claimSet.has(r.rightClaimId)).map(r=>r.relationId).sort(),inputHash=hash({eventIds,claimIds,artifactIds,sourceIds,openContradictionIds,cutoff:input.cutoff}),provenanceHash=hash({inputHash,authority:'EVIDENCE_ONLY'})
 return Object.freeze({bundleId:`info-bundle:${provenanceHash}`,informationCutoff:input.cutoff,eventIds:Object.freeze(eventIds),claimIds:Object.freeze(claimIds),artifactIds:Object.freeze(artifactIds),sourceIds:Object.freeze(sourceIds),openContradictionIds:Object.freeze(openContradictionIds),inputHash,provenanceHash,authority:'EVIDENCE_ONLY'})
}
export function assertInformationCannotAuthorize(x:{authority:string}){if(x.authority!=='EVIDENCE_ONLY')throw new Error('MONEY_038_AUTHORITY_VIOLATION')}
