import assert from 'node:assert/strict'
import test from 'node:test'
import { assertIssuerIdentifier, assertIssuerInstrumentRelationship, assertPointInTimeFact, buildFundamentalState, factWasAvailableAt, relationshipWasEffectiveAt, revisionsForFact, selectActiveFactsAtCutoff, selectFactsAtCutoff, selectIssuerIdentifiersAt, selectIssuerInstrumentRelationshipsAt } from './issuer-reality-contracts.js'
import type { FactRevision, FinancialFact, IssuerIdentifier, IssuerInstrumentRelationship } from './issuer-reality-contracts.js'

const fact = (overrides: Partial<FinancialFact> = {}): FinancialFact => ({ factId: 'fact-1', issuerId: 'issuer-1', filingId: 'filing-1', taxonomy: 'us-gaap', concept: 'Revenue', value: { coefficient: 1000n, scale: 2, currency: 'USD', unit: 'USD' }, dimensions: [], reportedAt: '2026-02-20T12:00:00Z', availableAt: '2026-02-20T12:00:00Z', receivedAt: '2026-02-20T12:01:00Z', status: 'REPORTED', evidenceRefs: [], provenanceHash: 'hash-1', ...overrides })
const revision = (overrides: Partial<FactRevision> = {}): FactRevision => ({ revisionId: 'revision-1', factId: 'fact-1', revisionType: 'RESTATEMENT', revisedAt: '2026-03-10T12:00:00Z', evidenceRefs: [], provenanceHash: 'revision-hash', ...overrides })
const identifier = (overrides: Partial<IssuerIdentifier> = {}): IssuerIdentifier => ({ identifierId: 'id-1', issuerId: 'issuer-1', type: 'CIK', value: '0001234567', effectiveAt: '2026-01-01T00:00:00Z', evidenceRefs: [], provenanceHash: 'id-hash', ...overrides })
const relation = (overrides: Partial<IssuerInstrumentRelationship> = {}): IssuerInstrumentRelationship => ({ relationshipId: 'rel-1', issuerId: 'issuer-1', instrumentId: 'instrument-1', relationshipType: 'ISSUER_OF', effectiveAt: '2026-01-01T00:00:00Z', evidenceRefs: [], provenanceHash: 'rel-hash', ...overrides })
const build = (facts: readonly FinancialFact[], revisions: readonly FactRevision[] = [], cutoff = '2026-02-25T00:00:00Z') => buildFundamentalState('issuer-1', facts, revisions, cutoff, '2026-03-02T00:00:00Z', '035.1', `snapshot-${cutoff}`, [], `state-hash-${cutoff}`)

test('rejects invalid point-in-time ordering', () => { assert.throws(() => assertPointInTimeFact(fact({ availableAt: '2026-02-19T12:00:00Z' }))); assert.throws(() => assertPointInTimeFact(fact({ receivedAt: '2026-02-20T11:59:00Z' }))) })
test('enforces information cutoff', () => { const future = fact({ factId: 'fact-2', availableAt: '2026-02-21T12:00:00Z' }); assert.equal(factWasAvailableAt(future, '2026-02-20T12:30:00Z'), false); assert.deepEqual(selectFactsAtCutoff([fact(), future], '2026-02-20T12:30:00Z').map((x) => x.factId), ['fact-1']) })
test('builds distinct point-in-time states', () => { const later = fact({ factId: 'fact-2', concept: 'NetIncome', availableAt: '2026-03-01T12:00:00Z' }); const early = build([fact(), later]); const late = build([fact(), later], [], '2026-03-02T00:00:00Z'); assert.deepEqual(early.factIds, ['fact-1']); assert.deepEqual(late.factIds, ['fact-1', 'fact-2']); assert.notEqual(early.stateId, late.stateId) })
test('revision ledger is append-only and withdrawal changes only active projection', () => { const withdrawal = revision({ revisionType: 'WITHDRAWAL', revisedAt: '2026-03-10T12:00:00Z' }); assert.equal(revisionsForFact([withdrawal], 'fact-1').length, 1); assert.deepEqual(selectActiveFactsAtCutoff([fact()], [withdrawal], '2026-03-11T00:00:00Z'), []); assert.deepEqual(selectFactsAtCutoff([fact()], '2026-03-11T00:00:00Z').map((x) => x.factId), ['fact-1']) })
test('fundamental state consumes revisions', () => { const state = build([fact()], [revision()], '2026-03-11T00:00:00Z'); assert.equal(state.status, 'RESTATEMENT_PENDING') })
test('issuer identifiers are point-in-time', () => { const oldId = identifier({ identifierId: 'old', value: 'old', expiresAt: '2026-06-01T00:00:00Z' }); const newId = identifier({ identifierId: 'new', value: 'new', effectiveAt: '2026-06-01T00:00:00Z' }); assert.deepEqual(selectIssuerIdentifiersAt([oldId, newId], 'issuer-1', '2026-05-31T23:59:59Z').map((x) => x.identifierId), ['old']); assert.deepEqual(selectIssuerIdentifiersAt([oldId, newId], 'issuer-1', '2026-06-01T00:00:00Z').map((x) => x.identifierId), ['new']) })
test('issuer-instrument relationships are point-in-time', () => { const old = relation({ relationshipId: 'old', expiresAt: '2026-06-01T00:00:00Z' }); const next = relation({ relationshipId: 'new', effectiveAt: '2026-06-01T00:00:00Z' }); assert.deepEqual(selectIssuerInstrumentRelationshipsAt([old, next], 'issuer-1', 'instrument-1', '2026-06-01T00:00:00Z').map((x) => x.relationshipId), ['new']); assert.equal(relationshipWasEffectiveAt(next, '2026-05-31T23:59:59Z'), false) })
test('rejects inverted temporal windows', () => { assert.throws(() => assertIssuerIdentifier(identifier({ effectiveAt: '2026-06-02T00:00:00Z', expiresAt: '2026-06-01T00:00:00Z' }))); assert.throws(() => assertIssuerInstrumentRelationship(relation({ effectiveAt: '2026-06-02T00:00:00Z', expiresAt: '2026-06-01T00:00:00Z' }))) })
