import { createHash } from 'node:crypto'
import type { ExecutionMarketSnapshot, ExecutionPlan, ExecutionPreflight, ExecutionRouteSnapshot } from './execution-planning-contracts.js'
import type { ShadowCertificationReport, ShadowReadinessAssessment } from './shadow-market-contracts.js'

export type BrokerAccountStatus='ACTIVE'|'RESTRICTED'|'CLOSED'|'UNKNOWN'
export type BrokerAssetClass='EQUITY'|'ETF'|'FOREX'|'CRYPTO'|'OPTION'|'FUTURE'|'OTHER'
export type BrokerOrderCapability='MARKET'|'LIMIT'|'STOP'|'STOP_LIMIT'
export type BrokerAccountCapabilitySnapshot=Readonly<{snapshotId:string;provider:string;accountId:string;status:BrokerAccountStatus;assetClasses:readonly BrokerAssetClass[];orderTypes:readonly BrokerOrderCapability[];currencies:readonly string[];canBuy:boolean;canSell:boolean;canShort:boolean;canBorrow:boolean;maxLeverage:string;buyingPowerMinor:bigint;settledCashMinor:bigint;reservedCashMinor:bigint;longPositionMarketValueMinorByInstrument:Readonly<Record<string,bigint>>;currency:string;restrictionCodes:readonly string[];observedAt:string;receivedAt:string;availableAt:string;expiresAt:string;evidenceIds:readonly string[];provenanceHash:string;authority:'EVIDENCE_ONLY'}>
export type BrokerCapabilityContext=Readonly<{environment:'LIVE_READ_ONLY';provider:string;accountId:string;informationCutoff:string;now:string}>
export interface BrokerCapabilityDiscoveryAdapter{readonly provider:string;readonly environment:'LIVE_READ_ONLY';readAccountCapabilities(context:BrokerCapabilityContext):Promise<BrokerAccountCapabilitySnapshot>}
export type LiveExecutionPreflight=Readonly<{preflightId:string;executionPlanId:string;provider:string;accountId:string;status:'PASS_FOR_HUMAN_APPROVAL'|'BLOCK';reasonCodes:readonly string[];accountCapabilitySnapshotId:string;routeSnapshotId:string;marketSnapshotId:string;shadowCertificationReportId:string;checkedAt:string;expiresAt:string;inputHash:string;provenanceHash:string;authority:'PREFLIGHT_ONLY';requiresHumanApproval:true;canSubmitOrders:false;canAuthorizeLive:false}>
export type LiveApprovalCandidate=Readonly<{candidateId:string;executionPlanId:string;preflightId:string;provider:string;accountId:string;capability:'money.trade.submit';requestedAt:string;expiresAt:string;reasonCodes:readonly string[];authority:'APPROVAL_REQUEST_ONLY';requiresExplicitHumanApproval:true;canExecute:false}>
export type PreflightReplayManifest=Readonly<{replayId:string;informationCutoff:string;includedCapabilitySnapshotIds:readonly string[];excludedFutureSnapshotIds:readonly string[];inputHash:string;provenanceHash:string;authority:'RESEARCH_ONLY'}>
export type LivePreflightCertificationCase=Readonly<{caseId:string;name:string;passed:boolean;evidenceIds:readonly string[]}>
export type LivePreflightCertificationReport=Readonly<{reportId:string;provider:string;cases:readonly LivePreflightCertificationCase[];passed:boolean;executionEnabled:false;authority:'CERTIFICATION_ONLY';provenanceHash:string}>

export function hash046(v:unknown){return createHash('sha256').update(JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x)).digest('hex')}
export function assertCapabilityDiscoveryAdapter(adapter:unknown):asserts adapter is BrokerCapabilityDiscoveryAdapter{const x=adapter as Record<string,unknown>;if(x.environment!=='LIVE_READ_ONLY'||typeof x.readAccountCapabilities!=='function')throw new Error('MONEY_046_DISCOVERY_ADAPTER_INVALID');for(const k of ['submitOrder','cancelOrder','replaceOrder','transfer','withdraw','borrow'])if(typeof x[k]==='function')throw new Error('MONEY_046_MUTATING_ADAPTER_FORBIDDEN:'+k)}
export function assertAccountCapabilitySnapshot(s:BrokerAccountCapabilitySnapshot,cutoff:string,now:string){if(s.authority!=='EVIDENCE_ONLY'||!s.snapshotId||!s.provider||!s.accountId||!s.evidenceIds.length||!s.provenanceHash)throw new Error('MONEY_046_ACCOUNT_CAPABILITY_INVALID');if(s.buyingPowerMinor<0n||s.settledCashMinor<0n||s.reservedCashMinor<0n)throw new Error('MONEY_046_ACCOUNT_BALANCE_INVALID');if(s.reservedCashMinor>s.settledCashMinor)throw new Error('MONEY_046_RESERVED_CASH_INVALID');if(!/^\d+(\.\d+)?$/.test(s.maxLeverage))throw new Error('MONEY_046_LEVERAGE_INVALID');if(s.availableAt>cutoff)throw new Error('MONEY_046_FUTURE_ACCOUNT_CAPABILITY');if(s.expiresAt<=now)throw new Error('MONEY_046_STALE_ACCOUNT_CAPABILITY')}
export function assertLivePreflightInputs(input:{plan:ExecutionPlan;market:ExecutionMarketSnapshot;route:ExecutionRouteSnapshot;executionPreflight:ExecutionPreflight;shadow:ShadowReadinessAssessment;shadowCertification:ShadowCertificationReport}){if(input.plan.authority!=='ANALYSIS_ONLY'||!input.plan.requiresHumanApproval)throw new Error('MONEY_046_PLAN_GOVERNANCE_INVALID');if(input.executionPreflight.executionPlanId!==input.plan.executionPlanId)throw new Error('MONEY_046_EXECUTION_PREFLIGHT_BINDING_INVALID');if(input.market.snapshotId!==input.plan.marketSnapshotId||input.route.routeId!==input.plan.routeId)throw new Error('MONEY_046_MARKET_ROUTE_BINDING_INVALID');if(input.shadow.authority!=='REVIEW_ONLY'||input.shadowCertification.authority!=='CERTIFICATION_ONLY')throw new Error('MONEY_046_SHADOW_GOVERNANCE_INVALID')}
