import type { PermitStore } from './execution-permit.js'
export type LiveCanaryPolicy=Readonly<{policyId:string;currency:string;maxOrderNotionalMinor:bigint;maxDailySubmittedNotionalMinor:bigint;maxDailyOrders:number;maxDailyRealizedLossMinor:bigint;maxGrossExposureMinor:bigint;maxOpenUnknownExecutions:number;maxRiskMetricAgeSeconds:number;authority:'RISK_POLICY_ONLY'}>
export type LiveRiskMetricSnapshot=Readonly<{snapshotId:string;provider:string;accountId:string;currency:string;grossExposureMinor:bigint;realizedPnlMinor:bigint;observedAt:string;availableAt:string;evidenceIds:readonly string[];authority:'EVIDENCE_ONLY'}>
export type LiveCanaryState=Readonly<{provider:string;accountId:string;tradingDate:string;currency:string;submittedNotionalMinor:bigint;submittedOrders:number;realizedLossMinor:bigint;grossExposureMinor:bigint;unresolvedExecutionIds:readonly string[];riskMetricObservedAt?:string;riskMetricEvidenceIds:readonly string[];halted:boolean;haltReason?:string;version:number;updatedAt:string}>
export type CanaryReservation=Readonly<{reservationId:string;provider:string;accountId:string;tradingDate:string;notionalMinor:bigint;side:'BUY'|'SELL';stateVersion:number;authority:'RISK_GATE_ONLY';canExecute:false}>
export type CanaryReserveResult=Readonly<{allowed:true;reservation:CanaryReservation;state:LiveCanaryState}|{allowed:false;reasonCodes:readonly string[];state:LiveCanaryState}>
export interface LiveCanaryStateStore{get(provider:string,accountId:string,tradingDate:string):Promise<LiveCanaryState|undefined>|LiveCanaryState|undefined;updateRiskMetrics(snapshot:LiveRiskMetricSnapshot,tradingDate:string,now:string):Promise<LiveCanaryState>|LiveCanaryState;reserve(input:{provider:string;accountId:string;tradingDate:string;currency:string;notionalMinor:bigint;side:'BUY'|'SELL';policy:LiveCanaryPolicy;now:string}):Promise<CanaryReserveResult>|CanaryReserveResult;release(reservation:CanaryReservation,now:string):Promise<void>|void;markUnknown(provider:string,accountId:string,tradingDate:string,executionId:string,now:string):Promise<void>|void;resolveUnknown(provider:string,accountId:string,tradingDate:string,executionId:string,now:string):Promise<void>|void;halt(provider:string,accountId:string,tradingDate:string,reason:string,now:string):Promise<void>|void}
export function assertCanaryPolicy(p:LiveCanaryPolicy){if(p.authority!=='RISK_POLICY_ONLY'||!p.policyId||!p.currency)throw new Error('MONEY_050_CANARY_POLICY_INVALID');if([p.maxOrderNotionalMinor,p.maxDailySubmittedNotionalMinor,p.maxDailyRealizedLossMinor,p.maxGrossExposureMinor].some(x=>x<0n)||!Number.isInteger(p.maxDailyOrders)||p.maxDailyOrders<1||!Number.isInteger(p.maxOpenUnknownExecutions)||p.maxOpenUnknownExecutions<0||!Number.isInteger(p.maxRiskMetricAgeSeconds)||p.maxRiskMetricAgeSeconds<1)throw new Error('MONEY_050_CANARY_POLICY_LIMIT_INVALID')}
export function assertRiskMetricSnapshot(s:LiveRiskMetricSnapshot,input:{provider:string;accountId:string;currency:string;cutoff:string}){if(s.authority!=='EVIDENCE_ONLY'||s.provider!==input.provider||s.accountId!==input.accountId||s.currency!==input.currency||!s.evidenceIds.length)throw new Error('MONEY_050_RISK_METRIC_BINDING_INVALID');if(s.grossExposureMinor<0n)throw new Error('MONEY_050_GROSS_EXPOSURE_INVALID');if(s.availableAt>input.cutoff)throw new Error('MONEY_050_FUTURE_RISK_METRIC')}
export async function activateLiveKillSwitch(input:{store:LiveCanaryStateStore;permitStore:PermitStore;provider:string;accountId:string;tradingDate:string;reason:string;now:string}){if(!input.reason.trim())throw new Error('MONEY_050_KILL_SWITCH_REASON_REQUIRED');await input.store.halt(input.provider,input.accountId,input.tradingDate,input.reason,input.now);await input.permitStore.haltAll();return Object.freeze({provider:input.provider,accountId:input.accountId,tradingDate:input.tradingDate,reason:input.reason,activatedAt:input.now,authority:'EMERGENCY_STOP_ONLY' as const})}
