import { createHash } from 'node:crypto'
import { parseDecimal, subtractDecimal, type ExactDecimal } from './exact-money.js'

export type MacroIndicator=Readonly<{indicatorId:string;name:string;unit:string;frequency:'DAILY'|'WEEKLY'|'MONTHLY'|'QUARTERLY'|'ANNUAL'|'IRREGULAR';seasonalAdjustment:'SA'|'NSA'|'OTHER';sourceAuthority:string;methodologyVersion:string}>
export type EconomicObservation=Readonly<{observationId:string;indicatorId:string;periodStart:string;periodEnd:string;effectiveAt:string;observedAt:string;availableAt:string;value:ExactDecimal;vintageId:string;sourceRef:string;evidenceRefs:readonly string[];provenanceHash:string}>
export type EconomicVintage=Readonly<{vintageId:string;indicatorId:string;releasedAt:string;availableAt:string;revisionOfVintageId?:string;revisionSequence:number;observationIds:readonly string[];evidenceRefs:readonly string[];provenanceHash:string}>
export type MacroFactorState=Readonly<{factorId:string;value:ExactDecimal;direction:'RISING'|'FALLING'|'FLAT'|'UNKNOWN';confidence:number;inputObservationIds:readonly string[];methodologyVersion:string}>
export type MacroRegime=Readonly<{regimeId:string;label:string;effectiveAt:string;availableAt:string;factorStates:readonly MacroFactorState[];confidence:number;methodologyVersion:string;evidenceRefs:readonly string[];provenanceHash:string}>
export type RegimeTransition=Readonly<{transitionId:string;fromRegimeId:string;toRegimeId:string;effectiveAt:string;availableAt:string;triggerEvidenceIds:readonly string[];confidence:number;methodologyVersion:string;provenanceHash:string}>
export type PolicyEvent=Readonly<{policyEventId:string;authority:string;eventType:'DECISION'|'GUIDANCE'|'MINUTES'|'IMPLEMENTATION'|'REVISION';decisionAt:string;effectiveAt:string;availableAt:string;revisionOfEventId?:string;parameters:Readonly<Record<string,string>>;evidenceRefs:readonly string[];provenanceHash:string}>
export type EconomicEvent=Readonly<{economicEventId:string;indicatorId:string;scheduledFor:string;releasedAt?:string;availableAt?:string;consensus?:ExactDecimal;actual?:ExactDecimal;prior?:ExactDecimal;priorVintageId?:string;evidenceRefs:readonly string[];provenanceHash:string}>
export type EconomicSurprise=Readonly<{surpriseId:string;economicEventId:string;rawDifference:ExactDecimal;standardized?:number;consensusSource:string;computedAt:string;informationCutoff:string;methodologyVersion:string;provenanceHash:string}>
export type MacroSensitivity=Readonly<{sensitivityId:string;instrumentId:string;factorId:string;beta:number;confidence:number;effectiveAt:string;availableAt:string;decayHalfLifeDays:number;methodologyVersion:string;evidenceRefs:readonly string[]}>
export type MacroContradiction=Readonly<{contradictionId:string;subjectId:string;leftArtifactId:string;rightArtifactId:string;reason:string;status:'OPEN'|'RESOLVED';detectedAt:string;resolutionEvidenceId?:string}>
export type MacroStateSnapshot=Readonly<{snapshotId:string;informationCutoff:string;observationIds:readonly string[];vintageIds:readonly string[];regimeIds:readonly string[];transitionIds:readonly string[];policyEventIds:readonly string[];surpriseIds:readonly string[];sensitivityIds:readonly string[];contradictionIds:readonly string[];methodologyVersion:string;inputSnapshotHash:string;provenanceHash:string;authority:'INTELLIGENCE_ONLY'}>

function proven(x:{evidenceRefs:readonly string[];provenanceHash:string}){if(!x.evidenceRefs.length||!x.provenanceHash)throw new Error('MONEY_MACRO_ARTIFACT_UNPROVEN')}
export function assertEconomicObservation(o:EconomicObservation){proven(o);if(o.periodEnd<o.periodStart)throw new Error('MONEY_MACRO_PERIOD_INVALID');if(o.availableAt<o.observedAt)throw new Error('MONEY_MACRO_CLOCK_INVALID');if(!o.vintageId)throw new Error('MONEY_MACRO_VINTAGE_REQUIRED')}
export function selectLatestVintageAtCutoff(vintages:readonly EconomicVintage[],indicatorId:string,cutoff:string):EconomicVintage|undefined{return vintages.filter(v=>v.indicatorId===indicatorId&&v.availableAt<=cutoff).sort((a,b)=>b.revisionSequence-a.revisionSequence||b.availableAt.localeCompare(a.availableAt))[0]}
export function observationsAtCutoff(observations:readonly EconomicObservation[],vintages:readonly EconomicVintage[],cutoff:string):readonly EconomicObservation[]{const indicators=[...new Set(observations.map(o=>o.indicatorId))],allowed=new Set<string>();for(const id of indicators){const v=selectLatestVintageAtCutoff(vintages,id,cutoff);if(v){proven(v);for(const x of v.observationIds)allowed.add(x)}}return Object.freeze(observations.filter(o=>{assertEconomicObservation(o);return o.availableAt<=cutoff&&allowed.has(o.observationId)}))}
export function computeEconomicSurprise(event:EconomicEvent,cutoff:string,consensusSource:string,methodologyVersion:string,standardDeviation?:number):EconomicSurprise{proven(event);if(!event.releasedAt||!event.availableAt||event.availableAt>cutoff||!event.actual||!event.consensus)throw new Error('MONEY_MACRO_SURPRISE_INPUT_INVALID');const rawDifference=subtractDecimal(event.actual,event.consensus),standardized=standardDeviation&&standardDeviation>0?Number(rawDifference.coefficient)/(10**rawDifference.scale)/standardDeviation:undefined;const provenanceHash=createHash('sha256').update(JSON.stringify({id:event.economicEventId,raw:rawDifference.coefficient.toString(),scale:rawDifference.scale,cutoff,consensusSource,methodologyVersion})).digest('hex');return Object.freeze({surpriseId:`surprise:${provenanceHash}`,economicEventId:event.economicEventId,rawDifference,standardized,consensusSource,computedAt:event.availableAt,informationCutoff:cutoff,methodologyVersion,provenanceHash})}
export function effectiveSensitivity(s:MacroSensitivity,at:string):number{if(s.availableAt>at)return 0;const days=Math.max(0,(Date.parse(at)-Date.parse(s.effectiveAt))/86400000);return s.beta*Math.pow(.5,days/s.decayHalfLifeDays)*s.confidence}
export function buildMacroStateSnapshot(input:{cutoff:string;observations:readonly EconomicObservation[];vintages:readonly EconomicVintage[];regimes:readonly MacroRegime[];transitions:readonly RegimeTransition[];policyEvents:readonly PolicyEvent[];surprises:readonly EconomicSurprise[];sensitivities:readonly MacroSensitivity[];contradictions:readonly MacroContradiction[];methodologyVersion:string}):MacroStateSnapshot{
 const obs=observationsAtCutoff(input.observations,input.vintages,input.cutoff),vintageIds=[...new Set(obs.map(o=>o.vintageId))].sort()
 const regimes=input.regimes.filter(x=>x.availableAt<=input.cutoff),transitions=input.transitions.filter(x=>x.availableAt<=input.cutoff),policies=input.policyEvents.filter(x=>x.availableAt<=input.cutoff),surprises=input.surprises.filter(x=>x.informationCutoff<=input.cutoff),sens=input.sensitivities.filter(x=>x.availableAt<=input.cutoff),contr=input.contradictions.filter(x=>x.detectedAt<=input.cutoff)
 for(const x of regimes)proven(x);for(const x of transitions){if(!x.triggerEvidenceIds.length||!x.provenanceHash)throw new Error('MONEY_MACRO_TRANSITION_UNPROVEN')}for(const x of policies)proven(x);for(const x of sens){if(!x.evidenceRefs.length)throw new Error('MONEY_MACRO_SENSITIVITY_UNPROVEN')}
 const manifest={observationIds:obs.map(x=>x.observationId).sort(),vintageIds,regimeIds:regimes.map(x=>x.regimeId).sort(),transitionIds:transitions.map(x=>x.transitionId).sort(),policyEventIds:policies.map(x=>x.policyEventId).sort(),surpriseIds:surprises.map(x=>x.surpriseId).sort(),sensitivityIds:sens.map(x=>x.sensitivityId).sort(),contradictionIds:contr.map(x=>x.contradictionId).sort()}
 const inputSnapshotHash=createHash('sha256').update(JSON.stringify({manifest,provenance:[...obs,...regimes,...transitions,...policies,...surprises].map((x:any)=>x.provenanceHash).filter(Boolean).sort()})).digest('hex'),provenanceHash=createHash('sha256').update(JSON.stringify({cutoff:input.cutoff,methodologyVersion:input.methodologyVersion,inputSnapshotHash,manifest})).digest('hex')
 return Object.freeze({snapshotId:`macro:${provenanceHash}`,informationCutoff:input.cutoff,...manifest,methodologyVersion:input.methodologyVersion,inputSnapshotHash,provenanceHash,authority:'INTELLIGENCE_ONLY'})
}
export function assertMacroDecisionBoundary(snapshot:MacroStateSnapshot){if(snapshot.authority!=='INTELLIGENCE_ONLY')throw new Error('MONEY_MACRO_AUTHORITY_VIOLATION')}
export function macroObservationFromStrings(input:Omit<EconomicObservation,'value'> & {value:string}):EconomicObservation{return Object.freeze({...input,value:parseDecimal(input.value)})}
