import { randomUUID } from 'node:crypto'
import { requireBrokerAccountEntitlement, type BrokerAccountEntitlementStore } from './broker-account-entitlement.js'
import { createExecutionAttempt, type ExecutionAttempt, type ExecutionAttemptStore } from './execution-attempt.js'
import { authorizeAndConsumeMoneyPermit, type MoneyExecutionPermit } from './execution-permit-gate.js'
import type { PermitStore } from './execution-permit.js'
import type { ProviderExecutionEvent } from './execution-receipt-contracts.js'
import type { ExecutionPlan } from './execution-planning-contracts.js'
import type { LiveExecutionPreflight } from './live-preflight-contracts.js'
import type { LiveTradePermitPackage } from './live-trade-approval-bridge.js'
import { assertManualTrigger, type LiveBrokerOrderRequest, type LiveBrokerSubmissionResult, type ManualLiveBrokerAdapter, type ManualLiveExecutionTrigger } from './manual-live-broker-contracts.js'

export type ManualLiveExecutionResult=Readonly<{attempt:ExecutionAttempt;providerEvent:ProviderExecutionEvent;providerReference?:string;state:'SUBMITTED'|'REJECTED'|'UNKNOWN';retryAllowed:false;authority:'MANUAL_LIVE_EXECUTION'}>
const permitView=(p:LiveTradePermitPackage):MoneyExecutionPermit=>({permitId:p.permit.permitId,nonce:p.permit.nonce,authorityId:p.permit.binding.authorityId,actionRequestFingerprint:p.permit.binding.actionRequestFingerprint,policyVersion:p.permit.binding.policyVersion,policyHash:p.permit.binding.policyHash,approvalId:p.permit.binding.approvalId,opportunityId:p.permit.binding.opportunityId,riskDecisionId:p.permit.binding.riskDecisionId,allocationDecisionId:p.permit.binding.allocationDecisionId})
function assertLiveTradeInstrument(id:string){if(!(id.startsWith('stock:')||id.startsWith('etf:')||id.startsWith('forex:')))throw new Error('MONEY_049_INSTRUMENT_NOT_MANUAL_LIVE_ELIGIBLE')}
function orderFrom(input:{pkg:LiveTradePermitPackage;plan:ExecutionPlan;attempt:ExecutionAttempt}):LiveBrokerOrderRequest{const {pkg,plan,attempt}=input;if(plan.slices.length!==1)throw new Error('MONEY_049_ONE_PERMIT_ONE_ORDER_REQUIRED');const s=plan.slices[0]!;if(pkg.action.amount!==plan.notional.minor.toString()||pkg.action.instrumentId!==plan.instrumentId||pkg.action.side!==plan.side||pkg.action.executionPlanId!==plan.executionPlanId)throw new Error('MONEY_049_PERMIT_PLAN_MISMATCH');return Object.freeze({clientOrderId:attempt.idempotencyKey,accountId:pkg.action.accountId!,instrumentId:plan.instrumentId,side:plan.side,orderType:'LIMIT',notionalMinor:plan.notional.minor.toString(),limitPriceMinor:s.limitPriceMinor.toString(),currency:plan.notional.currency,timeInForce:'DAY'})}
function eventFrom(input:{attempt:ExecutionAttempt;result?:LiveBrokerSubmissionResult;now:string;error?:unknown}):ProviderExecutionEvent{if(input.result){const r=input.result;return Object.freeze({eventId:'live-submit:'+input.attempt.attemptId+':'+r.providerEventId,providerEventId:r.providerEventId,provider:input.attempt.provider,executionId:input.attempt.attemptId,actionFingerprint:input.attempt.actionFingerprint,providerReference:r.providerReference,state:r.state,occurredAt:r.occurredAt,observedAt:r.observedAt,receivedAt:r.receivedAt,availableAt:r.availableAt,sequence:1,evidenceIds:Object.freeze([...r.evidenceIds]),payloadHash:input.attempt.idempotencyKey+':'+r.providerEventId,provenanceHash:input.attempt.actionFingerprint+':'+r.providerEventId,authority:'EVIDENCE_ONLY'})}const evidence='live-submit-unknown:'+input.attempt.attemptId;return Object.freeze({eventId:evidence,providerEventId:evidence,provider:input.attempt.provider,executionId:input.attempt.attemptId,actionFingerprint:input.attempt.actionFingerprint,state:'UNKNOWN',occurredAt:input.now,observedAt:input.now,receivedAt:input.now,availableAt:input.now,sequence:1,evidenceIds:Object.freeze([evidence]),payloadHash:evidence,provenanceHash:input.attempt.actionFingerprint+':unknown',authority:'EVIDENCE_ONLY'})}

export async function executeManualLiveTrade(input:{adapter:ManualLiveBrokerAdapter;permitStore:PermitStore;attemptStore:ExecutionAttemptStore;entitlementStore:BrokerAccountEntitlementStore;permitPackage:LiveTradePermitPackage;preflight:LiveExecutionPreflight;plan:ExecutionPlan;trigger:ManualLiveExecutionTrigger;now:string;attemptIdFactory?:()=>string}):Promise<ManualLiveExecutionResult>{
 const {permitPackage:pkg,preflight,plan}=input
 if(pkg.autonomous||pkg.mode!=='MANUAL_LIVE_ONLY')throw new Error('MONEY_049_MANUAL_PERMIT_REQUIRED')
 if(pkg.action.capability!=='money.trade.submit'||pkg.request.type!=='money.trade.submit')throw new Error('MONEY_049_TRADE_CAPABILITY_REQUIRED')
 if(input.adapter.environment!=='LIVE'||input.adapter.provider!==pkg.action.provider)throw new Error('MONEY_049_PROVIDER_BINDING_MISMATCH')
 if(preflight.preflightId!==pkg.action.preflightId||preflight.executionPlanId!==pkg.action.executionPlanId||preflight.provider!==pkg.action.provider||preflight.accountId!==pkg.action.accountId)throw new Error('MONEY_049_PREFLIGHT_BINDING_MISMATCH')
 if(preflight.status!=='PASS_FOR_HUMAN_APPROVAL'||input.now>=preflight.expiresAt||input.now>=pkg.permit.expiresAt)throw new Error('MONEY_049_PREFLIGHT_OR_PERMIT_NOT_ACTIVE')
 assertLiveTradeInstrument(plan.instrumentId)
 assertManualTrigger(input.trigger,{userId:pkg.request.userId,approvalReceiptId:pkg.approvalReceiptId,notBefore:pkg.authority.authorizedAt,notAfter:pkg.permit.expiresAt})
 await requireBrokerAccountEntitlement(input.entitlementStore,{userId:pkg.request.userId,provider:pkg.action.provider,accountId:pkg.action.accountId!,capability:'money.trade.submit',now:input.now})
 const attemptId=input.attemptIdFactory?.()??randomUUID()
 const previewAttempt=createExecutionAttempt({attemptId,requestId:pkg.request.id,permitId:pkg.permit.permitId,action:pkg.action,operation:'money.trade.submit',now:input.now})
 const request=orderFrom({pkg,plan,attempt:previewAttempt})
 await authorizeAndConsumeMoneyPermit(input.permitStore,permitView(pkg),pkg.request,pkg.action,input.now)
 const attempt=previewAttempt
 await input.attemptStore.start(attempt)
 try{const result=await input.adapter.submitOrder(Object.freeze({environment:'LIVE',executionId:attempt.attemptId,idempotencyKey:attempt.idempotencyKey,actionFingerprint:attempt.actionFingerprint,permitId:pkg.permit.permitId,userId:pkg.request.userId,manualTriggerId:input.trigger.triggerId,now:input.now}),request),event=eventFrom({attempt,result,now:input.now});if(result.state==='UNKNOWN'){await input.attemptStore.complete(attempt.attemptId,{state:'UNKNOWN',providerReference:result.providerReference,errorCode:'MONEY_PROVIDER_OUTCOME_UNKNOWN',recoveryRequired:true},input.now);return Object.freeze({attempt:{...attempt,state:'UNKNOWN',providerReference:result.providerReference,recoveryRequired:true},providerEvent:event,providerReference:result.providerReference,state:'UNKNOWN',retryAllowed:false,authority:'MANUAL_LIVE_EXECUTION'})}if(result.state==='REJECTED'){await input.attemptStore.complete(attempt.attemptId,{state:'FAILED',providerReference:result.providerReference,errorCode:'MONEY_PROVIDER_REJECTED',recoveryRequired:false},input.now);return Object.freeze({attempt:{...attempt,state:'FAILED',providerReference:result.providerReference,recoveryRequired:false},providerEvent:event,providerReference:result.providerReference,state:'REJECTED',retryAllowed:false,authority:'MANUAL_LIVE_EXECUTION'})}await input.attemptStore.complete(attempt.attemptId,{state:'SUCCEEDED',providerReference:result.providerReference,recoveryRequired:false},input.now);return Object.freeze({attempt:{...attempt,state:'SUCCEEDED',providerReference:result.providerReference,recoveryRequired:false},providerEvent:event,providerReference:result.providerReference,state:'SUBMITTED',retryAllowed:false,authority:'MANUAL_LIVE_EXECUTION'})}catch(error){const event=eventFrom({attempt,now:input.now,error});await input.attemptStore.complete(attempt.attemptId,{state:'UNKNOWN',errorCode:'MONEY_PROVIDER_OUTCOME_UNKNOWN',errorMessage:error instanceof Error?error.message:String(error),recoveryRequired:true},input.now);return Object.freeze({attempt:{...attempt,state:'UNKNOWN',errorCode:'MONEY_PROVIDER_OUTCOME_UNKNOWN',recoveryRequired:true},providerEvent:event,state:'UNKNOWN',retryAllowed:false,authority:'MANUAL_LIVE_EXECUTION'})}
}
