import test from 'node:test'
import assert from 'node:assert/strict'
import { bindApprovedExecution, buildExecutionReplay, learnFromExecution, planExecution, preflightExecution } from './execution-planning-engine.js'
import type { ExecutionMarketSnapshot, ExecutionOutcomeObservation, ExecutionRouteSnapshot } from './execution-planning-contracts.js'
import type { RebalanceIntent } from './portfolio-construction-contracts.js'

const intent=(minor=100000n):RebalanceIntent=>({intentId:'rebalance:p:i',planId:'portfolio:p',instrumentId:'stock:x',side:'BUY',notional:{minor,currency:'USD'},reasonCodes:['TARGET_ALLOCATION'],authority:'NONE'})
const market=(availableAt='2026-01-02T00:00:00Z'):ExecutionMarketSnapshot=>({snapshotId:'market:1',instrumentId:'stock:x',currency:'USD',bidMinor:9990n,askMinor:10010n,bidSize:'100',askSize:'100',visibleDepthNotionalMinor:1000000n,observedAt:availableAt,availableAt,expiresAt:'2026-01-02T00:05:00Z',evidenceIds:['quote'],provenanceHash:'quote-hash'})
const route=(status:ExecutionRouteSnapshot['status']='ACCEPTING',availableAt='2026-01-02T00:00:00Z'):ExecutionRouteSnapshot=>({routeId:'route:1',provider:'broker',venue:'XNYS',instrumentId:'stock:x',status,observedAt:availableAt,availableAt,evidenceIds:['broker','venue'],provenanceHash:'route-hash'})
const plan=()=>planExecution({intent:intent(),portfolioPlanId:'portfolio:p',market:market(),route:route(),informationCutoff:'2026-01-02T00:00:30Z',expiresAt:'2026-01-02T00:04:00Z',urgency:'NORMAL',maxSpreadBps:50,maxParticipationBps:5000,sliceCount:2})

test('041.1 execution planning starts from authority-free rebalance intent',()=>{const p=plan();assert.equal(p.authority,'ANALYSIS_ONLY');assert.equal(p.requiresHumanApproval,true)})
test('041.2 route and market identity are bound to exact instrument',()=>{assert.throws(()=>planExecution({intent:intent(),portfolioPlanId:'p',market:{...market(),instrumentId:'stock:y'},route:route(),informationCutoff:'2026-01-02T00:00:30Z',expiresAt:'2026-01-02T00:04:00Z',urgency:'NORMAL',maxSpreadBps:50,maxParticipationBps:5000,sliceCount:2}),/INSTRUMENT_BINDING_MISMATCH/)})
test('041.3 slices are deterministic exact notional and idempotent',()=>{const a=plan(),b=plan();assert.equal(a.slices.reduce((n,s)=>n+s.notional.minor,0n),a.notional.minor);assert.deepEqual(a.slices.map(s=>s.idempotencyKey),b.slices.map(s=>s.idempotencyKey));assert.ok(a.slices.every(s=>s.authority==='NONE'))})
test('041.4 spread and visible-depth participation fail closed',()=>{assert.throws(()=>planExecution({intent:intent(),portfolioPlanId:'p',market:{...market(),bidMinor:9000n,askMinor:11000n},route:route(),informationCutoff:'2026-01-02T00:00:30Z',expiresAt:'2026-01-02T00:04:00Z',urgency:'NORMAL',maxSpreadBps:50,maxParticipationBps:5000,sliceCount:2}),/SPREAD_LIMIT_BREACH/);assert.throws(()=>planExecution({intent:intent(900000n),portfolioPlanId:'p',market:market(),route:route(),informationCutoff:'2026-01-02T00:00:30Z',expiresAt:'2026-01-02T00:04:00Z',urgency:'NORMAL',maxSpreadBps:50,maxParticipationBps:1000,sliceCount:2}),/PARTICIPATION_LIMIT_BREACH/)})
test('041.5 future market/route evidence and rejecting routes are blocked',()=>{assert.throws(()=>planExecution({intent:intent(),portfolioPlanId:'p',market:market('2027-01-01T00:00:00Z'),route:route(),informationCutoff:'2026-01-02T00:00:30Z',expiresAt:'2026-01-02T00:04:00Z',urgency:'NORMAL',maxSpreadBps:50,maxParticipationBps:5000,sliceCount:2}),/FUTURE_MARKET_SNAPSHOT/);assert.throws(()=>planExecution({intent:intent(),portfolioPlanId:'p',market:market(),route:route('REJECTING'),informationCutoff:'2026-01-02T00:00:30Z',expiresAt:'2026-01-02T00:04:00Z',urgency:'NORMAL',maxSpreadBps:50,maxParticipationBps:5000,sliceCount:2}),/ROUTE_NOT_ACCEPTING/)})
test('041.5 preflight rechecks conditions immediately before authorization',()=>{const p=plan(),x=preflightExecution({plan:p,market:{...market(),expiresAt:'2026-01-02T00:00:45Z'},route:route(),checkedAt:'2026-01-02T00:01:00Z'});assert.equal(x.status,'BLOCK');assert.ok(x.reasonCodes.includes('MARKET_NOT_CURRENT'))})
test('041.6 plan and slices cannot manufacture order or execution authority',()=>{const p=plan();assert.equal('permitId' in p,false);assert.equal('orderId' in p,false);assert.equal('approvalId' in p,false);assert.ok(p.slices.every(s=>s.authority==='NONE'))})
test('041.7 approval binding requires explicit Action Core references and passing preflight',()=>{const p=plan(),pf=preflightExecution({plan:p,market:market(),route:route(),checkedAt:'2026-01-02T00:01:00Z'}),b=bindApprovedExecution({plan:p,preflight:pf,actionRequestId:'ar:1',approvalId:'approval:1',authorityId:'action-core',policyVersion:'1',policyHash:'policy',actionRequestFingerprint:'fingerprint',expiresAt:'2026-01-02T00:03:00Z'});assert.equal(b.authority,'APPROVAL_REFERENCE_ONLY');assert.equal('permitId' in b,false);assert.throws(()=>bindApprovedExecution({plan:p,preflight:{...pf,status:'BLOCK'},actionRequestId:'ar:1',approvalId:'approval:1',authorityId:'action-core',policyVersion:'1',policyHash:'policy',actionRequestFingerprint:'fingerprint',expiresAt:'2026-01-02T00:03:00Z'}),/PREFLIGHT_NOT_PASSING/)})
test('041.8 approval reference still cannot submit or consume an execution permit',()=>{const p=plan(),pf=preflightExecution({plan:p,market:market(),route:route(),checkedAt:'2026-01-02T00:01:00Z'}),b=bindApprovedExecution({plan:p,preflight:pf,actionRequestId:'ar:1',approvalId:'approval:1',authorityId:'action-core',policyVersion:'1',policyHash:'policy',actionRequestFingerprint:'fingerprint',expiresAt:'2026-01-02T00:03:00Z'});assert.equal('nonce' in b,false);assert.equal('state' in b,false)})
test('041.9 execution outcomes create evidence-backed learning only',()=>{const p=plan(),o:ExecutionOutcomeObservation=p.slices.map((s,i)=>({observationId:'o:'+i,executionPlanId:p.executionPlanId,sliceId:s.sliceId,state:'FILLED' as const,requestedNotional:s.notional,filledNotional:s.notional,referencePriceMinor:10010n,averageFillPriceMinor:10020n,observedAt:'2026-01-02T00:03:00Z',evidenceIds:['fill:'+i],providerReference:'provider:'+i,authority:'EVIDENCE_ONLY' as const}))[0]!,l=learnFromExecution({plan:p,outcomes:[o],createdAt:'2026-01-02T00:04:00Z'});assert.equal(l.fillRateBps,10000);assert.ok((l.slippageBps??0)>0);assert.equal(l.authority,'LEARNING_ONLY')})
test('041.9 UNKNOWN provider outcome remains explicit and never treated as a retry instruction',()=>{const p=plan(),s=p.slices[0]!,o:ExecutionOutcomeObservation={observationId:'unknown',executionPlanId:p.executionPlanId,sliceId:s.sliceId,state:'UNKNOWN',requestedNotional:s.notional,filledNotional:{minor:0n,currency:'USD'},referencePriceMinor:10010n,observedAt:'2026-01-02T00:03:00Z',evidenceIds:['timeout'],authority:'EVIDENCE_ONLY'},l=learnFromExecution({plan:p,outcomes:[o],createdAt:'2026-01-02T00:04:00Z'});assert.equal(l.unknownOutcome,true);assert.equal(l.authority,'LEARNING_ONLY')})
test('041.10 deterministic replay rejects future market or route state',()=>{const p=plan(),r=buildExecutionReplay({plan:p,market:market(),route:route(),informationCutoff:'2026-01-02T00:00:30Z',futureEvidenceIds:['future-quote']});assert.deepEqual(r.excludedFutureEvidenceIds,['future-quote']);assert.equal(r.authority,'RESEARCH_ONLY');assert.throws(()=>buildExecutionReplay({plan:p,market:market('2027-01-01T00:00:00Z'),route:route(),informationCutoff:'2026-01-02T00:00:30Z'}),/REPLAY_FUTURE_LEAK/)})
