import test from 'node:test'
import assert from 'node:assert/strict'
import { assessThesisDialectically, buildFinancialThesis, createOpportunityFromThesis, evidenceWeight, interpretThesisInRegime, traceTransmission } from './cross-asset-fusion-engine.js'
import { assertCalibrationCannotMutateAuthority, assertFusionDecisionCannotSelfAuthorize, buildFusionReplayManifest, calibrateThesisOutcome, resolveThesisOutcome, toDecisionWorkflow } from './cross-asset-decision-learning.js'
import { adaptGovernedIntelligence } from './cross-asset-fusion-adapters.js'
import { assertOpportunityBoundary, assertThesisBoundary, type FusionEvidence, type ThesisAssumption } from './cross-asset-fusion-contracts.js'

const ev=(id:string,domain:FusionEvidence['domain'],stance:FusionEvidence['stance']='SUPPORTS',availableAt='2026-01-01T00:00:00Z',sourceGroup=id):FusionEvidence=>({evidenceId:id,domain,subjectId:'issuer:abc',instrumentId:'stock:abc',assetClass:'STOCK',stance,direction:stance==='CONTRADICTS'?'BEARISH':'BULLISH',strength:.8,confidence:.8,effectiveAt:'2025-12-31T00:00:00Z',availableAt,sourceGroup,inputHash:'input:'+id,provenanceHash:'prov:'+id,authority:'NONE'})
const assumption:ThesisAssumption={assumptionId:'a1',statement:'demand persists',status:'ACTIVE',evidenceIds:['fund']}
const thesis=(evidence:readonly FusionEvidence[]= [ev('fund','FUNDAMENTAL'),ev('macro','MACRO')])=>buildFinancialThesis({subjectId:'issuer:abc',instrumentIds:['stock:abc'],assetClasses:['STOCK'],direction:'BULLISH',horizon:'MEDIUM',statement:'fundamentals and macro support upside',evidence,assumptions:[assumption],informationCutoff:'2026-01-02T00:00:00Z',createdAt:'2026-01-02T01:00:00Z',expiresAt:'2026-04-02T00:00:00Z',modelId:'fusion',modelVersion:'1',methodologyVersion:'039.1'})

test('039.1 thesis is deterministic, evidence-bound, and intelligence only',()=>{const a=thesis(),b=thesis();assert.equal(a.thesisId,b.thesisId);assert.equal(a.inputHash,b.inputHash);assert.equal(a.authority,'INTELLIGENCE_ONLY');assert.doesNotThrow(()=>assertThesisBoundary(a))})
test('039.1 future evidence is rejected at thesis cutoff',()=>{assert.throws(()=>thesis([ev('future','EVENT','SUPPORTS','2027-01-01T00:00:00Z')]),/FUTURE_EVIDENCE/)})
test('039.2 fusion keeps domains explicit rather than collapsing provenance',()=>{const t=thesis([ev('market','MARKET'),ev('fund','FUNDAMENTAL'),ev('macro','MACRO'),ev('event','EVENT'),ev('prediction','PREDICTION'),ev('shark','SHARK')]);const a=assessThesisDialectically(t,[ev('market','MARKET'),ev('fund','FUNDAMENTAL'),ev('macro','MACRO'),ev('event','EVENT'),ev('prediction','PREDICTION'),ev('shark','SHARK')],[]);assert.deepEqual(a.supportingDomains,['EVENT','FUNDAMENTAL','MACRO','MARKET','PREDICTION','SHARK'])})
test('039.3 copied evidence in one source group does not multiply thesis confidence',()=>{const one=thesis([ev('x1','EVENT','SUPPORTS','2026-01-01T00:00:00Z','wire')]),copied=thesis([ev('x1','EVENT','SUPPORTS',undefined,'wire'),ev('x2','EVENT','SUPPORTS','2026-01-01T00:00:00Z','wire')]);assert.equal(one.confidence,copied.confidence);assert.equal(evidenceWeight(ev('x','EVENT')),.64)})
test('039.4 dialectical engine preserves opposition and blocks supported status when material',()=>{const evidence=[ev('fund','FUNDAMENTAL'),ev('macro','MACRO','CONTRADICTS')],t=thesis(evidence),a=assessThesisDialectically(t,evidence,['contradiction:1']);assert.equal(a.status,'CONTESTED');assert.deepEqual(a.opposingDomains,['MACRO']);assert.throws(()=>createOpportunityFromThesis({thesis:t,assessment:a,expectedUpside:.2,expectedDownside:-.1,liquidityStatus:'ASSESSED',riskStatus:'ASSESSED',invalidationConditions:['earnings miss'],expiresAt:t.expiresAt}),/NOT_SUPPORTED/)})
test('039.5 regime interpretation is PIT and changes interpretation, not underlying fact',()=>{const t=thesis(),r=interpretThesisInRegime({thesis:t,regimeId:'risk-off',regimeLabel:'RISK_OFF',compatibility:-1,regimeConfidence:.8,rationaleEvidenceIds:['macro'],regimeCutoff:'2026-01-02T00:00:00Z'});assert.ok(r.confidenceMultiplier<1);assert.equal(t.direction,'BULLISH');assert.throws(()=>interpretThesisInRegime({thesis:t,regimeId:'future',regimeLabel:'FUTURE',compatibility:1,regimeConfidence:.8,rationaleEvidenceIds:['m'],regimeCutoff:'2027-01-01T00:00:00Z'}),/FUTURE_LEAK/)})
test('039.6 cross-asset transmission never upgrades modeled relationship to causal fact',()=>{const edges=[{edgeId:'e1',fromId:'rates',toId:'usd',channel:'RATE' as const,relationship:'MODELED' as const,direction:1 as const,strength:.8,confidence:.8,effectiveAt:'2025-01-01',availableAt:'2025-01-02',evidenceIds:['m1'],methodologyVersion:'1',provenanceHash:'p1'},{edgeId:'e2',fromId:'usd',toId:'gold',channel:'FX' as const,relationship:'OBSERVED' as const,direction:-1 as const,strength:.7,confidence:.7,effectiveAt:'2025-01-01',availableAt:'2025-01-02',evidenceIds:['m2'],methodologyVersion:'1',provenanceHash:'p2'}],p=traceTransmission({fromId:'rates',toId:'gold',edges,cutoff:'2026-01-01'});assert.equal(p.netDirection,-1);assert.equal(p.causality,'OBSERVED_OR_MODELED');assert.equal(p.authority,'ANALYSIS_ONLY')})
test('039.7 opportunity requires supported thesis plus assessed risk/liquidity and remains authority-free',()=>{const evidence=[ev('fund','FUNDAMENTAL'),ev('macro','MACRO')],t=thesis(evidence),a=assessThesisDialectically(t,evidence,[]),o=createOpportunityFromThesis({thesis:t,assessment:a,expectedUpside:.25,expectedDownside:-.1,liquidityStatus:'ASSESSED',riskStatus:'ASSESSED',invalidationConditions:['guidance cut'],expiresAt:t.expiresAt});assert.equal(a.status,'SUPPORTED');assert.equal(o.authority,'NONE');assert.doesNotThrow(()=>assertOpportunityBoundary(o));assert.throws(()=>createOpportunityFromThesis({thesis:t,assessment:a,expectedUpside:.25,expectedDownside:-.1,liquidityStatus:'UNKNOWN',riskStatus:'ASSESSED',invalidationConditions:['x'],expiresAt:t.expiresAt}),/RISK_INCOMPLETE/)})
test('039.8 DecisionCase integration cannot self-authorize or become proposal eligible',()=>{const evidence=[ev('fund','FUNDAMENTAL'),ev('macro','MACRO')],t=thesis(evidence),a=assessThesisDialectically(t,evidence,[]),o=createOpportunityFromThesis({thesis:t,assessment:a,expectedUpside:.2,expectedDownside:-.1,liquidityStatus:'ASSESSED',riskStatus:'ASSESSED',invalidationConditions:['x'],expiresAt:t.expiresAt}),d=toDecisionWorkflow({opportunity:o,accountId:'acct',requestedBy:'jhadina',createdAt:'2026-01-03',stressComplete:true,simulationComplete:true,calibrationSufficient:true,openContradictionIds:[]});assert.equal(d.assessment.disposition,'OPPORTUNITY');assert.equal(d.assessment.authorityStatus,'MISSING');assert.equal(d.authority,'NONE');assert.doesNotThrow(()=>assertFusionDecisionCannotSelfAuthorize(d))})
test('039.8 unresolved contradictions force review even after opportunity creation',()=>{const evidence=[ev('fund','FUNDAMENTAL'),ev('macro','MACRO')],t=thesis(evidence),a=assessThesisDialectically(t,evidence,[]),o=createOpportunityFromThesis({thesis:t,assessment:a,expectedUpside:.2,expectedDownside:-.1,liquidityStatus:'ASSESSED',riskStatus:'ASSESSED',invalidationConditions:['x'],expiresAt:t.expiresAt}),d=toDecisionWorkflow({opportunity:o,accountId:'acct',requestedBy:'jhadina',createdAt:'2026-01-03',stressComplete:true,simulationComplete:true,calibrationSufficient:true,openContradictionIds:['c']});assert.equal(d.assessment.disposition,'REQUIRES_REVIEW')})
test('039.9 outcomes calibrate learning but cannot mutate authority',()=>{const t=thesis(),o=resolveThesisOutcome({thesis:t,observedAt:'2026-04-03',realizedDirection:'BEARISH',realizedReturn:-.12,evidenceIds:['price-resolution'],resolutionAuthority:'canonical-market',ruleVersion:'1'}),c=calibrateThesisOutcome({thesis:t,outcome:o,createdAt:'2026-04-04'});assert.equal(o.matched,false);assert.ok(c.brierLikeError>0);assert.equal(c.authority,'LEARNING_ONLY');assert.doesNotThrow(()=>assertCalibrationCannotMutateAuthority(c))})
test('039.10 historical replay excludes future evidence and dependent theses/opportunities',()=>{const base=[ev('fund','FUNDAMENTAL'),ev('macro','MACRO')],t=thesis(base),a=assessThesisDialectically(t,base,[]),o=createOpportunityFromThesis({thesis:t,assessment:a,expectedUpside:.2,expectedDownside:-.1,liquidityStatus:'ASSESSED',riskStatus:'ASSESSED',invalidationConditions:['x'],expiresAt:t.expiresAt}),future=ev('future','EVENT','SUPPORTS','2027-01-01'),r=buildFusionReplayManifest({cutoff:'2026-01-02',evidence:[...base,future],theses:[t],opportunities:[o],methodologyVersion:'039.10'});assert.deepEqual(r.excludedFutureEvidenceIds,['future']);assert.deepEqual(r.thesisIds,[t.thesisId]);assert.deepEqual(r.opportunityIds,[o.opportunityId]);assert.equal(r.authority,'RESEARCH_ONLY')})
test('039.10 replay rejects thesis whose required evidence did not yet exist',()=>{const future=ev('future','EVENT','SUPPORTS','2027-01-01'),t=buildFinancialThesis({subjectId:'x',instrumentIds:['i'],assetClasses:['STOCK'],direction:'BULLISH',horizon:'SHORT',statement:'future-only',evidence:[future],assumptions:[],informationCutoff:'2027-01-02',createdAt:'2027-01-03',expiresAt:'2027-02-01',modelId:'m',modelVersion:'1',methodologyVersion:'1'}),r=buildFusionReplayManifest({cutoff:'2026-01-02',evidence:[future],theses:[t],opportunities:[],methodologyVersion:'039.10'});assert.deepEqual(r.thesisIds,[])})

test('039.2 governed adapters can ingest SHARK/market intelligence without inheriting authority',()=>{const e=adaptGovernedIntelligence({artifactId:'shark:1',domain:'SHARK',subjectId:'token:x',instrumentId:'crypto:x',assetClass:'CRYPTO',direction:'BULLISH',strength:.7,confidence:.6,informationCutoff:'2026-01-01',evidenceRefs:['wallet-cluster','liquidity'],provenanceHash:'shark-hash',financialAuthority:'NONE'},'SUPPORTS','shark-model');assert.equal(e.domain,'SHARK');assert.equal(e.authority,'NONE');assert.deepEqual(evidenceWeight(e),.42)})
