import test from 'node:test'
import assert from 'node:assert/strict'
import { createExecutionAttempt } from './execution-attempt.js'
import { InMemoryDurableProviderEventStore,processDurableProviderEvent } from './durable-provider-event-processor.js'
import type { ProviderExecutionEvent } from './execution-receipt-contracts.js'
const action={actionId:'a1',userId:'u1',capability:'money.trade.submit',provider:'alpaca',accountId:'acct1',instrumentId:'stock:AAPL',side:'BUY' as const,amount:'10000',currency:'USD'}
const attempt=createExecutionAttempt({attemptId:'e1',requestId:'a1',permitId:'p1',action,operation:'money.trade.submit',now:'2026-09-20T18:00:00Z'})
const event=(hash='payload'):ProviderExecutionEvent=>({eventId:'ev1',providerEventId:'alpaca-1',provider:'alpaca',executionId:'e1',actionFingerprint:attempt.actionFingerprint,providerReference:'order1',state:'FILLED',economics:{orderId:'order1',instrumentId:'stock:AAPL',side:'BUY',filledQuantity:'1',fillPrice:{coefficient:10000n,scale:2,currency:'USD'},fee:{coefficient:10n,scale:2,currency:'USD'},settlementStatus:'SETTLED',settlementExpectedAt:'2026-09-22T00:00:00Z',settlementActualAt:'2026-09-22T00:00:00Z'},occurredAt:'2026-09-20T18:00:01Z',observedAt:'2026-09-20T18:00:02Z',receivedAt:'2026-09-20T18:00:03Z',availableAt:'2026-09-20T18:00:03Z',sequence:1,evidenceIds:['alpaca:req1'],payloadHash:hash,provenanceHash:'prov',authority:'EVIDENCE_ONLY'})
test('057.1 provider event is claimed and fully persisted with receipt/outbox',async()=>{const s=new InMemoryDurableProviderEventStore(),r=await processDurableProviderEvent({store:s,attempt,event:event(),priorEvents:[],recordedAt:'2026-09-20T18:00:04Z'});assert.equal(r.disposition,'PROCESSED');const row=await s.get('ev1');assert.equal(row?.status,'PROCESSED');assert.equal(row?.receipt?.providerEventId,'alpaca-1');assert.deepEqual(row?.postingIntents?.map(x=>x.kind),['FILL','FEE','SETTLEMENT']);assert.ok((row?.outbox?.length??0)>=4)})
test('057.2 processed duplicate is ignored without double posting',async()=>{const s=new InMemoryDurableProviderEventStore();await processDurableProviderEvent({store:s,attempt,event:event(),priorEvents:[],recordedAt:'2026-09-20T18:00:04Z'});const r=await processDurableProviderEvent({store:s,attempt,event:event(),priorEvents:[],recordedAt:'2026-09-20T18:00:05Z'});assert.equal(r.disposition,'DUPLICATE');assert.equal(r.projection,undefined)})
test('057.3 claimed but unfinished event replays after crash',async()=>{const s=new InMemoryDurableProviderEventStore();const c=await s.claim(event(),'2026-09-20T18:00:04Z');assert.equal(c.disposition,'CLAIMED');const r=await processDurableProviderEvent({store:s,attempt,event:event(),priorEvents:[],recordedAt:'2026-09-20T18:00:05Z'});assert.equal(r.disposition,'PROCESSED');assert.equal((await s.get('ev1'))?.status,'PROCESSED')})
test('057.4 same provider event id with a different payload fails closed',async()=>{const s=new InMemoryDurableProviderEventStore();await s.claim(event(),'2026-09-20T18:00:04Z');await assert.rejects(()=>processDurableProviderEvent({store:s,attempt,event:event('tampered'),priorEvents:[],recordedAt:'2026-09-20T18:00:05Z'}),/PROVIDER_EVENT_CONFLICT/)})
