import test from 'node:test'
import assert from 'node:assert/strict'
import type { ExecutionMarketSnapshot, ExecutionPlan, ExecutionPreflight, ExecutionRouteSnapshot, ExecutionSlice } from './execution-planning-contracts.js'
import type { ShadowCertificationReport, ShadowReadinessAssessment } from './shadow-market-contracts.js'
import { assertCapabilityDiscoveryAdapter, type BrokerAccountCapabilitySnapshot, type BrokerCapabilityDiscoveryAdapter, type LivePreflightCertificationCase } from './live-preflight-contracts.js'
import { assessShadowReadiness, certifyShadowObservation } from './shadow-market-engine.js'
import { buildPreflightReplay, certifyLivePreflight, createLiveApprovalCandidate, discoverBrokerAccountCapabilities, preflightLiveExecution } from './live-preflight-engine.js'

const market:ExecutionMarketSnapshot={snapshotId:'m1',instrumentId:'stock:x',currency:'USD',bidMinor:9990n,askMinor:10000n,bidSize:'100',askSize:'100',visibleDepthNotionalMinor:200000n,observedAt:'2026-01-02T14:00:00Z',availableAt:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T14:05:00Z',evidenceIds:['quote:m1'],provenanceHash:'market:p'}
const route:ExecutionRouteSnapshot={routeId:'r1',provider:'broker-live-read',venue:'venue',instrumentId:'stock:x',status:'ACCEPTING',observedAt:'2026-01-02T14:00:00Z',availableAt:'2026-01-02T14:00:00Z',evidenceIds:['route:r1'],provenanceHash:'route:p'}
const slice:ExecutionSlice={sliceId:'s1',sequence:1,notional:{minor:100000n,currency:'USD'},instruction:'MARKETABLE_LIMIT',limitPriceMinor:10100n,earliestAt:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T14:05:00Z',idempotencyKey:'idem',authority:'NONE'}
const plan:ExecutionPlan={executionPlanId:'ep1',rebalanceIntentId:'ri1',portfolioPlanId:'pp1',instrumentId:'stock:x',side:'BUY',notional:{minor:100000n,currency:'USD'},urgency:'NORMAL',routeId:'r1',marketSnapshotId:'m1',slices:[slice],maxSpreadBps:100,maxParticipationBps:10000,informationCutoff:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T14:05:00Z',inputHash:'ih',provenanceHash:'ph',authority:'ANALYSIS_ONLY',requiresHumanApproval:true}
const executionPreflight:ExecutionPreflight={preflightId:'pf1',executionPlanId:'ep1',status:'PASS',reasonCodes:[],checkedAt:'2026-01-02T14:03:00Z',routeSnapshotId:'r1',marketSnapshotId:'m1',authority:'NONE'}
const shadow:ShadowReadinessAssessment={assessmentId:'shadow-ready',sampleSize:25,status:'ELIGIBLE_FOR_REVIEW',reasonCodes:[],maxAbsPriceDriftBps:100,maxSpreadDriftBps:100,minDepthRatioBps:5000,authority:'REVIEW_ONLY',canAuthorizeLive:false}
const shadowCertification:ShadowCertificationReport={reportId:'shadow-cert',provider:'live-read',cases:[],passed:true,liveExecutionEligible:false,authority:'CERTIFICATION_ONLY',provenanceHash:'shadow:p'}
const account=(id='acct-cap-1',availableAt='2026-01-02T14:02:00Z'):BrokerAccountCapabilitySnapshot=>({snapshotId:id,provider:'broker-live-read',accountId:'acct1',status:'ACTIVE',assetClasses:['EQUITY','FOREX'],orderTypes:['LIMIT'],currencies:['USD'],canBuy:true,canSell:true,canShort:true,canBorrow:true,maxLeverage:'2',buyingPowerMinor:500000n,settledCashMinor:250000n,reservedCashMinor:50000n,longPositionMarketValueMinorByInstrument:{'stock:x':300000n},currency:'USD',restrictionCodes:[],observedAt:availableAt,receivedAt:availableAt,availableAt,expiresAt:'2026-01-02T14:10:00Z',evidenceIds:['broker:cap'],provenanceHash:'cap:p',authority:'EVIDENCE_ONLY'})
const adapter=(s=account()):BrokerCapabilityDiscoveryAdapter=>({provider:'broker-live-read',environment:'LIVE_READ_ONLY',async readAccountCapabilities(){return s}})
const good=()=>preflightLiveExecution({plan,market,route,executionPreflight,account:account(),shadow,shadowCertification,provider:'broker-live-read',accountId:'acct1',checkedAt:'2026-01-02T14:03:00Z',expiresAt:'2026-01-02T14:04:00Z'})

test('046.1 capability discovery adapter is structurally read-only',()=>{assert.doesNotThrow(()=>assertCapabilityDiscoveryAdapter(adapter()));assert.throws(()=>assertCapabilityDiscoveryAdapter({...adapter(),submitOrder(){}}),/MUTATING_ADAPTER_FORBIDDEN/)})
test('046.2 account capability discovery is evidence-only provider/account bound',async()=>{const s=await discoverBrokerAccountCapabilities({adapter:adapter(),accountId:'acct1',informationCutoff:'2026-01-02T14:03:00Z',now:'2026-01-02T14:03:00Z'});assert.equal(s.authority,'EVIDENCE_ONLY');assert.equal(s.accountId,'acct1')})
test('046.3 future account capability evidence is rejected',async()=>{await assert.rejects(()=>discoverBrokerAccountCapabilities({adapter:adapter(account('future','2026-01-02T14:04:00Z')),accountId:'acct1',informationCutoff:'2026-01-02T14:03:00Z',now:'2026-01-02T14:03:00Z'}),/FUTURE_ACCOUNT_CAPABILITY/)})
test('046.4 passing live preflight is approval-eligible only and has zero execution authority',()=>{const p=good();assert.equal(p.status,'PASS_FOR_HUMAN_APPROVAL');assert.equal(p.authority,'PREFLIGHT_ONLY');assert.equal(p.requiresHumanApproval,true);assert.equal(p.canSubmitOrders,false);assert.equal(p.canAuthorizeLive,false)})
test('046.5 cash-only buy ignores margin buying power and blocks insufficient settled cash',()=>{const a={...account(),buyingPowerMinor:900000n,settledCashMinor:100000n,reservedCashMinor:50000n},p=preflightLiveExecution({plan,market,route,executionPreflight,account:a,shadow,shadowCertification,provider:'broker-live-read',accountId:'acct1',checkedAt:'2026-01-02T14:03:00Z',expiresAt:'2026-01-02T14:04:00Z'});assert.equal(p.status,'BLOCK');assert.ok(p.reasonCodes.includes('CASH_ONLY_BUY_INSUFFICIENT'))})
test('046.6 long-only sell blocks a sell larger than verified long inventory',()=>{const sellPlan={...plan,side:'SELL' as const},a={...account(),longPositionMarketValueMinorByInstrument:{'stock:x':50000n}},p=preflightLiveExecution({plan:sellPlan,market,route,executionPreflight,account:a,shadow,shadowCertification,provider:'broker-live-read',accountId:'acct1',checkedAt:'2026-01-02T14:03:00Z',expiresAt:'2026-01-02T14:04:00Z'});assert.equal(p.status,'BLOCK');assert.ok(p.reasonCodes.includes('VERIFIED_LONG_POSITION_INSUFFICIENT'))})
test('046.7 shadow and execution preflight gates must both pass',()=>{const blockedShadow={...shadow,status:'REJECTED' as const},p=preflightLiveExecution({plan,market,route,executionPreflight,account:account(),shadow:blockedShadow,shadowCertification,provider:'broker-live-read',accountId:'acct1',checkedAt:'2026-01-02T14:03:00Z',expiresAt:'2026-01-02T14:04:00Z'});assert.equal(p.status,'BLOCK');assert.ok(p.reasonCodes.includes('SHADOW_READINESS_NOT_ELIGIBLE'))})
test('046.8 approval candidate still requires explicit human approval and cannot execute',()=>{const c=createLiveApprovalCandidate({preflight:good(),requestedAt:'2026-01-02T14:03:30Z'});assert.equal(c.capability,'money.trade.submit');assert.equal(c.authority,'APPROVAL_REQUEST_ONLY');assert.equal(c.requiresExplicitHumanApproval,true);assert.equal(c.canExecute,false)})
test('046.9 PIT replay excludes account capability snapshots unavailable at cutoff',()=>{const r=buildPreflightReplay({snapshots:[account(),account('future','2026-01-02T14:04:00Z')],informationCutoff:'2026-01-02T14:03:00Z'});assert.deepEqual(r.includedCapabilitySnapshotIds,['acct-cap-1']);assert.deepEqual(r.excludedFutureSnapshotIds,['future']);assert.equal(r.authority,'RESEARCH_ONLY')})
test('046.10 certification can validate preflight governance but cannot enable execution',()=>{const names=['read-only-capability-discovery','account-binding','asset-order-currency-gates','buying-power-gate','leverage-short-disabled','execution-preflight-required','shadow-certification-required','human-approval-required','pit-replay','no-execution-authority'],cases:LivePreflightCertificationCase[]=names.map((name,i)=>({caseId:'c'+i,name,passed:true,evidenceIds:['test:'+name]})),r=certifyLivePreflight({provider:'broker-live-read',cases});assert.equal(r.passed,true);assert.equal(r.executionEnabled,false);assert.equal(r.authority,'CERTIFICATION_ONLY')})
