import test from 'node:test'
import assert from 'node:assert/strict'
import { buildPortfolioReplay, buildRebalanceIntents, calibrateAllocation, constructPortfolio, portfolioTotal, recordPaperPortfolioRun, scoreOpportunity } from './portfolio-construction-engine.js'
import type { AllocationConstraint, PortfolioConstructionSnapshot, PortfolioObjective } from './portfolio-construction-contracts.js'
import type { OpportunityCandidateV2 } from './cross-asset-fusion-contracts.js'

const snapshot=(cutoff='2026-01-02T00:00:00Z'):PortfolioConstructionSnapshot=>({snapshotId:'p1',accountId:'a1',currency:'USD',cash:{minor:400000n,currency:'USD'},reservedCash:{minor:100000n,currency:'USD'},holdings:[{instrumentId:'stock:old',assetClass:'STOCK',marketValue:{minor:600000n,currency:'USD'},liquidValue:{minor:550000n,currency:'USD'},clusterIds:['legacy'],evidenceIds:['position']}],informationCutoff:cutoff,stateHash:'state',evidenceIds:['ledger']})
const opp=(id:string,asset:'STOCK'|'FOREX'|'CRYPTO'='STOCK',confidence=.8,cutoff='2026-01-01T00:00:00Z'):OpportunityCandidateV2=>({opportunityId:id,thesisId:'t:'+id,subjectId:'s:'+id,instrumentIds:['i:'+id],assetClasses:[asset],direction:'BULLISH',horizon:'MEDIUM',expectedUpside:.2,expectedDownside:-.1,confidence,liquidityStatus:'ASSESSED',riskStatus:'ASSESSED',invalidationConditions:['thesis break'],evidenceIds:['e:'+id],informationCutoff:cutoff,expiresAt:'2026-06-01T00:00:00Z',provenanceHash:'p:'+id,authority:'NONE'})
const objectives:PortfolioObjective[]=[{objectiveId:'risk-adjusted',kind:'RISK_ADJUSTED_RETURN',weightBps:6000,methodologyVersion:'1'},{objectiveId:'preserve',kind:'CAPITAL_PRESERVATION',weightBps:4000,methodologyVersion:'1'}]
const constraints:AllocationConstraint[]=[{constraintId:'reserve',kind:'MIN_CASH_RESERVE_BPS',limitBps:2000,policyVersion:'1'},{constraintId:'position',kind:'MAX_POSITION_BPS',limitBps:4000,policyVersion:'1'},{constraintId:'opportunity',kind:'MAX_OPPORTUNITY_BPS',limitBps:3500,policyVersion:'1'},{constraintId:'turnover',kind:'MAX_TURNOVER_BPS',limitBps:10000,policyVersion:'1'},{constraintId:'no-short',kind:'NO_SHORT',policyVersion:'1'},{constraintId:'no-leverage',kind:'NO_LEVERAGE',policyVersion:'1'}]
const plan=()=>constructPortfolio({snapshot:snapshot(),opportunities:[opp('alpha'),opp('beta','FOREX',.6)],constraints,objectives,expiresAt:'2026-02-01T00:00:00Z'})

test('040.1 portfolio snapshot uses exact minor units and deterministic total',()=>{assert.equal(portfolioTotal(snapshot()),1000000n)})
test('040.2 opportunity scoring consumes governed 039 opportunities without authority',()=>{const o=opp('alpha');assert.ok(scoreOpportunity(o,objectives)>0);assert.equal(o.authority,'NONE')})
test('040.2 rejects future and stale opportunity inputs',()=>{assert.throws(()=>constructPortfolio({snapshot:snapshot(),opportunities:[opp('future','STOCK',.8,'2027-01-01T00:00:00Z')],constraints,objectives,expiresAt:'2026-02-01T00:00:00Z'}),/FUTURE_OPPORTUNITY/);const stale={...opp('stale'),expiresAt:'2026-01-01T00:00:00Z'};assert.throws(()=>constructPortfolio({snapshot:snapshot(),opportunities:[stale],constraints,objectives,expiresAt:'2026-02-01T00:00:00Z'}),/STALE_OPPORTUNITY/)})
test('040.3 objective weights must be explicit and total 10000 bps',()=>{assert.throws(()=>scoreOpportunity(opp('x'),[{objectiveId:'bad',kind:'LIQUIDITY',weightBps:9000,methodologyVersion:'1'}]),/OBJECTIVE_WEIGHTS_NOT_10000/)})
test('040.3-040.5 plan enforces reserve and per-position concentration',()=>{const p=plan();assert.ok(p.cashTargetBps>=2000);assert.ok(p.targets.every(t=>t.targetBps<=3500));assert.equal(p.authority,'ANALYSIS_ONLY')})
test('040.4 asset-class concentration can bind independently',()=>{const cs=[...constraints,{constraintId:'stock-cap',kind:'MAX_ASSET_CLASS_BPS' as const,limitBps:1000,subject:'STOCK',policyVersion:'1'}],p=constructPortfolio({snapshot:snapshot(),opportunities:[opp('a'),opp('b')],constraints:cs,objectives,expiresAt:'2026-02-01T00:00:00Z'});assert.ok(p.targets.reduce((n,t)=>n+(t.assetClass==='STOCK'?t.targetBps:0),0)<=1000)})
test('040.5 unassessed liquidity/risk cannot enter portfolio construction',()=>{const bad={...opp('x'),liquidityStatus:'UNKNOWN' as const};assert.throws(()=>constructPortfolio({snapshot:snapshot(),opportunities:[bad],constraints,objectives,expiresAt:'2026-02-01T00:00:00Z'}),/NOT_GOVERNED/)})
test('040.6 turnover limit fails closed rather than silently scaling trades',()=>{const cs=constraints.map(c=>c.kind==='MAX_TURNOVER_BPS'?{...c,limitBps:100}:c);assert.throws(()=>constructPortfolio({snapshot:snapshot(),opportunities:[opp('x')],constraints:cs,objectives,expiresAt:'2026-02-01T00:00:00Z'}),/TURNOVER_LIMIT_BREACH/)})
test('040.6-040.7 rebalance outputs intents only and cannot execute',()=>{const p=plan(),xs=buildRebalanceIntents(p,snapshot());assert.ok(xs.some(x=>x.side==='BUY'));assert.ok(xs.some(x=>x.instrumentId==='stock:old'&&x.side==='SELL'));assert.ok(xs.every(x=>x.authority==='NONE'))})
test('040.7 portfolio plan never creates ActionRequest permit order or trade authority',()=>{const p=plan();assert.equal(p.authority,'ANALYSIS_ONLY');assert.equal('approvalId' in p,false);assert.equal('executionPermit' in p,false);assert.equal('orderId' in p,false)})
test('040.8 paper portfolio is isolated from live authority',()=>{const p=plan(),r=recordPaperPortfolioRun({plan:p,startingValue:{minor:1000000n,currency:'USD'},endingValue:{minor:1050000n,currency:'USD'},fees:{minor:1000n,currency:'USD'},slippage:{minor:500n,currency:'USD'},startedAt:'2026-01-03',endedAt:'2026-02-01',evidenceIds:['paper-ledger']});assert.equal(r.authority,'PAPER_ONLY');assert.equal(r.endingValue.minor,1050000n)})
test('040.9 allocation calibration learns from paper outcomes but carries no execution authority',()=>{const p=plan(),r=recordPaperPortfolioRun({plan:p,startingValue:{minor:1000000n,currency:'USD'},endingValue:{minor:1050000n,currency:'USD'},fees:{minor:1000n,currency:'USD'},slippage:{minor:500n,currency:'USD'},startedAt:'2026-01-03',endedAt:'2026-02-01',evidenceIds:['paper-ledger']}),c=calibrateAllocation({plan:p,run:r,maxDrawdownBps:250,createdAt:'2026-02-02'});assert.equal(c.returnBps,485);assert.equal(c.authority,'LEARNING_ONLY')})
test('040.10 PIT replay excludes future opportunities and preserves the certified plan',()=>{const p=plan(),future=opp('future','CRYPTO',.9,'2027-01-01T00:00:00Z'),r=buildPortfolioReplay({snapshot:snapshot(),opportunities:[opp('alpha'),opp('beta','FOREX',.6),future],plan:p,cutoff:'2026-01-02T00:00:00Z'});assert.deepEqual(r.excludedFutureOpportunityIds,['future']);assert.deepEqual(r.opportunityIds,['alpha','beta']);assert.equal(r.authority,'RESEARCH_ONLY')})
test('040.10 replay rejects a plan contaminated by evidence unavailable at replay cutoff',()=>{const p=plan();assert.throws(()=>buildPortfolioReplay({snapshot:snapshot(),opportunities:[opp('future','CRYPTO',.9,'2027-01-01T00:00:00Z')],plan:p,cutoff:'2026-01-02T00:00:00Z'}),/REPLAY_PLAN_CONTAMINATED/)})
