import test from 'node:test'
import assert from 'node:assert/strict'
import { certifyMoney060LiveCanary,certifyMoney060Software,type Money060SoftwareCaseName,type Money060PrimaryLiveCanaryEvidence,type Money060FailureDrillEvidence } from './money-060-live-canary.js'

const names:Money060SoftwareCaseName[]=['alpaca-paper-live-separation','credential-isolation','durable-provider-event-replay','provider-event-conflict-block','realized-pnl-lot-accounting','corporate-action-basis','fx-path-costs','tax-review-no-auto-adjust','operator-approval-execute-separation','unknown-kill-switch-boundary']
const primary=(overrides:Partial<Money060PrimaryLiveCanaryEvidence>={}):Money060PrimaryLiveCanaryEvidence=>({environment:'LIVE',provider:'alpaca',accountId:'acct1',instrumentId:'stock:AAPL',side:'BUY',notionalMinor:1000n,currency:'USD',approvalReceiptId:'approval1',permitId:'permit1',executionId:'exec1',providerReference:'alpaca-order1',providerStates:['ACKNOWLEDGED','FILLED'],receiptIds:['receipt1'],fillIds:['fill1'],settlementEvidenceIds:['settlement1'],portfolioReconciliationId:'recon1',portfolioStatus:'MATCH',humanApproved:true,manualExecuteTriggerId:'click1',recordedAt:'2026-09-20T19:00:00Z',evidenceIds:['live:req','broker:fill'],...overrides})
const drills=(overrides:Partial<Money060FailureDrillEvidence>={}):Money060FailureDrillEvidence=>({timeoutUnknownBlocked:true,unknownReconciledBeforeNewAttempt:true,cancelReconciled:true,duplicateProviderEventDeduped:true,restartReplayVerified:true,killSwitchVerified:true,evidenceIds:['drill:timeout','drill:cancel','drill:restart','drill:kill'],...overrides})

test('060.1 software certification ends at READY_FOR_HUMAN_LIVE_CANARY, not live authority',()=>{const r=certifyMoney060Software(names.map((name,i)=>({caseId:'c'+i,name,passed:true,evidenceIds:['test:'+name]})));assert.equal(r.passed,true);assert.equal(r.status,'READY_FOR_HUMAN_LIVE_CANARY');assert.equal(r.autonomousStockForexEnabled,false);assert.equal(r.authority,'CERTIFICATION_ONLY')})
test('060.2 a paper execution cannot be presented as the funded live canary',()=>{assert.throws(()=>certifyMoney060LiveCanary({primary:primary({environment:'PAPER' as any}),drills:drills(),maxCanaryNotionalMinor:5000n}),/LIVE_ENVIRONMENT_REQUIRED/)})
test('060.3 canary size is independently capped even after all prior approvals',()=>{assert.throws(()=>certifyMoney060LiveCanary({primary:primary({notionalMinor:10000n}),drills:drills(),maxCanaryNotionalMinor:5000n}),/CANARY_NOTIONAL_LIMIT/)})
test('060.4 settlement and canonical portfolio reconciliation are mandatory',()=>{assert.throws(()=>certifyMoney060LiveCanary({primary:primary({settlementEvidenceIds:[],portfolioStatus:'DISCREPANCY'}),drills:drills(),maxCanaryNotionalMinor:5000n}),/SETTLEMENT_EVIDENCE_REQUIRED|PORTFOLIO_RECONCILIATION_REQUIRED/)})
test('060.5 UNKNOWN cancel restart duplicate and kill-switch drills all require evidence',()=>{assert.throws(()=>certifyMoney060LiveCanary({primary:primary(),drills:drills({restartReplayVerified:false}),maxCanaryNotionalMinor:5000n}),/DRILL_REQUIRED:restartReplayVerified/)})
test('060.6 a complete live evidence bundle certifies only tiny manual-canary scope',()=>{const r=certifyMoney060LiveCanary({primary:primary(),drills:drills(),maxCanaryNotionalMinor:5000n});assert.equal(r.passed,true);assert.equal(r.scope,'TINY_MANUAL_CANARY_ONLY');assert.equal(r.autonomousStockForexEnabled,false);assert.equal(r.canIncreaseLimits,false);assert.equal(r.authority,'CERTIFICATION_ONLY')})
