import test from 'node:test'
import assert from 'node:assert/strict'
import { artifactsAtCutoff, assertInformationCannotAuthorize, buildInformationEvent, buildInformationEvidenceBundle, claimsAtCutoff, relateClaims, type InformationArtifact, type InformationClaim, type InformationSource } from './information-integrity-engine.js'
import { assessSourceIndependence, classifyArtifactNovelty, createInformationReplayFrame, createMarketRelevance, toDecisionEvidenceIngress } from './information-analysis-engine.js'

const source=(id:string,group:string,reliability:InformationSource['reliability']='INDEPENDENT_SECONDARY'):InformationSource=>({sourceId:id,name:id,kind:'NEWS',reliability,canonicalDomain:id+'.test',independenceGroup:group,effectiveFrom:'2020-01-01',methodologyVersion:'1',evidenceRefs:['registry'],provenanceHash:'src-'+id})
const artifact=(id:string,sourceId:string,availableAt='2026-01-01T12:00:00Z'):InformationArtifact=>({artifactId:id,sourceId,sourceArtifactId:id,contentHash:'hash-'+id,observedAt:availableAt,receivedAt:availableAt,availableAt,status:'ACTIVE',retrievalRef:'ref:'+id,evidenceRefs:['capture:'+id],provenanceHash:'artifact-'+id})
const claim=(id:string,artifactId:string,polarity:InformationClaim['polarity']='AFFIRMS',availableAt='2026-01-01T12:00:00Z'):InformationClaim=>({claimId:id,artifactId,subjectIds:['issuer:abc'],predicate:'guidance-raised',object:'yes',polarity,availableAt,extractorVersion:'1',confidence:.9,evidenceRefs:['span:'+id],provenanceHash:'claim-'+id})

test('038 point-in-time gate excludes future artifacts and claims',()=>{const a1=artifact('a1','s1'),a2=artifact('a2','s2','2026-02-01T00:00:00Z'),c1=claim('c1','a1'),c2=claim('c2','a2','2026-02-01T00:00:00Z');assert.deepEqual(artifactsAtCutoff([a1,a2],'2026-01-15T00:00:00Z').map(x=>x.artifactId),['a1']);assert.deepEqual(claimsAtCutoff([c1,c2],[a1,a2],'2026-01-15T00:00:00Z').map(x=>x.claimId),['c1'])})

test('038 corrections supersede old artifacts without rewriting history',()=>{const old=artifact('old','s1'),correction={...artifact('new','s1','2026-01-02T00:00:00Z'),status:'CORRECTED' as const,revisionOfArtifactId:'old'};assert.deepEqual(artifactsAtCutoff([old,correction],'2026-01-01T18:00:00Z').map(x=>x.artifactId),['old']);assert.deepEqual(artifactsAtCutoff([old,correction],'2026-01-03T00:00:00Z').map(x=>x.artifactId),['new'])})

test('038 copied stories count as one independence group',()=>{const xs=[source('wire','wire-group'),source('site-a','wire-group'),source('site-b','wire-group')];const a=assessSourceIndependence(xs.map(x=>x.sourceId),xs);assert.equal(a.independentCount,1);assert.equal(a.duplicateRisk,'HIGH')})

test('038 corroboration requires independent source groups',()=>{const sources=[source('s1','g1'),source('s2','g2')],arts=[artifact('a1','s1'),artifact('a2','s2')],claims=[claim('c1','a1'),claim('c2','a2')],rel=[relateClaims(claims[0]!,claims[1]!,'1','2026-01-01T12:01:00Z')];const e=buildInformationEvent({eventClass:'GUIDANCE',subjectIds:['issuer:abc'],instrumentIds:['instrument:abc'],effectiveAt:'2026-01-01T11:00:00Z',cutoff:'2026-01-02T00:00:00Z',claims,artifacts:arts,sources,relations:rel,methodologyVersion:'1'});assert.equal(e.status,'CORROBORATED');assert.equal(e.corroborationCount,2);assert.equal(e.authority,'EVIDENCE_ONLY')})

test('038 primary authority is explicit but still evidence only',()=>{const s=source('sec','sec','PRIMARY_AUTHORITY'),a=artifact('a','sec'),c=claim('c','a');const e=buildInformationEvent({eventClass:'FILING',subjectIds:['issuer:abc'],instrumentIds:['instrument:abc'],effectiveAt:'2026-01-01',cutoff:'2026-01-02',claims:[c],artifacts:[a],sources:[s],relations:[],methodologyVersion:'1'});assert.equal(e.status,'PRIMARY_CONFIRMED');assert.doesNotThrow(()=>assertInformationCannotAuthorize(e));assert.equal(e.authority,'EVIDENCE_ONLY')})

test('038 contradictions prevent false consensus',()=>{const sources=[source('s1','g1'),source('s2','g2')],arts=[artifact('a1','s1'),artifact('a2','s2')],c1=claim('c1','a1'),c2={...claim('c2','a2','DENIES'),object:'no'},rel=relateClaims(c1,c2,'1','2026-01-01T12:01:00Z'),e=buildInformationEvent({eventClass:'GUIDANCE',subjectIds:['issuer:abc'],instrumentIds:['instrument:abc'],effectiveAt:'2026-01-01',cutoff:'2026-01-02',claims:[c1,c2],artifacts:arts,sources,relations:[rel],methodologyVersion:'1'});assert.equal(rel.relation,'CONTRADICTS');assert.equal(e.status,'CONTESTED');assert.ok(e.contradictionClaimIds.length===2)})

test('038 exact duplicates are not novel information',()=>{const a1=artifact('a1','s1'),a2={...artifact('a2','s2'),contentHash:a1.contentHash};assert.equal(classifyArtifactNovelty(a2,[a1],'1').status,'EXACT_DUPLICATE')})

test('038 market relevance is analysis only',()=>{const r=createMarketRelevance({eventId:'e',instrumentId:'i',channels:['FUNDAMENTAL'],direction:'POSITIVE',confidence:.7,horizon:'MEDIUM',methodologyVersion:'1',evidenceClaimIds:['c']});assert.equal(r.authority,'ANALYSIS_ONLY')})

test('038 evidence bundles retain contradictions and cutoff lineage',()=>{const sources=[source('s1','g1'),source('s2','g2')],arts=[artifact('a1','s1'),artifact('a2','s2')],c1=claim('c1','a1'),c2={...claim('c2','a2','DENIES'),object:'no'},rel=relateClaims(c1,c2,'1','2026-01-01T12:01:00Z'),e=buildInformationEvent({eventClass:'RUMOR',subjectIds:['issuer:abc'],instrumentIds:['i'],effectiveAt:'2026-01-01',cutoff:'2026-01-02',claims:[c1,c2],artifacts:arts,sources,relations:[rel],methodologyVersion:'1'}),b=buildInformationEvidenceBundle({cutoff:'2026-01-02',events:[e],claims:[c1,c2],artifacts:arts,relations:[rel]});assert.equal(b.openContradictionIds.length,1);assert.equal(b.authority,'EVIDENCE_ONLY')})

test('038 replay frame excludes information unavailable at historical cutoff',()=>{const a1=artifact('a1','s1'),a2=artifact('a2','s2','2027-01-01T00:00:00Z'),c1=claim('c1','a1'),c2=claim('c2','a2','AFFIRMS','2027-01-01T00:00:00Z'),frame=createInformationReplayFrame('2026-02-01T00:00:00Z',[a1,a2],[c1,c2],[]);assert.deepEqual(frame.artifactIds,['a1']);assert.deepEqual(frame.claimIds,['c1'])})

test('038 decision ingress cannot smuggle execution authority',()=>{const ingress=toDecisionEvidenceIngress({informationCutoff:'2026-01-01',eventIds:['e'],openContradictionIds:[],authority:'EVIDENCE_ONLY'},'2026-01-02');assert.equal(ingress.authority,'NONE');assert.throws(()=>toDecisionEvidenceIngress({informationCutoff:'2027-01-01',eventIds:['e'],openContradictionIds:[],authority:'EVIDENCE_ONLY'},'2026-01-02'),/FUTURE_LEAK/)})
