import test from 'node:test'
import assert from 'node:assert/strict'
import { buildExecutionOutbox, buildExecutionReceiptReplay, buildJournalPostingIntents, claimProviderEvent, createExecutionReceipt, learnFromExecutionReceipts, projectFillFromProviderEvent, projectSettlementFromProviderEvent, reconcileProviderEvent } from './execution-receipt-engine.js'
import type { ProviderExecutionEvent } from './execution-receipt-contracts.js'
import { createExecutionAttempt } from './execution-attempt.js'
import type { ExecutionAction } from './execution-permit.js'

const action:ExecutionAction={actionId:'ar1',userId:'u1',capability:'money.trade.submit',provider:'broker',accountId:'acct',instrumentId:'stock:x',amount:'1000.00',currency:'USD'}
const attempt=createExecutionAttempt({attemptId:'exec1',requestId:'ar1',permitId:'permit1',action,operation:'money.trade.submit',now:'2026-01-02T00:00:00Z'})
const ev=(id:string,state:ProviderExecutionEvent['state']='ACKNOWLEDGED',availableAt='2026-01-02T00:00:03Z',sequence=1):ProviderExecutionEvent=>({eventId:'event:'+id,providerEventId:'provider:'+id,provider:'broker',executionId:'exec1',actionFingerprint:attempt.actionFingerprint,providerReference:'order:1',state,economics:state==='FILLED'||state==='PARTIALLY_FILLED'?{orderId:'order:1',instrumentId:'stock:x',side:'BUY',filledQuantity:'10',fillPrice:{coefficient:10000n,scale:2,currency:'USD'},fee:{coefficient:100n,scale:2,currency:'USD'},settlementStatus:'SETTLED',settlementExpectedAt:'2026-01-04T00:00:00Z',settlementActualAt:'2026-01-04T00:00:00Z'}:undefined,occurredAt:'2026-01-02T00:00:01Z',observedAt:'2026-01-02T00:00:02Z',receivedAt:'2026-01-02T00:00:03Z',availableAt,sequence,evidenceIds:['provider-payload:'+id],payloadHash:'payload:'+id,provenanceHash:'prov:'+id,authority:'EVIDENCE_ONLY'})

test('042.1 provider execution event is evidence-only and clock/provenance bound',()=>{const e=ev('1');assert.equal(e.authority,'EVIDENCE_ONLY');assert.equal(claimProviderEvent(e,[]).disposition,'ACCEPTED')})
test('042.2 duplicate provider event is idempotent but conflicting payload fails closed',()=>{const e=ev('1');assert.equal(claimProviderEvent(e,[e]).disposition,'DUPLICATE');assert.throws(()=>claimProviderEvent({...e,payloadHash:'tampered'},[e]),/PROVIDER_EVENT_ID_CONFLICT/)})
test('042.3 immutable execution receipt hashes exact provider event',()=>{const e=ev('1'),r=createExecutionReceipt(e,'2026-01-02T00:00:04Z');assert.equal(r.executionId,e.executionId);assert.equal(r.authority,'EVIDENCE_ONLY');assert.ok(r.eventHash)})
test('042.4 reconciliation binds execution identity provider and action fingerprint',()=>{const e={...ev('1'),actionFingerprint:'wrong'};const d=reconcileProviderEvent({attempt,event:e,priorEvents:[]});assert.equal(d.disposition,'BLOCK_CONFLICT');assert.ok(d.reasonCodes.includes('ACTION_FINGERPRINT_MISMATCH'));assert.equal(d.nextState,'RECOVERY_REQUIRED')})
test('042.4 duplicate event never reapplies financial state',()=>{const e=ev('1'),d=reconcileProviderEvent({attempt,event:e,priorEvents:[e]});assert.equal(d.disposition,'IGNORE_DUPLICATE')})
test('042.5 out-of-order or conflicting terminal provider state requires review',()=>{const filled=ev('filled','FILLED','2026-01-02T00:00:04Z',3),late=ev('late','ACKNOWLEDGED','2026-01-02T00:00:05Z',2),d=reconcileProviderEvent({attempt,event:late,priorEvents:[filled]});assert.equal(d.disposition,'MANUAL_REVIEW');assert.equal(d.nextState,'RECOVERY_REQUIRED')})
test('042.5 UNKNOWN remains recovery-required and never implies retry safety',()=>{const d=reconcileProviderEvent({attempt,event:ev('unknown','UNKNOWN'),priorEvents:[]});assert.equal(d.nextState,'RECOVERY_REQUIRED');assert.equal(d.authority,'RECONCILIATION_ONLY')})
test('042.6 provider fill projection requires complete fill economics',()=>{const e=ev('fill','FILLED'),f=projectFillFromProviderEvent(e);assert.ok(f);assert.equal(f?.providerExecutionId,'order:1');assert.throws(()=>projectFillFromProviderEvent({...e,economics:{...e.economics!,fillPrice:undefined}}),/FILL_ECONOMICS_INCOMPLETE/)})
test('042.7 settlement projection is evidence-derived and linked to exact fill',()=>{const e=ev('fill','FILLED'),f=projectFillFromProviderEvent(e)!,s=projectSettlementFromProviderEvent(e,f);assert.equal(s?.status,'SETTLED');assert.deepEqual(s?.fillIds,[f.fillId])})
test('042.8 journal and outbox generation is intent-only and replay-safe',()=>{const e=ev('fill','FILLED'),r=createExecutionReceipt(e,'2026-01-04T00:00:01Z'),p=buildJournalPostingIntents(e),o=buildExecutionOutbox(e,r,'2026-01-04T00:00:02Z');assert.deepEqual(p.map(x=>x.kind),['FILL','FEE','SETTLEMENT']);assert.ok(p.every(x=>x.authority==='NONE'));assert.ok(o.every(x=>x.status==='PENDING'&&x.authority==='NONE'));assert.equal(buildExecutionOutbox(e,r,'2026-01-04T00:00:02Z')[0]?.outboxId,o[0]?.outboxId)})
test('042.9 receipt outcomes may calibrate learning but cannot authorize execution',()=>{const l=learnFromExecutionReceipts({executionId:'exec1',events:[ev('ack'),ev('fill','FILLED','2026-01-02T00:00:04Z',2)],createdAt:'2026-01-05T00:00:00Z'});assert.equal(l.terminalState,'FILLED');assert.equal(l.authority,'LEARNING_ONLY');assert.equal('permitId' in l,false)})
test('042.10 PIT replay excludes provider evidence not yet available',()=>{const r=buildExecutionReceiptReplay({executionId:'exec1',events:[ev('ack'),ev('future','FILLED','2027-01-01T00:00:00Z',2)],informationCutoff:'2026-01-02T00:00:05Z'});assert.deepEqual(r.includedEventIds,['event:ack']);assert.deepEqual(r.excludedFutureEventIds,['event:future']);assert.equal(r.terminalState,'ACKNOWLEDGED');assert.equal(r.authority,'RESEARCH_ONLY')})
