import test from 'node:test'
import assert from 'node:assert/strict'
import { assertPaperCapability, createPaperOrder, type PaperFillModel } from './paper-execution-contracts.js'
import { assessPaperPromotion, buildPaperPortfolio, buildPaperReplay, cancelPaperOrder, paperOrderState, simulatePaperFill, summarizePaperExecution } from './paper-execution-engine.js'
import type { ExecutionMarketSnapshot, ExecutionPlan, ExecutionSlice } from './execution-planning-contracts.js'

const market=(id='m1',availableAt='2026-01-02T00:00:00Z'):ExecutionMarketSnapshot=>({snapshotId:id,instrumentId:'stock:x',currency:'USD',bidMinor:9990n,askMinor:10000n,bidSize:'100',askSize:'100',visibleDepthNotionalMinor:100000n,observedAt:availableAt,availableAt,expiresAt:'2026-01-03T00:00:00Z',evidenceIds:['quote:'+id],provenanceHash:'p:'+id})
const slice:ExecutionSlice={sliceId:'s1',sequence:1,notional:{minor:100000n,currency:'USD'},instruction:'MARKETABLE_LIMIT',limitPriceMinor:10100n,earliestAt:'2026-01-02T00:00:00Z',expiresAt:'2026-01-03T00:00:00Z',idempotencyKey:'idem',authority:'NONE'}
const plan:ExecutionPlan={executionPlanId:'ep1',rebalanceIntentId:'ri1',portfolioPlanId:'pp1',instrumentId:'stock:x',side:'BUY',notional:{minor:100000n,currency:'USD'},urgency:'NORMAL',routeId:'paper',marketSnapshotId:'m1',slices:[slice],maxSpreadBps:100,maxParticipationBps:10000,informationCutoff:'2026-01-02T00:00:00Z',expiresAt:'2026-01-03T00:00:00Z',inputHash:'ih',provenanceHash:'ph',authority:'ANALYSIS_ONLY',requiresHumanApproval:true}
const model:PaperFillModel={modelVersion:'paper-v1',liquidityFillBps:10000,slippageBps:10,feeBps:5,passiveFillBps:2500,assumptionIds:['assumption:liquidity','assumption:costs']}
const order=()=>createPaperOrder({paperRunId:'run1',plan,slice,market:market(),submittedAt:'2026-01-02T00:00:01Z'})

test('043.1 paper capabilities are physically namespaced away from live trade authority',()=>{assert.doesNotThrow(()=>assertPaperCapability('money.simulation.order.submit'));assert.throws(()=>assertPaperCapability('money.trade.submit'),/LIVE_CAPABILITY_FORBIDDEN/)})
test('043.2 paper order consumes an analysis plan but grants simulation authority only',()=>{const o=order();assert.equal(o.authority,'SIMULATION_ONLY');assert.equal('permitId' in o,false);assert.equal('approvalId' in o,false)})
test('043.2 rejects future or stale market snapshots',()=>{assert.throws(()=>createPaperOrder({paperRunId:'r',plan:{...plan,marketSnapshotId:'future'},slice,market:market('future','2027-01-01T00:00:00Z'),submittedAt:'2026-01-02T00:00:00Z'}),/FUTURE_MARKET_SNAPSHOT/)})
test('043.3 fill model is explicit versioned and evidence bound',()=>{const f=simulatePaperFill({order:order(),market:market(),model,filledAt:'2026-01-02T00:00:02Z'});assert.ok(f);assert.equal(f?.authority,'SIMULATION_ONLY');assert.ok(f?.evidenceIds.includes('assumption:costs'))})
test('043.4 spread slippage and fees are charged rather than hidden',()=>{const f=simulatePaperFill({order:order(),market:market(),model,filledAt:'2026-01-02T00:00:02Z'})!;assert.ok(f.fillPriceMinor>f.referencePriceMinor);assert.ok(f.fee.minor>0n);assert.equal(f.slippageBps,10)})
test('043.5 visible liquidity caps simulated fills and preserves partial state',()=>{const thin={...market(),visibleDepthNotionalMinor:25000n},o=createPaperOrder({paperRunId:'run1',plan,slice,market:thin,submittedAt:'2026-01-02T00:00:01Z'}),f=simulatePaperFill({order:o,market:thin,model,filledAt:'2026-01-02T00:00:02Z'})!;assert.equal(f.notional.minor,25000n);assert.equal(paperOrderState(o,[f],'2026-01-02T00:00:03Z'),'PARTIALLY_FILLED')})
test('043.6 paper cancellation is local simulation state and cannot cancel provider orders',()=>{const c=cancelPaperOrder(order(),'2026-01-02T00:00:02Z');assert.equal(c.state,'CANCELLED');assert.equal(c.authority,'SIMULATION_ONLY');assert.equal('providerReference' in c,false)})
test('043.7 paper portfolio is deterministic exact-minor state',()=>{const o=order(),f=simulatePaperFill({order:o,market:market(),model,filledAt:'2026-01-02T00:00:02Z'})!,a=buildPaperPortfolio({paperRunId:'run1',currency:'USD',initialCash:{minor:200000n,currency:'USD'},orders:[o],fills:[f],marks:{'stock:x':10000n},asOf:'2026-01-02T00:00:03Z'}),b=buildPaperPortfolio({paperRunId:'run1',currency:'USD',initialCash:{minor:200000n,currency:'USD'},orders:[o],fills:[f],marks:{'stock:x':10000n},asOf:'2026-01-02T00:00:03Z'});assert.equal(a.stateHash,b.stateHash);assert.equal(a.authority,'SIMULATION_ONLY')})
test('043.8 paper outcome attribution remains learning-only',()=>{const o=order(),f=simulatePaperFill({order:o,market:market(),model,filledAt:'2026-01-02T00:00:02Z'})!,x=summarizePaperExecution({paperRunId:'run1',executionPlanId:'ep1',orders:[o],fills:[f],createdAt:'2026-01-02T00:00:04Z'});assert.equal(x.authority,'LEARNING_ONLY');assert.equal(x.fillRateBps,10000);assert.ok(x.feesPaid.minor>0n)})
test('043.9 paper success may become review-eligible but can never authorize live execution',()=>{const o=order(),f=simulatePaperFill({order:o,market:market(),model,filledAt:'2026-01-02T00:00:02Z'})!,x=summarizePaperExecution({paperRunId:'run1',executionPlanId:'ep1',orders:[o],fills:[f],createdAt:'2026-01-02T00:00:04Z'}),a=assessPaperPromotion({paperRunId:'run1',outcomes:[x],minSamples:1,minFillRateBps:9000,maxAbsSlippageBps:50});assert.equal(a.status,'ELIGIBLE_FOR_REVIEW');assert.equal(a.canAuthorizeLive,false);assert.equal(a.authority,'REVIEW_ONLY')})
test('043.10 PIT paper replay excludes market evidence unavailable at cutoff',()=>{const r=buildPaperReplay({paperRunId:'run1',markets:[market(),market('future','2027-01-01T00:00:00Z')],informationCutoff:'2026-01-02T00:00:01Z'});assert.deepEqual(r.includedMarketSnapshotIds,['m1']);assert.deepEqual(r.excludedFutureSnapshotIds,['future']);assert.equal(r.authority,'RESEARCH_ONLY')})
