import test from 'node:test'
import assert from 'node:assert/strict'
import { createExecutionAttempt } from './execution-attempt.js'
import type { ExecutionAction } from './execution-permit.js'
import { assertProviderExecutionEvent } from './execution-receipt-contracts.js'
import { brokerContextFromAttempt, hash044, type BrokerCertificationCase, type BrokerOrderRequest } from './sandbox-broker-contracts.js'
import { certifySandboxBroker, DeterministicSandboxBroker, reconcileSandboxOrder, submitSandboxAttempt } from './sandbox-broker-engine.js'

const action=(capability='money.simulation.order.submit'):ExecutionAction=>({actionId:'paper-action-1',userId:'u1',capability,provider:'sandbox-broker',accountId:'paper-acct',instrumentId:'stock:x',amount:'1000',currency:'USD'})
const attempt=(capability='money.simulation.order.submit')=>createExecutionAttempt({attemptId:'sandbox-exec-1',requestId:'paper-action-1',permitId:'simulation-permit-not-live',action:action(capability),operation:capability,now:'2026-01-02T00:00:00Z'})
const order:BrokerOrderRequest={clientOrderId:'client-1',instrumentId:'stock:x',side:'BUY',orderType:'LIMIT',quantity:'10',limitPrice:'100',timeInForce:'DAY',currency:'USD'}

test('044.1 broker adapter context is sandbox-only and rejects live capability attempts',()=>{const c=brokerContextFromAttempt(attempt(),'2026-01-02T00:00:01Z');assert.equal(c.environment,'SANDBOX');assert.throws(()=>brokerContextFromAttempt(attempt('money.trade.submit'),'2026-01-02T00:00:01Z'),/LIVE_CAPABILITY_FORBIDDEN/)})
test('044.2 sandbox submission binds execution id idempotency fingerprint and provider',async()=>{const a=attempt(),b=new DeterministicSandboxBroker('sandbox-broker'),x=await submitSandboxAttempt({adapter:b,attempt:a,request:order,now:'2026-01-02T00:00:01Z'});assert.equal(x.event.executionId,a.attemptId);assert.equal(x.event.actionFingerprint,a.actionFingerprint);assert.equal(x.event.provider,a.provider)})
test('044.3 same idempotency key returns same provider reference without duplicate order',async()=>{const a=attempt(),b=new DeterministicSandboxBroker('sandbox-broker'),c=brokerContextFromAttempt(a,'2026-01-02T00:00:01Z'),x=await b.submitOrder(c,order),y=await b.submitOrder(c,order);assert.equal(x.providerReference,y.providerReference);await assert.rejects(()=>b.submitOrder(c,{...order,quantity:'11'}),/IDEMPOTENCY_CONFLICT/)})
test('044.4 sandbox ACK becomes canonical evidence-only provider event',async()=>{const x=await submitSandboxAttempt({adapter:new DeterministicSandboxBroker('sandbox-broker'),attempt:attempt(),request:order,now:'2026-01-02T00:00:01Z'});assert.equal(x.event.state,'ACKNOWLEDGED');assert.equal(x.event.authority,'EVIDENCE_ONLY');assert.doesNotThrow(()=>assertProviderExecutionEvent(x.event))})
test('044.5 reject path is provider evidence and does not manufacture success',async()=>{const x=await submitSandboxAttempt({adapter:new DeterministicSandboxBroker('sandbox-broker','REJECT'),attempt:attempt(),request:order,now:'2026-01-02T00:00:01Z'});assert.equal(x.event.state,'REJECTED');assert.ok(x.result)})
test('044.6 timeout after provider acceptance becomes UNKNOWN, never automatic retry',async()=>{const x=await submitSandboxAttempt({adapter:new DeterministicSandboxBroker('sandbox-broker','TIMEOUT_AFTER_ACCEPT'),attempt:attempt(),request:order,now:'2026-01-02T00:00:01Z'});assert.equal(x.event.state,'UNKNOWN');assert.equal(x.result,undefined);assert.equal('retry' in x.event,false)})
test('044.7 reconciliation queries provider after ambiguous outcome',async()=>{const a=attempt(),b=new DeterministicSandboxBroker('sandbox-broker','TIMEOUT_AFTER_ACCEPT'),x=await submitSandboxAttempt({adapter:b,attempt:a,request:order,now:'2026-01-02T00:00:01Z'});assert.equal(x.event.state,'UNKNOWN');const reference='sandbox-order:'+hash044({provider:'sandbox-broker',idempotencyKey:a.idempotencyKey}).slice(0,24);const reconciled=await reconcileSandboxOrder({adapter:b,attempt:a,providerReference:reference,now:'2026-01-02T00:00:02Z'});assert.equal(reconciled.state,'ACKNOWLEDGED')})
test('044.8 cancellation is sandbox-local and unknown references fail ambiguous',async()=>{const a=attempt(),b=new DeterministicSandboxBroker('sandbox-broker'),c=brokerContextFromAttempt(a,'2026-01-02T00:00:01Z'),s=await b.submitOrder(c,order),r=await b.cancelOrder({...c,now:'2026-01-02T00:00:02Z'},{clientOrderId:order.clientOrderId,providerReference:s.providerReference});assert.equal(r.state,'CANCELLED');const u=await b.cancelOrder({...c,now:'2026-01-02T00:00:03Z'},{clientOrderId:'bad',providerReference:'missing'});assert.equal(u.state,'UNKNOWN')})
test('044.9 sandbox query UNKNOWN remains evidence-only and compatible with 042 receipts',async()=>{const a=attempt(),b=new DeterministicSandboxBroker('sandbox-broker','UNKNOWN_QUERY'),e=await reconcileSandboxOrder({adapter:b,attempt:a,providerReference:'missing',now:'2026-01-02T00:00:02Z'});assert.equal(e.state,'UNKNOWN');assert.doesNotThrow(()=>assertProviderExecutionEvent(e))})
test('044.10 certification can pass sandbox contract but can never grant live eligibility',()=>{const names=['environment-isolation','idempotent-submit','timeout-unknown','reconciliation','cancel-safety','receipt-compatibility','no-live-authority'],cases:BrokerCertificationCase[]=names.map((name,i)=>({caseId:'c'+i,name,passed:true,evidenceIds:['test:'+name]})),r=certifySandboxBroker({provider:'sandbox-broker',cases});assert.equal(r.passed,true);assert.equal(r.liveEligible,false);assert.equal(r.authority,'CERTIFICATION_ONLY')})
