import test from 'node:test'
import assert from 'node:assert/strict'
import { ProductionBrokerHttpAdapter } from './production-broker-http-adapter.js'
import { reconcileProductionPortfolio } from './production-portfolio-reconciliation.js'
import { buildLiveOperationsConsole } from './live-operations-console.js'
import { certifyMoney055,type Money055CaseName } from './money-055-certification.js'
import { InMemoryLiveCanaryStateStore } from './live-canary-store.js'
import type { PortfolioState } from './canonical-financial-state.js'
import type { ExecutionPlan } from './execution-planning-contracts.js'
import type { LiveExecutionPreflight } from './live-preflight-contracts.js'

const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})
const adapter=()=>new ProductionBrokerHttpAdapter({provider:'broker',baseUrl:'https://broker.example/',credential:()=> 'secret',fetchImpl:async(input,init)=>{const u=String(input);if(init?.method==='POST')return response({id:'o1',state:'ACK'});if(u.includes('/positions'))return response([{instrumentId:'stock:x',quantity:'10',marketValueMinor:'100000'}]);if(u.includes('/orders/'))return response({id:'o1',clientOrderId:'idem',state:'FILLED'});return response({accountId:'acct1',cashMinor:'100000',settledCashMinor:'100000',buyingPowerMinor:'100000'})},accountPath:id=>'/accounts/'+id,positionsPath:id=>'/accounts/'+id+'/positions',ordersPath:'/orders',orderStatusPath:(id,client)=>'/orders/'+(id??client),cancelPath:id=>'/orders/'+id,mapAccount:(p:any,provider)=>({provider,accountId:p.accountId,currency:'USD',cashMinor:BigInt(p.cashMinor),settledCashMinor:BigInt(p.settledCashMinor),buyingPowerMinor:BigInt(p.buyingPowerMinor),asOf:'2026-09-20T17:00:00Z',evidenceIds:['account']}),mapPositions:(p:any,provider)=>p.map((x:any)=>({provider,accountId:'acct1',instrumentId:x.instrumentId,quantity:x.quantity,marketValueMinor:BigInt(x.marketValueMinor),currency:'USD',asOf:'2026-09-20T17:00:00Z',evidenceIds:['positions']})),mapSubmission:(p:any,now)=>({providerReference:p.id,providerEventId:'submit:'+p.id,state:'ACKNOWLEDGED',occurredAt:now,observedAt:now,receivedAt:now,availableAt:now,evidenceIds:['submit']}),mapOrder:(p:any,now)=>({providerReference:p.id,clientOrderId:p.clientOrderId,state:p.state,observedAt:now,evidenceIds:['order']}),serializeOrder:x=>x})
const canonical:PortfolioState={portfolioId:'p',accountId:'acct1',cash:{accountId:'acct1',cash:{coefficient:100000n,scale:0,currency:'USD'},settled:{coefficient:100000n,scale:0,currency:'USD'},unsettled:{coefficient:0n,scale:0,currency:'USD'},reserved:{coefficient:0n,scale:0,currency:'USD'},available:{coefficient:100000n,scale:0,currency:'USD'},buyingPower:{coefficient:100000n,scale:0,currency:'USD'},asOf:'2026-09-20T17:00:00Z',evidenceRefs:['cash']},positions:[{accountId:'acct1',instrumentId:'stock:x',side:'LONG',quantity:'10',lotIds:['l1'],asOf:'2026-09-20T17:00:00Z',evidenceRefs:['position']}],lots:[],asOf:'2026-09-20T17:00:00Z',sourceEventIds:['e1'],stateHash:'h'}
const plan:ExecutionPlan={executionPlanId:'ep',rebalanceIntentId:'ri',portfolioPlanId:'pp',instrumentId:'stock:x',side:'BUY',notional:{minor:1000n,currency:'USD'},urgency:'NORMAL',routeId:'r',marketSnapshotId:'m',slices:[],maxSpreadBps:100,maxParticipationBps:100,informationCutoff:'2026-09-20T16:00:00Z',expiresAt:'2026-09-20T18:00:00Z',inputHash:'i',provenanceHash:'p',authority:'ANALYSIS_ONLY',requiresHumanApproval:true}
const preflight:LiveExecutionPreflight={preflightId:'pf',executionPlanId:'ep',provider:'broker',accountId:'acct1',status:'PASS_FOR_HUMAN_APPROVAL',reasonCodes:[],accountCapabilitySnapshotId:'c',routeSnapshotId:'r',marketSnapshotId:'m',shadowCertificationReportId:'s',checkedAt:'2026-09-20T16:00:00Z',expiresAt:'2026-09-20T18:00:00Z',inputHash:'i',provenanceHash:'p',authority:'PREFLIGHT_ONLY',requiresHumanApproval:true,canSubmitOrders:false,canAuthorizeLive:false}

test('051 production adapter requires HTTPS and isolates credential callback',()=>{assert.throws(()=>new ProductionBrokerHttpAdapter({...((adapter() as any).o??{}),provider:'x',baseUrl:'http://bad'}),/HTTPS/);assert.equal(adapter().environment,'LIVE')})
test('051 provider adapter submits idempotent live order and exposes reconciliation surface',async()=>{const a=adapter(),r=await a.submitOrder({environment:'LIVE',executionId:'e',idempotencyKey:'idem',actionFingerprint:'f',permitId:'p',userId:'u',manualTriggerId:'t',now:'2026-09-20T17:00:00Z'},{clientOrderId:'idem',accountId:'acct1',instrumentId:'stock:x',side:'BUY',orderType:'LIMIT',notionalMinor:'1000',limitPriceMinor:'100',currency:'USD',timeInForce:'DAY'});assert.equal(r.state,'ACKNOWLEDGED');assert.equal(a.canReconcile({provider:'broker',operation:'money.trade.submit'} as any),true)})
test('053 production portfolio truth matches provider without mutation',async()=>{const r=await reconcileProductionPortfolio({provider:'broker',accountId:'acct1',canonical,broker:adapter(),now:'2026-09-20T17:00:00Z'});assert.equal(r.status,'MATCH');assert.equal(r.autoCorrected,false)})
test('053 discrepancies are blocking evidence and never auto-correct canonical state',async()=>{const bad={...canonical,cash:{...canonical.cash,cash:{coefficient:999n,scale:0,currency:'USD'}}},r=await reconcileProductionPortfolio({provider:'broker',accountId:'acct1',canonical:bad,broker:adapter(),now:'2026-09-20T17:00:00Z'});assert.equal(r.status,'DISCREPANCY');assert.equal(r.discrepancies[0]?.severity,'BLOCKING');assert.equal(bad.cash.cash.coefficient,999n)})
test('054 console is display-only and blocks execute on discrepancy unknown or kill switch',async()=>{const canary=new InMemoryLiveCanaryStateStore();await canary.updateRiskMetrics({snapshotId:'r',provider:'broker',accountId:'acct1',currency:'USD',grossExposureMinor:0n,realizedPnlMinor:0n,observedAt:'2026-09-20T17:00:00Z',availableAt:'2026-09-20T17:00:00Z',evidenceIds:['r'],authority:'EVIDENCE_ONLY'},'2026-09-20','2026-09-20T17:00:00Z');const state=(await canary.get('broker','acct1','2026-09-20'))!,portfolio=await reconcileProductionPortfolio({provider:'broker',accountId:'acct1',canonical,broker:adapter(),now:'2026-09-20T17:00:00Z'}),ui=buildLiveOperationsConsole({plan,preflight,portfolio,canary:state,now:'2026-09-20T17:00:00Z'});assert.equal(ui.executeEnabled,true);assert.equal(ui.approvalRequired,true);assert.equal(ui.canExecute,false);assert.equal(ui.authority,'DISPLAY_ONLY')})
test('055 certification requires every production safety case and permanently reports autonomy disabled',()=>{const names:Money055CaseName[]=['provider-adapter-https-credentials','one-approval-one-permit-one-order','partial-fill-reconciliation','cancel-reconciliation','timeout-unknown-block','portfolio-truth-no-autocorrect','kill-switch','accounting-projection','operations-console-human-gate','autonomy-disabled'],r=certifyMoney055(names.map((name,i)=>({caseId:'c'+i,name,passed:true,evidenceIds:['test:'+name]})));assert.equal(r.passed,true);assert.equal(r.productionMode,'MANUAL_CANARY_ONLY');assert.equal(r.autonomousStockForexEnabled,false)})
