import test from 'node:test'
import assert from 'node:assert/strict'
import type { ExecutionMarketSnapshot, ExecutionPlan, ExecutionSlice } from './execution-planning-contracts.js'
import type { PaperExecutionOutcome } from './paper-execution-contracts.js'
import { assertReadOnlyObservationAdapter, hash045, type LiveMarketObservationAdapter, type LiveMarketQuote, type ShadowCertificationCase } from './shadow-market-contracts.js'
import { assessShadowReadiness, buildShadowReplay, buildShadowSession, certifyShadowObservation, compareShadowExecution, observeLiveMarket } from './shadow-market-engine.js'

const baseline:ExecutionMarketSnapshot={snapshotId:'base-1',instrumentId:'stock:x',currency:'USD',bidMinor:9990n,askMinor:10000n,bidSize:'100',askSize:'100',visibleDepthNotionalMinor:100000n,observedAt:'2026-01-02T14:00:00Z',availableAt:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T14:05:00Z',evidenceIds:['baseline:quote'],provenanceHash:'base:p'}
const slice:ExecutionSlice={sliceId:'s1',sequence:1,notional:{minor:100000n,currency:'USD'},instruction:'MARKETABLE_LIMIT',limitPriceMinor:10100n,earliestAt:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T15:00:00Z',idempotencyKey:'slice-idem',authority:'NONE'}
const plan:ExecutionPlan={executionPlanId:'ep-shadow',rebalanceIntentId:'ri1',portfolioPlanId:'pp1',instrumentId:'stock:x',side:'BUY',notional:{minor:100000n,currency:'USD'},urgency:'NORMAL',routeId:'paper',marketSnapshotId:'base-1',slices:[slice],maxSpreadBps:100,maxParticipationBps:10000,informationCutoff:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T15:00:00Z',inputHash:'ih',provenanceHash:'ph',authority:'ANALYSIS_ONLY',requiresHumanApproval:true}
const quote=(id='live-1',availableAt='2026-01-02T14:10:00Z'):LiveMarketQuote=>({quoteId:id,provider:'live-read',instrumentId:'stock:x',currency:'USD',bidMinor:10040n,askMinor:10050n,bidSize:'80',askSize:'90',visibleDepthNotionalMinor:80000n,observedAt:availableAt,receivedAt:availableAt,availableAt,expiresAt:'2026-01-02T14:20:00Z',evidenceIds:['live:'+id],payloadHash:'payload:'+id,provenanceHash:'prov:'+id,authority:'EVIDENCE_ONLY'})
const adapter=(q=quote()):LiveMarketObservationAdapter=>({provider:'live-read',environment:'LIVE_READ_ONLY',async observeQuote(){return q}})
const paper:PaperExecutionOutcome={outcomeId:'paper-outcome-1',paperRunId:'run1',executionPlanId:'ep-shadow',requestedNotional:{minor:100000n,currency:'USD'},filledNotional:{minor:100000n,currency:'USD'},fillRateBps:10000,weightedSlippageBps:10,feesPaid:{minor:50n,currency:'USD'},terminalState:'FILLED',createdAt:'2026-01-02T14:01:00Z',evidenceIds:['paper:evidence'],authority:'LEARNING_ONLY'}

test('045.1 live adapter surface is read-only and rejects mutating provider methods',()=>{assert.doesNotThrow(()=>assertReadOnlyObservationAdapter(adapter()));assert.throws(()=>assertReadOnlyObservationAdapter({...adapter(),submitOrder(){}}),/MUTATING_ADAPTER_FORBIDDEN/)})
test('045.2 live quote observation is evidence-only and provider/instrument bound',async()=>{const q=await observeLiveMarket({adapter:adapter(),observationId:'obs1',instrumentId:'stock:x',informationCutoff:'2026-01-02T14:10:00Z',now:'2026-01-02T14:10:01Z'});assert.equal(q.authority,'EVIDENCE_ONLY');assert.equal(q.provider,'live-read')})
test('045.3 future or stale live quote is rejected before shadow analysis',async()=>{await assert.rejects(()=>observeLiveMarket({adapter:adapter(quote('future','2026-01-02T14:11:00Z')),observationId:'obs',instrumentId:'stock:x',informationCutoff:'2026-01-02T14:10:00Z',now:'2026-01-02T14:10:00Z'}),/FUTURE_QUOTE/);await assert.rejects(()=>observeLiveMarket({adapter:adapter({...quote(),expiresAt:'2026-01-02T14:09:00Z'}),observationId:'obs',instrumentId:'stock:x',informationCutoff:'2026-01-02T14:10:00Z',now:'2026-01-02T14:10:00Z'}),/STALE_QUOTE/)})
test('045.4 shadow comparison measures price spread and depth drift without placing an order',()=>{const x=compareShadowExecution({plan,baseline,live:quote(),observedAt:'2026-01-02T14:10:01Z'});assert.equal(x.authority,'ANALYSIS_ONLY');assert.equal(x.priceDriftBps,50);assert.equal(x.depthRatioBps,8000);assert.equal(x.wouldCrossLimit,true);assert.equal('providerReference' in x,false)})
test('045.5 paper outcome can be compared but cannot become execution authority',()=>{const x=compareShadowExecution({plan,baseline,live:quote(),paperOutcome:paper,observedAt:'2026-01-02T14:10:01Z'});assert.equal(x.paperOutcomeId,paper.outcomeId);assert.ok(x.evidenceIds.includes('paper:evidence'));assert.equal(x.authority,'ANALYSIS_ONLY')})
test('045.6 shadow session is deterministic and physically records no-submit/no-cancel authority',()=>{const x=compareShadowExecution({plan,baseline,live:quote(),observedAt:'2026-01-02T14:10:01Z'}),a=buildShadowSession({executionPlanId:plan.executionPlanId,comparisons:[x],startedAt:'2026-01-02T14:10:00Z',endedAt:'2026-01-02T14:11:00Z',informationCutoff:'2026-01-02T14:11:00Z'}),b=buildShadowSession({executionPlanId:plan.executionPlanId,comparisons:[x],startedAt:'2026-01-02T14:10:00Z',endedAt:'2026-01-02T14:11:00Z',informationCutoff:'2026-01-02T14:11:00Z'});assert.equal(a.provenanceHash,b.provenanceHash);assert.equal(a.canSubmitOrders,false);assert.equal(a.canCancelOrders,false);assert.equal(a.canAuthorizeLive,false)})
test('045.7 drift thresholds can reject shadow readiness while remaining review-only',()=>{const x=compareShadowExecution({plan,baseline,live:quote(),observedAt:'2026-01-02T14:10:01Z'}),a=assessShadowReadiness({comparisons:[x],minSamples:1,maxAbsPriceDriftBps:25,maxSpreadDriftBps:100,minDepthRatioBps:5000});assert.equal(a.status,'REJECTED');assert.ok(a.reasonCodes.includes('PRICE_DRIFT_ABOVE_THRESHOLD'));assert.equal(a.canAuthorizeLive,false)})
test('045.8 insufficient observations never promote by confidence or a single good sample',()=>{const a=assessShadowReadiness({comparisons:[],minSamples:10,maxAbsPriceDriftBps:100,maxSpreadDriftBps:100,minDepthRatioBps:5000});assert.equal(a.status,'INSUFFICIENT_DATA');assert.equal(a.canAuthorizeLive,false)})
test('045.9 PIT replay excludes live observations unavailable at historical cutoff',()=>{const future={...quote('future','2026-01-02T14:12:00Z'),expiresAt:'2026-01-02T14:30:00Z'},r=buildShadowReplay({quotes:[quote(),future],informationCutoff:'2026-01-02T14:10:30Z'});assert.deepEqual(r.includedQuoteIds,['live-1']);assert.deepEqual(r.excludedFutureQuoteIds,['future']);assert.equal(r.authority,'RESEARCH_ONLY')})
test('045.10 passing shadow certification still cannot grant live execution',()=>{const names=['read-only-adapter','live-quote-evidence','pit-clock-gate','plan-comparison','paper-comparison','drift-assessment','deterministic-session','replay-no-future','no-order-methods','no-live-authority'],cases:ShadowCertificationCase[]=names.map((name,i)=>({caseId:'c'+i,name,passed:true,evidenceIds:['test:'+name]})),r=certifyShadowObservation({provider:'live-read',cases});assert.equal(r.passed,true);assert.equal(r.liveExecutionEligible,false);assert.equal(r.authority,'CERTIFICATION_ONLY');assert.equal(r.provenanceHash,hash045({provider:'live-read',cases,missing:[]}))})
