import test from 'node:test'
import assert from 'node:assert/strict'
import { InMemoryApprovalReceiptStore } from '@jhadina/action-core'
import { createBrokerAccountEntitlement,InMemoryBrokerAccountEntitlementStore } from './broker-account-entitlement.js'
import type { ExecutionAttempt,ExecutionAttemptOutcome,ExecutionAttemptStore } from './execution-attempt.js'
import type { ExecutionPermit,PermitStore } from './execution-permit.js'
import type { ExecutionPlan,ExecutionSlice } from './execution-planning-contracts.js'
import type { LiveApprovalCandidate,LiveExecutionPreflight } from './live-preflight-contracts.js'
import { consumeApprovalAndIssueLiveTradePermit,createLiveTradeApprovalRequest,requestLiveTradeHumanApproval } from './live-trade-approval-bridge.js'
import { executeManualLiveTrade } from './manual-live-broker-executor.js'
import type { LiveBrokerOrderRequest,LiveBrokerSubmitContext,ManualLiveBrokerAdapter,ManualLiveExecutionTrigger } from './manual-live-broker-contracts.js'

class PermitMemory implements PermitStore{rows=new Map<string,ExecutionPermit>();issue(p:ExecutionPermit){this.rows.set(p.permitId,p)}get(id:string){return this.rows.get(id)}consume(id:string,nonce:string){const p=this.rows.get(id);if(!p||p.nonce!==nonce||p.state!=='ISSUED')return false;this.rows.set(id,{...p,state:'CONSUMED'});return true}revoke(id:string){const p=this.rows.get(id);if(p)this.rows.set(id,{...p,state:'REVOKED'})}haltAll(){for(const [id,p] of this.rows)if(p.state==='ISSUED')this.rows.set(id,{...p,state:'HALTED'})}}
class AttemptMemory implements ExecutionAttemptStore{rows=new Map<string,ExecutionAttempt>();start(a:ExecutionAttempt){this.rows.set(a.attemptId,a)}complete(id:string,o:ExecutionAttemptOutcome,at='2026-01-02T14:02:00Z'){const a=this.rows.get(id)!;this.rows.set(id,{...a,...o,completedAt:at})}resolve(id:string,o:ExecutionAttemptOutcome,at='2026-01-02T14:02:00Z'){this.complete(id,o,at)}get(id:string){return this.rows.get(id)}}
class FakeLiveBroker implements ManualLiveBrokerAdapter{readonly environment='LIVE' as const;calls:{context:LiveBrokerSubmitContext;request:LiveBrokerOrderRequest}[]=[];constructor(readonly provider='broker',private mode:'ACK'|'REJECT'|'THROW'|'UNKNOWN'='ACK'){}async submitOrder(context:LiveBrokerSubmitContext,request:LiveBrokerOrderRequest){this.calls.push({context,request});if(this.mode==='THROW')throw new Error('network ambiguous');return{providerReference:'order-live-1',providerEventId:'event-live-1',state:this.mode==='ACK'?'ACKNOWLEDGED' as const:this.mode==='REJECT'?'REJECTED' as const:'UNKNOWN' as const,occurredAt:context.now,observedAt:context.now,receivedAt:context.now,availableAt:context.now,evidenceIds:['provider:submit']}}}
const slice:ExecutionSlice={sliceId:'s1',sequence:1,notional:{minor:100000n,currency:'USD'},instruction:'MARKETABLE_LIMIT',limitPriceMinor:10100n,earliestAt:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T14:05:00Z',idempotencyKey:'idem',authority:'NONE'}
const plan:ExecutionPlan={executionPlanId:'ep1',rebalanceIntentId:'ri1',portfolioPlanId:'pp1',instrumentId:'stock:x',side:'BUY',notional:{minor:100000n,currency:'USD'},urgency:'NORMAL',routeId:'r1',marketSnapshotId:'m1',slices:[slice],maxSpreadBps:100,maxParticipationBps:10000,informationCutoff:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T14:05:00Z',inputHash:'ih',provenanceHash:'ph',authority:'ANALYSIS_ONLY',requiresHumanApproval:true}
const preflight:LiveExecutionPreflight={preflightId:'pf-live',executionPlanId:'ep1',provider:'broker',accountId:'acct1',status:'PASS_FOR_HUMAN_APPROVAL',reasonCodes:[],accountCapabilitySnapshotId:'cap1',routeSnapshotId:'r1',marketSnapshotId:'m1',shadowCertificationReportId:'shadow1',checkedAt:'2026-01-02T14:01:00Z',expiresAt:'2026-01-02T14:04:00Z',inputHash:'pfi',provenanceHash:'pfp',authority:'PREFLIGHT_ONLY',requiresHumanApproval:true,canSubmitOrders:false,canAuthorizeLive:false}
const candidate:LiveApprovalCandidate={candidateId:'cand1',executionPlanId:'ep1',preflightId:'pf-live',provider:'broker',accountId:'acct1',capability:'money.trade.submit',requestedAt:'2026-01-02T14:01:10Z',expiresAt:'2026-01-02T14:04:00Z',reasonCodes:[],authority:'APPROVAL_REQUEST_ONLY',requiresExplicitHumanApproval:true,canExecute:false}
const entitlement=createBrokerAccountEntitlement({entitlementId:'ent1',userId:'u1',provider:'broker',accountId:'acct1',capabilities:['money.trade.submit'],createdAt:'2026-01-01T00:00:00Z',expiresAt:'2027-01-01T00:00:00Z',evidenceIds:['verified-link']})
const trigger:ManualLiveExecutionTrigger={triggerId:'human-click-1',kind:'EXPLICIT_HUMAN_EXECUTE',userId:'u1',approvalReceiptId:'placeholder',confirmedAt:'2026-01-02T14:02:10Z',source:'INTERACTIVE_USER_ACTION'}
async function fixture(){const approvals=new InMemoryApprovalReceiptStore(),permits=new PermitMemory(),attempts=new AttemptMemory(),entitlements=new InMemoryBrokerAccountEntitlementStore();entitlements.put(entitlement);const r=createLiveTradeApprovalRequest({actionId:'trade-action-1',userId:'u1',candidate,preflight,plan,entitlement,requestedAt:'2026-01-02T14:01:20Z'}),pending=await requestLiveTradeHumanApproval(approvals,r,'2027-01-01T00:00:00Z'),approved=await approvals.approve(pending.id,'u1'),pkg=await consumeApprovalAndIssueLiveTradePermit({approvalStore:approvals,permitStore:permits,request:r,approvalReceiptId:approved.id,candidate,preflight,plan,entitlement,authorityId:'auth1',policyVersion:'1',policyHash:'policy',authorizedAt:'2026-01-02T14:02:00Z',authorityExpiresAt:'2026-01-02T14:03:40Z',permitExpiresAt:'2026-01-02T14:03:00Z',permitId:'permit-1',nonce:'nonce-1'});return{permits,attempts,entitlements,pkg,trigger:{...trigger,approvalReceiptId:approved.id}}}

test('049.1 only an explicit interactive human trigger may cross the live adapter boundary',async()=>{const x=await fixture(),broker=new FakeLiveBroker();await assert.rejects(()=>executeManualLiveTrade({adapter:broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,permitPackage:x.pkg,preflight,plan,trigger:{...x.trigger,kind:'EXPLICIT_HUMAN_EXECUTE',source:'INTERACTIVE_USER_ACTION',userId:'other'},now:'2026-01-02T14:02:10Z'}),/TRIGGER_USER_MISMATCH/);assert.equal(broker.calls.length,0)})
test('049.2 exact entitlement is rechecked at action time',async()=>{const x=await fixture(),broker=new FakeLiveBroker();x.entitlements.revoke('ent1','2026-01-02T14:02:05Z');await assert.rejects(()=>executeManualLiveTrade({adapter:broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,permitPackage:x.pkg,preflight,plan,trigger:x.trigger,now:'2026-01-02T14:02:10Z'}),/ACCOUNT_NOT_ENTITLED/);assert.equal(broker.calls.length,0)})
test('049.3 one permit authorizes exactly one broker order',async()=>{const x=await fixture(),broker=new FakeLiveBroker(),r=await executeManualLiveTrade({adapter:broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,permitPackage:x.pkg,preflight,plan,trigger:x.trigger,now:'2026-01-02T14:02:10Z',attemptIdFactory:()=> 'exec-live-1'});assert.equal(r.state,'SUBMITTED');assert.equal(r.retryAllowed,false);assert.equal(broker.calls.length,1);assert.equal(broker.calls[0]!.request.notionalMinor,'100000');assert.equal(broker.calls[0]!.request.side,'BUY');await assert.rejects(()=>executeManualLiveTrade({adapter:broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,permitPackage:x.pkg,preflight,plan,trigger:x.trigger,now:'2026-01-02T14:02:20Z'}),/Permit is not executable|Permit replay/)})
test('049.4 multi-order slicing is rejected before permit consumption',async()=>{const x=await fixture(),broker=new FakeLiveBroker(),multi={...plan,slices:[slice,{...slice,sliceId:'s2',sequence:2}]};await assert.rejects(()=>executeManualLiveTrade({adapter:broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,permitPackage:x.pkg,preflight,plan:multi,trigger:x.trigger,now:'2026-01-02T14:02:10Z'}),/ONE_PERMIT_ONE_ORDER_REQUIRED/);assert.equal((await x.permits.get('permit-1'))?.state,'ISSUED');assert.equal(broker.calls.length,0)})
test('049.5 provider timeout becomes UNKNOWN and never auto-retries',async()=>{const x=await fixture(),broker=new FakeLiveBroker('broker','THROW'),r=await executeManualLiveTrade({adapter:broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,permitPackage:x.pkg,preflight,plan,trigger:x.trigger,now:'2026-01-02T14:02:10Z',attemptIdFactory:()=> 'exec-unknown'});assert.equal(r.state,'UNKNOWN');assert.equal(r.retryAllowed,false);assert.equal(r.providerEvent.state,'UNKNOWN');assert.equal((await x.attempts.get('exec-unknown'))?.recoveryRequired,true);assert.equal(broker.calls.length,1)})
test('049.6 provider rejection records FAILED without retry authority',async()=>{const x=await fixture(),broker=new FakeLiveBroker('broker','REJECT'),r=await executeManualLiveTrade({adapter:broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,permitPackage:x.pkg,preflight,plan,trigger:x.trigger,now:'2026-01-02T14:02:10Z',attemptIdFactory:()=> 'exec-reject'});assert.equal(r.state,'REJECTED');assert.equal(r.retryAllowed,false);assert.equal((await x.attempts.get('exec-reject'))?.state,'FAILED')})
test('049.7 SHARK/crypto instruments cannot enter this stock/forex live path',async()=>{const x=await fixture(),broker=new FakeLiveBroker(),cryptoPlan={...plan,instrumentId:'crypto:btc'};await assert.rejects(()=>executeManualLiveTrade({adapter:broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,permitPackage:x.pkg,preflight,plan:cryptoPlan,trigger:x.trigger,now:'2026-01-02T14:02:10Z'}),/INSTRUMENT_NOT_MANUAL_LIVE_ELIGIBLE|PERMIT_PLAN_MISMATCH/);assert.equal(broker.calls.length,0)})
