import test from 'node:test'
import assert from 'node:assert/strict'
import { addMoney, decimalToString, money, parseDecimal } from './exact-money.js'
import { assertOrderTransition, convertMoneyAtCutoff, deriveFinancialState } from './financial-state-engine.js'
import { selectLotsForDisposition } from './financial-lifecycle-engine.js'
import { calibratePredictions, resolveInstrument } from './instrument-prediction-engine.js'
import { reverseStress, runPathSimulation, runStressTest } from './risk-analysis-engine.js'
import { buildCanonicalMarketSnapshot, evaluateEvidenceGate, normalizeObservation, reconcileObservations, validateObservation } from './decision-provenance-engine.js'
import { buildMacroStateSnapshot, computeEconomicSurprise, macroObservationFromStrings } from './macro-economic-engine.js'

test('013 exact money never uses binary floating point',()=>{assert.equal(decimalToString(addMoney(money(1n,1,'USD'),money(2n,1,'USD'))),'0.3');assert.throws(()=>addMoney(money(1n,0,'USD'),money(1n,0,'EUR')),/CURRENCY_MISMATCH/)})
test('013-021 canonical state is deterministic, PIT and evidence bound',()=>{const e={eventId:'cash1',kind:'CASH' as const,accountId:'a',effectiveAt:'2026-01-01T00:00:00Z',recordedAt:'2026-01-01T00:00:01Z',amount:money(10000n,2,'USD'),bucket:'SETTLED' as const,evidenceRefs:['bank']};const a=deriveFinancialState({accountId:'a',currency:'USD',informationCutoff:'2026-01-02T00:00:00Z',events:[e]}),b=deriveFinancialState({accountId:'a',currency:'USD',informationCutoff:'2026-01-02T00:00:00Z',events:[e]});assert.equal(a.stateHash,b.stateHash);assert.equal(decimalToString(a.availableCash),'100');assert.throws(()=>deriveFinancialState({accountId:'a',currency:'USD',informationCutoff:'2026-01-02',events:[{...e,eventId:'bad',evidenceRefs:[]}]}),/UNPROVEN/)})
test('015 order UNKNOWN reconciles but terminal fill cannot reopen',()=>{assert.doesNotThrow(()=>assertOrderTransition('UNKNOWN','FILLED'));assert.throws(()=>assertOrderTransition('FILLED','SUBMITTED'),/INVALID/)})
test('019 deterministic FIFO lot selection',()=>{const lots=[{lotId:'l2',instrumentId:'i',openedAt:'2026-02-01',quantity:parseDecimal('2'),unitCost:money(12n,0,'USD'),sourceFillId:'f2'},{lotId:'l1',instrumentId:'i',openedAt:'2026-01-01',quantity:parseDecimal('2'),unitCost:money(10n,0,'USD'),sourceFillId:'f1'}];assert.deepEqual(selectLotsForDisposition(lots,'3','FIFO').map(x=>x.lotId),['l1','l2'])})
test('022 FX is point-in-time and fails without a verified rate',()=>{const fx={fxId:'x',base:'USD',quote:'EUR',rate:parseDecimal('0.9'),effectiveAt:'2026-01-01',availableAt:'2026-01-02',provider:'p',evidenceRefs:['e'],provenanceHash:'h'};assert.equal(decimalToString(convertMoneyAtCutoff(money(100n,0,'USD'),'EUR',[fx],'2026-01-03')),'90');assert.throws(()=>convertMoneyAtCutoff(money(1n,0,'USD'),'EUR',[fx],'2026-01-01'),/UNAVAILABLE/)})
test('027 symbol ambiguity blocks identity resolution',()=>{const mk=(id:string,venue:string)=>({instrumentId:id,assetClass:'STOCK' as const,venue,identifiers:[{type:'TICKER' as const,value:'ABC',effectiveFrom:'2020',evidenceRefs:['e']}],quoteCurrency:'USD',settlementCurrency:'USD',status:'ACTIVE' as const,evidenceRefs:['e'],provenanceHash:'h'});assert.equal(resolveInstrument([mk('1','X'),mk('2','Y')],'ABC','2026').status,'AMBIGUOUS');assert.equal(resolveInstrument([mk('1','X'),mk('2','Y')],'ABC','2026','X').instrumentId,'1')})
test('029 calibration refuses small-sample certainty',()=>{assert.equal(calibratePredictions('m','1',[{predictionId:'p',probability:.7,outcome:1,issuedAt:'a',resolvedAt:'b'}]).status,'INSUFFICIENT_DATA')})
test('031 stress and reverse stress are explicit analysis',()=>{const p=[{instrumentId:'i',marketValue:1000,priceSensitivity:1,liquidityHaircut:0,marginRequirement:0}],s={scenarioId:'s',name:'drop',shocks:[{target:'ALL',kind:'PRICE' as const,magnitude:-.2}],methodologyVersion:'1',evidenceRefs:['e']};assert.equal(runStressTest(p,s,100).breached,true);assert.ok(reverseStress(p,{scenarioId:'r',name:'reverse',methodologyVersion:'1',evidenceRefs:['e']},100).totalLoss>=100)})
test('032 simulation replay is deterministic',()=>{const s={simulationId:'s',randomSeed:'seed',pathCount:200,steps:5,initialValue:100,drift:0,volatility:.01,liquidityFeedback:0,lossLimit:10,modelVersion:'1',inputSnapshotHash:'h'};assert.deepEqual(runPathSimulation(s),runPathSimulation(s))})
test('033 authority remains mandatory at evidence gate',()=>{const r=evaluateEvidenceGate({evidenceIds:['e'],fresh:true,contradictionIds:[],riskComplete:true,stressComplete:true,simulationComplete:true,calibrationSufficient:true,authority:'NONE'});assert.equal(r.status,'BLOCKED');assert.deepEqual(r.reasons,['AUTHORITY_MISSING'])})
test('034 provenance pipeline rejects future evidence and preserves source lineage',()=>{const raw={rawId:'r',provider:'p',instrumentQuery:'ABC',field:'price',rawValue:'10',currency:'USD',effectiveAt:'2026-01-01',observedAt:'2026-01-01',receivedAt:'2026-01-01',availableAt:'2026-01-01',sourceRef:'s',sourceHash:'h'};const v=validateObservation(raw,{instrumentId:'i',cutoff:'2026-01-02',maxAgeMs:999999999999,now:'2026-01-02',validationVersion:'1'});const n=normalizeObservation(v,'1'),r=reconcileObservations([n],'1'),snap=buildCanonicalMarketSnapshot([r],'2026-01-02','1');assert.equal(snap.reconciliationIds[0],r.reconciliationId);assert.equal(validateObservation({...raw,availableAt:'2027-01-01'},{instrumentId:'i',cutoff:'2026-01-02',maxAgeMs:999999999999,now:'2026-01-02',validationVersion:'1'}).status,'FUTURE_LEAK')})
test('037 macro snapshot uses latest available vintage and excludes future policy state',()=>{const o1=macroObservationFromStrings({observationId:'o1',indicatorId:'cpi',periodStart:'2026-01-01',periodEnd:'2026-01-31',effectiveAt:'2026-01-31',observedAt:'2026-02-01',availableAt:'2026-02-01',value:'3.1',vintageId:'v1',sourceRef:'s',evidenceRefs:['e'],provenanceHash:'h1'}),o2=macroObservationFromStrings({...o1,observationId:'o2',value:'3.0',availableAt:'2026-03-01',observedAt:'2026-03-01',vintageId:'v2',provenanceHash:'h2'});const vintages=[{vintageId:'v1',indicatorId:'cpi',releasedAt:'2026-02-01',availableAt:'2026-02-01',revisionSequence:0,observationIds:['o1'],evidenceRefs:['e'],provenanceHash:'v1h'},{vintageId:'v2',indicatorId:'cpi',releasedAt:'2026-03-01',availableAt:'2026-03-01',revisionOfVintageId:'v1',revisionSequence:1,observationIds:['o2'],evidenceRefs:['e'],provenanceHash:'v2h'}];const snap=buildMacroStateSnapshot({cutoff:'2026-02-15',observations:[o1,o2],vintages,regimes:[],transitions:[],policyEvents:[],surprises:[],sensitivities:[],contradictions:[],methodologyVersion:'37.1'});assert.deepEqual(snap.observationIds,['o1']);assert.equal(snap.authority,'INTELLIGENCE_ONLY')})
test('037 surprise separates consensus from actual release',()=>{const e={economicEventId:'evt',indicatorId:'jobs',scheduledFor:'2026-01-01',releasedAt:'2026-01-01',availableAt:'2026-01-01',consensus:parseDecimal('100'),actual:parseDecimal('120'),evidenceRefs:['e'],provenanceHash:'h'};assert.equal(decimalToString(computeEconomicSurprise(e,'2026-01-02','survey','1').rawDifference),'20')})
