import test from 'node:test'
import assert from 'node:assert/strict'
import { InMemoryApprovalReceiptStore } from '@jhadina/action-core'
import { createBrokerAccountEntitlement } from './broker-account-entitlement.js'
import type { ExecutionPermit, PermitStore } from './execution-permit.js'
import type { ExecutionPlan, ExecutionSlice } from './execution-planning-contracts.js'
import type { LiveApprovalCandidate, LiveExecutionPreflight } from './live-preflight-contracts.js'
import { consumeApprovalAndIssueLiveTradePermit, createLiveTradeApprovalRequest, requestLiveTradeHumanApproval } from './live-trade-approval-bridge.js'

class PermitMemory implements PermitStore{rows=new Map<string,ExecutionPermit>();issue(p:ExecutionPermit){this.rows.set(p.permitId,p)}get(id:string){return this.rows.get(id)}consume(id:string,nonce:string){const p=this.rows.get(id);if(!p||p.nonce!==nonce||p.state!=='ISSUED')return false;this.rows.set(id,{...p,state:'CONSUMED'});return true}revoke(id:string){const p=this.rows.get(id);if(p)this.rows.set(id,{...p,state:'REVOKED'})}haltAll(){for(const [id,p] of this.rows)if(p.state==='ISSUED')this.rows.set(id,{...p,state:'HALTED'})}}
const slice:ExecutionSlice={sliceId:'s1',sequence:1,notional:{minor:100000n,currency:'USD'},instruction:'MARKETABLE_LIMIT',limitPriceMinor:10100n,earliestAt:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T14:05:00Z',idempotencyKey:'idem',authority:'NONE'}
const plan:ExecutionPlan={executionPlanId:'ep1',rebalanceIntentId:'ri1',portfolioPlanId:'pp1',instrumentId:'stock:x',side:'BUY',notional:{minor:100000n,currency:'USD'},urgency:'NORMAL',routeId:'r1',marketSnapshotId:'m1',slices:[slice],maxSpreadBps:100,maxParticipationBps:10000,informationCutoff:'2026-01-02T14:00:00Z',expiresAt:'2026-01-02T14:05:00Z',inputHash:'ih',provenanceHash:'ph',authority:'ANALYSIS_ONLY',requiresHumanApproval:true}
const preflight:LiveExecutionPreflight={preflightId:'pf-live',executionPlanId:'ep1',provider:'broker',accountId:'acct1',status:'PASS_FOR_HUMAN_APPROVAL',reasonCodes:[],accountCapabilitySnapshotId:'cap1',routeSnapshotId:'r1',marketSnapshotId:'m1',shadowCertificationReportId:'shadow1',checkedAt:'2026-01-02T14:01:00Z',expiresAt:'2026-01-02T14:04:00Z',inputHash:'pfi',provenanceHash:'pfp',authority:'PREFLIGHT_ONLY',requiresHumanApproval:true,canSubmitOrders:false,canAuthorizeLive:false}
const candidate:LiveApprovalCandidate={candidateId:'cand1',executionPlanId:'ep1',preflightId:'pf-live',provider:'broker',accountId:'acct1',capability:'money.trade.submit',requestedAt:'2026-01-02T14:01:10Z',expiresAt:'2026-01-02T14:04:00Z',reasonCodes:[],authority:'APPROVAL_REQUEST_ONLY',requiresExplicitHumanApproval:true,canExecute:false}
const entitlement=createBrokerAccountEntitlement({entitlementId:'ent1',userId:'u1',provider:'broker',accountId:'acct1',capabilities:['money.trade.submit'],createdAt:'2026-01-01T00:00:00Z',expiresAt:'2027-01-01T00:00:00Z',evidenceIds:['verified-link']})
const request=()=>createLiveTradeApprovalRequest({actionId:'trade-action-1',userId:'u1',candidate,preflight,plan,entitlement,requestedAt:'2026-01-02T14:01:20Z'})

test('048.1 approval request binds exact user account provider instrument side amount plan and preflight',()=>{const r=request();assert.deepEqual(r.action,{capability:'money.trade.submit',provider:'broker',accountId:'acct1',instrumentId:'stock:x',side:'BUY',notionalMinor:'100000',currency:'USD',executionPlanId:'ep1',preflightId:'pf-live',approvalCandidateId:'cand1',entitlementId:'ent1'})})
test('048.2 unapproved receipt cannot issue a live permit',async()=>{const approvals=new InMemoryApprovalReceiptStore(),permits=new PermitMemory(),r=request(),receipt=await requestLiveTradeHumanApproval(approvals,r,'2026-01-02T14:03:30Z');await assert.rejects(()=>consumeApprovalAndIssueLiveTradePermit({approvalStore:approvals,permitStore:permits,request:r,approvalReceiptId:receipt.id,candidate,preflight,plan,entitlement,authorityId:'auth1',policyVersion:'1',policyHash:'policy',authorizedAt:'2026-01-02T14:02:00Z',authorityExpiresAt:'2026-01-02T14:03:40Z',permitExpiresAt:'2026-01-02T14:03:00Z'}),/APPROVAL_INVALID/)})
test('048.3 explicit approved receipt issues exact short-lived single-use manual permit',async()=>{const approvals=new InMemoryApprovalReceiptStore(),permits=new PermitMemory(),r=request(),pending=await requestLiveTradeHumanApproval(approvals,r,'2027-01-01T00:00:00Z'),approved=await approvals.approve(pending.id,'u1'),pkg=await consumeApprovalAndIssueLiveTradePermit({approvalStore:approvals,permitStore:permits,request:r,approvalReceiptId:approved.id,candidate,preflight,plan,entitlement,authorityId:'auth1',policyVersion:'1',policyHash:'policy',authorizedAt:'2026-01-02T14:02:00Z',authorityExpiresAt:'2026-01-02T14:03:40Z',permitExpiresAt:'2026-01-02T14:03:00Z',permitId:'permit-live-1',nonce:'nonce-live-1'});assert.equal(pkg.autonomous,false);assert.equal(pkg.mode,'MANUAL_LIVE_ONLY');assert.equal(pkg.permit.binding.approvalId,approved.id);assert.equal(pkg.action.side,'BUY');assert.equal(pkg.action.executionPlanId,'ep1');assert.equal(pkg.action.preflightId,'pf-live');assert.equal(pkg.action.amount,'100000')})
test('048.4 approval receipt replay cannot mint a second permit',async()=>{const approvals=new InMemoryApprovalReceiptStore(),permits=new PermitMemory(),r=request(),pending=await requestLiveTradeHumanApproval(approvals,r,'2027-01-01T00:00:00Z'),approved=await approvals.approve(pending.id,'u1'),args={approvalStore:approvals,permitStore:permits,request:r,approvalReceiptId:approved.id,candidate,preflight,plan,entitlement,authorityId:'auth1',policyVersion:'1',policyHash:'policy',authorizedAt:'2026-01-02T14:02:00Z',authorityExpiresAt:'2026-01-02T14:03:40Z',permitExpiresAt:'2026-01-02T14:03:00Z'};await consumeApprovalAndIssueLiveTradePermit(args);await assert.rejects(()=>consumeApprovalAndIssueLiveTradePermit(args),/APPROVAL_INVALID_EXPIRED_OR_REPLAYED/)})
test('048.5 approved economics cannot be mutated after human approval',async()=>{const approvals=new InMemoryApprovalReceiptStore(),permits=new PermitMemory(),r=request(),pending=await requestLiveTradeHumanApproval(approvals,r,'2027-01-01T00:00:00Z'),approved=await approvals.approve(pending.id,'u1'),mutated={...r,action:{...r.action,notionalMinor:'200000'}};await assert.rejects(()=>consumeApprovalAndIssueLiveTradePermit({approvalStore:approvals,permitStore:permits,request:mutated,approvalReceiptId:approved.id,candidate,preflight,plan,entitlement,authorityId:'auth1',policyVersion:'1',policyHash:'policy',authorizedAt:'2026-01-02T14:02:00Z',authorityExpiresAt:'2026-01-02T14:03:40Z',permitExpiresAt:'2026-01-02T14:03:00Z'}),/APPROVAL_REQUEST_MUTATED/)})
