import test from 'node:test'
import assert from 'node:assert/strict'
import { createBrokerAccountEntitlement,InMemoryBrokerAccountEntitlementStore,requireBrokerAccountEntitlement } from './broker-account-entitlement.js'
const entitlement=()=>createBrokerAccountEntitlement({entitlementId:'ent-1',userId:'user-1',provider:'broker',accountId:'acct-1',capabilities:['money.market.observe','money.trade.submit'],createdAt:'2026-01-01T00:00:00Z',expiresAt:'2027-01-01T00:00:00Z',evidenceIds:['broker-link:verified']})
test('047.1 broker account ownership is explicit and evidence-bound',()=>{const e=entitlement();assert.equal(e.authority,'ENTITLEMENT_ONLY');assert.equal(e.userId,'user-1');assert.ok(e.provenanceHash)})
test('047.2 exact user/provider/account/capability must match',async()=>{const s=new InMemoryBrokerAccountEntitlementStore();s.put(entitlement());await assert.doesNotReject(()=>requireBrokerAccountEntitlement(s,{userId:'user-1',provider:'broker',accountId:'acct-1',capability:'money.trade.submit',now:'2026-06-01T00:00:00Z'}));await assert.rejects(()=>requireBrokerAccountEntitlement(s,{userId:'user-2',provider:'broker',accountId:'acct-1',capability:'money.trade.submit',now:'2026-06-01T00:00:00Z'}),/ACCOUNT_NOT_ENTITLED/)})
test('047.3 caller-supplied neighboring account cannot inherit ownership',async()=>{const s=new InMemoryBrokerAccountEntitlementStore();s.put(entitlement());await assert.rejects(()=>requireBrokerAccountEntitlement(s,{userId:'user-1',provider:'broker',accountId:'acct-2',capability:'money.trade.submit',now:'2026-06-01T00:00:00Z'}),/ACCOUNT_NOT_ENTITLED/)})
test('047.4 revoked entitlement fails closed',async()=>{const s=new InMemoryBrokerAccountEntitlementStore();s.put(entitlement());s.revoke('ent-1','2026-05-01T00:00:00Z');await assert.rejects(()=>requireBrokerAccountEntitlement(s,{userId:'user-1',provider:'broker',accountId:'acct-1',capability:'money.trade.submit',now:'2026-06-01T00:00:00Z'}),/ACCOUNT_NOT_ENTITLED/)})
test('047.5 expired entitlement cannot authorize access',async()=>{const s=new InMemoryBrokerAccountEntitlementStore();s.put(entitlement());await assert.rejects(()=>requireBrokerAccountEntitlement(s,{userId:'user-1',provider:'broker',accountId:'acct-1',capability:'money.trade.submit',now:'2028-01-01T00:00:00Z'}),/ACCOUNT_NOT_ENTITLED/)})
