import type { BrokerAccountEntitlementStore } from './broker-account-entitlement.js'
import type { DurableProviderEventStore } from './durable-provider-event-processor.js'
import { processDurableProviderEvent } from './durable-provider-event-processor.js'
import type { ExecutionAttemptStore } from './execution-attempt.js'
import type { ExecutionPlan } from './execution-planning-contracts.js'
import type { PermitStore } from './execution-permit.js'
import type { ProviderExecutionEvent } from './execution-receipt-contracts.js'
import type { LiveCanaryPolicy,LiveCanaryStateStore,LiveRiskMetricSnapshot } from './live-canary-contracts.js'
import { executeCanaryGovernedLiveTrade,type CanaryGovernedLiveExecutionResult } from './live-execution-governance.js'
import type { LiveExecutionPreflight } from './live-preflight-contracts.js'
import type { LiveTradePermitPackage } from './live-trade-approval-bridge.js'
import type { ManualLiveBrokerAdapter,ManualLiveExecutionTrigger } from './manual-live-broker-contracts.js'

export type Money060SoftwareCaseName='alpaca-paper-live-separation'|'credential-isolation'|'durable-provider-event-replay'|'provider-event-conflict-block'|'realized-pnl-lot-accounting'|'corporate-action-basis'|'fx-path-costs'|'tax-review-no-auto-adjust'|'operator-approval-execute-separation'|'unknown-kill-switch-boundary'
export type Money060SoftwareCase=Readonly<{caseId:string;name:Money060SoftwareCaseName;passed:boolean;evidenceIds:readonly string[]}>
export type Money060SoftwareCertification=Readonly<{certificationId:string;passed:boolean;status:'READY_FOR_HUMAN_LIVE_CANARY'|'BLOCKED';productionMode:'MANUAL_CANARY_ONLY';autonomousStockForexEnabled:false;authority:'CERTIFICATION_ONLY'}>

export type Money060PrimaryLiveCanaryEvidence=Readonly<{environment:'LIVE';provider:string;accountId:string;instrumentId:string;side:'BUY'|'SELL';notionalMinor:bigint;currency:string;approvalReceiptId:string;permitId:string;executionId:string;providerReference:string;providerStates:readonly string[];receiptIds:readonly string[];fillIds:readonly string[];settlementEvidenceIds:readonly string[];portfolioReconciliationId:string;portfolioStatus:'MATCH'|'DISCREPANCY';humanApproved:true;manualExecuteTriggerId:string;recordedAt:string;evidenceIds:readonly string[]}>
export type Money060FailureDrillEvidence=Readonly<{timeoutUnknownBlocked:boolean;unknownReconciledBeforeNewAttempt:boolean;cancelReconciled:boolean;duplicateProviderEventDeduped:boolean;restartReplayVerified:boolean;killSwitchVerified:boolean;evidenceIds:readonly string[]}>
export type Money060LiveCanaryCertificate=Readonly<{certificateId:string;passed:boolean;provider:string;accountId:string;executionId:string;scope:'TINY_MANUAL_CANARY_ONLY';autonomousStockForexEnabled:false;canIncreaseLimits:false;authority:'CERTIFICATION_ONLY';evidenceIds:readonly string[]}>

const stable=(v:unknown)=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x)
function hash(v:unknown){let h=2166136261,s=stable(v);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
export function certifyMoney060Software(cases:readonly Money060SoftwareCase[]):Money060SoftwareCertification{const required:Money060SoftwareCaseName[]=['alpaca-paper-live-separation','credential-isolation','durable-provider-event-replay','provider-event-conflict-block','realized-pnl-lot-accounting','corporate-action-basis','fx-path-costs','tax-review-no-auto-adjust','operator-approval-execute-separation','unknown-kill-switch-boundary'],names=new Set(cases.filter(x=>x.passed).map(x=>x.name)),passed=required.every(x=>names.has(x))&&cases.every(x=>x.passed);return Object.freeze({certificationId:'money-060-software:'+hash({cases,required}),passed,status:passed?'READY_FOR_HUMAN_LIVE_CANARY':'BLOCKED',productionMode:'MANUAL_CANARY_ONLY',autonomousStockForexEnabled:false,authority:'CERTIFICATION_ONLY'})}
export function certifyMoney060LiveCanary(input:{primary:Money060PrimaryLiveCanaryEvidence;drills:Money060FailureDrillEvidence;maxCanaryNotionalMinor:bigint}):Money060LiveCanaryCertificate{const p=input.primary,d=input.drills,reasons:string[]=[];if(p.environment!=='LIVE')reasons.push('LIVE_ENVIRONMENT_REQUIRED');if(p.provider!=='alpaca')reasons.push('CERTIFIED_PROVIDER_REQUIRED');if(!(p.instrumentId.startsWith('stock:')||p.instrumentId.startsWith('etf:')))reasons.push('EQUITY_CANARY_REQUIRED');if(p.notionalMinor<=0n||p.notionalMinor>input.maxCanaryNotionalMinor)reasons.push('CANARY_NOTIONAL_LIMIT');if(!p.approvalReceiptId||!p.permitId||!p.executionId||!p.providerReference||!p.manualExecuteTriggerId)reasons.push('MANUAL_AUTHORITY_LINEAGE_REQUIRED');if(!p.providerStates.includes('ACKNOWLEDGED')||!p.providerStates.some(x=>x==='FILLED'||x==='CANCELLED'||x==='REJECTED'))reasons.push('PROVIDER_LIFECYCLE_INCOMPLETE');if(!p.receiptIds.length||!p.fillIds.length)reasons.push('EXECUTION_RECEIPTS_REQUIRED');if(!p.settlementEvidenceIds.length)reasons.push('SETTLEMENT_EVIDENCE_REQUIRED');if(p.portfolioStatus!=='MATCH'||!p.portfolioReconciliationId)reasons.push('PORTFOLIO_RECONCILIATION_REQUIRED');if(!p.evidenceIds.length)reasons.push('LIVE_EVIDENCE_REQUIRED');for(const [name,value] of Object.entries({timeoutUnknownBlocked:d.timeoutUnknownBlocked,unknownReconciledBeforeNewAttempt:d.unknownReconciledBeforeNewAttempt,cancelReconciled:d.cancelReconciled,duplicateProviderEventDeduped:d.duplicateProviderEventDeduped,restartReplayVerified:d.restartReplayVerified,killSwitchVerified:d.killSwitchVerified}))if(!value)reasons.push('DRILL_REQUIRED:'+name);if(!d.evidenceIds.length)reasons.push('DRILL_EVIDENCE_REQUIRED');if(reasons.length)throw new Error('MONEY_060_LIVE_CANARY_NOT_CERTIFIED:'+reasons.join(','));const evidenceIds=Object.freeze([...new Set([...p.evidenceIds,...p.receiptIds,...p.fillIds,...p.settlementEvidenceIds,...d.evidenceIds])].sort());return Object.freeze({certificateId:'money-060-live:'+hash({primary:p,drills:d,max:input.maxCanaryNotionalMinor}),passed:true,provider:p.provider,accountId:p.accountId,executionId:p.executionId,scope:'TINY_MANUAL_CANARY_ONLY',autonomousStockForexEnabled:false,canIncreaseLimits:false,authority:'CERTIFICATION_ONLY',evidenceIds})}

export async function executeMoney060HumanCanary(input:{adapter:ManualLiveBrokerAdapter;permitStore:PermitStore;attemptStore:ExecutionAttemptStore;entitlementStore:BrokerAccountEntitlementStore;canaryStore:LiveCanaryStateStore;policy:LiveCanaryPolicy;riskMetrics:LiveRiskMetricSnapshot;permitPackage:LiveTradePermitPackage;preflight:LiveExecutionPreflight;plan:ExecutionPlan;trigger:ManualLiveExecutionTrigger;now:string;maxCanaryNotionalMinor:bigint;attemptIdFactory?:()=>string}):Promise<CanaryGovernedLiveExecutionResult>{if(input.adapter.provider!=='alpaca'||input.adapter.environment!=='LIVE')throw new Error('MONEY_060_CERTIFIED_LIVE_PROVIDER_REQUIRED');if(input.plan.notional.minor<=0n||input.plan.notional.minor>input.maxCanaryNotionalMinor)throw new Error('MONEY_060_CANARY_NOTIONAL_LIMIT');return executeCanaryGovernedLiveTrade(input)}
export async function recordMoney060ProviderEvidence(input:{store:DurableProviderEventStore;attempt:Awaited<ReturnType<ExecutionAttemptStore['get']>>;event:ProviderExecutionEvent;priorEvents:readonly ProviderExecutionEvent[];recordedAt:string;canaryStore:LiveCanaryStateStore;accountId:string}){if(!input.attempt)throw new Error('MONEY_060_EXECUTION_ATTEMPT_REQUIRED');return processDurableProviderEvent({store:input.store,attempt:input.attempt,event:input.event,priorEvents:input.priorEvents,recordedAt:input.recordedAt,canaryStore:input.canaryStore,accountId:input.accountId})}
