import test from 'node:test'
import assert from 'node:assert/strict'
import { InMemoryApprovalReceiptStore } from '@jhadina/action-core'
import { createBrokerAccountEntitlement,InMemoryBrokerAccountEntitlementStore } from './broker-account-entitlement.js'
import { createExecutionAttempt,type ExecutionAttempt,type ExecutionAttemptOutcome,type ExecutionAttemptStore } from './execution-attempt.js'
import type { ExecutionPermit,PermitStore } from './execution-permit.js'
import type { ExecutionPlan,ExecutionSlice } from './execution-planning-contracts.js'
import type { ProviderExecutionEvent } from './execution-receipt-contracts.js'
import type { LiveApprovalCandidate,LiveExecutionPreflight } from './live-preflight-contracts.js'
import { consumeApprovalAndIssueLiveTradePermit,createLiveTradeApprovalRequest,requestLiveTradeHumanApproval } from './live-trade-approval-bridge.js'
import { InMemoryLiveCanaryStateStore } from './live-canary-store.js'
import type { LiveCanaryPolicy,LiveRiskMetricSnapshot,Money050CertificationCase } from './live-canary-contracts.js'
import { activateMoney050KillSwitch,applyLiveExecutionTruth,certifyMoney050,comparePlannedPaperShadowActual,executeCanaryGovernedLiveTrade } from './live-execution-governance.js'
import type { LiveBrokerOrderRequest,LiveBrokerSubmitContext,ManualLiveBrokerAdapter,ManualLiveExecutionTrigger } from './manual-live-broker-contracts.js'
import type { PaperExecutionOutcome } from './paper-execution-contracts.js'
import type { ShadowExecutionComparison } from './shadow-market-contracts.js'

class PermitMemory implements PermitStore{rows=new Map<string,ExecutionPermit>();issue(p:ExecutionPermit){this.rows.set(p.permitId,p)}get(id:string){return this.rows.get(id)}consume(id:string,nonce:string){const p=this.rows.get(id);if(!p||p.nonce!==nonce||p.state!=='ISSUED')return false;this.rows.set(id,{...p,state:'CONSUMED'});return true}revoke(id:string){const p=this.rows.get(id);if(p)this.rows.set(id,{...p,state:'REVOKED'})}haltAll(){for(const [id,p] of this.rows)if(p.state==='ISSUED')this.rows.set(id,{...p,state:'HALTED'})}}
class AttemptMemory implements ExecutionAttemptStore{rows=new Map<string,ExecutionAttempt>();start(a:ExecutionAttempt){this.rows.set(a.attemptId,a)}complete(id:string,o:ExecutionAttemptOutcome,at='2026-09-20T15:00:00Z'){const a=this.rows.get(id)!;this.rows.set(id,{...a,...o,completedAt:at})}resolve(id:string,o:ExecutionAttemptOutcome,at='2026-09-20T15:00:00Z'){this.complete(id,o,at)}get(id:string){return this.rows.get(id)}}
class FakeBroker implements ManualLiveBrokerAdapter{readonly environment='LIVE' as const;calls:{context:LiveBrokerSubmitContext;request:LiveBrokerOrderRequest}[]=[];constructor(readonly provider='broker',private mode:'ACK'|'THROW'='ACK'){}async submitOrder(context:LiveBrokerSubmitContext,request:LiveBrokerOrderRequest){this.calls.push({context,request});if(this.mode==='THROW')throw new Error('ambiguous timeout');return{providerReference:'order-1',providerEventId:'event-ack',state:'ACKNOWLEDGED' as const,occurredAt:context.now,observedAt:context.now,receivedAt:context.now,availableAt:context.now,evidenceIds:['broker:ack']}}}
const slice:ExecutionSlice={sliceId:'s1',sequence:1,notional:{minor:100000n,currency:'USD'},instruction:'MARKETABLE_LIMIT',limitPriceMinor:10100n,earliestAt:'2026-09-20T14:00:00Z',expiresAt:'2026-09-20T16:00:00Z',idempotencyKey:'idem',authority:'NONE'}
const plan:ExecutionPlan={executionPlanId:'ep1',rebalanceIntentId:'ri1',portfolioPlanId:'pp1',instrumentId:'stock:x',side:'BUY',notional:{minor:100000n,currency:'USD'},urgency:'NORMAL',routeId:'r1',marketSnapshotId:'m1',slices:[slice],maxSpreadBps:100,maxParticipationBps:10000,informationCutoff:'2026-09-20T14:00:00Z',expiresAt:'2026-09-20T16:00:00Z',inputHash:'ih',provenanceHash:'ph',authority:'ANALYSIS_ONLY',requiresHumanApproval:true}
const preflight:LiveExecutionPreflight={preflightId:'pf-live',executionPlanId:'ep1',provider:'broker',accountId:'acct1',status:'PASS_FOR_HUMAN_APPROVAL',reasonCodes:[],accountCapabilitySnapshotId:'cap1',routeSnapshotId:'r1',marketSnapshotId:'m1',shadowCertificationReportId:'shadow1',checkedAt:'2026-09-20T14:20:00Z',expiresAt:'2026-09-20T15:30:00Z',inputHash:'pfi',provenanceHash:'pfp',authority:'PREFLIGHT_ONLY',requiresHumanApproval:true,canSubmitOrders:false,canAuthorizeLive:false}
const candidate:LiveApprovalCandidate={candidateId:'cand1',executionPlanId:'ep1',preflightId:'pf-live',provider:'broker',accountId:'acct1',capability:'money.trade.submit',requestedAt:'2026-09-20T14:21:00Z',expiresAt:'2026-09-20T15:30:00Z',reasonCodes:[],authority:'APPROVAL_REQUEST_ONLY',requiresExplicitHumanApproval:true,canExecute:false}
const entitlement=createBrokerAccountEntitlement({entitlementId:'ent1',userId:'u1',provider:'broker',accountId:'acct1',capabilities:['money.trade.submit'],createdAt:'2026-01-01T00:00:00Z',expiresAt:'2027-01-01T00:00:00Z',evidenceIds:['verified-link']})
const policy:LiveCanaryPolicy={policyId:'canary-v1',currency:'USD',maxOrderNotionalMinor:150000n,maxDailySubmittedNotionalMinor:300000n,maxDailyOrders:3,maxDailyRealizedLossMinor:50000n,maxGrossExposureMinor:500000n,maxOpenUnknownExecutions:0,maxRiskMetricAgeSeconds:300,authority:'RISK_POLICY_ONLY'}
const metrics=(gross=200000n,pnl=10000n):LiveRiskMetricSnapshot=>({snapshotId:'risk1',provider:'broker',accountId:'acct1',currency:'USD',grossExposureMinor:gross,realizedPnlMinor:pnl,observedAt:'2026-09-20T14:24:00Z',availableAt:'2026-09-20T14:24:00Z',evidenceIds:['risk:verified'],authority:'EVIDENCE_ONLY'})
async function liveFixture(mode:'ACK'|'THROW'='ACK'){const approvals=new InMemoryApprovalReceiptStore(),permits=new PermitMemory(),attempts=new AttemptMemory(),entitlements=new InMemoryBrokerAccountEntitlementStore(),canary=new InMemoryLiveCanaryStateStore();entitlements.put(entitlement);const r=createLiveTradeApprovalRequest({actionId:'trade-1',userId:'u1',candidate,preflight,plan,entitlement,requestedAt:'2026-09-20T14:22:00Z'}),pending=await requestLiveTradeHumanApproval(approvals,r,'2027-01-01T00:00:00Z'),approved=await approvals.approve(pending.id,'u1'),pkg=await consumeApprovalAndIssueLiveTradePermit({approvalStore:approvals,permitStore:permits,request:r,approvalReceiptId:approved.id,candidate,preflight,plan,entitlement,authorityId:'auth1',policyVersion:'1',policyHash:'policy',authorizedAt:'2026-09-20T14:23:00Z',authorityExpiresAt:'2026-09-20T15:20:00Z',permitExpiresAt:'2026-09-20T15:10:00Z',permitId:'permit-1',nonce:'nonce-1'}),trigger:ManualLiveExecutionTrigger={triggerId:'click1',kind:'EXPLICIT_HUMAN_EXECUTE',userId:'u1',approvalReceiptId:approved.id,confirmedAt:'2026-09-20T14:25:00Z',source:'INTERACTIVE_USER_ACTION'};return{permits,attempts,entitlements,canary,pkg,trigger,broker:new FakeBroker('broker',mode)}}

test('050.1 canary blocks execution without fresh verified risk metrics',async()=>{const s=new InMemoryLiveCanaryStateStore(),r=await s.reserve({provider:'broker',accountId:'acct1',tradingDate:'2026-09-20',currency:'USD',notionalMinor:100000n,side:'BUY',policy,now:'2026-09-20T14:25:00Z'});assert.equal(r.allowed,false);if(!r.allowed)assert.ok(r.reasonCodes.includes('RISK_METRICS_REQUIRED'))})
test('050.2 max order and daily order/notional limits fail closed',async()=>{const s=new InMemoryLiveCanaryStateStore();await s.updateRiskMetrics(metrics(),'2026-09-20','2026-09-20T14:25:00Z');const big=await s.reserve({provider:'broker',accountId:'acct1',tradingDate:'2026-09-20',currency:'USD',notionalMinor:200000n,side:'BUY',policy,now:'2026-09-20T14:25:00Z'});assert.equal(big.allowed,false);for(let i=0;i<3;i++){const r=await s.reserve({provider:'broker',accountId:'acct1',tradingDate:'2026-09-20',currency:'USD',notionalMinor:100000n,side:'SELL',policy,now:'2026-09-20T14:25:0'+i+'Z'});assert.equal(r.allowed,true)}const fourth=await s.reserve({provider:'broker',accountId:'acct1',tradingDate:'2026-09-20',currency:'USD',notionalMinor:1n,side:'SELL',policy,now:'2026-09-20T14:25:10Z'});assert.equal(fourth.allowed,false)})
test('050.3 daily loss and gross exposure caps are enforced',async()=>{const lossStore=new InMemoryLiveCanaryStateStore();await lossStore.updateRiskMetrics(metrics(200000n,-60000n),'2026-09-20','2026-09-20T14:25:00Z');const l=await lossStore.reserve({provider:'broker',accountId:'acct1',tradingDate:'2026-09-20',currency:'USD',notionalMinor:1000n,side:'BUY',policy,now:'2026-09-20T14:25:01Z'});assert.equal(l.allowed,false);const expStore=new InMemoryLiveCanaryStateStore();await expStore.updateRiskMetrics(metrics(450000n,0n),'2026-09-20','2026-09-20T14:25:00Z');const e=await expStore.reserve({provider:'broker',accountId:'acct1',tradingDate:'2026-09-20',currency:'USD',notionalMinor:100000n,side:'BUY',policy,now:'2026-09-20T14:25:01Z'});assert.equal(e.allowed,false)})
test('050.4 canary-governed live order remains manual and records reservation',async()=>{const x=await liveFixture(),r=await executeCanaryGovernedLiveTrade({adapter:x.broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,canaryStore:x.canary,policy,riskMetrics:metrics(),permitPackage:x.pkg,preflight,plan,trigger:x.trigger,now:'2026-09-20T14:25:00Z',attemptIdFactory:()=> 'exec-1'});assert.equal(r.execution.state,'SUBMITTED');assert.equal(r.autonomous,false);assert.equal(r.reservation.canExecute,false);assert.equal(x.broker.calls.length,1)})
test('050.5 UNKNOWN live outcome blocks the next order until reconciled',async()=>{const x=await liveFixture('THROW'),r=await executeCanaryGovernedLiveTrade({adapter:x.broker,permitStore:x.permits,attemptStore:x.attempts,entitlementStore:x.entitlements,canaryStore:x.canary,policy,riskMetrics:metrics(),permitPackage:x.pkg,preflight,plan,trigger:x.trigger,now:'2026-09-20T14:25:00Z',attemptIdFactory:()=> 'exec-unknown'});assert.equal(r.execution.state,'UNKNOWN');await x.canary.updateRiskMetrics(metrics(),'2026-09-20','2026-09-20T14:26:00Z');const next=await x.canary.reserve({provider:'broker',accountId:'acct1',tradingDate:'2026-09-20',currency:'USD',notionalMinor:1000n,side:'BUY',policy,now:'2026-09-20T14:26:01Z'});assert.equal(next.allowed,false);if(!next.allowed)assert.ok(next.reasonCodes.includes('UNRESOLVED_EXECUTION_BLOCK'))})
test('050.6 kill switch halts canary state and all outstanding permits',async()=>{const x=await liveFixture();await x.canary.updateRiskMetrics(metrics(),'2026-09-20','2026-09-20T14:25:00Z');const k=await activateMoney050KillSwitch({store:x.canary,permitStore:x.permits,provider:'broker',accountId:'acct1',now:'2026-09-20T14:25:01Z',reason:'operator emergency stop'});assert.equal(k.authority,'EMERGENCY_STOP_ONLY');assert.equal((await x.canary.get('broker','acct1','2026-09-20'))?.halted,true);assert.equal((await x.permits.get('permit-1'))?.state,'HALTED')})
test('050.7 provider truth feeds 042 receipt reconciliation journal and resolves UNKNOWN',async()=>{const s=new InMemoryLiveCanaryStateStore();await s.updateRiskMetrics(metrics(),'2026-09-20','2026-09-20T14:25:00Z');await s.markUnknown('broker','acct1','2026-09-20','exec-truth','2026-09-20T14:25:01Z');const action={actionId:'a1',userId:'u1',capability:'money.trade.submit',provider:'broker',accountId:'acct1',instrumentId:'stock:x',side:'BUY' as const,amount:'100000',currency:'USD'},attempt=createExecutionAttempt({attemptId:'exec-truth',requestId:'a1',permitId:'p1',action,operation:'money.trade.submit',now:'2026-09-20T14:25:00Z'}),event:ProviderExecutionEvent={eventId:'fill-event',providerEventId:'pe1',provider:'broker',executionId:'exec-truth',actionFingerprint:attempt.actionFingerprint,providerReference:'order-1',state:'FILLED',economics:{orderId:'order-1',instrumentId:'stock:x',side:'BUY',filledQuantity:'10',fillPrice:{coefficient:10000n,scale:2,currency:'USD'},fee:{coefficient:100n,scale:2,currency:'USD'},settlementStatus:'SETTLED',settlementExpectedAt:'2026-09-22T00:00:00Z',settlementActualAt:'2026-09-22T00:00:00Z'},occurredAt:'2026-09-20T14:26:00Z',observedAt:'2026-09-20T14:26:01Z',receivedAt:'2026-09-20T14:26:02Z',availableAt:'2026-09-20T14:26:02Z',sequence:2,evidenceIds:['provider:fill'],payloadHash:'payload',provenanceHash:'prov',authority:'EVIDENCE_ONLY'},truth=await applyLiveExecutionTruth({attempt,event,priorEvents:[],recordedAt:'2026-09-20T14:26:03Z',canaryStore:s,accountId:'acct1'});assert.equal(truth.terminal,true);assert.deepEqual(truth.postingIntents.map(x=>x.kind),['FILL','FEE','SETTLEMENT']);assert.equal((await s.get('broker','acct1','2026-09-20'))?.unresolvedExecutionIds.length,0)})
test('050.8 planned paper shadow actual comparison is learning-only',()=>{const paper:PaperExecutionOutcome={outcomeId:'paper1',paperRunId:'run1',executionPlanId:'ep1',requestedNotional:{minor:100000n,currency:'USD'},filledNotional:{minor:100000n,currency:'USD'},fillRateBps:10000,weightedSlippageBps:10,feesPaid:{minor:10n,currency:'USD'},terminalState:'FILLED',createdAt:'2026-09-20T14:10:00Z',evidenceIds:['paper'],authority:'LEARNING_ONLY'},shadow:ShadowExecutionComparison={comparisonId:'shadow1',executionPlanId:'ep1',baselineMarketSnapshotId:'m1',liveQuoteId:'q1',instrumentId:'stock:x',side:'BUY',baselineReferencePriceMinor:10000n,liveReferencePriceMinor:10050n,priceDriftBps:50,baselineSpreadBps:10,liveSpreadBps:12,spreadDriftBps:2,baselineDepthNotionalMinor:100000n,liveDepthNotionalMinor:90000n,depthRatioBps:9000,wouldCrossLimit:true,observedAt:'2026-09-20T14:20:00Z',evidenceIds:['shadow'],authority:'ANALYSIS_ONLY'},event={eventId:'actual1',providerEventId:'p1',provider:'broker',executionId:'e1',actionFingerprint:'f',providerReference:'o1',state:'FILLED' as const,occurredAt:'2026-09-20T14:30:00Z',observedAt:'2026-09-20T14:30:00Z',receivedAt:'2026-09-20T14:30:00Z',availableAt:'2026-09-20T14:30:00Z',evidenceIds:['actual'],payloadHash:'h',provenanceHash:'p',authority:'EVIDENCE_ONLY' as const},c=comparePlannedPaperShadowActual({plan,paper,shadow:[shadow],events:[event]});assert.equal(c.actualTerminalState,'FILLED');assert.equal(c.paperFillRateBps,10000);assert.equal(c.shadowAverageAbsPriceDriftBps,50);assert.equal(c.authority,'LEARNING_ONLY');assert.equal(c.canAuthorizeLive,false)})
test('050.9 certification locks live mode to manual-only with autonomy disabled',()=>{const names=['atomic-canary-reservation','max-order-limit','daily-notional-order-limits','daily-loss-limit','gross-exposure-limit','unknown-blocks-next-order','kill-switch-halts-permits','receipt-reconciliation-truth','planned-paper-shadow-actual','manual-only-no-autonomy'],cases:Money050CertificationCase[]=names.map((name,i)=>({caseId:'c'+i,name,passed:true,evidenceIds:['test:'+name]})),r=certifyMoney050({cases});assert.equal(r.passed,true);assert.equal(r.liveMode,'MANUAL_ONLY');assert.equal(r.autonomousTradingEnabled,false)})
