import test from 'node:test'
import assert from 'node:assert/strict'
import { ALPACA_LIVE_BASE_URL,ALPACA_PAPER_BASE_URL,AlpacaManualLiveBrokerAdapter,AlpacaTradingApiClient,createAlpacaLiveAdapter,createAlpacaPaperClient } from './alpaca-trading-adapter.js'
import type { HttpClient } from './read-only-http-bank-adapter.js'

function fakeFetch(log:{url:string;headers:Headers;method:string;body?:string}[]):HttpClient{return async(input,init)=>{const url=String(input),headers=new Headers(init?.headers);log.push({url,headers,method:init?.method??'GET',body:typeof init?.body==='string'?init.body:undefined});if(url.endsWith('/v2/account'))return new Response(JSON.stringify({id:'acct1',currency:'USD',cash:'1000.00',buying_power:'1000.00'}),{status:200,headers:{'X-Request-ID':'req-account'}});if(url.endsWith('/v2/positions'))return new Response(JSON.stringify([{symbol:'AAPL',qty:'2',market_value:'400.00'}]),{status:200,headers:{'X-Request-ID':'req-pos'}});if(url.includes('/v2/orders:by_client_order_id'))return new Response(JSON.stringify({id:'order1',client_order_id:'cid1',status:'filled'}),{status:200,headers:{'X-Request-ID':'req-order'}});if(init?.method==='DELETE')return new Response(null,{status:204,headers:{'X-Request-ID':'req-cancel'}});if(url.endsWith('/v2/orders')&&init?.method==='POST')return new Response(JSON.stringify({id:'order1',client_order_id:'cid1',status:'accepted',submitted_at:'2026-09-20T18:00:00Z'}),{status:200,headers:{'X-Request-ID':'req-submit'}});return new Response('{}',{status:404,headers:{'X-Request-ID':'req-404'}})}}
const credentials=()=>({keyId:'key',secretKey:'secret'})

test('056.1 paper and live domains are hard separated',()=>{const paper=createAlpacaPaperClient({credentials,fetchImpl:fakeFetch([])});assert.equal(paper.baseUrl,ALPACA_PAPER_BASE_URL);const live=createAlpacaLiveAdapter({credentials,fetchImpl:fakeFetch([]),liveTradingEnabled:false});assert.equal((live as any).client.baseUrl,ALPACA_LIVE_BASE_URL);assert.throws(()=>new AlpacaManualLiveBrokerAdapter(paper,false),/LIVE_CLIENT_REQUIRED/)})
test('056.2 Alpaca credentials stay in provider headers and account binding is exact',async()=>{const log:any[]=[];const c=createAlpacaPaperClient({credentials,fetchImpl:fakeFetch(log)}),a=await c.getAccount('acct1','2026-09-20T18:00:00Z');assert.equal(a.cashMinor,100000n);assert.equal(log[0].headers.get('apca-api-key-id'),'key');assert.equal(log[0].headers.get('apca-api-secret-key'),'secret');await assert.rejects(()=>c.getAccount('other','2026-09-20T18:00:00Z'),/ACCOUNT_BINDING/)})
test('056.3 positions normalize to canonical stock instrument ids',async()=>{const p=await createAlpacaPaperClient({credentials,fetchImpl:fakeFetch([])}).listPositions('acct1','2026-09-20T18:00:00Z');assert.deepEqual(p.map(x=>[x.instrumentId,x.quantity,x.marketValueMinor]),[['stock:AAPL','2',40000n]])})
test('056.4 live submit is disabled unless explicitly enabled',async()=>{const live=createAlpacaLiveAdapter({credentials,fetchImpl:fakeFetch([]),liveTradingEnabled:false});await assert.rejects(()=>live.submitOrder({environment:'LIVE',executionId:'e1',idempotencyKey:'cid1',actionFingerprint:'fp',permitId:'p',userId:'u',manualTriggerId:'click',now:'2026-09-20T18:00:00Z'},{clientOrderId:'cid1',accountId:'acct1',instrumentId:'stock:AAPL',side:'BUY',orderType:'LIMIT',notionalMinor:'100000',limitPriceMinor:'20000',currency:'USD',timeInForce:'DAY'}),/LIVE_DISABLED/)})
test('056.5 enabled live submit maps approved notional to a bounded fractional limit quantity',async()=>{const log:any[]=[];const live=createAlpacaLiveAdapter({credentials,fetchImpl:fakeFetch(log),liveTradingEnabled:true}),r=await live.submitOrder({environment:'LIVE',executionId:'e1',idempotencyKey:'cid1',actionFingerprint:'fp',permitId:'p',userId:'u',manualTriggerId:'click',now:'2026-09-20T18:00:00Z'},{clientOrderId:'cid1',accountId:'acct1',instrumentId:'stock:AAPL',side:'BUY',orderType:'LIMIT',notionalMinor:'100000',limitPriceMinor:'20000',currency:'USD',timeInForce:'DAY'});assert.equal(r.state,'ACKNOWLEDGED');const body=JSON.parse(log.at(-1).body);assert.equal(body.symbol,'AAPL');assert.equal(body.qty,'5');assert.equal(body.limit_price,'200.00');assert.equal(body.client_order_id,'cid1');assert.equal(body.extended_hours,false)})
test('056.6 forex is not silently routed through the equity broker',async()=>{const live=createAlpacaLiveAdapter({credentials,fetchImpl:fakeFetch([]),liveTradingEnabled:true});await assert.rejects(()=>live.submitOrder({environment:'LIVE',executionId:'e1',idempotencyKey:'cid1',actionFingerprint:'fp',permitId:'p',userId:'u',manualTriggerId:'click',now:'2026-09-20T18:00:00Z'},{clientOrderId:'cid1',accountId:'acct1',instrumentId:'forex:EURUSD',side:'BUY',orderType:'LIMIT',notionalMinor:'100000',limitPriceMinor:'100',currency:'USD',timeInForce:'DAY'}),/INSTRUMENT_UNSUPPORTED/)})
test('056.7 order lookup and cancellation remain read/reconcile safe',async()=>{const c=new AlpacaTradingApiClient('LIVE',{mode:'LIVE',credentials,fetchImpl:fakeFetch([])}),o=await c.getOrder(undefined,'cid1','2026-09-20T18:00:00Z');assert.equal(o.state,'FILLED');const cancel=await c.cancelOrder('order1','2026-09-20T18:00:01Z');assert.equal(cancel.state,'PENDING')})
