import { createHash } from 'node:crypto'
import type { ExactAmount } from './portfolio-construction-contracts.js'
import type { ExecutionMarketSnapshot, ExecutionPlan, ExecutionSlice } from './execution-planning-contracts.js'

export type PaperCapability='money.simulation.order.submit'|'money.simulation.order.cancel'|'money.simulation.portfolio.read'
export type PaperFillModel=Readonly<{modelVersion:string;liquidityFillBps:number;slippageBps:number;feeBps:number;passiveFillBps:number;assumptionIds:readonly string[]}>
export type PaperOrderState='OPEN'|'PARTIALLY_FILLED'|'FILLED'|'CANCELLED'|'EXPIRED'|'NO_FILL'
export type PaperOrder=Readonly<{paperOrderId:string;paperRunId:string;executionPlanId:string;sliceId:string;instrumentId:string;side:'BUY'|'SELL';requestedNotional:ExactAmount;instruction:'MARKETABLE_LIMIT'|'PASSIVE_LIMIT';limitPriceMinor:bigint;submittedAt:string;expiresAt:string;marketSnapshotId:string;state:PaperOrderState;authority:'SIMULATION_ONLY'}>
export type PaperFill=Readonly<{paperFillId:string;paperOrderId:string;instrumentId:string;side:'BUY'|'SELL';notional:ExactAmount;quantityMicros:bigint;referencePriceMinor:bigint;fillPriceMinor:bigint;fee:ExactAmount;slippageBps:number;filledAt:string;marketSnapshotId:string;evidenceIds:readonly string[];authority:'SIMULATION_ONLY'}>
export type PaperPosition=Readonly<{instrumentId:string;quantityMicros:bigint;costBasis:ExactAmount;marketValue:ExactAmount;unrealizedPnl:ExactAmount;evidenceIds:readonly string[]}>
export type PaperPortfolio=Readonly<{paperPortfolioId:string;paperRunId:string;currency:string;cash:ExactAmount;positions:readonly PaperPosition[];realizedPnl:ExactAmount;feesPaid:ExactAmount;asOf:string;stateHash:string;authority:'SIMULATION_ONLY'}>
export type PaperExecutionOutcome=Readonly<{outcomeId:string;paperRunId:string;executionPlanId:string;requestedNotional:ExactAmount;filledNotional:ExactAmount;fillRateBps:number;weightedSlippageBps:number;feesPaid:ExactAmount;terminalState:PaperOrderState;createdAt:string;evidenceIds:readonly string[];authority:'LEARNING_ONLY'}>
export type PaperPromotionAssessment=Readonly<{assessmentId:string;paperRunId:string;sampleSize:number;status:'INSUFFICIENT_DATA'|'ELIGIBLE_FOR_REVIEW'|'REJECTED';reasonCodes:readonly string[];authority:'REVIEW_ONLY';canAuthorizeLive:false}>
export type PaperReplayManifest=Readonly<{replayId:string;paperRunId:string;informationCutoff:string;includedMarketSnapshotIds:readonly string[];excludedFutureSnapshotIds:readonly string[];inputHash:string;provenanceHash:string;authority:'RESEARCH_ONLY'}>

export function hash043(v:unknown){return createHash('sha256').update(JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x)).digest('hex')}
export function assertPaperCapability(c:string):asserts c is PaperCapability{if(!c.startsWith('money.simulation.'))throw new Error('MONEY_043_LIVE_CAPABILITY_FORBIDDEN');if(!['money.simulation.order.submit','money.simulation.order.cancel','money.simulation.portfolio.read'].includes(c))throw new Error('MONEY_043_SIMULATION_CAPABILITY_UNKNOWN')}
export function assertPaperPlan(plan:ExecutionPlan){if(plan.authority!=='ANALYSIS_ONLY'||!plan.requiresHumanApproval)throw new Error('MONEY_043_EXECUTION_PLAN_GOVERNANCE_INVALID')}
export function createPaperOrder(input:{paperRunId:string;plan:ExecutionPlan;slice:ExecutionSlice;market:ExecutionMarketSnapshot;submittedAt:string}):PaperOrder{assertPaperPlan(input.plan);if(!input.plan.slices.some(s=>s.sliceId===input.slice.sliceId))throw new Error('MONEY_043_SLICE_PLAN_MISMATCH');if(input.market.snapshotId!==input.plan.marketSnapshotId||input.market.instrumentId!==input.plan.instrumentId)throw new Error('MONEY_043_MARKET_BINDING_MISMATCH');if(input.market.availableAt>input.submittedAt)throw new Error('MONEY_043_FUTURE_MARKET_SNAPSHOT');if(input.market.expiresAt<=input.submittedAt)throw new Error('MONEY_043_STALE_MARKET_SNAPSHOT');const id='paper-order:'+hash043({run:input.paperRunId,plan:input.plan.executionPlanId,slice:input.slice.sliceId,market:input.market.snapshotId});return Object.freeze({paperOrderId:id,paperRunId:input.paperRunId,executionPlanId:input.plan.executionPlanId,sliceId:input.slice.sliceId,instrumentId:input.plan.instrumentId,side:input.plan.side,requestedNotional:input.slice.notional,instruction:input.slice.instruction,limitPriceMinor:input.slice.limitPriceMinor,submittedAt:input.submittedAt,expiresAt:input.slice.expiresAt,marketSnapshotId:input.market.snapshotId,state:'OPEN',authority:'SIMULATION_ONLY'})}
