import type { ExecutionMarketSnapshot } from './execution-planning-contracts.js'
import { hash043, type PaperExecutionOutcome, type PaperFill, type PaperFillModel, type PaperOrder, type PaperPortfolio, type PaperPosition, type PaperPromotionAssessment, type PaperReplayManifest } from './paper-execution-contracts.js'
import type { ExactAmount } from './portfolio-construction-contracts.js'

const bps=(n:number,label:string)=>{if(!Number.isInteger(n)||n<0||n>10000)throw new Error('MONEY_043_'+label+'_BPS_INVALID')}
const amount=(minor:bigint,currency:string):ExactAmount=>Object.freeze({minor,currency})
export function simulatePaperFill(input:{order:PaperOrder;market:ExecutionMarketSnapshot;model:PaperFillModel;filledAt:string}):PaperFill|undefined{const {order,market,model}=input;[model.liquidityFillBps,model.passiveFillBps].forEach((x,i)=>bps(x,i?'PASSIVE_FILL':'LIQUIDITY_FILL'));bps(Math.abs(model.slippageBps),'SLIPPAGE');bps(model.feeBps,'FEE');if(!model.modelVersion||!model.assumptionIds.length)throw new Error('MONEY_043_FILL_MODEL_UNPROVEN');if(market.snapshotId!==order.marketSnapshotId||market.instrumentId!==order.instrumentId)throw new Error('MONEY_043_MARKET_BINDING_MISMATCH');if(market.availableAt>input.filledAt)throw new Error('MONEY_043_FUTURE_MARKET_SNAPSHOT');if(market.expiresAt<=input.filledAt)throw new Error('MONEY_043_STALE_MARKET_SNAPSHOT');if(input.filledAt>=order.expiresAt)return undefined
 const fillBps=order.instruction==='PASSIVE_LIMIT'?Math.min(model.liquidityFillBps,model.passiveFillBps):model.liquidityFillBps,requested=order.requestedNotional.minor,visibleCap=market.visibleDepthNotionalMinor,modelCap=requested*BigInt(fillBps)/10000n,filled= modelCap<visibleCap?modelCap:visibleCap;if(filled<=0n)return undefined;const reference=order.side==='BUY'?market.askMinor:market.bidMinor,sign=order.side==='BUY'?1n:-1n,fillPrice=reference+(reference*BigInt(model.slippageBps)*sign/10000n);if(fillPrice<=0n)throw new Error('MONEY_043_FILL_PRICE_INVALID');if(order.side==='BUY'&&fillPrice>order.limitPriceMinor&&order.instruction==='PASSIVE_LIMIT')return undefined;if(order.side==='SELL'&&fillPrice<order.limitPriceMinor&&order.instruction==='PASSIVE_LIMIT')return undefined;const quantityMicros=filled*1000000n/fillPrice,feeMinor=filled*BigInt(model.feeBps)/10000n;return Object.freeze({paperFillId:'paper-fill:'+hash043({order:order.paperOrderId,market:market.snapshotId,model:model.modelVersion,filled:filled.toString()}),paperOrderId:order.paperOrderId,instrumentId:order.instrumentId,side:order.side,notional:amount(filled,order.requestedNotional.currency),quantityMicros,referencePriceMinor:reference,fillPriceMinor:fillPrice,fee:amount(feeMinor,order.requestedNotional.currency),slippageBps:model.slippageBps,filledAt:input.filledAt,marketSnapshotId:market.snapshotId,evidenceIds:Object.freeze([...market.evidenceIds,...model.assumptionIds].sort()),authority:'SIMULATION_ONLY'})}
export function paperOrderState(order:PaperOrder,fills:readonly PaperFill[],asOf:string):PaperOrder['state']{const own=fills.filter(f=>f.paperOrderId===order.paperOrderId),filled=own.reduce((n,f)=>n+f.notional.minor,0n);if(filled>=order.requestedNotional.minor)return'FILLED';if(filled>0n)return asOf>=order.expiresAt?'PARTIALLY_FILLED':'PARTIALLY_FILLED';return asOf>=order.expiresAt?'EXPIRED':'OPEN'}
export function cancelPaperOrder(order:PaperOrder,at:string):PaperOrder{if(at>=order.expiresAt)throw new Error('MONEY_043_ORDER_ALREADY_EXPIRED');if(order.state==='FILLED'||order.state==='CANCELLED')throw new Error('MONEY_043_ORDER_TERMINAL');return Object.freeze({...order,state:'CANCELLED'})}
export function buildPaperPortfolio(input:{paperRunId:string;currency:string;initialCash:ExactAmount;orders:readonly PaperOrder[];fills:readonly PaperFill[];marks:Readonly<Record<string,bigint>>;asOf:string}):PaperPortfolio{
 if(input.initialCash.currency!==input.currency)throw new Error('MONEY_043_PORTFOLIO_CURRENCY_MISMATCH')
 const orders=input.orders.filter(o=>o.paperRunId===input.paperRunId),orderById=new Map(orders.map(o=>[o.paperOrderId,o] as const))
 if(orderById.size!==orders.length)throw new Error('MONEY_043_DUPLICATE_ORDER_ID')
 const seenFills=new Set<string>(),orderedFills=[...input.fills].sort((a,b)=>a.filledAt.localeCompare(b.filledAt)||a.paperFillId.localeCompare(b.paperFillId))
 let cash=input.initialCash.minor,fees=0n,realized=0n
 const state=new Map<string,{quantityMicros:bigint;costBasisMinor:bigint;evidence:string[]}>()
 for(const f of orderedFills){
  if(seenFills.has(f.paperFillId))throw new Error('MONEY_043_DUPLICATE_FILL_ID');seenFills.add(f.paperFillId)
  const order=orderById.get(f.paperOrderId);if(!order)throw new Error('MONEY_043_FILL_ORDER_BINDING_MISMATCH')
  if(order.instrumentId!==f.instrumentId||order.side!==f.side)throw new Error('MONEY_043_FILL_ORDER_IDENTITY_MISMATCH')
  if(f.filledAt>input.asOf)throw new Error('MONEY_043_FUTURE_FILL')
  if(f.notional.currency!==input.currency||f.fee.currency!==input.currency)throw new Error('MONEY_043_FILL_CURRENCY_MISMATCH')
  if(f.quantityMicros<=0n||f.notional.minor<0n||f.fee.minor<0n)throw new Error('MONEY_043_FILL_AMOUNT_INVALID')
  const current=state.get(f.instrumentId)??{quantityMicros:0n,costBasisMinor:0n,evidence:[]}
  const evidence=[...current.evidence,...f.evidenceIds]
  if(f.side==='BUY'){
   cash-=f.notional.minor+f.fee.minor;if(cash<0n)throw new Error('MONEY_043_PORTFOLIO_INSUFFICIENT_CASH')
   state.set(f.instrumentId,{quantityMicros:current.quantityMicros+f.quantityMicros,costBasisMinor:current.costBasisMinor+f.notional.minor+f.fee.minor,evidence})
  }else{
   if(f.quantityMicros>current.quantityMicros||current.quantityMicros<=0n)throw new Error('MONEY_043_SELL_EXCEEDS_LONG_POSITION')
   const releasedBasis=f.quantityMicros===current.quantityMicros?current.costBasisMinor:current.costBasisMinor*f.quantityMicros/current.quantityMicros
   realized+=f.notional.minor-f.fee.minor-releasedBasis
   cash+=f.notional.minor-f.fee.minor
   state.set(f.instrumentId,{quantityMicros:current.quantityMicros-f.quantityMicros,costBasisMinor:current.costBasisMinor-releasedBasis,evidence})
  }
  fees+=f.fee.minor
 }
 const positions:PaperPosition[]=[]
 for(const [instrumentId,current] of state){
  if(current.quantityMicros===0n){if(current.costBasisMinor!==0n)throw new Error('MONEY_043_CLOSED_POSITION_BASIS_REMAINS');continue}
  const mark=input.marks[instrumentId];if(mark===undefined)throw new Error('MONEY_043_MARK_REQUIRED')
  const marketValue=current.quantityMicros*mark/1000000n,pnl=marketValue-current.costBasisMinor
  positions.push(Object.freeze({instrumentId,quantityMicros:current.quantityMicros,costBasis:amount(current.costBasisMinor,input.currency),marketValue:amount(marketValue,input.currency),unrealizedPnl:amount(pnl,input.currency),evidenceIds:Object.freeze([...(new Set(current.evidence))].sort())}))
 }
 positions.sort((a,b)=>a.instrumentId.localeCompare(b.instrumentId))
 const stateHash=hash043({run:input.paperRunId,cash:cash.toString(),positions,realized:realized.toString(),fees:fees.toString(),fills:[...seenFills].sort(),asOf:input.asOf})
 return Object.freeze({paperPortfolioId:'paper-portfolio:'+stateHash,paperRunId:input.paperRunId,currency:input.currency,cash:amount(cash,input.currency),positions:Object.freeze(positions),realizedPnl:amount(realized,input.currency),feesPaid:amount(fees,input.currency),asOf:input.asOf,stateHash,authority:'SIMULATION_ONLY'})
}
export function summarizePaperExecution(input:{paperRunId:string;executionPlanId:string;orders:readonly PaperOrder[];fills:readonly PaperFill[];createdAt:string}):PaperExecutionOutcome{const orders=input.orders.filter(o=>o.paperRunId===input.paperRunId&&o.executionPlanId===input.executionPlanId);if(!orders.length)throw new Error('MONEY_043_OUTCOME_ORDERS_REQUIRED');const currency=orders[0]!.requestedNotional.currency,requested=orders.reduce((n,o)=>n+o.requestedNotional.minor,0n),fills=input.fills.filter(f=>orders.some(o=>o.paperOrderId===f.paperOrderId)),filled=fills.reduce((n,f)=>n+f.notional.minor,0n),fees=fills.reduce((n,f)=>n+f.fee.minor,0n),weighted=filled?Number(fills.reduce((n,f)=>n+BigInt(f.slippageBps)*f.notional.minor,0n)/filled):0,terminal=filled>=requested?'FILLED':filled>0n?'PARTIALLY_FILLED':'NO_FILL',evidence=[...new Set(fills.flatMap(f=>f.evidenceIds))].sort();return Object.freeze({outcomeId:'paper-outcome:'+hash043({run:input.paperRunId,plan:input.executionPlanId,orders:orders.map(o=>o.paperOrderId),fills:fills.map(f=>f.paperFillId)}),paperRunId:input.paperRunId,executionPlanId:input.executionPlanId,requestedNotional:amount(requested,currency),filledNotional:amount(filled,currency),fillRateBps:requested?Number(filled*10000n/requested):0,weightedSlippageBps:weighted,feesPaid:amount(fees,currency),terminalState:terminal,createdAt:input.createdAt,evidenceIds:Object.freeze(evidence),authority:'LEARNING_ONLY'})}
export function assessPaperPromotion(input:{paperRunId:string;outcomes:readonly PaperExecutionOutcome[];minSamples:number;minFillRateBps:number;maxAbsSlippageBps:number}):PaperPromotionAssessment{if(input.minSamples<1)throw new Error('MONEY_043_MIN_SAMPLES_INVALID');bps(input.minFillRateBps,'MIN_FILL_RATE');bps(input.maxAbsSlippageBps,'MAX_SLIPPAGE');const xs=input.outcomes.filter(o=>o.paperRunId===input.paperRunId),reasons:string[]=[];let status:PaperPromotionAssessment['status']='ELIGIBLE_FOR_REVIEW';if(xs.length<input.minSamples){status='INSUFFICIENT_DATA';reasons.push('INSUFFICIENT_SAMPLE')}if(xs.some(x=>x.fillRateBps<input.minFillRateBps)){status='REJECTED';reasons.push('FILL_RATE_BELOW_THRESHOLD')}if(xs.some(x=>Math.abs(x.weightedSlippageBps)>input.maxAbsSlippageBps)){status='REJECTED';reasons.push('SLIPPAGE_ABOVE_THRESHOLD')}return Object.freeze({assessmentId:'paper-promotion:'+hash043({run:input.paperRunId,outcomes:xs.map(x=>x.outcomeId),criteria:[input.minSamples,input.minFillRateBps,input.maxAbsSlippageBps]}),paperRunId:input.paperRunId,sampleSize:xs.length,status,reasonCodes:Object.freeze(reasons),authority:'REVIEW_ONLY',canAuthorizeLive:false})}
export function buildPaperReplay(input:{paperRunId:string;markets:readonly ExecutionMarketSnapshot[];informationCutoff:string}):PaperReplayManifest{const included=input.markets.filter(m=>m.availableAt<=input.informationCutoff).map(m=>m.snapshotId).sort(),excluded=input.markets.filter(m=>m.availableAt>input.informationCutoff).map(m=>m.snapshotId).sort();if(!included.length)throw new Error('MONEY_043_REPLAY_NO_MARKET_EVIDENCE');const inputHash=hash043({run:input.paperRunId,cutoff:input.informationCutoff,included}),provenanceHash=hash043({inputHash,excluded});return Object.freeze({replayId:'paper-replay:'+provenanceHash,paperRunId:input.paperRunId,informationCutoff:input.informationCutoff,includedMarketSnapshotIds:Object.freeze(included),excludedFutureSnapshotIds:Object.freeze(excluded),inputHash,provenanceHash,authority:'RESEARCH_ONLY'})}
