import { assertBps, assertExactAmount, assertPortfolioOpportunity, hash040, type AllocationCalibration, type AllocationConstraint, type ExactAmount, type PaperPortfolioRun, type PortfolioConstructionPlan, type PortfolioConstructionSnapshot, type PortfolioObjective, type PortfolioReplayManifest, type RebalanceIntent, type TargetAllocation } from './portfolio-construction-contracts.js'
import type { OpportunityCandidateV2 } from './cross-asset-fusion-contracts.js'

const amt=(minor:bigint,currency:string):ExactAmount=>Object.freeze({minor,currency})
const bpsOf=(part:bigint,total:bigint)=>total===0n?0:Number((part*10000n)/total)
const abs=(x:bigint)=>x<0n?-x:x
export function portfolioTotal(s:PortfolioConstructionSnapshot):bigint{return s.cash.minor+s.holdings.reduce((n,h)=>n+h.marketValue.minor,0n)}
export function assertPortfolioSnapshot(s:PortfolioConstructionSnapshot){assertExactAmount(s.cash,s.currency);assertExactAmount(s.reservedCash,s.currency);if(!s.stateHash||!s.evidenceIds.length)throw new Error('MONEY_040_SNAPSHOT_UNPROVEN');if(s.reservedCash.minor>s.cash.minor)throw new Error('MONEY_040_RESERVE_EXCEEDS_CASH');for(const h of s.holdings){assertExactAmount(h.marketValue,s.currency);assertExactAmount(h.liquidValue,s.currency);if(h.liquidValue.minor>h.marketValue.minor||!h.evidenceIds.length)throw new Error('MONEY_040_HOLDING_UNPROVEN')}}
function constraint(cs:readonly AllocationConstraint[],kind:AllocationConstraint['kind'],subject?:string){return cs.find(c=>c.kind===kind&&(c.subject===undefined||c.subject===subject))}
function limit(cs:readonly AllocationConstraint[],kind:AllocationConstraint['kind'],fallback:number,subject?:string){const c=constraint(cs,kind,subject);const v=c?.limitBps??fallback;assertBps(v,kind);return v}
export function scoreOpportunity(o:OpportunityCandidateV2,objectives:readonly PortfolioObjective[]):number{for(const x of objectives)assertBps(x.weightBps,'objective_weight_bps');const objectiveWeight=objectives.reduce((n,x)=>n+x.weightBps,0);if(objectiveWeight!==10000)throw new Error('MONEY_040_OBJECTIVE_WEIGHTS_NOT_10000');const reward=Math.max(0,o.expectedUpside),risk=Math.max(0,-o.expectedDownside),ratio=reward/(risk||.000001);return Math.max(0,o.confidence*Math.min(4,ratio))}
export function constructPortfolio(input:{snapshot:PortfolioConstructionSnapshot;opportunities:readonly OpportunityCandidateV2[];constraints:readonly AllocationConstraint[];objectives:readonly PortfolioObjective[];expiresAt:string}):PortfolioConstructionPlan{
 const {snapshot:s}=input;assertPortfolioSnapshot(s);const total=portfolioTotal(s);if(total<=0n)throw new Error('MONEY_040_PORTFOLIO_EMPTY');if(input.expiresAt<=s.informationCutoff)throw new Error('MONEY_040_PLAN_EXPIRY_INVALID');input.opportunities.forEach(o=>assertPortfolioOpportunity(o,s.informationCutoff))
 const reserveBps=limit(input.constraints,'MIN_CASH_RESERVE_BPS',0),maxPos=limit(input.constraints,'MAX_POSITION_BPS',10000),maxOpp=limit(input.constraints,'MAX_OPPORTUNITY_BPS',maxPos),availableBps=Math.max(0,10000-reserveBps)
 const scored=input.opportunities.map(o=>({o,score:scoreOpportunity(o,input.objectives)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.o.opportunityId.localeCompare(b.o.opportunityId)),sum=scored.reduce((n,x)=>n+x.score,0)
 const raw=scored.map(x=>({o:x.o,bps:Math.min(maxPos,maxOpp,Math.floor(availableBps*x.score/sum))}))
 const assetUsed=new Map<string,number>(),clusterUsed=new Map<string,number>(),targets:TargetAllocation[]=[]
 for(const x of raw){let b=x.bps;const assetMax=limit(input.constraints,'MAX_ASSET_CLASS_BPS',10000,x.o.assetClasses[0]);b=Math.min(b,Math.max(0,assetMax-(assetUsed.get(x.o.assetClasses[0]??'OTHER')??0)));const clusters=x.o.instrumentIds.map(id=>`instrument:${id}`);for(const cl of clusters){const m=limit(input.constraints,'MAX_CLUSTER_BPS',10000,cl);b=Math.min(b,Math.max(0,m-(clusterUsed.get(cl)??0)))}if(b<=0)continue;assetUsed.set(x.o.assetClasses[0]??'OTHER',(assetUsed.get(x.o.assetClasses[0]??'OTHER')??0)+b);for(const cl of clusters)clusterUsed.set(cl,(clusterUsed.get(cl)??0)+b);targets.push(Object.freeze({instrumentId:x.o.instrumentIds[0]!,assetClass:x.o.assetClasses[0]!,opportunityId:x.o.opportunityId,targetBps:b,targetValue:amt(total*BigInt(b)/10000n,s.currency),confidenceBps:Math.round(x.o.confidence*10000),clusterIds:Object.freeze(clusters),evidenceIds:Object.freeze([...x.o.evidenceIds])}))}
 const current=new Map(s.holdings.map(h=>[h.instrumentId,h.marketValue.minor])),targetIds=new Set(targets.map(t=>t.instrumentId)),turnoverMinor=targets.reduce((n,t)=>n+abs(t.targetValue.minor-(current.get(t.instrumentId)??0n)),0n)+s.holdings.filter(h=>!targetIds.has(h.instrumentId)).reduce((n,h)=>n+h.marketValue.minor,0n),turnoverBps=bpsOf(turnoverMinor,total*2n),maxTurn=limit(input.constraints,'MAX_TURNOVER_BPS',10000);if(turnoverBps>maxTurn)throw new Error('MONEY_040_TURNOVER_LIMIT_BREACH')
 const targetSum=targets.reduce((n,t)=>n+t.targetBps,0),cashTargetBps=10000-targetSum;if(cashTargetBps<reserveBps)throw new Error('MONEY_040_RESERVE_LIMIT_BREACH');const inputHash=hash040({snapshotId:s.snapshotId,opportunityIds:input.opportunities.map(o=>o.opportunityId).sort(),constraints:input.constraints,objectives:input.objectives,cutoff:s.informationCutoff}),provenanceHash=hash040({inputHash,targets:targets.map(t=>({i:t.instrumentId,b:t.targetBps}))})
 return Object.freeze({planId:`portfolio-plan:${provenanceHash}`,snapshotId:s.snapshotId,targets:Object.freeze(targets),cashTargetBps,turnoverBps,constraintIds:Object.freeze(input.constraints.map(c=>c.constraintId).sort()),objectiveIds:Object.freeze(input.objectives.map(o=>o.objectiveId).sort()),informationCutoff:s.informationCutoff,expiresAt:input.expiresAt,inputHash,provenanceHash,authority:'ANALYSIS_ONLY'})
}
export function buildRebalanceIntents(plan:PortfolioConstructionPlan,s:PortfolioConstructionSnapshot):readonly RebalanceIntent[]{if(plan.snapshotId!==s.snapshotId)throw new Error('MONEY_040_REBALANCE_SNAPSHOT_MISMATCH');const current=new Map(s.holdings.map(h=>[h.instrumentId,h.marketValue.minor])),out:RebalanceIntent[]=[];for(const t of plan.targets){const delta=t.targetValue.minor-(current.get(t.instrumentId)??0n);out.push(Object.freeze({intentId:`rebalance:${plan.planId}:${t.instrumentId}`,planId:plan.planId,instrumentId:t.instrumentId,side:delta>0n?'BUY':delta<0n?'SELL':'HOLD',notional:amt(abs(delta),s.currency),reasonCodes:Object.freeze(['TARGET_ALLOCATION']),authority:'NONE'}))}for(const h of s.holdings)if(!plan.targets.some(t=>t.instrumentId===h.instrumentId))out.push(Object.freeze({intentId:`rebalance:${plan.planId}:${h.instrumentId}`,planId:plan.planId,instrumentId:h.instrumentId,side:'SELL',notional:amt(h.marketValue.minor,s.currency),reasonCodes:Object.freeze(['NOT_IN_TARGET_PORTFOLIO']),authority:'NONE'}));return Object.freeze(out)}
export function recordPaperPortfolioRun(input:{plan:PortfolioConstructionPlan;startingValue:ExactAmount;endingValue:ExactAmount;fees:ExactAmount;slippage:ExactAmount;startedAt:string;endedAt:string;evidenceIds:readonly string[]}):PaperPortfolioRun{const c=input.startingValue.currency;[input.startingValue,input.endingValue,input.fees,input.slippage].forEach(x=>assertExactAmount(x,c));if(input.endedAt<=input.startedAt||!input.evidenceIds.length)throw new Error('MONEY_040_PAPER_RUN_UNPROVEN');const provenanceHash=hash040({planId:input.plan.planId,...input});return Object.freeze({runId:`paper-portfolio:${provenanceHash}`,planId:input.plan.planId,startingValue:input.startingValue,endingValue:input.endingValue,fees:input.fees,slippage:input.slippage,startedAt:input.startedAt,endedAt:input.endedAt,evidenceIds:Object.freeze([...input.evidenceIds]),provenanceHash,authority:'PAPER_ONLY'})}
export function calibrateAllocation(input:{plan:PortfolioConstructionPlan;run:PaperPortfolioRun;maxDrawdownBps:number;createdAt:string}):AllocationCalibration{if(input.run.planId!==input.plan.planId)throw new Error('MONEY_040_CALIBRATION_PLAN_MISMATCH');const net=input.run.endingValue.minor-input.run.fees.minor-input.run.slippage.minor,ret=bpsOf(net-input.run.startingValue.minor,input.run.startingValue.minor);return Object.freeze({calibrationId:`allocation-calibration:${hash040({plan:input.plan.planId,run:input.run.runId,createdAt:input.createdAt})}`,planId:input.plan.planId,paperRunId:input.run.runId,returnBps:ret,drawdownBps:input.maxDrawdownBps,turnoverBps:input.plan.turnoverBps,constraintBreaches:0,createdAt:input.createdAt,authority:'LEARNING_ONLY'})}
export function buildPortfolioReplay(input:{snapshot:PortfolioConstructionSnapshot;opportunities:readonly OpportunityCandidateV2[];plan:PortfolioConstructionPlan;cutoff:string}):PortfolioReplayManifest{if(input.snapshot.informationCutoff>input.cutoff||input.plan.informationCutoff>input.cutoff)throw new Error('MONEY_040_REPLAY_FUTURE_STATE');const eligible=input.opportunities.filter(o=>o.informationCutoff<=input.cutoff&&o.expiresAt>input.cutoff).map(o=>o.opportunityId).sort(),future=input.opportunities.filter(o=>o.informationCutoff>input.cutoff).map(o=>o.opportunityId).sort();if(input.plan.targets.some(t=>!eligible.includes(t.opportunityId)))throw new Error('MONEY_040_REPLAY_PLAN_CONTAMINATED');const inputHash=hash040({snapshotId:input.snapshot.snapshotId,eligible,planId:input.plan.planId,cutoff:input.cutoff}),provenanceHash=hash040({inputHash,future});return Object.freeze({replayId:`portfolio-replay:${provenanceHash}`,informationCutoff:input.cutoff,snapshotId:input.snapshot.snapshotId,opportunityIds:Object.freeze(eligible),planId:input.plan.planId,excludedFutureOpportunityIds:Object.freeze(future),inputHash,provenanceHash,authority:'RESEARCH_ONLY'})}
