import type { SqlClient } from './postgres-idempotency-store.js'
import type { DurableProviderClaim,DurableProviderEventRecord,DurableProviderEventStore } from './durable-provider-event-processor.js'
import type { LiveExecutionTruthProjection } from './live-execution-governance.js'
import type { ProviderExecutionEvent } from './execution-receipt-contracts.js'

type Row={event_id:string;provider:string;provider_event_id:string;payload_hash:string;status:'CLAIMED'|'PROCESSED';event_json:ProviderExecutionEvent;claimed_at:string|Date;processed_at:string|Date|null;result_json:any}
const iso=(v:string|Date|null)=>v==null?undefined:v instanceof Date?v.toISOString():new Date(v).toISOString()
const map=(r:Row):DurableProviderEventRecord=>{const x=r.result_json??{};return Object.freeze({eventId:r.event_id,provider:r.provider,providerEventId:r.provider_event_id,payloadHash:r.payload_hash,status:r.status,event:r.event_json,claimedAt:iso(r.claimed_at)!,processedAt:iso(r.processed_at),receipt:x.receipt,reconciliation:x.reconciliation,postingIntents:x.postingIntents,outbox:x.outbox})}
const json=(v:unknown)=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x)
export class PostgresDurableProviderEventStore implements DurableProviderEventStore{
 constructor(private client:SqlClient,private eventTable='money_provider_execution_events',private outboxTable='money_execution_outbox'){for(const x of [eventTable,outboxTable])if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(x))throw new Error('MONEY_057_TABLE_INVALID')}
 async claim(event:ProviderExecutionEvent,now:string):Promise<DurableProviderClaim>{const inserted=await this.client.query<Row>(`INSERT INTO ${this.eventTable}(event_id,provider,provider_event_id,payload_hash,status,event_json,claimed_at) VALUES($1,$2,$3,$4,'CLAIMED',$5::jsonb,$6) ON CONFLICT(provider,provider_event_id) DO NOTHING RETURNING *`,[event.eventId,event.provider,event.providerEventId,event.payloadHash,json(event),now]);if(inserted.rows[0])return Object.freeze({disposition:'CLAIMED',record:map(inserted.rows[0])});const existing=await this.client.query<Row>(`SELECT * FROM ${this.eventTable} WHERE provider=$1 AND provider_event_id=$2 LIMIT 1`,[event.provider,event.providerEventId]);const row=existing.rows[0];if(!row)throw new Error('MONEY_057_CLAIM_RACE_UNRESOLVED');const record=map(row);if(row.payload_hash!==event.payloadHash)return Object.freeze({disposition:'CONFLICT',record});return Object.freeze({disposition:row.status==='PROCESSED'?'DUPLICATE':'REPLAY',record})}
 async complete(eventId:string,projection:LiveExecutionTruthProjection,processedAt:string){const payload=projection.outbox.map(x=>({outbox_id:x.outboxId,aggregate_id:x.aggregateId,event_type:x.eventType,payload_hash:x.payloadHash,created_at:x.createdAt,status:x.status})),result=json({receipt:projection.receipt,reconciliation:projection.reconciliation,postingIntents:projection.postingIntents,outbox:projection.outbox});const q=await this.client.query(`WITH input AS (SELECT * FROM jsonb_to_recordset($2::jsonb) AS x(outbox_id text,aggregate_id text,event_type text,payload_hash text,created_at timestamptz,status text)), ins AS (INSERT INTO ${this.outboxTable}(outbox_id,aggregate_id,event_type,payload_hash,created_at,status) SELECT outbox_id,aggregate_id,event_type,payload_hash,created_at,status FROM input ON CONFLICT(outbox_id) DO NOTHING) UPDATE ${this.eventTable} SET status='PROCESSED',processed_at=$3,result_json=$4::jsonb WHERE event_id=$1 AND status='CLAIMED'`,[eventId,json(payload),processedAt,result]);if((q.rowCount??0)!==1){const existing=await this.get(eventId);if(existing?.status!=='PROCESSED')throw new Error('MONEY_057_COMPLETE_FAILED')}}
 async get(eventId:string){const r=await this.client.query<Row>(`SELECT * FROM ${this.eventTable} WHERE event_id=$1 LIMIT 1`,[eventId]);return r.rows[0]?map(r.rows[0]):undefined}
}
