import { createHash } from 'node:crypto'
import type { HttpClient } from './read-only-http-bank-adapter.js'
import type { LiveBrokerOrderRequest,LiveBrokerSubmissionResult,LiveBrokerSubmitContext,ManualLiveBrokerAdapter } from './manual-live-broker-contracts.js'
import type { MoneyExecutionReconciliationAdapter } from './execution-reconciliation-adapter.js'
import type { ExecutionAttempt } from './execution-attempt.js'
import type { RecoveryObservation } from './execution-recovery.js'

export type ProductionBrokerAccountSnapshot=Readonly<{provider:string;accountId:string;currency:string;cashMinor:bigint;settledCashMinor:bigint;buyingPowerMinor:bigint;asOf:string;evidenceIds:readonly string[]}>
export type ProductionBrokerPosition=Readonly<{provider:string;accountId:string;instrumentId:string;quantity:string;marketValueMinor:bigint;currency:string;asOf:string;evidenceIds:readonly string[]}>
export type ProductionBrokerOrderObservation=Readonly<{providerReference:string;clientOrderId:string;state:'PENDING'|'ACKNOWLEDGED'|'PARTIALLY_FILLED'|'FILLED'|'REJECTED'|'CANCELLED'|'NOT_FOUND'|'UNKNOWN';observedAt:string;evidenceIds:readonly string[]}>
export interface ProductionBrokerReadSurface{getAccount(accountId:string,now:string):Promise<ProductionBrokerAccountSnapshot>;listPositions(accountId:string,now:string):Promise<readonly ProductionBrokerPosition[]>;getOrder(providerReference:string|undefined,clientOrderId:string,now:string):Promise<ProductionBrokerOrderObservation>}
export type ProductionBrokerHttpAdapterOptions=Readonly<{provider:string;baseUrl:string;credential:()=>Promise<string>|string;fetchImpl?:HttpClient;timeoutMs?:number;accountPath:(accountId:string)=>string;positionsPath:(accountId:string)=>string;ordersPath:string;orderStatusPath:(providerReference:string|undefined,clientOrderId:string)=>string;cancelPath:(providerReference:string)=>string;mapAccount:(payload:unknown,provider:string)=>ProductionBrokerAccountSnapshot;mapPositions:(payload:unknown,provider:string)=>readonly ProductionBrokerPosition[];mapSubmission:(payload:unknown,now:string)=>LiveBrokerSubmissionResult;mapOrder:(payload:unknown,now:string)=>ProductionBrokerOrderObservation;serializeOrder:(request:LiveBrokerOrderRequest)=>unknown}>
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x)).digest('hex')
export class ProductionBrokerHttpAdapter implements ManualLiveBrokerAdapter,ProductionBrokerReadSurface,MoneyExecutionReconciliationAdapter{
 readonly environment='LIVE' as const;readonly adapterId:string;readonly adapterVersion=1;readonly provider:string;private fetchImpl:HttpClient
 constructor(private o:ProductionBrokerHttpAdapterOptions){if(!/^https:\/\//i.test(o.baseUrl))throw new Error('MONEY_051_HTTPS_REQUIRED');if(!o.provider)throw new Error('MONEY_051_PROVIDER_REQUIRED');this.provider=o.provider;this.adapterId='money-051:'+o.provider;this.fetchImpl=o.fetchImpl??fetch}
 private async request(path:string,init:RequestInit,_now:string){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),this.o.timeoutMs??10000);try{const secret=await this.o.credential(),res=await this.fetchImpl(new URL(path,this.o.baseUrl),{...init,headers:{Accept:'application/json',Authorization:'Bearer '+secret,...init.headers},signal:controller.signal});if(!res.ok)throw new Error('MONEY_051_PROVIDER_HTTP:'+res.status);return await res.json()}finally{clearTimeout(timeout)}}
 async submitOrder(context:LiveBrokerSubmitContext,request:LiveBrokerOrderRequest){try{const p=await this.request(this.o.ordersPath,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':context.idempotencyKey,'X-Jhadina-Execution-Id':context.executionId},body:JSON.stringify(this.o.serializeOrder(request))},context.now);return this.o.mapSubmission(p,context.now)}catch(e){return Object.freeze({providerReference:'unknown:'+context.executionId,providerEventId:'unknown:'+context.executionId,state:'UNKNOWN' as const,occurredAt:context.now,observedAt:context.now,receivedAt:context.now,availableAt:context.now,evidenceIds:Object.freeze(['provider-submit-ambiguous:'+hash({e:String(e),id:context.executionId})])})}}
 async getAccount(accountId:string,now:string){return this.o.mapAccount(await this.request(this.o.accountPath(accountId),{method:'GET'},now),this.provider)}
 async listPositions(accountId:string,now:string){return this.o.mapPositions(await this.request(this.o.positionsPath(accountId),{method:'GET'},now),this.provider)}
 async getOrder(providerReference:string|undefined,clientOrderId:string,now:string){try{return this.o.mapOrder(await this.request(this.o.orderStatusPath(providerReference,clientOrderId),{method:'GET'},now),now)}catch{return Object.freeze({providerReference:providerReference??'',clientOrderId,state:'UNKNOWN' as const,observedAt:now,evidenceIds:Object.freeze(['provider-order-observation-unknown:'+clientOrderId])})}}
 async cancelOrder(providerReference:string,now:string){return this.o.mapOrder(await this.request(this.o.cancelPath(providerReference),{method:'DELETE'},now),now)}
 canReconcile(a:ExecutionAttempt){return a.provider===this.provider&&a.operation==='money.trade.submit'}
 async reconcile(a:ExecutionAttempt):Promise<RecoveryObservation>{const x=await this.getOrder(a.providerReference,a.idempotencyKey,new Date().toISOString()),state=x.state==='FILLED'?'SUCCEEDED':x.state==='REJECTED'||x.state==='CANCELLED'?'FAILED':x.state==='PENDING'||x.state==='ACKNOWLEDGED'||x.state==='PARTIALLY_FILLED'?'PENDING':x.state==='NOT_FOUND'?'NOT_FOUND':'UNKNOWN';return{executionId:a.attemptId,proposalHash:a.actionFingerprint,providerOperation:a.operation,providerReference:x.providerReference||a.providerReference,observedState:state,evidence:{provider:this.provider,order:x},evidenceHash:hash(x),adapterId:this.adapterId,adapterVersion:this.adapterVersion,checkedAt:x.observedAt}}
}
