import { createHash } from 'node:crypto'

export type RelationshipEdge=Readonly<{edgeId:string;from:string;to:string;kind:'CORRELATION'|'BETA'|'FACTOR'|'SUPPLY_CHAIN'|'CURRENCY'|'ISSUER'|'CUSTOM';value:number;confidence:number;effectiveAt:string;availableAt:string;expiresAt?:string;evidenceRefs:readonly string[];methodologyVersion:string}>
export type ExposureNode=Readonly<{instrumentId:string;weight:number;marketValue:number}>
export type ClusterExposure=Readonly<{clusterId:string;instrumentIds:readonly string[];grossExposure:number;effectiveExposure:number}>
export function relationshipSnapshot(edges:readonly RelationshipEdge[],cutoff:string){const usable=edges.filter(e=>e.availableAt<=cutoff&&(!e.expiresAt||cutoff<e.expiresAt)&&e.evidenceRefs.length);const canonical=usable.slice().sort((a,b)=>a.edgeId.localeCompare(b.edgeId));const hash=createHash('sha256').update(JSON.stringify(canonical)).digest('hex');return Object.freeze({cutoff,edgeIds:Object.freeze(canonical.map(e=>e.edgeId)),hash})}
export function computeClusterExposure(nodes:readonly ExposureNode[],edges:readonly RelationshipEdge[],threshold=.6):readonly ClusterExposure[]{const remaining=new Set(nodes.map(n=>n.instrumentId)),out:ClusterExposure[]=[];const byId=new Map(nodes.map(n=>[n.instrumentId,n]));while(remaining.size){const seed=remaining.values().next().value as string;const cluster=new Set([seed]);const queue=[seed];remaining.delete(seed);while(queue.length){const x=queue.shift()!;for(const e of edges){if(Math.abs(e.value)<threshold)continue;const y=e.from===x?e.to:e.to===x?e.from:null;if(y&&remaining.has(y)){remaining.delete(y);cluster.add(y);queue.push(y)}}}const xs=[...cluster].map(id=>byId.get(id)!).filter(Boolean);out.push(Object.freeze({clusterId:`cluster:${[...cluster].sort().join(':')}`,instrumentIds:Object.freeze([...cluster].sort()),grossExposure:xs.reduce((n,x)=>n+Math.abs(x.marketValue),0),effectiveExposure:xs.reduce((n,x)=>n+Math.abs(x.marketValue*x.weight),0)}))}return Object.freeze(out)}

export type StressShock=Readonly<{target:string;kind:'PRICE'|'FX'|'RATE'|'VOLATILITY'|'LIQUIDITY'|'CORRELATION'|'MARGIN';magnitude:number}>
export type StressScenario=Readonly<{scenarioId:string;name:string;shocks:readonly StressShock[];methodologyVersion:string;evidenceRefs:readonly string[]}>
export type StressPosition=Readonly<{instrumentId:string;marketValue:number;priceSensitivity:number;liquidityHaircut:number;marginRequirement:number}>
export type StressResult=Readonly<{scenarioId:string;pnl:number;liquidityLoss:number;marginIncrease:number;totalLoss:number;breached:boolean;inputHash:string}>
export function runStressTest(positions:readonly StressPosition[],scenario:StressScenario,lossLimit:number):StressResult{if(!scenario.evidenceRefs.length)throw new Error('MONEY_STRESS_SCENARIO_UNPROVEN');let pnl=0,liq=0,margin=0;for(const p of positions){for(const s of scenario.shocks){if(s.target!==p.instrumentId&&s.target!=='ALL')continue;if(s.kind==='PRICE'||s.kind==='FX'||s.kind==='RATE')pnl+=p.marketValue*p.priceSensitivity*s.magnitude;if(s.kind==='LIQUIDITY')liq+=Math.abs(p.marketValue)*Math.max(p.liquidityHaircut,s.magnitude);if(s.kind==='MARGIN')margin+=Math.abs(p.marketValue)*p.marginRequirement*s.magnitude}}const totalLoss=Math.max(0,-pnl)+liq+margin;const inputHash=createHash('sha256').update(JSON.stringify({positions,scenario})).digest('hex');return Object.freeze({scenarioId:scenario.scenarioId,pnl,liquidityLoss:liq,marginIncrease:margin,totalLoss,breached:totalLoss>lossLimit,inputHash})}
export function reverseStress(positions:readonly StressPosition[],base:Omit<StressScenario,'shocks'>,targetLoss:number,steps=100):StressResult{for(let i=1;i<=steps;i++){const magnitude=-i/steps;const r=runStressTest(positions,{...base,shocks:[{target:'ALL',kind:'PRICE',magnitude}]},targetLoss);if(r.totalLoss>=targetLoss)return r}throw new Error('MONEY_REVERSE_STRESS_THRESHOLD_NOT_REACHED')}

function seedInt(seed:string){const h=createHash('sha256').update(seed).digest();return h.readUInt32LE(0)||1}
function rng(seed:string){let x=seedInt(seed);return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function normal(r:()=>number){const u=Math.max(r(),1e-12),v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
export type SimulationSpec=Readonly<{simulationId:string;randomSeed:string;pathCount:number;steps:number;initialValue:number;drift:number;volatility:number;liquidityFeedback:number;lossLimit:number;modelVersion:string;inputSnapshotHash:string}>
export type SimulationDistribution=Readonly<{simulationId:string;mean:number;median:number;var95:number;expectedShortfall95:number;breachRate:number;pathCount:number;provenanceHash:string}>
export function runPathSimulation(s:SimulationSpec):SimulationDistribution{if(!s.randomSeed||s.pathCount<100||s.steps<1||s.volatility<0||Math.abs(s.liquidityFeedback)>1)throw new Error('MONEY_SIMULATION_SPEC_INVALID');const r=rng(s.randomSeed),ends:number[]=[];let breaches=0;for(let p=0;p<s.pathCount;p++){let v=s.initialValue;for(let t=0;t<s.steps;t++){const ret=s.drift+s.volatility*normal(r);const feedback=Math.max(-.95,Math.min(.95,s.liquidityFeedback*(v/s.initialValue-1)));v=Math.max(0,v*(1+ret+feedback))}ends.push(v);if(s.initialValue-v>s.lossLimit)breaches++}ends.sort((a,b)=>a-b);const mean=ends.reduce((a,b)=>a+b,0)/ends.length,median=ends[Math.floor(ends.length/2)]!,idx=Math.floor(.05*ends.length),var95=s.initialValue-ends[idx]!,tail=ends.slice(0,Math.max(1,idx+1)),expectedShortfall95=s.initialValue-tail.reduce((a,b)=>a+b,0)/tail.length;const provenanceHash=createHash('sha256').update(JSON.stringify(s)).digest('hex');return Object.freeze({simulationId:s.simulationId,mean,median,var95,expectedShortfall95,breachRate:breaches/s.pathCount,pathCount:s.pathCount,provenanceHash})}
