import type { ExecutionAttempt } from './execution-attempt.js'
import { assertBrokerRequest, brokerContextFromAttempt, hash044, toProviderExecutionEvent, type BrokerAdapterContext, type BrokerCancellationResult, type BrokerCertificationCase, type BrokerCertificationReport, type BrokerOrderRequest, type BrokerOrderSnapshot, type BrokerSubmissionResult, type SandboxBrokerAdapter, type SandboxFaultMode } from './sandbox-broker-contracts.js'
import type { ProviderExecutionEvent } from './execution-receipt-contracts.js'

type Stored=Readonly<{request:BrokerOrderRequest;providerReference:string;state:BrokerOrderSnapshot['state'];createdAt:string}>
export class DeterministicSandboxBroker implements SandboxBrokerAdapter{
 readonly environment='SANDBOX' as const;private readonly byIdempotency=new Map<string,Stored>();private readonly byReference=new Map<string,Stored>();private sequence=0
 constructor(readonly provider:string,private readonly fault:SandboxFaultMode='NONE'){}
 async submitOrder(context:BrokerAdapterContext,request:BrokerOrderRequest):Promise<BrokerSubmissionResult>{assertBrokerRequest(request);if(context.environment!=='SANDBOX'||context.provider!==this.provider)throw new Error('MONEY_044_SANDBOX_CONTEXT_INVALID');const prior=this.byIdempotency.get(context.idempotencyKey);if(prior){if(hash044(prior.request)!==hash044(request))throw new Error('MONEY_044_IDEMPOTENCY_CONFLICT');return Object.freeze({providerReference:prior.providerReference,state:prior.state,acceptedAt:prior.createdAt,rawEvidenceId:'sandbox-submit:'+prior.providerReference})}if(this.fault==='REJECT')return Object.freeze({providerReference:'sandbox-rejected:'+hash044(request).slice(0,16),state:'REJECTED',acceptedAt:context.now,rawEvidenceId:'sandbox-reject:'+hash044(request)});const providerReference='sandbox-order:'+hash044({provider:this.provider,idempotencyKey:context.idempotencyKey}).slice(0,24),stored=Object.freeze({request,providerReference,state:'ACKNOWLEDGED' as const,createdAt:context.now});this.byIdempotency.set(context.idempotencyKey,stored);this.byReference.set(providerReference,stored);if(this.fault==='TIMEOUT_AFTER_ACCEPT')throw new Error('MONEY_044_PROVIDER_TIMEOUT_AFTER_ACCEPT');return Object.freeze({providerReference,state:'ACKNOWLEDGED',acceptedAt:context.now,rawEvidenceId:'sandbox-submit:'+providerReference})}
 async cancelOrder(context:BrokerAdapterContext,request:{clientOrderId:string;providerReference:string}):Promise<BrokerCancellationResult>{if(context.environment!=='SANDBOX'||context.provider!==this.provider)throw new Error('MONEY_044_SANDBOX_CONTEXT_INVALID');const row=this.byReference.get(request.providerReference);if(!row||row.request.clientOrderId!==request.clientOrderId)return Object.freeze({providerReference:request.providerReference,state:'UNKNOWN',observedAt:context.now,rawEvidenceId:'sandbox-cancel-unknown:'+request.providerReference});if(row.state==='FILLED')return Object.freeze({providerReference:row.providerReference,state:'FILLED',observedAt:context.now,rawEvidenceId:'sandbox-cancel-filled:'+row.providerReference});const next=Object.freeze({...row,state:'CANCELLED' as const});this.byReference.set(row.providerReference,next);for(const [k,v] of this.byIdempotency)if(v.providerReference===row.providerReference)this.byIdempotency.set(k,next);return Object.freeze({providerReference:row.providerReference,state:'CANCELLED',observedAt:context.now,rawEvidenceId:'sandbox-cancel:'+row.providerReference})}
 async getOrder(context:BrokerAdapterContext,providerReference:string):Promise<BrokerOrderSnapshot|undefined>{if(context.environment!=='SANDBOX'||context.provider!==this.provider)throw new Error('MONEY_044_SANDBOX_CONTEXT_INVALID');if(this.fault==='UNKNOWN_QUERY')return undefined;const row=this.byReference.get(providerReference);if(!row)return undefined;return Object.freeze({providerReference:row.providerReference,clientOrderId:row.request.clientOrderId,state:row.state,filledQuantity:'0',updatedAt:context.now})}
}
export async function submitSandboxAttempt(input:{adapter:SandboxBrokerAdapter;attempt:ExecutionAttempt;request:BrokerOrderRequest;now:string}):Promise<{result?:BrokerSubmissionResult;event:ProviderExecutionEvent}>{const context=brokerContextFromAttempt(input.attempt,input.now);try{const result=await input.adapter.submitOrder(context,input.request),event=toProviderExecutionEvent({attempt:input.attempt,providerEventId:'submit:'+result.rawEvidenceId,providerReference:result.providerReference,state:result.state,occurredAt:result.acceptedAt,observedAt:result.acceptedAt,receivedAt:result.acceptedAt,availableAt:result.acceptedAt,evidenceId:result.rawEvidenceId,sequence:1});return{result,event}}catch(error){const evidenceId='sandbox-timeout:'+hash044({executionId:input.attempt.attemptId,message:error instanceof Error?error.message:String(error)}),event=toProviderExecutionEvent({attempt:input.attempt,providerEventId:'timeout:'+evidenceId,state:'UNKNOWN',occurredAt:input.now,observedAt:input.now,receivedAt:input.now,availableAt:input.now,evidenceId,sequence:1});return{event}}}
export async function reconcileSandboxOrder(input:{adapter:SandboxBrokerAdapter;attempt:ExecutionAttempt;providerReference:string;now:string;sequence?:number}):Promise<ProviderExecutionEvent>{const context=brokerContextFromAttempt(input.attempt,input.now),snapshot=await input.adapter.getOrder(context,input.providerReference);if(!snapshot)return toProviderExecutionEvent({attempt:input.attempt,providerEventId:'query-unknown:'+hash044({r:input.providerReference,now:input.now}),providerReference:input.providerReference,state:'UNKNOWN',occurredAt:input.now,observedAt:input.now,receivedAt:input.now,availableAt:input.now,evidenceId:'sandbox-query-unknown:'+input.providerReference,sequence:input.sequence??2});return toProviderExecutionEvent({attempt:input.attempt,providerEventId:'query:'+hash044(snapshot),providerReference:snapshot.providerReference,state:snapshot.state,occurredAt:snapshot.updatedAt,observedAt:snapshot.updatedAt,receivedAt:snapshot.updatedAt,availableAt:snapshot.updatedAt,evidenceId:'sandbox-query:'+snapshot.providerReference,sequence:input.sequence??2})}
export function certifySandboxBroker(input:{provider:string;cases:readonly BrokerCertificationCase[]}):BrokerCertificationReport{const required=['environment-isolation','idempotent-submit','timeout-unknown','reconciliation','cancel-safety','receipt-compatibility','no-live-authority'];const names=new Set(input.cases.filter(c=>c.passed).map(c=>c.name)),missing=required.filter(x=>!names.has(x)),passed=missing.length===0&&input.cases.every(c=>c.passed),provenanceHash=hash044({provider:input.provider,cases:input.cases,missing});return Object.freeze({reportId:'sandbox-broker-cert:'+provenanceHash,provider:input.provider,environment:'SANDBOX',cases:Object.freeze([...input.cases]),passed,liveEligible:false,authority:'CERTIFICATION_ONLY',provenanceHash})}
