import { createHash } from 'node:crypto'
import type { ExecutionMarketSnapshot, ExecutionPlan } from './execution-planning-contracts.js'
import type { PaperExecutionOutcome } from './paper-execution-contracts.js'

export type ShadowCapability='money.market.observe'|'money.shadow.compare'|'money.shadow.replay'
export type LiveMarketQuote=Readonly<{quoteId:string;provider:string;instrumentId:string;currency:string;bidMinor:bigint;askMinor:bigint;bidSize:string;askSize:string;visibleDepthNotionalMinor:bigint;observedAt:string;receivedAt:string;availableAt:string;expiresAt:string;evidenceIds:readonly string[];payloadHash:string;provenanceHash:string;authority:'EVIDENCE_ONLY'}>
export type LiveMarketObservationContext=Readonly<{environment:'LIVE_READ_ONLY';observationId:string;instrumentId:string;informationCutoff:string;now:string}>
export interface LiveMarketObservationAdapter{readonly provider:string;readonly environment:'LIVE_READ_ONLY';observeQuote(context:LiveMarketObservationContext):Promise<LiveMarketQuote>}
export type ShadowExecutionComparison=Readonly<{comparisonId:string;executionPlanId:string;paperOutcomeId?:string;baselineMarketSnapshotId:string;liveQuoteId:string;instrumentId:string;side:'BUY'|'SELL';baselineReferencePriceMinor:bigint;liveReferencePriceMinor:bigint;priceDriftBps:number;baselineSpreadBps:number;liveSpreadBps:number;spreadDriftBps:number;baselineDepthNotionalMinor:bigint;liveDepthNotionalMinor:bigint;depthRatioBps:number;wouldCrossLimit:boolean;observedAt:string;evidenceIds:readonly string[];authority:'ANALYSIS_ONLY'}>
export type ShadowSession=Readonly<{shadowSessionId:string;executionPlanId:string;comparisonIds:readonly string[];startedAt:string;endedAt:string;informationCutoff:string;inputHash:string;provenanceHash:string;authority:'OBSERVATION_ONLY';canSubmitOrders:false;canCancelOrders:false;canAuthorizeLive:false}>
export type ShadowReadinessAssessment=Readonly<{assessmentId:string;sampleSize:number;status:'INSUFFICIENT_DATA'|'ELIGIBLE_FOR_REVIEW'|'REJECTED';reasonCodes:readonly string[];maxAbsPriceDriftBps:number;maxSpreadDriftBps:number;minDepthRatioBps:number;authority:'REVIEW_ONLY';canAuthorizeLive:false}>
export type ShadowReplayManifest=Readonly<{replayId:string;informationCutoff:string;includedQuoteIds:readonly string[];excludedFutureQuoteIds:readonly string[];inputHash:string;provenanceHash:string;authority:'RESEARCH_ONLY'}>
export type ShadowCertificationCase=Readonly<{caseId:string;name:string;passed:boolean;evidenceIds:readonly string[]}>
export type ShadowCertificationReport=Readonly<{reportId:string;provider:string;cases:readonly ShadowCertificationCase[];passed:boolean;liveExecutionEligible:false;authority:'CERTIFICATION_ONLY';provenanceHash:string}>

export function hash045(v:unknown){return createHash('sha256').update(JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x)).digest('hex')}
export function assertShadowCapability(c:string):asserts c is ShadowCapability{if(!['money.market.observe','money.shadow.compare','money.shadow.replay'].includes(c))throw new Error('MONEY_045_CAPABILITY_FORBIDDEN');if(c.startsWith('money.trade.')||c.startsWith('money.execution.'))throw new Error('MONEY_045_LIVE_EXECUTION_FORBIDDEN')}
export function assertReadOnlyObservationAdapter(adapter:unknown):asserts adapter is LiveMarketObservationAdapter{const x=adapter as Record<string,unknown>;if(x.environment!=='LIVE_READ_ONLY'||typeof x.observeQuote!=='function')throw new Error('MONEY_045_OBSERVATION_ADAPTER_INVALID');for(const k of ['submitOrder','cancelOrder','replaceOrder','createOrder','closePosition'])if(typeof x[k]==='function')throw new Error('MONEY_045_MUTATING_ADAPTER_FORBIDDEN:'+k)}
export function assertLiveMarketQuote(q:LiveMarketQuote,cutoff:string,now:string){if(q.authority!=='EVIDENCE_ONLY'||!q.quoteId||!q.provider||!q.instrumentId||!q.evidenceIds.length)throw new Error('MONEY_045_QUOTE_INVALID');if(q.askMinor<q.bidMinor||q.bidMinor<=0n)throw new Error('MONEY_045_QUOTE_PRICE_INVALID');const ts=[q.observedAt,q.receivedAt,q.availableAt,q.expiresAt,cutoff,now].map(Date.parse);if(ts.some(Number.isNaN))throw new Error('MONEY_045_QUOTE_CLOCK_INVALID');if(q.receivedAt<q.observedAt||q.availableAt<q.receivedAt)throw new Error('MONEY_045_QUOTE_CLOCK_ORDER_INVALID');if(q.availableAt>cutoff)throw new Error('MONEY_045_FUTURE_QUOTE');if(q.expiresAt<=now)throw new Error('MONEY_045_STALE_QUOTE')}
export function assertShadowInputs(plan:ExecutionPlan,baseline:ExecutionMarketSnapshot,paper?:PaperExecutionOutcome){if(plan.authority!=='ANALYSIS_ONLY'||!plan.requiresHumanApproval)throw new Error('MONEY_045_PLAN_GOVERNANCE_INVALID');if(baseline.snapshotId!==plan.marketSnapshotId||baseline.instrumentId!==plan.instrumentId)throw new Error('MONEY_045_BASELINE_BINDING_INVALID');if(paper&&paper.executionPlanId!==plan.executionPlanId)throw new Error('MONEY_045_PAPER_BINDING_INVALID')}
