import { createHash } from 'node:crypto'
import type { MoneyAmount } from './exact-money.js'
export type TaxRuleSet=Readonly<{ruleSetId:string;jurisdiction:string;version:string;effectiveFrom:string;effectiveTo?:string;washSaleWindowDays:number;evidenceIds:readonly string[];authority:'TAX_RULE_ONLY'}>
export type RealizedLossSale=Readonly<{saleId:string;accountId:string;instrumentId:string;disposedAt:string;quantity:string;realizedPnl:MoneyAmount;evidenceIds:readonly string[]}>
export type ReplacementAcquisition=Readonly<{lotId:string;accountId:string;instrumentId:string;acquiredAt:string;quantity:string;costBasis:MoneyAmount;evidenceIds:readonly string[]}>
export type WashSaleAssessment=Readonly<{assessmentId:string;ruleSetId:string;saleId:string;status:'NOT_APPLICABLE'|'POTENTIAL_WASH_SALE'|'INSUFFICIENT_EVIDENCE';replacementLotIds:readonly string[];reasonCodes:readonly string[];autoAdjust:false;authority:'TAX_REVIEW_ONLY'}>
const h=(v:unknown)=>createHash('sha256').update(JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x)).digest('hex')
export function assertTaxRuleSet(r:TaxRuleSet,at:string){if(r.authority!=='TAX_RULE_ONLY'||!r.ruleSetId||!r.version||!r.evidenceIds.length||!Number.isInteger(r.washSaleWindowDays)||r.washSaleWindowDays<0)throw new Error('MONEY_058_TAX_RULE_INVALID');if(at<r.effectiveFrom||r.effectiveTo&&at>=r.effectiveTo)throw new Error('MONEY_058_TAX_RULE_NOT_EFFECTIVE')}
export function assessWashSale(input:{ruleSet:TaxRuleSet;sale:RealizedLossSale;replacements:readonly ReplacementAcquisition[]}):WashSaleAssessment{assertTaxRuleSet(input.ruleSet,input.sale.disposedAt);if(input.sale.realizedPnl.coefficient>=0n)return Object.freeze({assessmentId:'wash:'+h({sale:input.sale.saleId,rule:input.ruleSet.ruleSetId}),ruleSetId:input.ruleSet.ruleSetId,saleId:input.sale.saleId,status:'NOT_APPLICABLE',replacementLotIds:Object.freeze([]),reasonCodes:Object.freeze(['NO_REALIZED_LOSS']),autoAdjust:false,authority:'TAX_REVIEW_ONLY'});if(!input.sale.evidenceIds.length)return Object.freeze({assessmentId:'wash:'+h({sale:input.sale.saleId,rule:input.ruleSet.ruleSetId}),ruleSetId:input.ruleSet.ruleSetId,saleId:input.sale.saleId,status:'INSUFFICIENT_EVIDENCE',replacementLotIds:Object.freeze([]),reasonCodes:Object.freeze(['SALE_EVIDENCE_REQUIRED']),autoAdjust:false,authority:'TAX_REVIEW_ONLY'});const center=Date.parse(input.sale.disposedAt),window=input.ruleSet.washSaleWindowDays*86400000,matches=input.replacements.filter(x=>x.accountId===input.sale.accountId&&x.instrumentId===input.sale.instrumentId&&x.evidenceIds.length&&Math.abs(Date.parse(x.acquiredAt)-center)<=window).map(x=>x.lotId).sort();return Object.freeze({assessmentId:'wash:'+h({sale:input.sale.saleId,rule:input.ruleSet.ruleSetId,matches}),ruleSetId:input.ruleSet.ruleSetId,saleId:input.sale.saleId,status:matches.length?'POTENTIAL_WASH_SALE':'NOT_APPLICABLE',replacementLotIds:Object.freeze(matches),reasonCodes:Object.freeze(matches.length?['REPLACEMENT_ACQUISITION_IN_WINDOW']:['NO_REPLACEMENT_IN_WINDOW']),autoAdjust:false,authority:'TAX_REVIEW_ONLY'})}
