'use client';

import { useMemo, useState } from 'react';
import { setClipFade, setClipEffect, addTransition, type FadeCurve } from '@jhadina/director-core/timeline-editing';

type Clip = { id: string; name: string; startSeconds: number; durationSeconds: number; kind: 'video' | 'audio'; trackId: string; assetId: string; volume?: number; opacity?: number; fade?: { fadeInSeconds: number; fadeOutSeconds: number; curve: FadeCurve }; effects?: { id: string; type: string; enabled: boolean; parameters: Record<string, unknown> }[] };
type Track = { id: string; name: string; kind: 'video' | 'audio'; clips: Clip[]; muted?: boolean; solo?: boolean; locked?: boolean };
type Marker = { id: string; timeSeconds: number; label: string };

export type WorkstationTimelineProps = { projectId: string; durationSeconds: number; tracks: Track[]; markers?: Marker[]; onTimelineChange?: (timeline: { tracks: Track[]; playheadSeconds: number }) => void };
const PX_PER_SECOND = 90;

export function WorkstationTimeline({ projectId, durationSeconds, tracks: initialTracks, markers = [], onTimelineChange }: WorkstationTimelineProps) {
  const [tracks, setTracks] = useState(initialTracks);
  const [playheadSeconds, setPlayheadSeconds] = useState(0);
  const [selectedClipId, setSelectedClipId] = useState<string | null>(null);
  const [prompt, setPrompt] = useState('');
  const [approval, setApproval] = useState<{ status: 'idle' | 'pending' | 'approved' | 'rejected'; regionId?: string }>({ status: 'idle' });
  const selectedClip = useMemo(() => tracks.flatMap(t => t.clips).find(c => c.id === selectedClipId) ?? null, [tracks, selectedClipId]);
  const timelineWidth = Math.max(durationSeconds * PX_PER_SECOND, 900);
  function updateTracks(next: Track[]) { setTracks(next); onTimelineChange?.({ tracks: next, playheadSeconds }); }
  function updateClipLocal(clipId: string, patch: Partial<Clip>) { updateTracks(tracks.map(t => ({ ...t, clips: t.clips.map(c => c.id === clipId ? { ...c, ...patch } : c) }))); }
  function moveClip(clipId: string, deltaSeconds: number) { updateClipLocal(clipId, { startSeconds: Math.max(0, (tracks.flatMap(t => t.clips).find(c => c.id === clipId)?.startSeconds ?? 0) + deltaSeconds) }); }
  function applyFade(kind: 'in' | 'out') { if (!selectedClip) return; const next = setClipFade({ version: 1, projectId, fps: 30, width: 1920, height: 1080, durationSeconds, playheadSeconds, tracks: tracks as any, transitions: [], markers, versions: [] }, selectedClip.id, { [kind === 'in' ? 'fadeInSeconds' : 'fadeOutSeconds']: Math.min(2, selectedClip.durationSeconds / 2), curve: 'equal-power' }); updateTracks(next.tracks as any); }
  function applyCrossfade() { if (!selectedClip) return; const next = addTransition({ version: 1, projectId, fps: 30, width: 1920, height: 1080, durationSeconds, playheadSeconds, tracks: tracks as any, transitions: [], markers, versions: [] }, { id: `xfade-${selectedClip.id}`, fromClipId: selectedClip.id, toClipId: selectedClip.id, type: 'cross-dissolve', durationSeconds: 0.5 }); onTimelineChange?.({ tracks: next.tracks as any, playheadSeconds }); }
  async function askJhadina() { if (!selectedClip || !prompt.trim()) return; setApproval({ status: 'pending' }); const response = await fetch('/api/workstation/timeline/generative-region', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId, clipId: selectedClip.id, startSeconds: playheadSeconds, durationSeconds: Math.max(0.1, Math.min(selectedClip.durationSeconds, durationSeconds - playheadSeconds)), instruction: prompt.trim() }) }); const data = await response.json(); if (!response.ok) { setApproval({ status: 'rejected' }); return; } setApproval({ status: 'pending', regionId: data.region.id }); }

  return <section className="flex min-h-[680px] flex-col overflow-hidden rounded-xl border bg-background">
    <div className="flex items-center justify-between border-b px-4 py-3"><div><h2 className="font-semibold">DirectorOS Timeline</h2><p className="text-xs text-muted-foreground">{selectedClip ? `Selected: ${selectedClip.name}` : 'Select a clip to edit'}</p></div><div className="flex items-center gap-2 text-sm"><span>Playhead {playheadSeconds.toFixed(2)}s</span><button className="rounded border px-2 py-1" onClick={() => setPlayheadSeconds(Math.max(0, playheadSeconds - 1))}>−</button><button className="rounded border px-2 py-1" onClick={() => setPlayheadSeconds(Math.min(durationSeconds, playheadSeconds + 1))}>+</button></div></div>
    <div className="grid flex-1 grid-cols-[180px_1fr] overflow-auto"><div className="sticky left-0 z-10 bg-background/95"><div className="h-9 border-b px-3 py-2 text-xs text-muted-foreground">TRACKS</div>{tracks.map(track => <div key={track.id} className="flex h-20 items-center gap-2 border-b px-3 text-sm"><span className="font-medium">{track.name}</span><span className="ml-auto text-[10px] uppercase text-muted-foreground">{track.kind}</span></div>)}</div><div className="relative" style={{ width: timelineWidth }}><div className="sticky top-0 z-20 h-9 border-b bg-background/95" onClick={e => { const rect = e.currentTarget.getBoundingClientRect(); setPlayheadSeconds(Math.max(0, Math.min(durationSeconds, (e.clientX - rect.left) / PX_PER_SECOND))); }}>{Array.from({ length: Math.ceil(durationSeconds) + 1 }, (_, i) => <span key={i} className="absolute top-2 text-[10px] text-muted-foreground" style={{ left: i * PX_PER_SECOND }}>{i}s</span>)}</div><div className="absolute inset-x-0 top-9 bottom-0">{markers.map(marker => <div key={marker.id} className="absolute top-0 z-30 h-full border-l border-dashed" style={{ left: marker.timeSeconds * PX_PER_SECOND }} title={marker.label} />)}{tracks.map(track => <div key={track.id} className="relative h-20 border-b">{track.clips.map(clip => <button key={clip.id} onClick={() => setSelectedClipId(clip.id)} onDoubleClick={() => moveClip(clip.id, 1)} className={`absolute top-2 h-16 overflow-hidden rounded-md border px-2 text-left text-xs ${selectedClipId === clip.id ? 'ring-2 ring-primary' : ''}`} style={{ left: clip.startSeconds * PX_PER_SECOND, width: Math.max(24, clip.durationSeconds * PX_PER_SECOND), opacity: clip.opacity ?? 1 }}><span className="font-medium">{clip.name}</span><span className="block opacity-60">{clip.durationSeconds.toFixed(1)}s</span>{clip.fade?.fadeInSeconds ? <span className="absolute inset-y-0 left-0 w-8 bg-gradient-to-r from-background/70 to-transparent" /> : null}{clip.fade?.fadeOutSeconds ? <span className="absolute inset-y-0 right-0 w-8 bg-gradient-to-l from-background/70 to-transparent" /> : null}</button>)}</div>)}<div className="pointer-events-none absolute top-0 z-40 h-full border-l-2 border-red-500" style={{ left: playheadSeconds * PX_PER_SECOND }} /></div></div></div>
    <aside className="border-t p-4">{selectedClip ? <div className="grid gap-4 lg:grid-cols-[1fr_420px]"><div><h3 className="font-semibold">Clip Inspector</h3><div className="mt-2 grid grid-cols-2 gap-2 text-sm"><label>Start<input className="w-full rounded border p-1" type="number" step="0.01" value={selectedClip.startSeconds} onChange={e => updateClipLocal(selectedClip.id, { startSeconds: Math.max(0, Number(e.target.value)) })} /></label><label>Duration<input className="w-full rounded border p-1" type="number" step="0.01" value={selectedClip.durationSeconds} onChange={e => updateClipLocal(selectedClip.id, { durationSeconds: Math.max(0.1, Number(e.target.value)) })} /></label><label>Volume<input className="w-full rounded border p-1" type="number" step="0.01" min="0" max="2" value={selectedClip.volume ?? 1} onChange={e => updateClipLocal(selectedClip.id, { volume: Number(e.target.value) })} /></label><label>Opacity<input className="w-full rounded border p-1" type="number" step="0.01" min="0" max="1" value={selectedClip.opacity ?? 1} onChange={e => updateClipLocal(selectedClip.id, { opacity: Number(e.target.value) })} /></label></div><div className="mt-4 flex flex-wrap gap-2"><button className="rounded border px-3 py-2 text-sm" onClick={() => applyFade('in')}>Fade In</button><button className="rounded border px-3 py-2 text-sm" onClick={() => applyFade('out')}>Fade Out</button><button className="rounded border px-3 py-2 text-sm" onClick={applyCrossfade}>Cross Dissolve</button><button className="rounded border px-3 py-2 text-sm" onClick={() => moveClip(selectedClip.id, -1)}>Nudge −1s</button><button className="rounded border px-3 py-2 text-sm" onClick={() => moveClip(selectedClip.id, 1)}>Nudge +1s</button></div></div><div className="rounded-lg border p-3"><h3 className="font-semibold">Ask Jhadina to edit this region</h3><textarea className="mt-2 min-h-20 w-full rounded border p-2 text-sm" placeholder="Remove, replace, extend, reframe, make funnier, etc." value={prompt} onChange={e => setPrompt(e.target.value)} /><button className="mt-2 rounded bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={!prompt.trim() || approval.status === 'pending'} onClick={askJhadina}>{approval.status === 'pending' ? 'Awaiting approval…' : 'Create generative edit'}</button>{approval.regionId && <p className="mt-2 text-xs text-muted-foreground">Generative region {approval.regionId} is pending approval. The source clip remains unchanged.</p>}</div></div> : <p className="text-sm text-muted-foreground">Select a clip to open NLE controls and Jhadina edit controls.</p>}</aside>
  </section>;
}
