import type { HistoricalPoolTransaction } from './solana-pool-history'
import type { DlmmPositionTransition } from './meteora-dlmm-position-state'

export const METEORA_DLMM_PROGRAM_ID='LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo'
type Instruction={programId?:unknown;programIdIndex?:unknown;accounts?:unknown;data?:unknown};type AccountKey=string|{pubkey?:string}
export type MeteoraDlmmDecoderContext={poolAddress?:string;tokenMint?:string}
const D={ADD:[181,157,89,67,143,182,52,72],ADDW:[28,140,238,99,231,162,21,149],ADDS:[7,3,150,127,148,40,61,200],ADDS1:[41,5,238,175,100,225,6,205],ADD1:[94,155,103,151,70,95,220,165],REM:[80,85,209,72,24,206,177,108],REM2:[230,215,82,127,241,101,227,146],REMR:[26,82,102,152,240,74,105,26],REMR2:[204,2,195,145,53,145,145,205],INIT:[219,192,234,71,190,191,102,80],INITP:[46,82,125,146,85,141,228,153],INITO:[251,189,190,244,117,254,35,148],CLOSE:[123,134,81,0,49,68,98,98],CLOSE2:[174,90,35,115,186,40,147,226],CLOSEE:[59,124,212,118,91,152,110,157],REB:[92,4,176,193,119,185,83,9],FEE:[169,32,79,137,136,232,70,137]} as const
const E={ADD:[31,94,125,90,227,52,61,186],REM:[116,244,97,232,103,31,152,58],CREATE:[144,142,252,84,157,53,37,121],CLOSE:[255,196,16,107,28,202,53,128],REB:[0,109,117,179,61,91,199,200],FEE:[75,122,154,48,140,74,123,163]} as const
const same=(d:Uint8Array,p:readonly number[])=>d.length>=8&&p.every((v,i)=>d[i]===v)
const i32=(d:Uint8Array,o:number)=>d.length>=o+4?((d[o]|d[o+1]<<8|d[o+2]<<16|d[o+3]<<24)>>0):undefined
const u16=(d:Uint8Array,o:number)=>d.length>=o+2?d[o]|d[o+1]<<8:undefined
function u64(d:Uint8Array,o:number){if(d.length<o+8)return;let n=0n;for(let i=0;i<8;i++)n|=BigInt(d[o+i])<<BigInt(i*8);return n}
function pk(d:Uint8Array,o:number){if(d.length<o+32)return;const a='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(let i=0;i<32;i++)n=(n<<8n)+BigInt(d[o+i]);let s='';while(n){s=a[Number(n%58n)]+s;n/=58n}let z=0;while(z<32&&d[o+z]===0){s='1'+s;z++}return s||'1'}
function b58(v:string){const a='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const c of v){const x=a.indexOf(c);if(x<0)return; n=n*58n+BigInt(x)}const o:number[]=[];while(n){o.unshift(Number(n&255n));n>>=8n}for(const c of v)if(c==='1')o.unshift(0);else break;return Uint8Array.from(o)}
function b64(v:string){try{const s=globalThis.atob(v);return Uint8Array.from(s,c=>c.charCodeAt(0))}catch{return}}
function keys(r:Record<string,unknown>):AccountKey[]{const t=r.transaction&&typeof r.transaction==='object'?r.transaction as Record<string,unknown>:r,m=t.message&&typeof t.message==='object'?t.message as Record<string,unknown>:undefined,k=m?.accountKeys??t.accountKeys??r.accountKeys;return Array.isArray(k)?k.filter((x):x is AccountKey=>typeof x==='string'||!!x&&typeof x==='object'):[]}
const key=(k:AccountKey[],i:unknown)=>typeof i==='number'&&Number.isInteger(i)&&i>=0?(typeof k[i]==='string'?k[i]:(k[i] as {pubkey?:string}|undefined)?.pubkey):undefined
function instructions(r:Record<string,unknown>):Instruction[]{const t=r.transaction&&typeof r.transaction==='object'?r.transaction as Record<string,unknown>:r,m=t.message&&typeof t.message==='object'?t.message as Record<string,unknown>:undefined;return Array.isArray(m?.instructions)?m.instructions as Instruction[]:[]}
function logs(r:Record<string,unknown>):string[]{const m=r.meta&&typeof r.meta==='object'?r.meta as Record<string,unknown>:undefined,t=r.transaction&&typeof r.transaction==='object'?r.transaction as Record<string,unknown>:undefined,tm=t?.meta&&typeof t.meta==='object'?t.meta as Record<string,unknown>:undefined,v=m?.logMessages??tm?.logMessages;return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'):[]}
const make=(v:Omit<DlmmPositionTransition,'eventId'>,s:string):DlmmPositionTransition=>({...v,eventId:`meteora-dlmm:${v.signature}:${s}`})

export class MeteoraDlmmPositionInstructionDecoder{
 constructor(private readonly context:MeteoraDlmmDecoderContext={}){}
 decode(t:HistoricalPoolTransaction):DlmmPositionTransition[]{
  if(!t.raw||typeof t.raw!=='object')return[];const r=t.raw as Record<string,unknown>,k=keys(r),out:DlmmPositionTransition[]=[]
  const add=(v:Omit<DlmmPositionTransition,'eventId'>,s:string)=>out.push(make(v,s))
  for(const q of instructions(r)){
   if((typeof q.programId==='string'?q.programId:key(k,q.programIdIndex))!==METEORA_DLMM_PROGRAM_ID)continue
   const a=Array.isArray(q.accounts)?q.accounts:[],d=typeof q.data==='string'?b58(q.data):q.data instanceof Uint8Array?q.data:undefined;if(!d||d.length<8)continue
   const common={signature:t.signature,observedAt:t.observedAt,poolAddress:this.context.poolAddress??key(k,a[1])??'',tokenMint:this.context.tokenMint,evidenceIds:[t.evidenceId],confidence:1,semantic:'EXPLICIT' as const}
   if(same(d,D.INIT)||same(d,D.INITP)||same(d,D.INITO)){const op=same(d,D.INITO),pda=same(d,D.INITP),lo=i32(d,8),w=i32(d,12),p=key(k,a[op||pda?2:1]),owner=key(k,a[op||pda?4:3]),lb=key(k,a[op||pda?3:2]);if(p&&lb&&lo!==undefined&&w!==undefined&&w>=0)add({...common,positionAddress:p,poolAddress:lb,owner,operator:op?key(k,a[5]):undefined,fromBinId:lo,toBinId:lo+w,action:'OPEN'},'open:'+p)}
   else if(same(d,D.CLOSE)||same(d,D.CLOSE2)||same(d,D.CLOSEE)){const p=key(k,a[0]),owner=same(d,D.CLOSE)?key(k,a[4]):key(k,a[1]);if(p&&common.poolAddress)add({...common,positionAddress:p,owner,action:'CLOSE'},'close:'+p)}
   else if(same(d,D.REMR)||same(d,D.REMR2)){const p=key(k,a[0]),lb=key(k,a[1]),from=i32(d,8),to=i32(d,12),bps=u16(d,16),owner=key(k,a[11]??a[9]);if(p&&lb&&from!==undefined&&to!==undefined&&bps!==undefined)add({...common,positionAddress:p,poolAddress:lb,owner,fromBinId:from,toBinId:to,removedBps:bps,action:'REMOVE'},`remove-range:${p}:${from}:${to}`)}
   else if(same(d,D.REM)||same(d,D.REM2)){const p=key(k,a[0]),lb=key(k,a[1]),owner=key(k,a[11]??a[9]);if(p&&lb)add({...common,positionAddress:p,poolAddress:lb,owner,action:'REMOVE'},'remove:'+p)}
   else if(same(d,D.REB)){const p=key(k,a[0]),lb=key(k,a[1]),owner=key(k,a[9]??a[8]),active=i32(d,8);if(p&&lb)add({...common,positionAddress:p,poolAddress:lb,owner,activeBinId:active,action:'REBALANCE'},'rebalance:'+p)}
   else if(same(d,D.FEE)){const lb=key(k,a[0]),p=key(k,a[1]),owner=key(k,a[2]);if(p&&lb)add({...common,positionAddress:p,poolAddress:lb,owner,action:'CLAIM_FEE'},'claim-fee:'+p)}
   else if(same(d,D.ADD)||same(d,D.ADDW)||same(d,D.ADDS)||same(d,D.ADDS1)||same(d,D.ADD1)){const p=key(k,a[0]),lb=key(k,a[1]),owner=key(k,a[11]??a[8]);if(p&&lb)add({...common,positionAddress:p,poolAddress:lb,owner,action:'ADD'},'add:'+p)}
  }
  for(const line of logs(r)){const m=line.match(/Program data:\s*([A-Za-z0-9+/=]+)$/)?.[1],d=m?b64(m):undefined;if(!d||d.length<8)continue
   if(same(d,E.CREATE)){const lb=pk(d,8),p=pk(d,40),owner=pk(d,72);if(lb&&p&&owner&&(!this.context.poolAddress||lb===this.context.poolAddress))add({signature:t.signature,observedAt:t.observedAt,poolAddress:lb,tokenMint:this.context.tokenMint,positionAddress:p,owner,action:'OPEN',evidenceIds:[t.evidenceId],confidence:1,semantic:'EXPLICIT'},'event-open:'+p)}
   else if(same(d,E.CLOSE)){const p=pk(d,8),owner=pk(d,40);if(p&&owner&&this.context.poolAddress)add({signature:t.signature,observedAt:t.observedAt,poolAddress:this.context.poolAddress,tokenMint:this.context.tokenMint,positionAddress:p,owner,action:'CLOSE',evidenceIds:[t.evidenceId],confidence:1,semantic:'EXPLICIT'},'event-close:'+p)}
   else if(same(d,E.ADD)||same(d,E.REM)){const lb=pk(d,8),owner=pk(d,40),p=pk(d,72),x=u64(d,104),y=u64(d,112),active=i32(d,120);if(!lb||!p||x===undefined||y===undefined||active===undefined||(this.context.poolAddress&&lb!==this.context.poolAddress))continue;const action=same(d,E.ADD)?'ADD':'REMOVE';add({signature:t.signature,observedAt:t.observedAt,poolAddress:lb,tokenMint:this.context.tokenMint,positionAddress:p,owner,action,activeBinId:active,tokenXDeltas:x,tokenYDeltas:y,oneSided:(x===0n)!==(y===0n),evidenceIds:[t.evidenceId],confidence:1,semantic:'EXPLICIT'},`event-${action.toLowerCase()}:${p}`)}
   else if(same(d,E.REB)){const lb=pk(d,8),p=pk(d,40),owner=pk(d,72),active=i32(d,104),xw=u64(d,108),xa=u64(d,116),yw=u64(d,124),ya=u64(d,132),newMin=i32(d,164),newMax=i32(d,168);if(lb&&p&&owner&&active!==undefined&&xw!==undefined&&xa!==undefined&&yw!==undefined&&ya!==undefined&&newMin!==undefined&&newMax!==undefined&&(!this.context.poolAddress||lb===this.context.poolAddress))add({signature:t.signature,observedAt:t.observedAt,poolAddress:lb,tokenMint:this.context.tokenMint,positionAddress:p,owner,activeBinId:active,fromBinId:newMin,toBinId:newMax,tokenXWithdrawnRaw:xw,tokenXAddedRaw:xa,tokenYWithdrawnRaw:yw,tokenYAddedRaw:ya,action:'REBALANCE',evidenceIds:[t.evidenceId],confidence:1,semantic:'EXPLICIT'},'event-rebalance:'+p)}
   else if(same(d,E.FEE)){const lb=pk(d,8),p=pk(d,40),owner=pk(d,72);if(lb&&p&&owner&&(!this.context.poolAddress||lb===this.context.poolAddress))add({signature:t.signature,observedAt:t.observedAt,poolAddress:lb,tokenMint:this.context.tokenMint,positionAddress:p,owner,action:'CLAIM_FEE',evidenceIds:[t.evidenceId],confidence:1,semantic:'EXPLICIT'},'event-claim-fee:'+p)}
  }
  const map=new Map<string,DlmmPositionTransition>();for(const t0 of out){const id=`${t0.signature}:${t0.positionAddress}:${t0.action}`,event=t0.eventId.includes(':event-'),prev=map.get(id);if(!prev||event)map.set(id,prev?{...prev,...t0,fromBinId:t0.fromBinId??prev.fromBinId,toBinId:t0.toBinId??prev.toBinId,removedBps:t0.removedBps??prev.removedBps,tokenXDeltas:t0.tokenXDeltas??prev.tokenXDeltas,tokenYDeltas:t0.tokenYDeltas??prev.tokenYDeltas,tokenXWithdrawnRaw:t0.tokenXWithdrawnRaw??prev.tokenXWithdrawnRaw,tokenXAddedRaw:t0.tokenXAddedRaw??prev.tokenXAddedRaw,tokenYWithdrawnRaw:t0.tokenYWithdrawnRaw??prev.tokenYWithdrawnRaw,tokenYAddedRaw:t0.tokenYAddedRaw??prev.tokenYAddedRaw}:t0)}return[...map.values()]
 }
}
