import test from "node:test"; import assert from "node:assert/strict"
import {detectKnowledgeGaps,proposeKnowledgeFromMemory,rankKnowledge,retrieveKnowledge,temporalState,type KnowledgeRecord,type KnowledgeStore} from "./index.js"
const rec=(x:Partial<KnowledgeRecord>={}):KnowledgeRecord=>({id:"1",scope:"system",subject:"Mars",predicate:"has",claim:"Mars has two moons",object:{moons:2},confidence:.9,verificationState:"verified",authorityScore:.9,freshnessScore:.9,freshnessState:"fresh",observedAt:"2026-01-01T00:00:00Z",evidence:[{id:"e1",authorityScore:.9,verificationState:"verified",freshnessState:"fresh"}],...x})
test("temporal state rejects superseded and expired knowledge",()=>{assert.equal(temporalState(rec({supersededBy:"2"})),"superseded");assert.equal(temporalState(rec({validUntil:"2025-01-01T00:00:00Z"}),"2026-01-01T00:00:00Z"),"expired")})
test("evidence-aware ranking favors verified authoritative fresh record",()=>{assert.ok(rankKnowledge({text:"Mars moons"},rec()).score>rankKnowledge({text:"Mars moons"},rec({verificationState:"unverified",authorityScore:.1,freshnessScore:.1})).score)})
test("hybrid retrieval dedupes and filters superseded records",async()=>{const a=rec(),b=rec({id:"2",supersededBy:"3"});const s:KnowledgeStore={exact:async()=>[a,b],graph:async()=>[a],semantic:async()=>[a]};const c=await retrieveKnowledge(s,{text:"Mars moons"});assert.deepEqual(c.items.map(x=>x.record.id),["1"])})
test("contradictions create research-worthy gap",async()=>{const a=rec(),b=rec({id:"2",object:{moons:3},claim:"Mars has three moons"});const s:KnowledgeStore={exact:async()=>[a,b],graph:async()=>[],semantic:async()=>[]};const c=await retrieveKnowledge(s,{text:"Mars moons",mode:"exact"});assert.equal(c.contradictions.length,1);assert.ok(c.gaps.some(x=>x.kind==="contradictory"&&x.shouldResearch))})
test("missing knowledge produces gap",()=>assert.equal(detectKnowledgeGaps({text:"unknown"},[])[0].kind,"missing"))
test("memory bridge admits approved observations only as candidates",()=>{assert.equal(proposeKnowledgeFromMemory({id:"m",userId:"u",content:"likes jazz",confidence:.8,approved:false,observedAt:"2026-01-01"}),undefined);assert.equal(proposeKnowledgeFromMemory({id:"m",userId:"u",content:"likes jazz",confidence:.8,approved:true,observedAt:"2026-01-01"})?.status,"candidate")})
