'use client'

import { useEffect, useMemo, useState } from "react"

type Account={id:string;name:string;type:string;currentBalance:number;availableBalance?:number;currency:string;mask?:string}
type Tx={id:string;name:string;merchant?:string;amount:number;date:string;pending:boolean;category?:string[]}
type Snapshot={connected:boolean;accounts:Account[];transactions:Tx[];fetchedAt:string}

export default function MoneyCommandCenter(){
 const [snapshot,setSnapshot]=useState<Snapshot>({connected:false,accounts:[],transactions:[],fetchedAt:""}); const [loading,setLoading]=useState(true); const [error,setError]=useState("")
 useEffect(()=>{fetch("/api/money/financial-data",{credentials:"include",cache:"no-store"}).then(async r=>{const j=await r.json();setSnapshot(j.data);if(j.error)setError(j.error)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load financial data")).finally(()=>setLoading(false))},[])
 const cash=useMemo(()=>snapshot.accounts.reduce((n,a)=>n+(a.availableBalance ?? a.currentBalance ?? 0),0),[snapshot.accounts])
 const cards=snapshot.accounts.filter(a=>a.type==="credit"); const pending=snapshot.transactions.filter(t=>t.pending)
 return <main style={page}><div style={wrap}><div style={eyebrow}>Money Core</div><h1 style={h1}>Financial Command Center</h1><p style={sub}>Jhadina can watch your connected finances and surface what needs attention without receiving permission to move money.</p><section style={hero}><span>Available across connected accounts</span><strong>{loading?"Loading…":money(cash,snapshot.accounts[0]?.currency||"USD")}</strong><small>{snapshot.connected?`Last refreshed ${snapshot.fetchedAt ? new Date(snapshot.fetchedAt).toLocaleString():"now"}`:"No live financial connection"}</small></section>{error&&<div style={warning}>{error}</div>}<section style={grid}><Tile title="Accounts" value={String(snapshot.accounts.length)}/><Tile title="Credit cards" value={String(cards.length)}/><Tile title="Pending" value={String(pending.length)}/><Tile title="Transactions" value={String(snapshot.transactions.length)}/></section><section style={card}><h2 style={h2}>Connected accounts</h2>{snapshot.accounts.length===0?<p style={muted}>Connect a financial institution through Plaid to populate this section.</p>:snapshot.accounts.map(a=><div style={row} key={a.id}><div><strong>{a.name}</strong><div style={muted}>{a.type}{a.mask?` •••• ${a.mask}`:""}</div></div><strong>{money(a.currentBalance,a.currency)}</strong></div>)}</section><section style={card}><h2 style={h2}>Recent activity</h2>{snapshot.transactions.length===0?<p style={muted}>No transactions returned.</p>:snapshot.transactions.slice(0,12).map(t=><div style={row} key={t.id}><div><strong>{t.merchant||t.name}</strong><div style={muted}>{t.date}{t.pending?" • Pending":""}</div></div><span>{money(t.amount,"USD")}</span></div>)}</section><div style={note}><strong>Approval boundary</strong><br/>This screen is read-only. Payments, transfers, withdrawals, and cancellations remain separate approval actions.</div></div></main>
}
function Tile({title,value}:{title:string;value:string}){return <div style={tile}><span style={muted}>{title}</span><strong style={{fontSize:24}}>{value}</strong></div>}; function money(n:number,c:string){return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD"}).format(n)}
const page={minHeight:"100vh",background:"linear-gradient(180deg,#f6f1e9,#edf2ed)",color:"#29332e",padding:"30px 18px 100px",fontFamily:'ui-rounded,"Avenir Next",system-ui,sans-serif'};const wrap={maxWidth:920,margin:"0 auto"};const eyebrow={fontSize:10,letterSpacing:".2em",textTransform:"uppercase" as const,color:"#77847c"};const h1={fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400,fontSize:"clamp(38px,9vw,62px)",letterSpacing:"-.045em",margin:"12px 0 8px"};const h2={fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400,fontSize:26,margin:"0 0 12px"};const sub={color:"#718078",lineHeight:1.6,maxWidth:700};const hero={marginTop:25,padding:22,borderRadius:28,background:"#34443c",color:"#f8f6f1",display:"grid",gap:5};const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginTop:14};const tile={padding:18,borderRadius:22,background:"rgba(255,255,255,.72)",border:"1px solid #dce2dd",display:"grid",gap:5};const card={marginTop:14,padding:22,borderRadius:28,background:"rgba(255,255,255,.72)",border:"1px solid #dce2dd"};const row={display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",padding:"13px 0",borderBottom:"1px solid #e5e9e5"};const muted={color:"#718078",fontSize:12,lineHeight:1.5};const warning={marginTop:14,padding:14,borderRadius:16,background:"#f4e7df",color:"#795449"};const note={marginTop:14,padding:14,borderRadius:16,background:"#f1eee7",color:"#657169",fontSize:12,lineHeight:1.5}
