'use client';
import { useMemo, useState } from 'react';
import { dispatchJhadinaCommand, type JhadinaResult } from '../../lib/jhadina/command-bus';
import { createInteraction } from '../../lib/flow/jhadina-interaction';
import type { CommandContext } from '../../lib/flow/jhadina-command-context';

const greetings = ['What’s the deal, foolie?', 'What we getting into?', 'Talk to me.', 'What you need?'];

export function UniversalJhadinaButton() {
  const [open,setOpen]=useState(false),[text,setText]=useState(''),[result,setResult]=useState<JhadinaResult|null>(null),[busy,setBusy]=useState(false),[listening,setListening]=useState(false);
  const greeting = useMemo(() => greetings[Math.floor(Math.random()*greetings.length)], []);
  const context: CommandContext = useMemo(() => ({ current:{ app:'jhadina-web', activity:'global-command', timestamp:new Date().toISOString(), recentCommand:text||undefined }, awareness:[], source:'home' }), [text]);
  function openJhadina(){ createInteraction('open',context); setOpen(true); }
  async function submit(){const value=text.trim();if(!value||busy)return;setBusy(true);setResult(null);const interaction=createInteraction('type',context);try{setResult(await dispatchJhadinaCommand({id:interaction.id,text:value,source:'button',surface:context.source,createdAt:interaction.createdAt}));}finally{setBusy(false)}}
  async function listen(){setListening(true);if(typeof window!=='undefined'&&'SpeechRecognition' in window){const Recognition=(window as typeof window & {SpeechRecognition?:new()=>any}).SpeechRecognition; if(Recognition){const recognition=new Recognition();recognition.lang='en-US';recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onresult=(event:any)=>{setText(event.results[0][0].transcript);setListening(false)};recognition.onerror=()=>setListening(false);recognition.onend=()=>setListening(false);recognition.start();return;}} setListening(false);}
  return <><button type="button" aria-label="Ask Jhadina" onClick={openJhadina} style={{position:'fixed',right:20,bottom:88,zIndex:1000,border:'1px solid rgba(255,255,255,.16)',borderRadius:999,padding:'13px 18px',background:'#202225',color:'#fff',boxShadow:'0 12px 40px rgba(0,0,0,.28)',cursor:'pointer'}}>✦ Jhadina</button>{open&&<div role="dialog" aria-modal="true" onClick={()=>setOpen(false)} style={{position:'fixed',inset:0,zIndex:1100,background:'rgba(0,0,0,.5)',display:'grid',placeItems:'end center',padding:20}}><section onClick={e=>e.stopPropagation()} style={{width:'min(720px,100%)',borderRadius:24,padding:20,background:'#18191c',color:'#fff',boxShadow:'0 24px 80px rgba(0,0,0,.4)'}}><div style={{fontSize:12,opacity:.5,letterSpacing:'.18em',textTransform:'uppercase'}}>Jhadina</div><h2 style={{margin:'8px 0 6px'}}>{busy?'I’m on it.':greeting}</h2><p style={{margin:'0 0 16px',opacity:.55}}>Ask for anything available through Jhadina.</p><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')void submit()}} placeholder="Make a faceless video about this…" rows={4} style={{width:'100%',boxSizing:'border-box',resize:'vertical',borderRadius:16,border:'1px solid rgba(255,255,255,.12)',padding:14,background:'rgba(255,255,255,.05)',color:'inherit',font:'inherit'}}/><div style={{display:'flex',gap:10,justifyContent:'space-between',marginTop:12}}><button type="button" onClick={()=>void listen()} style={{border:'1px solid rgba(255,255,255,.1)',borderRadius:12,padding:'9px 14px',background:'transparent',color:'inherit'}}>{listening?'Listening…':'🎙 Voice'}</button><div style={{display:'flex',gap:10}}><button type="button" onClick={()=>setOpen(false)} style={{border:'1px solid rgba(255,255,255,.1)',borderRadius:12,padding:'9px 14px',background:'transparent',color:'inherit'}}>Close</button><button type="button" disabled={!text.trim()||busy} onClick={()=>void submit()} style={{border:0,borderRadius:12,padding:'9px 16px',background:'#fff',color:'#000',opacity:!text.trim()||busy?.5:1}}>{busy?'Working…':'Ask Jhadina'}</button></div></div>{result&&<div aria-live="polite" style={{marginTop:16,borderRadius:14,padding:14,background:'rgba(255,255,255,.05)'}}><strong>{result.status}</strong><div style={{marginTop:5,opacity:.7}}>{result.message}</div></div>}</section></div>}</>;
}
