import type { DirectorReviewRepository, GeneratedAssetRecord, MediaQualityEvidence, MediaReviewDecisionRecord } from '@jhadina/director-core';
type Result={data:unknown;error:{message:string}|null}; type Q={select(s:string):Q;eq(k:string,v:string|number):Q;maybeSingle():Promise<Result>;insert(v:unknown):Promise<Result>}; export type ReviewClient={from(t:string):Q};
export class SupabaseDirectorReviewRepository implements DirectorReviewRepository{
 constructor(private readonly c:ReviewClient){}
 async getAsset(id:string,p:string){const {data,error}=await this.c.from('director_generated_assets').select('*').eq('id',id).eq('project_id',p).maybeSingle();if(error)throw new Error(error.message);if(!data)return null;const a=data as any;return {id:a.id,projectId:a.project_id,generationJobId:a.generation_job_id,providerId:a.provider_id,mediaType:a.media_type,uri:a.uri,mimeType:a.mime_type,sha256:a.sha256,modelId:a.model_id,workflowId:a.workflow_id,workflowVersion:a.workflow_version,loras:a.loras,prompt:a.prompt,createdAt:a.created_at,provenance:a.provenance,metadata:a.metadata} as GeneratedAssetRecord;}
 async listEvidence(id:string,p:string){const {data,error}=await this.c.from('director_media_quality_evidence').select('*').eq('artifact_id',id).eq('project_id',p) as unknown as Result;if(error)throw new Error(error.message);return ((data??[]) as any[]).map(e=>({id:e.id,artifactId:e.artifact_id,kind:e.kind,status:e.status,score:e.score,checkedAt:e.checked_at,checker:e.checker,metrics:e.metrics,provenance:e.provenance,assetSha256:e.asset_sha256,notes:e.notes} as MediaQualityEvidence));}
 async getDecision(p:string,r:string,s:string,v:number,a:string){const {data,error}=await this.c.from('director_media_review_decisions').select('*').eq('project_id',p).eq('run_id',r).eq('review_stage_id',s).eq('review_stage_version',v).eq('asset_id',a).maybeSingle();if(error)throw new Error(error.message);if(!data)return null;const d=data as any;return {id:d.id,projectId:d.project_id,runId:d.run_id,gateId:d.gate_id,generationStageId:d.generation_stage_id,generationStageVersion:d.generation_stage_version,reviewStageId:d.review_stage_id,reviewStageVersion:d.review_stage_version,assetId:d.asset_id,generationJobId:d.generation_job_id,decision:d.decision,note:d.note,evidenceIds:d.evidence_ids,decidedBy:d.decided_by,decidedAt:d.decided_at,provenance:d.provenance} as MediaReviewDecisionRecord;}
 async appendDecision(d:MediaReviewDecisionRecord){const {error}=await this.c.from('director_media_review_decisions').insert({id:d.id,project_id:d.projectId,run_id:d.runId,gate_id:d.gateId,generation_stage_id:d.generationStageId,generation_stage_version:d.generationStageVersion,review_stage_id:d.reviewStageId,review_stage_version:d.reviewStageVersion,asset_id:d.assetId,generation_job_id:d.generationJobId,decision:d.decision,note:d.note??null,evidence_ids:d.evidenceIds,decided_by:d.decidedBy,decided_at:d.decidedAt,provenance:d.provenance});if(error)throw new Error(error.message);}
}
