'use client'

import { useEffect, useState } from "react"

type Draft={id:string;brand:string;platforms:string[];kind:string;title?:string;body:string;rationale:string;status:string;suggestedPublishAt?:string;createdAt:string;version:number;versionOf?:string}
const brandLabel:Record<string,string>={JHADINA:"Jhadina",JHADINATV:"JhadinaTV",JHADINA_MUSIC:"Jhadina Music",OVERAGEOS:"OverageOS",PUPSONSTUFF:"PupsonStuff",ATWOOD_BOOKIE:"Atwood Bookie"}

export default function GrowthCommandCenter(){
 const [drafts,setDrafts]=useState<Draft[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(""),[compareId,setCompareId]=useState<string|null>(null),[versions,setVersions]=useState<Draft[]>([]),[selectedVersion,setSelectedVersion]=useState<string|null>(null),[instruction,setInstruction]=useState(""),[scouting,setScouting]=useState(false),[scoutResult,setScoutResult]=useState<any>(null)
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/growth/drafts",{headers:{"x-jhadina-user-id":"user_demo"}}),j=await r.json();if(!r.ok)throw Error(j.error||"Could not load growth drafts");setDrafts(j.data?.drafts??[])}catch(e){setError(e instanceof Error?e.message:"Could not load growth drafts")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function action(path:string,draftId:string,extra:Record<string,string>={}){setBusy(draftId);setError("");try{const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json","x-jhadina-user-id":"user_demo"},body:JSON.stringify({draftId,...extra})}),j=await r.json();if(!r.ok)throw Error(j.error||"Action failed");await load();return true}catch(e){setError(e instanceof Error?e.message:"Action failed");return false}finally{setBusy(null)}}
 async function scout(){setScouting(true);setError("");setScoutResult(null);try{const r=await fetch("/api/growth/trends/scout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({})}),j=await r.json();if(!r.ok)throw Error(j.error||"Trend scout failed");setScoutResult(j.data)}catch(e){setError(e instanceof Error?e.message:"Trend scout failed")}finally{setScouting(false)}}
 async function openCompare(id:string){setCompareId(id);setSelectedVersion(id);setInstruction("");setError("");try{const r=await fetch(`/api/growth/drafts/versions?draftId=${encodeURIComponent(id)}`,{headers:{"x-jhadina-user-id":"user_demo"}}),j=await r.json();if(!r.ok)throw Error(j.error||"Could not load versions");const v=j.data?.versions??[];setVersions(v);setSelectedVersion(v[v.length-1]?.id||id)}catch(e){setError(e instanceof Error?e.message:"Could not load versions")}}
 async function createRedraft(){if(!compareId||!instruction.trim())return;const ok=await action("/api/growth/drafts/redraft",selectedVersion||compareId,{instruction:instruction.trim()});if(ok){setInstruction("");await openCompare(compareId)}}
 const pending=drafts.filter(d=>d.status==="PENDING_APPROVAL"),approved=drafts.filter(d=>d.status==="APPROVED"),scheduled=drafts.filter(d=>d.status==="SCHEDULED")
 const current=versions.find(v=>v.id===selectedVersion)||versions[versions.length-1],original=versions[0]
 return <main style={{minHeight:"100vh",background:"linear-gradient(180deg,#f5f1ea,#edf2ed 55%,#f3eee8)",color:"#29332e",padding:"28px 18px 110px",fontFamily:'ui-rounded,"Avenir Next",Avenir,system-ui,sans-serif'}}><div style={{maxWidth:820,margin:"0 auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:16}}><div><div style={{fontSize:10,letterSpacing:".2em",textTransform:"uppercase",color:"#77847c"}}>Jhadina Growth</div><h1 style={{margin:"12px 0 8px",fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400,fontSize:"clamp(36px,9vw,58px)",letterSpacing:"-.045em",lineHeight:1}}>Your content, with you in control.</h1><p style={{margin:0,color:"#718078",lineHeight:1.65,maxWidth:590}}>Jhadina can find ideas and prepare content. Nothing gets published without your approval.</p></div><button disabled={scouting} onClick={()=>void scout()} style={primary}>{scouting?"Scouting…":"Scout trends now"}</button></div>
  {scoutResult&&<section style={{marginTop:22,padding:20,borderRadius:25,background:"rgba(255,255,255,.78)",border:"1px solid #dce2dd"}}><div style={eyebrow}>Trend Scout</div><h2 style={{margin:"8px 0",fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400,fontSize:26}}>Fresh patterns</h2><div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:6}}>{(scoutResult.observations||[]).slice(0,6).map((o:any,i:number)=><a key={i} href={o.url} target="_blank" rel="noreferrer" style={{minWidth:210,padding:13,borderRadius:16,background:"#eef1ed",color:"#536159",textDecoration:"none",fontSize:13}}><strong>{o.title}</strong><div style={{marginTop:5,color:"#78847d"}}>{o.signals?.topic||"Web observation"}</div></a>)}</div>{scoutResult.proposal&&<div style={{marginTop:14,padding:15,borderRadius:18,background:"#f4efe5"}}><strong>{scoutResult.proposal.title}</strong><p style={{margin:"6px 0",lineHeight:1.55,color:"#657169"}}>{scoutResult.proposal.rationale}</p><span style={{fontSize:11,letterSpacing:".08em",textTransform:"uppercase",color:"#8b7b9d"}}>Pending approval · inspired, not copied</span></div>}</section>}
  <div style={{display:"flex",gap:24,overflowX:"auto",padding:"26px 2px 12px",marginBottom:18}}><Metric label="Needs you" value={pending.length}/><Metric label="Approved" value={approved.length}/><Metric label="Scheduled" value={scheduled.length}/></div>
  {error&&<div role="alert" style={{marginBottom:16,padding:13,borderRadius:16,background:"#f5e1dc",color:"#8d5148"}}>{error}</div>}
  {loading?<p style={{color:"#7b877f"}}>Loading your growth queue…</p>:pending.length===0?<section style={empty}><strong>You’re caught up.</strong><span>When Jhadina has a growth idea worth your attention, it will appear here.</span></section>:<section><h2 style={heading}>Needs your call</h2>{pending.map(d=><DraftCard key={d.id} draft={d} busy={busy===d.id} onApprove={()=>action("/api/growth/drafts/approve",d.id)} onReject={()=>action("/api/growth/drafts/reject",d.id)} onCompare={()=>void openCompare(d.id)}/>)}</section>}
  {approved.length>0&&<section style={{marginTop:38}}><h2 style={heading}>Ready to schedule</h2>{approved.map(d=><DraftCard key={d.id} draft={d} busy={busy===d.id} onCompare={()=>void openCompare(d.id)} onSchedule={()=>action("/api/growth/drafts/schedule",d.id,{scheduledAt:d.suggestedPublishAt||new Date(Date.now()+86400000).toISOString()})}/>)}</section>}
  {compareId&&<div role="dialog" aria-modal="true" style={backdrop} onClick={()=>busy?null:setCompareId(null)}><section style={modal} onClick={e=>e.stopPropagation()}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><div style={eyebrow}>Version review</div><h2 style={{margin:"8px 0 0",fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400,fontSize:30}}>Original vs. Redraft</h2></div><button disabled={!!busy} onClick={()=>setCompareId(null)} style={secondary}>Close</button></div><div style={versionTabs}>{versions.map(v=><button key={v.id} onClick={()=>setSelectedVersion(v.id)} style={v.id===selectedVersion?tabActive:tab}>{v.version===1?"Original":`Version ${v.version}`} {v.status==="APPROVED"?"✓":""}</button>)}</div>{original&&current&&<div style={compareGrid}><Version title={`Original · v${original.version}`} body={original.body}/><Version title={`${current.id===original.id?"Current":`Redraft · v${current.version}`} · ${current.status}`} body={current.body} selected={current.status==="PENDING_APPROVAL"}/></div>}<label style={{display:"block",marginTop:16,fontSize:13,color:"#657169"}}>Redraft this version</label><textarea value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Make it less robotic, shorter, and more like me…" style={textarea} rows={3}/><div style={{display:"flex",gap:8,justifyContent:"flex-end",marginTop:12,flexWrap:"wrap"}}><button disabled={!!busy} onClick={()=>setCompareId(null)} style={secondary}>Keep original</button>{current?.status==="PENDING_APPROVAL"&&<button disabled={!!busy} onClick={()=>void action("/api/growth/drafts/approve",current.id).then(()=>openCompare(compareId))} style={primary}>{busy?"Approving…":"Approve this version"}</button>}<button disabled={!!busy||!instruction.trim()} onClick={()=>void createRedraft()} style={secondary}>{busy?"Creating…":"Redraft again"}</button></div></section></div>}
 </div></main>
}
function DraftCard({draft,busy,onApprove,onReject,onSchedule,onCompare}:{draft:Draft;busy:boolean;onApprove?:()=>void;onReject?:()=>void;onSchedule?:()=>void;onCompare?:()=>void}){return <article style={{padding:20,marginBottom:12,borderRadius:25,background:"rgba(255,255,255,.72)",border:"1px solid #dce2dd",boxShadow:"0 14px 38px rgba(67,76,69,.07)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><span style={eyebrow}>{brandLabel[draft.brand]||draft.brand} · {draft.kind}</span><span style={{...eyebrow,color:"#8b7b9d"}}>{draft.platforms.join(" · ")}</span></div>{draft.title&&<h3 style={{margin:"12px 0 7px",fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400,fontSize:24}}>{draft.title}</h3>}<p style={{margin:"8px 0 14px",fontSize:15,lineHeight:1.6}}>{draft.body}</p><div style={{padding:13,borderRadius:16,background:"#eef1ed",color:"#657169",fontSize:13,lineHeight:1.55}}><strong>Why Jhadina suggested it:</strong> {draft.rationale}</div><div style={{display:"flex",gap:8,marginTop:15,flexWrap:"wrap"}}>{onCompare&&<button disabled={busy} onClick={onCompare} style={secondary}>Compare versions</button>}{onApprove&&<button disabled={busy} onClick={onApprove} style={primary}>{busy?"Working…":"Approve"}</button>}{onReject&&<button disabled={busy} onClick={onReject} style={secondary}>Reject</button>}{onSchedule&&<button disabled={busy} onClick={onSchedule} style={primary}>{busy?"Scheduling…":"Schedule"}</button>}</div></article>}
function Version({title,body,selected}:{title:string;body:string;selected?:boolean}){return <div style={{padding:18,borderRadius:22,background:"white",border:selected?"2px solid #879a8e":"1px solid #dce2dd",boxShadow:selected?"0 10px 30px rgba(52,68,60,.08)":"none"}}><div style={{...eyebrow,marginBottom:10}}>{title}</div><div style={{whiteSpace:"pre-wrap",lineHeight:1.7,fontSize:15}}>{body}</div></div>}
function Metric({label,value}:{label:string;value:number}){return <div style={{minWidth:92}}><div style={{fontSize:26,fontFamily:'Georgia,"Times New Roman",serif'}}>{value}</div><div style={{fontSize:10,textTransform:"uppercase",letterSpacing:".14em",color:"#7d8982"}}>{label}</div></div>}
const heading={margin:"0 4px 14px",fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400 as const,fontSize:26};const eyebrow={fontSize:10,letterSpacing:".11em",textTransform:"uppercase" as const,color:"#758179"};const primary={border:0,borderRadius:999,padding:"10px 17px",background:"#34443c",color:"#f8f6f1",fontWeight:600,cursor:"pointer"};const secondary={border:"1px solid #d4dcd5",borderRadius:999,padding:"9px 16px",background:"rgba(255,255,255,.5)",color:"#56635c",fontWeight:600,cursor:"pointer"};const empty={display:"flex",flexDirection:"column" as const,gap:7,padding:22,borderRadius:22,background:"rgba(255,255,255,.55)",border:"1px solid #dce2dd",color:"#68756e",lineHeight:1.5};const backdrop={position:"fixed" as const,inset:0,zIndex:50,display:"flex",alignItems:"center",justifyContent:"center",padding:18,background:"rgba(38,45,41,.28)",backdropFilter:"blur(8px)"};const modal={width:"min(980px,100%)",maxHeight:"90vh",overflowY:"auto" as const,padding:24,borderRadius:28,background:"#faf8f3",border:"1px solid #d9dfda",boxShadow:"0 24px 80px rgba(36,45,40,.22)"};const versionTabs={display:"flex",gap:8,overflowX:"auto" as const,padding:"16px 0 4px"};const tab={border:"1px solid #d4dcd5",borderRadius:999,padding:"8px 13px",background:"white",color:"#657169",whiteSpace:"nowrap" as const,cursor:"pointer"};const tabActive={...tab,background:"#34443c",color:"white",borderColor:"#34443c"};const compareGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:12,marginTop:14};const textarea={width:"100%",boxSizing:"border-box" as const,marginTop:7,padding:14,borderRadius:17,border:"1px solid #d4dcd5",background:"white",color:"#29332e",font:"inherit",lineHeight:1.5,resize:"vertical" as const};
