import { createCipheriv, createDecipheriv, randomBytes } from "crypto"
import { createServiceRoleClient } from "../supabase/service-role"
import { PlaidReadOnlyAdapter } from "@jhadina/money-core"

const PLAID_BASE_URL="https://sandbox.plaid.com"
type PlaidAppCredential={clientId:string;secret:string}
function appCredential():PlaidAppCredential{const raw=process.env.JHADINA_SECRET_PLAID_DEFAULT;if(!raw)throw new Error("CREDENTIAL_NOT_CONFIGURED:money/plaid/default");const parsed=JSON.parse(raw) as Partial<PlaidAppCredential>;if(!parsed.clientId||!parsed.secret)throw new Error("PLAID_APP_CREDENTIAL_INVALID");return {clientId:parsed.clientId,secret:parsed.secret}}
function key(){const raw=process.env.JHADINA_MONEY_CREDENTIAL_KEY;if(!raw)throw new Error("MONEY_CREDENTIAL_KEY_NOT_CONFIGURED");const value=Buffer.from(raw,"base64");if(value.length!==32)throw new Error("MONEY_CREDENTIAL_KEY_INVALID");return value}
export function encryptMoneyCredential(secret:string){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",key(),iv);const encrypted=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]);return [iv.toString("base64"),cipher.getAuthTag().toString("base64"),encrypted.toString("base64")].join(".")}
export function decryptMoneyCredential(value:string){const [iv,tag,data]=value.split(".");if(!iv||!tag||!data)throw new Error("MONEY_CREDENTIAL_CIPHERTEXT_INVALID");const decipher=createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64"));decipher.setAuthTag(Buffer.from(tag,"base64"));return Buffer.concat([decipher.update(Buffer.from(data,"base64")),decipher.final()]).toString("utf8")}
async function plaid<T>(path:string,body:Record<string,unknown>):Promise<T>{const credential=appCredential();const response=await fetch(`${PLAID_BASE_URL}${path}`,{method:"POST",headers:{"content-type":"application/json","PLAID-CLIENT-ID":credential.clientId,"PLAID-SECRET":credential.secret,"Plaid-Version":"2020-09-14"},body:JSON.stringify(body),cache:"no-store"});if(!response.ok)throw new Error(`PLAID_LINK_FAILED:${response.status}`);return await response.json() as T}
export async function createMoneyPlaidLinkToken(userId:string){return plaid<{link_token:string;expiration:string}>("/link/token/create",{user:{client_user_id:userId},client_name:"Jhadina",products:["transactions"],country_codes:["US"],language:"en",transactions:{days_requested:30}})}
export async function exchangeMoneyPlaidPublicToken(userId:string,publicToken:string){if(!publicToken.trim())throw new Error("PLAID_PUBLIC_TOKEN_REQUIRED");const exchanged=await plaid<{access_token:string;item_id:string}>("/item/public_token/exchange",{public_token:publicToken});const accounts=await plaid<{accounts:Array<{account_id:string}>}>("/accounts/get",{access_token:exchanged.access_token});const supabase=createServiceRoleClient();if(!supabase)throw new Error("MONEY_PRIVATE_STORE_NOT_CONFIGURED");const credentialRef=`money/plaid/${exchanged.item_id.toLowerCase().replace(/[^a-z0-9._-]+/g,"-")}`;const encryptedAccessToken=encryptMoneyCredential(exchanged.access_token);const {data:connection,error}=await supabase.from("jhadina_money_bank_connections").upsert({user_id:userId,provider:"plaid",provider_item_id:exchanged.item_id,credential_ref:credentialRef,encrypted_access_token:encryptedAccessToken,status:"active",updated_at:new Date().toISOString()},{onConflict:"user_id,provider,provider_item_id"}).select("id").single();if(error||!connection)throw new Error(`MONEY_BANK_CONNECTION_STORE_FAILED:${error?.message??"missing connection"}`);await supabase.from("jhadina_money_bank_accounts").update({status:"removed",updated_at:new Date().toISOString()}).eq("user_id",userId).eq("connection_id",connection.id);for(const account of accounts.accounts){const {error:accountError}=await supabase.from("jhadina_money_bank_accounts").upsert({connection_id:connection.id,user_id:userId,provider_account_id:account.account_id,status:"active",updated_at:new Date().toISOString()},{onConflict:"user_id,provider_account_id"});if(accountError)throw new Error(`MONEY_BANK_ACCOUNT_STORE_FAILED:${accountError.message}`)}return {connectionId:String(connection.id),accountCount:accounts.accounts.length}}
export async function disconnectMoneyBankConnection(userId:string,connectionId:string){const supabase=createServiceRoleClient();if(!supabase)throw new Error("MONEY_PRIVATE_STORE_NOT_CONFIGURED");const now=new Date().toISOString();const {data,error}=await supabase.from("jhadina_money_bank_connections").update({status:"disconnected",updated_at:now}).eq("id",connectionId).eq("user_id",userId).select("id");if(error||!data?.length)throw new Error(`MONEY_BANK_DISCONNECT_FAILED:${error?.message??"connection not found"}`);const {error:accountError}=await supabase.from("jhadina_money_bank_accounts").update({status:"removed",updated_at:now}).eq("connection_id",connectionId).eq("user_id",userId);if(accountError)throw new Error(`MONEY_BANK_DISCONNECT_FAILED:${accountError.message}`)}

export function createOwnedPlaidAdapter(encryptedAccessToken:string){const credential=appCredential();return new PlaidReadOnlyAdapter({baseUrl:PLAID_BASE_URL,credentialBundle:JSON.stringify({...credential,accessToken:decryptMoneyCredential(encryptedAccessToken)})})}
