import { describe,it,expect } from "vitest"
import { buildMoneyLiveOperationsProductModel } from "./live-operations-product-model"
import type { LiveOperationsConsoleModel } from "@jhadina/money-core"
const core=(executeEnabled=true,blockReasons:string[]=[]):LiveOperationsConsoleModel=>({executionPlanId:"ep1",provider:"alpaca",accountId:"acct1",instrumentId:"stock:AAPL",side:"BUY",notionalMinor:"10000",currency:"USD",preflightStatus:"PASS_FOR_HUMAN_APPROVAL",portfolioStatus:"MATCH",killSwitchActive:false,unknownExecutionIds:[],approvalRequired:true,executeEnabled,blockReasons,authority:"DISPLAY_ONLY",canExecute:false})
describe("MONEY-059 live operations UI boundary",()=>{
 it("requires distinct approval and execute actions",()=>{const before=buildMoneyLiveOperationsProductModel({core:core(),approvalState:"NOT_REQUESTED",executionState:"NOT_SUBMITTED"});expect(before.approveEnabled).toBe(true);expect(before.executeEnabled).toBe(false);const approved=buildMoneyLiveOperationsProductModel({core:core(),approvalState:"APPROVED",executionState:"NOT_SUBMITTED"});expect(approved.approveEnabled).toBe(false);expect(approved.executeEnabled).toBe(true);expect(approved.requiresSeparateApprovalAndExecute).toBe(true);expect(approved.canExecute).toBe(false)})
 it("UNKNOWN disables execute and requires reconciliation",()=>{const m=buildMoneyLiveOperationsProductModel({core:core(false,["UNKNOWN_EXECUTION_OPEN"]),approvalState:"APPROVED",executionState:"UNKNOWN"});expect(m.executeEnabled).toBe(false);expect(m.unknownRequiresReconciliation).toBe(true);expect(m.blockReasons).toContain("UNKNOWN_REQUIRES_RECONCILIATION")})
 it("kill switch/server blockers cannot be overridden by approval state",()=>{const m=buildMoneyLiveOperationsProductModel({core:core(false,["KILL_SWITCH_ACTIVE"]),approvalState:"APPROVED",executionState:"NOT_SUBMITTED"});expect(m.executeEnabled).toBe(false);expect(m.blockReasons).toContain("KILL_SWITCH_ACTIVE");expect(m.emergencyStopEnabled).toBe(true)})
})
