import {describe,expect,it,vi} from "vitest"
import {MoneyProviderRegistry,type BankAdapter,type ProviderConfig} from "@jhadina/money-core"
import type {JhadinaIdentityVerifier} from "../auth/supabase-identity-verifier"
import {createInMemoryAuditRpcClient} from "./reference-adapters"
import {runSessionGovernedMoneyTransactionRead} from "./governed-transaction-read-runtime"

const identity: JhadinaIdentityVerifier={async verify(request){if(request.userId&&request.userId!=="u1")throw new Error("Action identity mismatch");return {userId:"u1",sessionId:"s1"}}}
function providers(adapter:BankAdapter){const registry=new MoneyProviderRegistry();registry.register(adapter);const providerConfig:Readonly<Record<string,ProviderConfig>>={plaid:{enabled:true,credentialRef:"money/plaid/default",capabilities:["money.account.read","money.transaction.read"]}};return {registry,providerConfig}}

describe("Money read-spine acceptance",()=>{
 it("authenticated owner -> governed transaction read -> durable audit",async()=>{const adapter:BankAdapter={provider:"plaid",async listAccounts(){return[]},async listTransactions(_ctx,accountId){return[{id:"t1",accountId:`plaid:${accountId}`,amount:10,currency:"USD",occurredAt:"2026-09-20",description:"Store"}]}};const audit=createInMemoryAuditRpcClient();const result=await runSessionGovernedMoneyTransactionRead("acct-owned","accept-1",{identityVerifier:identity,supabase:audit,providers:providers(adapter),ownershipResolver:{async ownedAccountIds(){return new Set(["acct-owned"])}}});expect(result.transactions).toHaveLength(1);expect(audit.calls.map(c=>c.args.p_status)).toEqual(["started","completed"]);expect(audit.calls.every(c=>c.args.p_capability==="money.transaction.read")).toBe(true)})
 it("cross-user/unknown account fails before provider I/O",async()=>{const adapter:BankAdapter={provider:"plaid",async listAccounts(){return[]},listTransactions:vi.fn(async()=>[])};const audit=createInMemoryAuditRpcClient();await expect(runSessionGovernedMoneyTransactionRead("acct-other","accept-2",{identityVerifier:identity,supabase:audit,providers:providers(adapter),ownershipResolver:{async ownedAccountIds(){return new Set(["acct-owned"])}}})).rejects.toThrow("MONEY_ACCOUNT_ACCESS_DENIED");expect(adapter.listTransactions).not.toHaveBeenCalled()})
 it("revoked/disconnected equivalent empty ownership fails closed",async()=>{const adapter:BankAdapter={provider:"plaid",async listAccounts(){return[]},listTransactions:vi.fn(async()=>[])};await expect(runSessionGovernedMoneyTransactionRead("acct-owned","accept-3",{identityVerifier:identity,supabase:createInMemoryAuditRpcClient(),providers:providers(adapter),ownershipResolver:{async ownedAccountIds(){return new Set()}}})).rejects.toThrow("MONEY_ACCOUNT_ACCESS_DENIED");expect(adapter.listTransactions).not.toHaveBeenCalled()})
})
