'use client'

import Link from 'next/link'
import { useMediaPlayerState, useMediaPlayerStore } from '@jhadina/tv-core'

export default function JhadinaMediaPlayer() {
  const state = useMediaPlayerState()
  const store = useMediaPlayerStore()
  const { item, queue, playback, capabilities, target } = state
  if (!item) return <main style={{ minHeight: '100vh', padding: 32, background: '#08090c', color: '#f7f7f8' }}><Link href="/jhadinatv">← Media Home</Link><h1>Player</h1><p style={{ color: '#9da2ae' }}>Nothing is playing yet. Choose media from Media Home.</p></main>
  const progress = playback.durationMs ? Math.min(100, playback.positionMs / playback.durationMs * 100) : 0
  return <main style={{ minHeight: '100vh', background: '#08090c', color: '#f7f7f8', fontFamily: 'system-ui, sans-serif' }}><div style={{ maxWidth: 1180, margin: '0 auto', padding: 24 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><Link href="/jhadinatv" style={{ color: '#aeb2bd', textDecoration: 'none' }}>← Media Home</Link><span style={{ color: '#9da2ae' }}>{target?.name ?? 'This device'}</span></div><section style={{ marginTop: 24, display: 'grid', gridTemplateColumns: '1fr 320px', gap: 20 }}><div><div style={{ aspectRatio: '16 / 9', background: '#111319', borderRadius: 18, overflow: 'hidden' }}>{item.artworkUrl && <img src={item.artworkUrl} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />}</div><h1>{item.title}</h1><p style={{ color: '#9da2ae' }}>{item.providerId} · {item.kind} · {Math.floor(playback.positionMs / 1000)}s / {playback.durationMs ? `${Math.floor(playback.durationMs / 1000)}s` : '—'}</p><div style={{ height: 4, background: '#242832', borderRadius: 4, overflow: 'hidden' }}><div style={{ width: `${progress}%`, height: '100%', background: '#f7f7f8' }} /></div><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 14 }}><button type="button" onClick={() => store.previous()}>Previous</button><button type="button" onClick={() => playback.status === 'playing' ? store.pause() : store.play()}>{playback.status === 'playing' ? 'Pause' : 'Play'}</button><button type="button" onClick={() => store.next()}>Next</button>{capabilities?.captions && <button type="button">Captions</button>}{capabilities?.audioTracks && <button type="button">Audio</button>}{capabilities?.cast && <button type="button" onClick={() => store.discoverTargets()}>Cast / Device</button>}</div></div><aside style={{ padding: 18, background: '#111319', borderRadius: 18 }}><h2>Up next</h2>{queue.items.slice(queue.currentIndex + 1, queue.currentIndex + 2).map((next) => <p key={`${next.providerId}:${next.id}`}>{next.title}</p>)}<h2 style={{ marginTop: 28 }}>Queue</h2>{queue.items.map((entry, index) => <button key={`${entry.providerId}:${entry.id}:${index}`} type="button" onClick={() => store.playAt(index)} style={{ display: 'block', width: '100%', textAlign: 'left', padding: '10px 0', background: 'transparent', color: '#f7f7f8', border: 0, borderBottom: '1px solid #242832' }}>{index === queue.currentIndex ? '▶ ' : ''}{entry.title}</button>)}</aside></section></div></main>
}
