import type { CinematicNote } from './cinematic-notebook';

export const CLAUDE_CAPCUT_REMOTION_EDITING_NOTES: Array<Omit<CinematicNote, 'createdAt' | 'updatedAt'>> = [
  { id: 'editing-color-foundation', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Establish the color foundation first', body: 'Treat the base grade as a project-wide foundation before layering effects. Use a reusable LUT when it efficiently packages a look, then tune intensity and make local corrections as needed.', tags: ['editing','color','lut','foundation'] },
  { id: 'editing-semantic-visuals', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Turn meaning into visuals', body: 'When narration contains numbers, quotes, locations, or process steps, consider a visual treatment that reinforces comprehension instead of leaving the information static.', tags: ['editing','semantic-editing','visualization','storytelling'] },
  { id: 'editing-srt-counter', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'transition', title: 'Use timed text as an animation primitive', body: 'Timed subtitle states can become a lightweight animation mechanism for counters, emphasis, and sequential information; group and retime them when appropriate.', tags: ['srt','typography','timing','animation'] },
  { id: 'editing-reference-driven', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Make references explicit', body: 'Use reference imagery to communicate visual intent and record constraints such as palette, texture, layout, aspect ratio, duration, and what must remain unchanged.', tags: ['references','style','constraints','motion-design'] },
  { id: 'editing-clarify-intent', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Clarify before expensive generation', body: 'Resolve ambiguity around sequencing, dimensions, typography, motion, hold/fade behavior, and background treatment before committing to a render.', tags: ['creative-intent','clarification','workflow'] },
  { id: 'editing-modular-overlays', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Build effects as modular overlays', body: 'Keep motion backgrounds, graphics, highlights, maps, and other effects independently revisable so changes do not damage the underlying edit.', tags: ['layers','overlays','alpha','modularity'] },
  { id: 'editing-iterate-preview', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Preview, critique, revise', body: 'A successful render is not the same as a successful edit. Watch the result, identify issues such as sluggish or choppy motion, make targeted revisions, and preview again.', tags: ['preview','qa','iteration','motion'] },
  { id: 'editing-parallel-effects', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Develop independent effects concurrently', body: 'When effects have independent inputs and outputs, treat them as parallel generation jobs and assemble them after their visual QA passes.', tags: ['parallel','workflow','generation','throughput'] },
  { id: 'editing-transparent-compositing', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Prefer reusable compositing assets', body: 'Transparent renders allow generated graphics to be reused over different footage and backgrounds without rebuilding the effect.', tags: ['transparency','compositing','reuse'] },
  { id: 'editing-provider-fallback', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Separate creative intent from provider choice', body: 'If a preferred service or token is unavailable, preserve the creative brief and use a compatible fallback provider or open implementation where possible.', tags: ['fallback','providers','resilience','open-source'] },
  { id: 'editing-self-audit', sourceId: 'user-transcript-claude-capcut-remotion', kind: 'edit', title: 'Self-audit generated edits', body: 'Before accepting a generated asset, check dimensions, duration, transparency, timing, readability, continuity, renderability, and alignment with the creative brief.', tags: ['self-audit','qa','continuity','quality'] },
];

export function editingStudyNotes(): Array<Omit<CinematicNote, 'createdAt' | 'updatedAt'>> {
  return CLAUDE_CAPCUT_REMOTION_EDITING_NOTES.map(note => ({ ...note, tags: [...note.tags] }));
}
