import {describe,expect,it} from 'vitest';
import {commitDirectorMediaReview,type DirectorReviewAuthority,type DirectorReviewRepository} from './media-review-lifecycle';
const provenance={projectId:'p',storyboardBoardIds:['b'],storyboardVersion:1,generationStageId:'gen',generationStageVersion:2,generationJobId:'job'};
const authority:DirectorReviewAuthority={run:{id:'run',projectId:'p',status:'review',createdAt:'t',updatedAt:'t',shotIds:[],gateIds:['gate']},gate:{id:'gate',runId:'run',kind:'rough_cut',decision:'approved',requestedAt:'t'},generationStage:{id:'gen',projectId:'p',kind:'generation',dependsOn:[],status:'review',inputArtifactIds:[],outputArtifactIds:['asset'],version:2},reviewStage:{id:'review',projectId:'p',kind:'review',dependsOn:['gen'],status:'review',inputArtifactIds:['asset'],outputArtifactIds:[],version:3},asset:{id:'asset',projectId:'p',generationJobId:'job',providerId:'provider',mediaType:'video',uri:'x',sha256:'hash',createdAt:'t',provenance},evidence:[{id:'ev',artifactId:'asset',kind:'video',status:'pass',checkedAt:'t',checker:'qc',metrics:{},assetSha256:'hash',provenance}],expectedProvenance:provenance};
function repo(existing:null|'approved'|'rejected'=null){let saved:any;const r:DirectorReviewRepository={getAsset:async()=>authority.asset,listEvidence:async()=>authority.evidence,getDecision:async()=>existing?{id:'old',projectId:'p',runId:'run',gateId:'gate',generationStageId:'gen',generationStageVersion:2,reviewStageId:'review',reviewStageVersion:3,assetId:'asset',generationJobId:'job',decision:existing,evidenceIds:['ev'],decidedBy:'u',decidedAt:'t',provenance}:null,appendDecision:async x=>{saved=x}};return {r,get:()=>saved};}
describe('media review lifecycle',()=>{
 it('appends an explicit approved decision only after review gate passes',async()=>{const x=repo();const d=await commitDirectorMediaReview({authority,decision:'approved',decisionId:'d',decidedBy:'u',repository:x.r,now:'now'});expect(d.evidenceIds).toEqual(['ev']);expect(x.get().provenance).toEqual(provenance);});
 it('is idempotent for the same canonical decision',async()=>{const x=repo('approved');const d=await commitDirectorMediaReview({authority,decision:'approved',decisionId:'new',decidedBy:'u',repository:x.r});expect(d.id).toBe('old');});
 it('rejects conflicting replay against the same stage version',async()=>{const x=repo('approved');await expect(commitDirectorMediaReview({authority,decision:'rejected',decisionId:'new',decidedBy:'u',repository:x.r})).rejects.toThrow('DIRECTOR_REVIEW_DECISION_CONFLICT');});
 it('rejects mismatched quality evidence',async()=>{const x=repo();const bad={...authority,evidence:[{...authority.evidence[0],assetSha256:'forged'}]};await expect(commitDirectorMediaReview({authority:bad,decision:'approved',decisionId:'d',decidedBy:'u',repository:x.r})).rejects.toThrow('DIRECTOR_REVIEW_BLOCKED');});
});
