create table if not exists public.jhadina_sam_catalog (
  notice_id text primary key,
  solicitation_number text,
  title text not null,
  notice_type text,
  posted_date text,
  response_deadline text,
  naics_codes text[] not null default '{}',
  classification_codes text[] not null default '{}',
  set_aside text,
  agency text,
  office text,
  place_of_performance jsonb,
  description text,
  source_url text not null,
  resource_links jsonb not null default '[]'::jsonb,
  checksum text not null,
  version integer not null default 1 check (version >= 1),
  raw jsonb not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jhadina_sam_versions (
  id bigint generated by default as identity primary key,
  notice_id text not null references public.jhadina_sam_catalog(notice_id) on delete cascade,
  version integer not null check (version >= 1),
  checksum text not null,
  snapshot jsonb not null,
  captured_at timestamptz not null default now(),
  unique (notice_id, checksum),
  unique (notice_id, version)
);

create table if not exists public.jhadina_sam_scan_runs (
  id bigint generated by default as identity primary key,
  posted_from text not null,
  posted_to text not null,
  status text not null check (status in ('running','completed','failed','environment_blocked')),
  pages integer not null default 0,
  total_records integer not null default 0,
  seen_records integer not null default 0,
  new_records integer not null default 0,
  amended_records integer not null default 0,
  unchanged_records integer not null default 0,
  resource_links integer not null default 0,
  errors jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.jhadina_sam_documents (
  id bigint generated by default as identity primary key,
  notice_id text not null references public.jhadina_sam_catalog(notice_id) on delete cascade,
  source_url text not null,
  source_kind text not null,
  checksum text,
  content_type text,
  byte_length bigint,
  extracted_text text,
  fetch_status text not null,
  evidence jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (notice_id, source_url)
);

create table if not exists public.jhadina_sam_analysis (
  notice_id text primary key references public.jhadina_sam_catalog(notice_id) on delete cascade,
  requirements jsonb not null default '[]'::jsonb,
  solicitation jsonb not null default '{}'::jsonb,
  subcontractability jsonb not null default '{}'::jsonb,
  analyzed_at timestamptz not null default now()
);

create table if not exists public.jhadina_sam_provider_candidates (
  id bigint generated by default as identity primary key,
  notice_id text not null references public.jhadina_sam_catalog(notice_id) on delete cascade,
  requirement_id text not null,
  provider_key text not null,
  provider_name text not null,
  country text,
  uei text,
  cage text,
  naics_codes text[] not null default '{}',
  score numeric not null default 0,
  status text not null,
  sources jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  discovered_at timestamptz not null default now(),
  unique (notice_id, requirement_id, provider_key)
);

create index if not exists jhadina_sam_catalog_posted_idx on public.jhadina_sam_catalog(posted_date desc);
create index if not exists jhadina_sam_catalog_naics_idx on public.jhadina_sam_catalog using gin(naics_codes);
create index if not exists jhadina_sam_versions_notice_idx on public.jhadina_sam_versions(notice_id, version desc);
create index if not exists jhadina_sam_documents_notice_idx on public.jhadina_sam_documents(notice_id);
create index if not exists jhadina_sam_provider_notice_idx on public.jhadina_sam_provider_candidates(notice_id, score desc);

alter table public.jhadina_sam_catalog enable row level security;
alter table public.jhadina_sam_versions enable row level security;
alter table public.jhadina_sam_scan_runs enable row level security;
alter table public.jhadina_sam_documents enable row level security;
alter table public.jhadina_sam_analysis enable row level security;
alter table public.jhadina_sam_provider_candidates enable row level security;

revoke all on table public.jhadina_sam_catalog from anon, authenticated;
revoke all on table public.jhadina_sam_versions from anon, authenticated;
revoke all on table public.jhadina_sam_scan_runs from anon, authenticated;
revoke all on table public.jhadina_sam_documents from anon, authenticated;
revoke all on table public.jhadina_sam_analysis from anon, authenticated;
revoke all on table public.jhadina_sam_provider_candidates from anon, authenticated;

grant select, insert, update, delete on table public.jhadina_sam_catalog to service_role;
grant select, insert, update, delete on table public.jhadina_sam_versions to service_role;
grant select, insert, update, delete on table public.jhadina_sam_scan_runs to service_role;
grant select, insert, update, delete on table public.jhadina_sam_documents to service_role;
grant select, insert, update, delete on table public.jhadina_sam_analysis to service_role;
grant select, insert, update, delete on table public.jhadina_sam_provider_candidates to service_role;
grant usage, select on all sequences in schema public to service_role;
