import type { SupabaseClient } from "@supabase/supabase-js";
import type { Album, Artist, Artwork, ListeningEvent, Lyrics, MediaAsset, MusicRepository, MusicSource, Playlist, Track } from "@jhadina/music-core";

type Row = Record<string, unknown>;
const jsonRecord = (value: unknown): Record<string, string> => (value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, string> : {});
const jsonStrings = (value: unknown): string[] => Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : [];

export class SupabaseMusicRepository implements MusicRepository {
  constructor(private readonly db: SupabaseClient) {}
  private async one(table: string, userId: string, id: string) { const { data, error } = await this.db.from(table).select("*").eq("user_id", userId).eq("id", id).maybeSingle(); if (error) throw error; return data as Row | null; }
  private track(row: Row): Track { return { id: String(row.id), title: String(row.title), artistIds: jsonStrings(row.artist_ids), ...(row.album_id ? { albumId: String(row.album_id) } : {}), ...(row.duration_ms != null ? { durationMs: Number(row.duration_ms) } : {}), ...(row.track_number != null ? { trackNumber: Number(row.track_number) } : {}), ...(row.disc_number != null ? { discNumber: Number(row.disc_number) } : {}), ...(row.isrc ? { isrc: String(row.isrc) } : {}), ...(row.explicit != null ? { explicit: Boolean(row.explicit) } : {}), ...(row.artwork_id ? { artworkId: String(row.artwork_id) } : {}), externalIds: jsonRecord(row.external_ids) }; }
  private source(row: Row): MusicSource { return { id: String(row.id), userId: String(row.user_id), kind: row.kind as MusicSource["kind"], name: String(row.name), ...(row.external_account_id ? { externalAccountId: String(row.external_account_id) } : {}), authorized: Boolean(row.authorized), metadata: (row.metadata && typeof row.metadata === "object" ? row.metadata : {}) as Record<string, unknown> }; }
  private asset(row: Row): MediaAsset { return { id: String(row.id), trackId: String(row.track_id), sourceId: String(row.source_id), kind: row.kind as MediaAsset["kind"], uri: String(row.uri), ...(row.mime_type ? { mimeType: String(row.mime_type) } : {}), ...(row.codec ? { codec: String(row.codec) } : {}), ...(row.bitrate != null ? { bitrate: Number(row.bitrate) } : {}), ...(row.lossless != null ? { lossless: Boolean(row.lossless) } : {}), ...(row.duration_ms != null ? { durationMs: Number(row.duration_ms) } : {}), provenance: (row.provenance && typeof row.provenance === "object" ? row.provenance : {}) as Record<string, unknown> }; }
  async getTrack(userId: string, trackId: string) { const row = await this.one("music_tracks", userId, trackId); return row ? this.track(row) : null; }
  async listTracks(userId: string) { const { data, error } = await this.db.from("music_tracks").select("*").eq("user_id", userId).order("title"); if (error) throw error; return (data ?? []).map(row => this.track(row as Row)); }
  async upsertTrack(userId: string, track: Track) { const { data, error } = await this.db.from("music_tracks").upsert({ user_id: userId, id: track.id, title: track.title, artist_ids: track.artistIds, album_id: track.albumId ?? null, duration_ms: track.durationMs ?? null, track_number: track.trackNumber ?? null, disc_number: track.discNumber ?? null, isrc: track.isrc ?? null, explicit: track.explicit ?? null, artwork_id: track.artworkId ?? null, external_ids: track.externalIds ?? {} }).select().single(); if (error) throw error; return this.track(data as Row); }
  async upsertArtist(userId: string, artist: Artist) { const { data, error } = await this.db.from("music_artists").upsert({ user_id: userId, id: artist.id, name: artist.name, sort_name: artist.sortName ?? null, external_ids: artist.externalIds ?? {} }).select().single(); if (error) throw error; return { ...artist, ...(data?.external_ids ? { externalIds: jsonRecord(data.external_ids) } : {}) }; }
  async upsertAlbum(userId: string, album: Album) { const { data, error } = await this.db.from("music_albums").upsert({ user_id: userId, id: album.id, title: album.title, artist_ids: album.artistIds, release_date: album.releaseDate ?? null, artwork_id: album.artworkId ?? null, external_ids: album.externalIds ?? {} }).select().single(); if (error) throw error; return { ...album, ...(data?.release_date ? { releaseDate: String(data.release_date) } : {}) }; }
  async upsertPlaylist(userId: string, playlist: Playlist) { if (playlist.ownerUserId !== userId) throw new Error("User scope violation"); const { data, error } = await this.db.from("music_playlists").upsert({ user_id: userId, id: playlist.id, name: playlist.name, track_ids: playlist.trackIds, source_id: playlist.sourceId ?? null }).select().single(); if (error) throw error; return playlist; }
  async upsertSource(source: MusicSource) { const { data, error } = await this.db.from("music_sources").upsert({ user_id: source.userId, id: source.id, kind: source.kind, name: source.name, external_account_id: source.externalAccountId ?? null, authorized: source.authorized, metadata: source.metadata }).select().single(); if (error) throw error; return this.source(data as Row); }
  async listSources(userId: string) { const { data, error } = await this.db.from("music_sources").select("*").eq("user_id", userId); if (error) throw error; return (data ?? []).map(row => this.source(row as Row)); }
  async addAsset(userId: string, asset: MediaAsset) { const { data, error } = await this.db.from("music_assets").upsert({ user_id: userId, id: asset.id, track_id: asset.trackId, source_id: asset.sourceId, kind: asset.kind, uri: asset.uri, mime_type: asset.mimeType ?? null, codec: asset.codec ?? null, bitrate: asset.bitrate ?? null, lossless: asset.lossless ?? null, duration_ms: asset.durationMs ?? null, provenance: asset.provenance ?? {} }).select().single(); if (error) throw error; return this.asset(data as Row); }
  async listAssets(userId: string, trackId: string) { const { data, error } = await this.db.from("music_assets").select("*").eq("user_id", userId).eq("track_id", trackId); if (error) throw error; return (data ?? []).map(row => this.asset(row as Row)); }
  async removeAssets(userId: string, trackId: string) { const { error } = await this.db.from("music_assets").delete().eq("user_id", userId).eq("track_id", trackId); if (error) throw error; }
  async upsertArtwork(userId: string, artwork: Artwork) { const { data, error } = await this.db.from("music_artwork").upsert({ user_id: userId, id: artwork.id, uri: artwork.uri, width: artwork.width ?? null, height: artwork.height ?? null, source: artwork.source ?? null }).select().single(); if (error) throw error; return { ...artwork, ...(data?.uri ? { uri: String(data.uri) } : {}) }; }
  async upsertLyrics(userId: string, lyrics: Lyrics) { const { data, error } = await this.db.from("music_lyrics").upsert({ user_id: userId, id: lyrics.id, track_id: lyrics.trackId, text: lyrics.text, synced: lyrics.synced ?? null, source: lyrics.source ?? null }).select().single(); if (error) throw error; return { ...lyrics, ...(data?.text ? { text: String(data.text) } : {}) }; }
  async recordListeningEvent(event: ListeningEvent) { const { data, error } = await this.db.from("music_listening_events").upsert({ user_id: event.userId, id: event.id, track_id: event.trackId, source_id: event.sourceId ?? null, started_at: event.startedAt, ended_at: event.endedAt ?? null, position_ms: event.positionMs ?? null, completed: event.completed, skipped: event.skipped }).select().single(); if (error) throw error; return event; }
}
