'use client'

import { useMemo, useState } from "react"
import type { RoyaltyLedgerEntry } from "@/lib/music/royaltyLedger"

const demo: RoyaltyLedgerEntry[] = []

export default function RoyaltiesPage() {
  const [entries, setEntries] = useState(demo)
  const [status, setStatus] = useState("")
  const [csv, setCsv] = useState("")
  const totals = useMemo(() => entries.reduce((a, e) => ({ streams: a.streams + (e.streams || 0), gross: a.gross + Number(e.grossAmount || 0), reconciled: a.reconciled + (e.status === "RECONCILED" ? Number(e.grossAmount || 0) : 0) }), { streams: 0, gross: 0, reconciled: 0 }), [entries])

  function importCsv() {
    const lines = csv.trim().split(/\r?\n/).filter(Boolean)
    if (lines.length < 2) return setStatus("Paste a CSV with a header row and at least one statement row.")
    const headers = lines.shift()!.split(",").map(x => x.trim())
    const rows = lines.map(line => { const v = line.split(","); return Object.fromEntries(headers.map((h, i) => [h, v[i]?.trim() || ""])) })
    const imported = rows.map((r, i) => ({ id:`import_${Date.now()}_${i}`, statementId:r.statementId || `statement_${Date.now()}`, periodStart:r.periodStart || "", periodEnd:r.periodEnd || "", source:r.platform || "unknown", releaseId:r.releaseId || undefined, isrc:r.isrc || undefined, streams:Number(r.streams || 0), grossAmount:Number(r.grossAmount || 0), currency:r.currency || "USD", status:(r.releaseId || r.isrc ? "RECONCILED" : "NEEDS_MATCHING") })) as RoyaltyLedgerEntry[]
    setEntries(p => [...p, ...imported]); setStatus(`${imported.length} statement row(s) imported.`)
  }

  return <main style={{minHeight:"100vh",background:"linear-gradient(180deg,#f6f1e9,#edf2ed)",color:"#29332e",padding:"30px 18px 100px",fontFamily:'ui-rounded,"Avenir Next",system-ui,sans-serif'}}><div style={{maxWidth:900,margin:"0 auto"}}><div style={eyebrow}>Jhadina Music</div><h1 style={h1}>Royalty Dashboard</h1><p style={sub}>See reported streaming income, reconciliation status, and what is ready to move into Money Core.</p><div style={grid}><Metric label="Streams" value={totals.streams.toLocaleString()}/><Metric label="Reported" value={money(totals.gross,"USD")}/><Metric label="Reconciled" value={money(totals.reconciled,"USD")}/><Metric label="Rows" value={String(entries.length)}/></div><section style={card}><h2 style={h2}>Import statement</h2><p style={sub}>Paste a CSV exported from your legitimate distributor, DSP, or rights organization. Nothing is marked paid just because it was imported.</p><textarea value={csv} onChange={e=>setCsv(e.target.value)} placeholder="statementId,periodStart,periodEnd,platform,releaseId,isrc,streams,grossAmount,currency" style={{...input,minHeight:130,resize:"vertical"}}/><button onClick={importCsv} style={primary}>Import & reconcile</button>{status&&<div role="status" style={notice}>{status}</div>}</section><section style={card}><h2 style={h2}>Royalty ledger</h2>{entries.length===0?<div style={empty}>No royalty statements imported yet.</div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Platform","Period","ISRC / Release","Streams","Amount","Status"].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{entries.map(e=><tr key={e.id}><td style={td}>{e.source}</td><td style={td}>{e.periodStart} → {e.periodEnd}</td><td style={td}>{e.isrc || e.releaseId || "Needs matching"}</td><td style={td}>{(e.streams||0).toLocaleString()}</td><td style={td}>{money(Number(e.grossAmount||0),e.currency)}</td><td style={td}>{e.status}</td></tr>)}</tbody></table></div>}</section></div></main>
}
function Metric({label,value}:{label:string;value:string}){return <div style={metric}><span style={labelStyle}>{label}</span><strong style={{fontSize:24}}>{value}</strong></div>}; function money(n:number,c:string){return new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD"}).format(n)}
const eyebrow={fontSize:10,letterSpacing:".2em",textTransform:"uppercase" as const,color:"#77847c"};const h1={fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400,fontSize:"clamp(38px,9vw,62px)",letterSpacing:"-.045em",margin:"12px 0 8px"};const h2={fontFamily:'Georgia,"Times New Roman",serif',fontWeight:400,fontSize:25,margin:"0 0 8px"};const sub={color:"#718078",lineHeight:1.6,maxWidth:650};const grid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,margin:"25px 0"};const metric={padding:18,borderRadius:22,background:"rgba(255,255,255,.7)",border:"1px solid #dce2dd"};const card={marginTop:14,padding:22,borderRadius:28,background:"rgba(255,255,255,.7)",border:"1px solid #dce2dd",boxShadow:"0 16px 45px rgba(67,76,69,.08)"};const input={width:"100%",boxSizing:"border-box" as const,padding:13,borderRadius:16,border:"1px solid #d5ddd7",background:"rgba(255,255,255,.8)",font:"inherit",marginBottom:12};const primary={border:0,borderRadius:999,padding:"12px 18px",background:"#34443c",color:"#f8f6f1",fontWeight:700,cursor:"pointer"};const notice={marginTop:12,padding:13,borderRadius:16,background:"#e8eee8",color:"#4e6255"};const empty={padding:20,color:"#718078"};const th={textAlign:"left",padding:"10px 8px",borderBottom:"1px solid #dce2dd",color:"#657169"};const td={padding:"12px 8px",borderBottom:"1px solid #e5e9e5"};const labelStyle={fontSize:11,color:"#657169",display:"block",marginBottom:5}
